(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
SetOptions[$FrontEndSession,NotebookAutoSave->True]
NotebookSave[]


(* ::Input::Initialization:: *)
ClearAll[\[Beta]Function];

\[Beta]Function[coupling_]:=Module[{gr,\[Beta]f,nLoop,i},
Clear[g,g0,\[Mu],\[Epsilon]];
gr=coupling;
nLoop=Exponent[gr,g0];
(*Print[nLoop]*);
\[Beta]f=\[Mu] D[gr,\[Mu]]//Expand;
(*Print[\[Beta]f];*)

gr=g-gr+g0 \[Mu]^\[Epsilon];

Do[\[Beta]f=\[Beta]f/.g0^n_ \[Mu]^(n_ \[Epsilon]):>(gr)^n//Expand;
\[Beta]f=\[Beta]f/.(g0 \[Mu]^\[Epsilon]):>(gr)//Expand;
\[Beta]f=\[Beta]f/.g0^n_/;n>nLoop:>0;
,{i,1,nLoop}];

(*For[i=1,i<=nLoop,i++,
\[Beta]f=\[Beta]f/.g0^n_ \[Mu]^(n_ \[Epsilon]):>(gr)^n//Expand;
\[Beta]f=\[Beta]f/.(g0 \[Mu]^\[Epsilon]):>(gr)//Expand;
];*)

\[Beta]f=\[Beta]f/.g0^n_ \[Mu]^(n_ \[Epsilon]):>(g)^n//Expand;
\[Beta]f=\[Beta]f/.(g0 \[Mu]^\[Epsilon]):>(g)//Expand;
\[Beta]f=Series[\[Beta]f,{g,0,nLoop}]//Expand;
(*Print[\[Beta]f];*)
(*\[Beta]f=Normal[\[Beta]f];*)
Return[\[Beta]f]]


(* ::Input::Initialization:: *)
ClearAll[\[Gamma]Function];

\[Gamma]Function[observable_,coupling_]:=Module[{U,gr,\[Gamma]f,nLoop,i},
Clear[g,g0,\[Mu],\[Epsilon]];
U=observable;
gr=coupling;
nLoop=Exponent[gr,g0]-1;
(*Print[nLoop]*);
\[Gamma]f=\[Mu] D[Log[U],\[Mu]]//Expand;
(*Print[\[Gamma]f];*)

gr=g-gr+g0 \[Mu]^\[Epsilon];

Do[\[Gamma]f=\[Gamma]f/.g0^n_ \[Mu]^(n_ \[Epsilon]):>(gr)^n//Expand;
\[Gamma]f=\[Gamma]f/.(g0 \[Mu]^\[Epsilon]):>(gr)//Expand;
\[Gamma]f=\[Gamma]f/.g0^n_/;n>nLoop:>0;
,{i,1,nLoop}];

(*For[i=1,i<=nLoop,i++,
\[Gamma]f=\[Gamma]f/.g0^n_ \[Mu]^(n_ \[Epsilon]):>(gr)^n//Expand;
\[Gamma]f=\[Gamma]f/.(g0 \[Mu]^\[Epsilon]):>(gr)//Expand;
];*)

\[Gamma]f=\[Gamma]f/.g0^n_ \[Mu]^(n_ \[Epsilon]):>(g)^n//Expand;
\[Gamma]f=\[Gamma]f/.(g0 \[Mu]^\[Epsilon]):>(g)//Expand;
\[Gamma]f=Series[\[Gamma]f,{g,0,nLoop}]//Expand;
(*Print[\[Gamma]f];*)
(*\[Gamma]f=Normal[\[Gamma]f];*)
Return[\[Gamma]f]]



