(* ::Package:: *)

(* ::Chapter::Closed:: *)
(*STILL NEED TO RERUN AND EXPORT SOME PURGED AVERAGES*)


(* ::Input:: *)
(*(*Quit*)*)


(* ::Input:: *)
(*FrontEndExecute[FrontEndToken["ClearDynamicEvaluationErrors"]];*)
(*FinishDynamic[];*)


(* ::Title::Closed:: *)
(*Initialization*)


(* ::Input:: *)
(*(*SetOptions[$FrontEndSession,NotebookAutoSave->True]*)*)
(*(*With[{nb=EvaluationNotebook[]},RunScheduledTask[If["ModifiedInMemory"/. NotebookInformation[nb],NotebookSave[nb]],300]]*)
(*NotebookSave[]*)*)


(* ::Input::Initialization:: *)
<<PaoloInitialization`
??PaoloInitialization`*


(* ::Input:: *)
(*$Paolofontsize=15*)
(*$Paolofont*)


(* ::Input:: *)
(*(*Quit*)*)


(* ::Input:: *)
(*FrontEndTokenExecute["SelectAll"]*)
(*FrontEndTokenExecute["SelectionCloseAllGroups"]*)


(* ::Input::Initialization:: *)
$Assumptions=b>0


(* ::Title:: *)
(*Data analysis for the Fractal Dimension of the b-LRW on 3d square Lattice*)


(* ::Chapter:: *)
(*Import data. MODIFY THE HIGHLIGHTED PARTS EVERY TIME*)


(* ::Section::Closed:: *)
(*b=0.5		still needs more statistics: 1.751 \[PlusMinus] 0.020*)
(*		(Using more estimates and then mean 1.748 \[PlusMinus] 0.004)*)


(* ::Input:: *)
(*b=0.5;*)
(**)
(*rawData=Import["data05-3d-HaloAndHybrid.mx"];*)
(**)
(*Length[rawData]*)
(*Developer`PackedArrayQ[rawData]*)


(* ::Subsubsection::Closed:: *)
(*Run once to export MX file*)


(* ::Input:: *)
(*rawData=Import["D:\\Offline_Documents\\University\\PhD_Paris\\PhD_work\\Simulations\\bLRW\\b-LRWdata\\3d-FromCluster\\b05-3d-clean_merged_data-HalolAndHybrid.csv","CSV"];*)
(*(*Immediately lock it into a Packed Array*)*)
(*rawData=Developer`ToPackedArray[rawData];*)
(* (* MODIFY FILE NAME *)*)
(**)
(*Length[rawData]*)
(*rawData=Cases[rawData,{_?NumericQ,_?NumericQ}];*)
(*Length[rawData]*)
(*rawData=Developer`ToPackedArray[rawData];*)
(*Developer`PackedArrayQ[rawData]*)


(* ::Input:: *)
(*Export["data05-3d-HaloAndHybrid.mx",rawData,"MX"]*)


(* ::Subsection:: *)
(*GatherBy x values*)


(* ::Input:: *)
(*(*1. Gather rows by their first element (x) at C-speed*)*)
(*gathered=GatherBy[rawData,First];*)
(**)
(*(*2. Extract the unique X values directly from the gathered groups*)*)
(*xValues=gathered[[All,1,1]];*)
(**)
(*(*3. Extract the Y values for each group*)*)
(*yGroups=gathered[[All,All,2]];*)
(**)
(*(*4. Map Mean and StandardDeviation across the groups in bulk*)*)
(*means=Mean/@yGroups/. 0.->1.0`*^-8;*)
(**)
(*(*Standard deviation throws an error/indeterminacy if length is 1,so we replace Indeterminate with 0 globally at the end*)*)
(*stdDevs=Check[StandardDeviation[#],missing](*/Sqrt[Length[#]]*)&/@yGroups(*/. Indeterminate->1.0`*^-8*);*)


(* ::Input:: *)
(*(*Position[yGroups,_?(Length[#]<50&),1]*)
(*yGroups[[Rest[Flatten@%]]]*)*)


(* ::Input:: *)
(*missingIndices=Flatten@Position[stdDevs,missing]*)
(**)
(*Part[#,missingIndices]&/@{means,stdDevs}*)
(*Times@@%*)
(*stdDevs[[missingIndices]]=%/.missing->Mean[Select[stdDevs/means//N,FreeQ[#,missing]&]]//N*)


(* ::Input:: *)
(*stdDevs=stdDevs/. 0.->1.0`*^-8;*)
(*(* stdDev on mean*)*)
(*stdDevsOnMean=(1/Sqrt[Length[#]]&/@yGroups)*stdDevs;*)
(**)
(*(* Maximum deviation*)*)
(*maxDevsPlus=MapThread[Max[#2-#1]&,{means//N,yGroups}]/. 0.->1.0`*^-8;*)
(*maxDevsMinus=MapThread[Min[#2-#1]&,{means//N,yGroups}]/. 0.->1.0`*^-8;*)
(**)
(*(*5. Combine them using the Threaded Around wrapper*)*)
(*averaged=Transpose[{xValues,means}];*)
(*averagedWithErrors=Transpose[{xValues,MapThread[Around,{means,stdDevs}]}];*)
(*averagedWithErrorsOnMean=Transpose[{xValues,MapThread[Around,{means,stdDevsOnMean}]}];*)
(*averagedWithMaxDev=Transpose[{xValues,MapThread[Around,{means,Transpose[{maxDevsMinus,maxDevsPlus}]}]}];*)
(**)
(*(*Drop points with low statistic*)*)
(*averagedWithErrorsOnMeanPurged=Delete[averagedWithErrorsOnMean,Rest[Position[yGroups,_?(Length[#]<2500&),{1}]]];*)
(*Length@averagedWithErrorsOnMean*)
(*Length@averagedWithErrorsOnMeanPurged*)
(**)
(*Export["averaged-b05.mx",{averaged,averagedWithErrors,averagedWithErrorsOnMean,averagedWithErrorsOnMeanPurged,averagedWithMaxDev,b},"MX"] *)


(* ::Input:: *)
(*(*NOT USING IT*)
(**)
(* Remove the Sqrt[N] factor from the StdDev estimates*)*)
(*(*MapThread[Times[#1,Sqrt[#2]]&,{stdDevs,yGroups}]*)
(**)
(*averagedWithErrors=Transpose[{xValues,MapThread[Around,{means,%}]}];*)*)


(* ::Input:: *)
(*(**)
(*(*Standard deviation with my code (Kay's trick for better estimate)*)*)
(*stdDevsEstimated=StdDevEstimate[#,280,"print"->tTrue]&/@yGroups/. Indeterminate->1.0`*^-8;*)
(*stdDevsEstimated=stdDevsEstimated/. 0.->1.0`*^-8;*)
(**)
(*averagedWithEstimatedStdDevs=Transpose[{xValues,MapThread[Around,{means,stdDevsEstimated}]}];*)*)


(* ::Subsection:: *)
(*Take the Log*)


(* ::Input:: *)
(*{averaged,averagedWithErrors,averagedWithErrorsOnMean,averagedWithErrorsOnMeanPurged,averagedWithMaxDev,b}=Import["averaged-b05.mx"];*)


(* ::Input:: *)
(*(*(*Drop points with low statistic*)*)
(*averagedWithErrorsOnMeanPurged=Delete[averagedWithErrorsOnMean,Rest[Position[yGroups,_?(Length[#]<2500&),{1}]]];*)
(*Length@averagedWithErrorsOnMean*)
(*Length@averagedWithErrorsOnMeanPurged*)*)


(* ::Input:: *)
(*exluded=5;*)
(**)
(*averaged=Select[averaged,#[[1]]=!=""&&#[[1]]>exluded&];*)
(*averagedWithErrors=Select[averagedWithErrors,#[[1]]=!=""&&#[[1]]>exluded&];*)
(**)
(*averagedWithErrorsOnMean=Select[averagedWithErrorsOnMean,#[[1]]=!=""&&#[[1]]>exluded&];*)
(*averagedWithErrorsOnMeanPurged=Select[averagedWithErrorsOnMeanPurged,#[[1]]=!=""&&#[[1]]>exluded&];*)
(**)
(*averagedWithMaxDev=Select[averagedWithMaxDev,#[[1]]=!=""&&#[[1]]>exluded&];*)
(*(*averagedWithEstimatedStdDevs=Select[averagedWithEstimatedStdDevs,#[[1]]=!=""&];*)
(*averagedWithEstimatedStdDevsOnMean=Select[averagedWithEstimatedStdDevsOnMean,#[[1]]=!=""&];*)*)


(* ::Input:: *)
(*logAveraged=Log[averaged];*)
(*logAveragedWithErrors=Log[averagedWithErrors](*/. 0->Around[1.0`*^-6,1.0`*^-6]*);*)
(**)
(*logAveragedWithErrorsOnMean=Log[averagedWithErrorsOnMean](*/. 0->Around[1.0`*^-6,1.0`*^-6]*);*)
(*logAveragedWithErrorsOnMeanPurged=Log[averagedWithErrorsOnMeanPurged](*/. 0->Around[1.0`*^-6,1.0`*^-6]*);*)
(**)
(*logAveragedWithMaxDev=Log[averagedWithMaxDev](*/. 0->Around[1.0`*^-6,1.0`*^-6]*);*)
(*(*logAveragedWithEstimatedStdDevs=Log[averagedWithEstimatedStdDevs]/. 0->Around[1.0`*^-6,1.0`*^-6];*)
(*logAveragedWithEstimatedStdDevsOnMean=Log[averagedWithEstimatedStdDevsOnMean]/. 0->Around[1.0`*^-6,1.0`*^-6];*)*)


(* ::Input:: *)
(*maxx=Max[averaged[[All,1]]];*)
(*maxy=Max[averaged[[All,2]]];*)
(**)
(*referencePlot=Plot[(x (#)-1.73),{x,Log[0+1],Log[maxx]},PlotStyle->{RGBColor[0, 0, 1],Dashed},PlotLegends->Placed[SwatchLegend[{Row[{"Guessed by eye: ",#}]}],Right]]&@1.8;*)
(* *)
(*Show[{ListPlot[logAveragedWithMaxDev,PlotStyle->{GrayLevel[0],Directive[Opacity[0.3]],PointSize->0.001},AxesLabel->{"Log[L]","Log[N]"}]*)
(*,ListPlot[logAveragedWithErrorsOnMeanPurged,PlotStyle->{RGBColor[0, 0.78, 1],PointSize->0.01},PlotLegends->PointLegend[{"logAveragedWithErrorsOnMeanPurged"},LegendMarkerSize->10,LegendMarkers->Graphics[Disk[]]]]*)
(*,ListPlot[logAveragedWithErrorsOnMean,PlotStyle->{RGBColor[1, 0.55, 1],Directive[Opacity[0.6]],PointSize->0.005},PlotLegends->PointLegend[{"logAveragedWithErrorsOnMean"},LegendMarkerSize->10,LegendMarkers->Graphics[Disk[]]]]*)
(*,referencePlot*)
(*}*)
(*,PlotLabel->Row[{" b = ",b}],PlotRange->{All,{0,Log[maxy]}},AxesOrigin->{1,0},ImageSize->700]*)


(* ::Input:: *)
(*normalizeWithReference:=Plus[{0,-#[[1]]*1.82+1.85},#]&;*)
(**)
(*logAveragedRefNorm=normalizeWithReference/@logAveraged;*)
(*logAveragedWithErrorsRefNorm=normalizeWithReference/@logAveragedWithErrors;*)
(**)
(*logAveragedWithErrorsOnMeanRefNorm=normalizeWithReference/@logAveragedWithErrorsOnMean;*)
(*logAveragedWithErrorsOnMeanPurgedRefNorm=normalizeWithReference/@logAveragedWithErrorsOnMeanPurged;*)
(**)
(*logAveragedWithMaxDevRefNorm=normalizeWithReference/@logAveragedWithMaxDev;*)
(**)
(*maxx=Max[logAveragedWithMaxDevRefNorm[[All,1]]];*)
(*{miny,maxy}=MinMax[logAveragedWithMaxDevRefNorm[[All,2,1]]];*)
(* *)
(*Show[{(*ListPlot[logAveragedWithMaxDevRefNorm,PlotStyle->{,Directive[Opacity[0.3]],PointSize->0.001}]*)
(*,*)ListPlot[logAveragedWithErrorsOnMeanPurgedRefNorm,PlotStyle->{RGBColor[0, 0.78, 1],PointSize->0.01},PlotLegends->PointLegend[{"logAveragedWithErrorsOnMeanPurgedRefNorm"},LegendMarkerSize->10,LegendMarkers->Graphics[Disk[]]]]*)
(*,ListPlot[logAveragedWithErrorsOnMeanRefNorm,PlotStyle->{RGBColor[1, 0.55, 1],Directive[Opacity[0.6]],PointSize->0.005},PlotLegends->PointLegend[{"logAveragedWithErrorsOnMeanRefNorm"},LegendMarkerSize->10,LegendMarkers->Graphics[Disk[]]]]*)
(*}*)
(*,PlotLabel->Row[{" b = ",b}],AxesLabel->{"Log[L]","Log[N]"},PlotRange->{{0,maxx},{-0.5,maxy}},AxesOrigin->{1,0},ImageSize->700]*)


(* ::Subsection:: *)
(*Take the Log WITH A SHIFT*)


(* ::Subsubsection::Closed:: *)
(*Check for best shift using \[Chi]^2 to test fit *)


(* ::Input:: *)
(*(*shift:=Plus[{+3,0},#]&; (*In the code, the stopping condition is with R-1*)*)
(**)
(*logAveragedWithErrorsOnMeanPurgedShifted=Log[shift/@averagedWithErrorsOnMeanPurged](*/. 0->Around[1.0`*^-6,1.0`*^-6]*);*)
(**)
(*fitFunc=a+c Exp[-x]+df  x*)
(**)
(*fit=Quiet[NonlinearModelFit[logAveragedWithErrorsOnMeanPurgedShifted,fitFunc,{a,c,df(*,{df,1.024}*)},x,MaxIterations->1000,Method->"NMinimize"],NonlinearModelFit::lmnl];*)
(**)
(*fit["ParameterTable"]*)
(*fit["ANOVATable"]*)
(*%[[1,1(*,2,2*)]]*)
(*fit["ANOVATableEntries"]*)
(**)
(*{fit["ParameterTable"][[1,1,-1,2]](*Slope*),*)
(*fit["ParameterTable"][[1,1,-1,3]](*Slope Error*),*)
(*fit["ANOVATableEntries"][[2,2]]/fit["ANOVATableEntries"][[2,1]](*Reduced Chi^2*)}*)
(*Clear[fit]*)*)


(* ::Input:: *)
(*(*Sort data ascending by x*)*)
(*(*dataSorted=SortBy[logAveragedWithErrorsOnMeanPurged,First];*)*)
(*fitFunc=a+0c Exp[-x]+df  x;*)
(*fitPar={a,(*c,*)df} ;*)
(**)
(*(*Scan across cutoff values xMin*)*)
(*scanResults=ParallelTable[With[{shift:=Plus[{-shiftValue,0},#]&},*)
(*With[{shiftedData=Log[Select[shift/@averagedWithErrorsOnMeanPurged,#[[1]]>0&]]},*)
(*Module[*)
(*{fit=Quiet[NonlinearModelFit[shiftedData,fitFunc,fitPar,x,MaxIterations->1000,Method->"NMinimize",VarianceEstimatorFunction->(1&)],NonlinearModelFit::lmnl]},*)
(**)
(*{shiftValue,fit["ParameterTable"][[1,1,-1,2]](*Slope*),*)
(*fit["ParameterTable"][[1,1,-1,3]](*Slope Error*),*)
(*fit["ANOVATableEntries"][[2,2]]/fit["ANOVATableEntries"][[2,1]](*Reduced Chi^2*)}]*)
(*]],*)
(*{shiftValue,1,3,0.1}];*)


(* ::Input:: *)
(*{min\[Chi]position,min\[Chi]}=Flatten@MinimalBy[scanResults[[All,{1,4}]],#[[2]]&]*)
(**)
(*(*1. Plot Reduced Chi^2 vs xMin*)*)
(*ListLinePlot[scanResults[[All,{1,4}]],AxesLabel->{"shift","Reduced Chi^2"},PlotRange->All,GridLines->{{min\[Chi]position},{1}}]*)
(**)
(*(*2. Plot Fitted Slope vs xMin with error bands*)*)
(*ListPlot[Table[{r[[1]],Around[r[[2]],r[[3]]]},{r,scanResults}],AxesLabel->{"shift","Slope"},PlotRange->All,GridLines->{{min\[Chi]position},None}]*)


(* ::Input:: *)
(*MinimalBy[scanResults(*[[All,{1,4}]]*),Last]*)
(**)
(*shift:=Plus[{-MinimalBy[scanResults(*[[All,{1,4}]]*),Last][[1,1]],0},#]&; (*In the code, the stopping condition is with R-1*)*)
(*(*shift:=Plus[{0,0},#]&;*)*)
(**)
(*logAveragedWithMaxDevShifted=Log[shift/@averagedWithMaxDev](*/. 0->Around[1.0`*^-6,1.0`*^-6]*);*)
(*logAveragedWithErrorsOnMeanShifted=Log[shift/@averagedWithErrorsOnMean](*/. 0->Around[1.0`*^-6,1.0`*^-6]*);*)
(*logAveragedWithErrorsOnMeanPurgedShifted=Log[shift/@averagedWithErrorsOnMeanPurged](*/. 0->Around[1.0`*^-6,1.0`*^-6]*);*)
(**)
(*(*fitFunc=a+c Exp[-x]+df  x;*)*)
(**)
(*nlmAveragedWithStdDevsUnconstrainedGlobalPurged=Quiet[NonlinearModelFit[logAveragedWithErrorsOnMeanPurgedShifted,fitFunc,fitPar,x,MaxIterations->1000,Method->"NMinimize"],NonlinearModelFit::lmnl];*)
(**)
(*maxx=Max[averaged[[All,1]]];*)
(*maxy=Max[averaged[[All,2]]];*)
(**)
(*thresholdBelow=0;*)
(*thresholdAbove=maxx-0;*)
(**)
(*Show[{ListPlot[logAveragedWithMaxDevShifted,PlotStyle->{GrayLevel[0],Directive[Opacity[0.3]],PointSize->0.001},AxesLabel->{"Log[L]","Log[N]"}]*)
(*,ListPlot[logAveragedWithErrorsOnMeanPurgedShifted,PlotStyle->{RGBColor[0, 0.78, 1],PointSize->0.01},PlotLegends->PointLegend[{"logAveragedWithErrorsOnMeanPurgedShifted"},LegendMarkerSize->10,LegendMarkers->Graphics[Disk[]]]]*)
(*,ListPlot[logAveragedWithErrorsOnMeanShifted,PlotStyle->{RGBColor[1, 0.55, 1],Directive[Opacity[0.6]],PointSize->0.005},PlotLegends->PointLegend[{"logAveragedWithErrorsOnMeanShifted"},LegendMarkerSize->10,LegendMarkers->Graphics[Disk[]]]]*)
(*,*)
(*Plot[ReleaseHold[#][x],{x,Log[thresholdBelow+1],Log[thresholdAbove]},PlotStyle->{RGBColor[0.24, 0.68, 0.8],Thickness->0.002},PlotLegends->Placed[SwatchLegend[{Row[{#,":\n ",TraditionalForm[ReleaseHold[#][x]]}]}],Right]]&@HoldForm[nlmAveragedWithStdDevsUnconstrainedGlobalPurged]*)
(*,Plot[(x (1.624)-1.4),{x,Log[0+1],Log[maxx]},PlotStyle->{RGBColor[0, 0, 1],Dashed},PlotLegends->Placed[SwatchLegend[{"David Wilson: 1.624"}],Right]]*)
(*}*)
(*,PlotLabel->Row[{" b = ",b}]*)
(*,PlotRange->{All,{0,All}},AxesOrigin->{1,0},ImageSize->700]*)
(**)
(**)


(* ::Input:: *)
(*measuredb1=Around[nlmAveragedWithStdDevsUnconstrainedGlobalPurged["ParameterTable"][[1,1,-1,2]],nlmAveragedWithStdDevsUnconstrainedGlobalPurged["ParameterTable"][[1,1,-1,3]]*4]*)


(* ::Input:: *)
(*ListPlot[Transpose[{logAveragedWithErrorsOnMeanPurged[[All,1]],nlmAveragedWithStdDevsUnconstrainedGlobalPurged["FitResiduals"]}],Filling->Axis,*)
(*AxesLabel->{"x","Residuals (y - y_fit)"},PlotLabel->"FitResiduals - nlmAveragedWithStdDevsUnconstrainedGlobalPurged",ImageSize->Large]*)


(* ::Subsubsection:: *)
(*Check for best shift using \[Chi]^2 to test linearity Dropping some too*)


(* ::Input:: *)
(*(*dataPurged=Delete[SortBy[averagedWithErrorsOnMeanPurged,First],{{1},{2},{3},{4}(*,{5},{6},{7},{8},{9}*)}];*)*)
(*(*dataPurged=Drop[SortBy[averagedWithErrorsOnMeanPurged,First],8];*)*)
(**)
(*fitFunc=a+0c Exp[-x]+df  x;*)
(*fitPar={a,(*c,*)df};*)
(**)
(*averagedWithErrorsOnMeanPurgedSorted=SortBy[averagedWithErrorsOnMeanPurged,First];*)
(*(*Scan across cutoff values xMin*)*)
(*scanResultsRaw=*)
(*ParallelTable[With[{dataPurged=Drop[averagedWithErrorsOnMeanPurgedSorted,dropFirstn]},*)
(*Table[With[{shift:=Plus[{-shiftValue,0},#]&},*)
(*With[{shiftedData=Log[Select[shift/@dataPurged,#[[1]]>0&]](*/. 0->Around[1.0`*^-6,1.0`*^-6]*)},*)
(*Module[*)
(*{fit=LinearModelFit[shiftedData,x,x,Weights->Automatic,VarianceEstimatorFunction->(1&)]},*)
(**)
(*{shiftValue,*)
(*fit["ParameterTable"][[1,1,3,2]](*Slope*),*)
(*fit["ParameterTable"][[1,1,3,3]](*Slope Error*),*)
(*fit["ANOVATableEntries"][[2,2]]/fit["ANOVATableEntries"][[2,1]](*Reduced Chi^2*),*)
(*dropFirstn}]*)
(*]],*)
(*{shiftValue,-3,10,0.5}]],*)
(*{dropFirstn,14,Length[averagedWithErrorsOnMeanPurgedSorted]-4}];*)
(**)
(*scanResults=Flatten[scanResultsRaw,1];*)


(* ::Input:: *)
(*Mean[Around[#[[1]],#[[2]]*3]&/@(MinimalBy[scanResults(*[[All,{1,4}]]*),Abs[#[[4]]-1]&,8][[All,{2,3}]])]*)


(* ::Input:: *)
(*MinimalBy[scanResults(*[[All,{1,4}]]*),Abs[#[[4]]-1]&,20]*)
(*minBy\[Chi]=%[[1]]*)
(*{min\[Chi]position,associatedSlope,min\[Chi]}=%[[{1,2,4}]](*Flatten@MinimalBy[scanResults[[All,{1,4}]],#[[2]]&]*)*)
(**)
(*(*1. Plot Reduced Chi^2 vs xMin*)*)
(*ListLinePlot[#[[All,All,{1,4}]],AxesLabel->{"shift","Reduced Chi^2"},PlotRange->{All,{0,100}},GridLines->{{min\[Chi]position},{1}},PlotLegends->LineLegend[#[[All,1,5]],LegendLabel->"Dropped:"],ScalingFunctions->"Log"(*,PlotLabel->{Row[{"Dropped first ",#[[5]]}]}*)]&@scanResultsRaw*)
(**)
(*(*2. Plot Fitted Slope vs xMin with error bands*)*)
(*ListPlot[Table[{r[[1]],Around[r[[2]],r[[3]]]},{r,#}]&/@#,AxesLabel->{"shift","Slope"},PlotRange->All,GridLines->{{min\[Chi]position},{associatedSlope}},PlotLegends->LineLegend[#[[All,1,5]],LegendLabel->"Dropped:"]]&@scanResultsRaw*)


(* ::Input:: *)
(*(*MinimalBy[scanResults(*[[All,{1,4}]]*),#[[4]]&]*)*)
(**)
(*shift:=Plus[{-minBy\[Chi][[1]],0},#]&; (*In the code, the stopping condition is with R-1*)*)
(**)
(*logAveragedWithMaxDevShifted=Log[shift/@averagedWithMaxDev](*/. 0->Around[1.0`*^-6,1.0`*^-6]*);*)
(*logAveragedWithErrorsOnMeanShifted=Log[shift/@averagedWithErrorsOnMean](*/. 0->Around[1.0`*^-6,1.0`*^-6]*);*)
(**)
(*dataPurged=Drop[SortBy[averagedWithErrorsOnMeanPurged,First],minBy\[Chi][[5]]];*)
(*logAveragedWithErrorsOnMeanPurgedShifted=Log[shift/@dataPurged](*/. 0->Around[1.0`*^-6,1.0`*^-6]*);*)
(**)
(**)
(*fitFunc=a+0c Exp[-x]+df  x;*)
(*fitPar={a,(*c,*)df};*)
(**)
(**)
(*nlmAveragedWithStdDevsUnconstrainedGlobalPurged=Quiet[NonlinearModelFit[logAveragedWithErrorsOnMeanPurgedShifted,fitFunc,fitPar,x,MaxIterations->1000,Method->"NMinimize"],NonlinearModelFit::lmnl];*)
(**)
(*maxx=Max[averaged[[All,1]]];*)
(*maxy=Max[averaged[[All,2]]];*)
(**)
(*thresholdBelow=0;*)
(*thresholdAbove=maxx-0;*)
(**)
(*Show[{ListPlot[logAveragedWithMaxDevShifted,PlotStyle->{GrayLevel[0],Directive[Opacity[0.3]],PointSize->0.001},AxesLabel->{"Log[L]","Log[N]"}]*)
(*,ListPlot[logAveragedWithErrorsOnMeanPurgedShifted,PlotStyle->{RGBColor[0, 0.78, 1],PointSize->0.01},PlotLegends->PointLegend[{"logAveragedWithErrorsOnMeanPurgedShifted"},LegendMarkerSize->10,LegendMarkers->Graphics[Disk[]]]]*)
(*,ListPlot[logAveragedWithErrorsOnMeanShifted,PlotStyle->{RGBColor[1, 0.55, 1],Directive[Opacity[0.6]],PointSize->0.005},PlotLegends->PointLegend[{"logAveragedWithErrorsOnMeanShifted"},LegendMarkerSize->10,LegendMarkers->Graphics[Disk[]]]]*)
(*,*)
(*Plot[ReleaseHold[#][x],{x,Log[thresholdBelow+1],Log[thresholdAbove]},PlotStyle->{RGBColor[0.24, 0.68, 0.8],Thickness->0.002},PlotLegends->Placed[SwatchLegend[{Row[{#,":\n ",TraditionalForm[ReleaseHold[#][x]]}]}],Right]]&@HoldForm[nlmAveragedWithStdDevsUnconstrainedGlobalPurged]*)
(*,referencePlot*)
(*}*)
(*,PlotLabel->Row[{" b = ",b}]*)
(*,PlotRange->{All,{0,All}},AxesOrigin->{1,0},ImageSize->700]*)
(**)
(**)


(* ::Input:: *)
(*measuredb05=Around[nlmAveragedWithStdDevsUnconstrainedGlobalPurged["ParameterTable"][[1,1,-1,2]],nlmAveragedWithStdDevsUnconstrainedGlobalPurged["ParameterTable"][[1,1,-1,3]]*4]*)


(* ::Input:: *)
(*ListPlot[Transpose[{logAveragedWithErrorsOnMeanPurgedShifted[[All,1]],nlmAveragedWithStdDevsUnconstrainedGlobalPurged["FitResiduals"]}],Filling->Axis,*)
(*AxesLabel->{"x","Residuals (y - y_fit)"},PlotLabel->"FitResiduals - nlmAveragedWithStdDevsUnconstrainedGlobalPurged",ImageSize->Large]*)


(* ::Section::Closed:: *)
(*b=1		Not too bad! 1.624 \[PlusMinus] 0.006 (Wilson 1.624!!!) *)
(*		(Using more estimates and then mean 1.623 \[PlusMinus] 0.002)*)


(* ::Input:: *)
(*b=1;*)
(**)
(*rawData=Import["data1-3d-HaloAndHybrid.mx"];*)
(**)
(*Length[rawData]*)
(*Developer`PackedArrayQ[rawData]*)


(* ::Subsubsection::Closed:: *)
(*Run once to export MX file*)


(* ::Input:: *)
(*rawData=data1=Import["D:\\Offline_Documents\\University\\PhD_Paris\\PhD_work\\Simulations\\bLRW\\b-LRWdata\\3d-FromCluster\\b1-3d-clean_merged_data-HaloAndHybrid.csv","CSV"];*)
(*(*Immediately lock it into a Packed Array*)*)
(*rawData=Developer`ToPackedArray[rawData];*)
(* (* MODIFY FILE NAME *)*)
(*Length[rawData]*)


(* ::Input:: *)
(*Length[rawData]*)
(*rawData=Cases[rawData,{_?NumericQ,_?NumericQ}];*)
(*Length[rawData]*)
(*rawData=Developer`ToPackedArray[rawData];*)
(*Developer`PackedArrayQ[rawData]*)
(* *)
(*Length[rawData]*)


(* ::Input:: *)
(*rawData=Pick[rawData,Length/@rawData,2];*)
(*Length[rawData]*)


(* ::Input:: *)
(*Export["data1-3d-HaloAndHybrid.mx",rawData,"MX"]*)


(* ::Subsection::Closed:: *)
(*GatherBy x values*)


(* ::Input:: *)
(*(*1. Gather rows by their first element (x) at C-speed*)*)
(*gathered=GatherBy[rawData,First];*)
(**)
(*(*2. Extract the unique X values directly from the gathered groups*)*)
(*xValues=gathered[[All,1,1]];*)
(**)
(*(*3. Extract the Y values for each group*)*)
(*yGroups=gathered[[All,All,2]];*)
(**)
(*(*4. Map Mean and StandardDeviation across the groups in bulk*)*)
(*means=Mean/@yGroups/. 0.->1.0`*^-8;*)
(**)
(*(*Standard deviation throws an error/indeterminacy if length is 1,so we replace Indeterminate with 0 globally at the end*)*)
(*stdDevs=Check[StandardDeviation[#],missing](*/Sqrt[Length[#]]*)&/@yGroups(*/. Indeterminate->1.0`*^-8*);*)


(* ::Input:: *)
(*(*Position[yGroups,_?(Length[#]<50&),1]*)
(*yGroups[[Rest[Flatten@%]]]*)*)


(* ::Input:: *)
(*missingIndices=Flatten@Position[stdDevs,missing]*)
(**)
(*Part[#,missingIndices]&/@{means,stdDevs}*)
(*Times@@%*)
(*stdDevs[[missingIndices]]=%/.missing->Mean[Select[stdDevs/means//N,FreeQ[#,missing]&]]//N*)


(* ::Input:: *)
(*stdDevs=stdDevs/. 0.->1.0`*^-8;*)
(*(* stdDev on mean*)*)
(*stdDevsOnMean=(1/Sqrt[Length[#]]&/@yGroups)*stdDevs;*)
(**)
(*(* Maximum deviation*)*)
(*maxDevsPlus=MapThread[Max[#2-#1]&,{means//N,yGroups}]/. 0.->1.0`*^-8;*)
(*maxDevsMinus=MapThread[Min[#2-#1]&,{means//N,yGroups}]/. 0.->1.0`*^-8;*)
(**)
(*(*5. Combine them using the Threaded Around wrapper*)*)
(*averaged=Transpose[{xValues,means}];*)
(*averagedWithErrors=Transpose[{xValues,MapThread[Around,{means,stdDevs}]}];*)
(*averagedWithErrorsOnMean=Transpose[{xValues,MapThread[Around,{means,stdDevsOnMean}]}];*)
(*averagedWithMaxDev=Transpose[{xValues,MapThread[Around,{means,Transpose[{maxDevsMinus,maxDevsPlus}]}]}];*)
(**)
(*(*Drop points with low statistic*)*)
(*averagedWithErrorsOnMeanPurged=Delete[averagedWithErrorsOnMean,Rest[Position[yGroups,_?(Length[#]<500&),{1}]]];*)
(*Length@averagedWithErrorsOnMean*)
(*Length@averagedWithErrorsOnMeanPurged*)
(**)
(*Export["averaged-b1.mx",{averaged,averagedWithErrors,averagedWithErrorsOnMean,averagedWithErrorsOnMeanPurged,averagedWithMaxDev,b},"MX"]*)


(* ::Input:: *)
(*(*NOT USING IT*)
(**)
(* Remove the Sqrt[N] factor from the StdDev estimates*)*)
(*(*MapThread[Times[#1,Sqrt[#2]]&,{stdDevs,yGroups}]*)
(**)
(*averagedWithErrors=Transpose[{xValues,MapThread[Around,{means,%}]}];*)*)


(* ::Input:: *)
(*(**)
(*(*Standard deviation with my code (Kay's trick for better estimate)*)*)
(*stdDevsEstimated=StdDevEstimate[#,280,"print"->tTrue]&/@yGroups/. Indeterminate->1.0`*^-8;*)
(*stdDevsEstimated=stdDevsEstimated/. 0.->1.0`*^-8;*)
(**)
(*averagedWithEstimatedStdDevs=Transpose[{xValues,MapThread[Around,{means,stdDevsEstimated}]}];*)*)


(* ::Subsection::Closed:: *)
(*Take the Log*)


(* ::Input:: *)
(* {averaged,averagedWithErrors,averagedWithErrorsOnMean,averagedWithErrorsOnMeanPurged,averagedWithMaxDev,b}=Import["averaged-b1.mx"];*)


(* ::Input:: *)
(*(*(*Drop points with low statistic*)*)
(*averagedWithErrorsOnMeanPurged=Delete[averagedWithErrorsOnMean,Rest[Position[yGroups,_?(Length[#]<500&),{1}]]];*)
(*Length@averagedWithErrorsOnMean*)
(*Length@averagedWithErrorsOnMeanPurged*)*)


(* ::Input:: *)
(*exluded=5;*)
(**)
(*averaged=Select[averaged,#[[1]]=!=""&&#[[1]]>exluded&];*)
(*averagedWithErrors=Select[averagedWithErrors,#[[1]]=!=""&&#[[1]]>exluded&];*)
(**)
(*averagedWithErrorsOnMean=Select[averagedWithErrorsOnMean,#[[1]]=!=""&&#[[1]]>exluded&];*)
(*averagedWithErrorsOnMeanPurged=Select[averagedWithErrorsOnMeanPurged,#[[1]]=!=""&&#[[1]]>exluded&];*)
(**)
(*averagedWithMaxDev=Select[averagedWithMaxDev,#[[1]]=!=""&&#[[1]]>exluded&];*)
(*(*averagedWithEstimatedStdDevs=Select[averagedWithEstimatedStdDevs,#[[1]]=!=""&];*)
(*averagedWithEstimatedStdDevsOnMean=Select[averagedWithEstimatedStdDevsOnMean,#[[1]]=!=""&];*)*)


(* ::Input:: *)
(*logAveraged=Log[averaged];*)
(*logAveragedWithErrors=Log[averagedWithErrors](*/. 0->Around[1.0`*^-6,1.0`*^-6]*);*)
(**)
(*logAveragedWithErrorsOnMean=Log[averagedWithErrorsOnMean](*/. 0->Around[1.0`*^-6,1.0`*^-6]*);*)
(*logAveragedWithErrorsOnMeanPurged=Log[averagedWithErrorsOnMeanPurged](*/. 0->Around[1.0`*^-6,1.0`*^-6]*);*)
(**)
(*logAveragedWithMaxDev=Log[averagedWithMaxDev](*/. 0->Around[1.0`*^-6,1.0`*^-6]*);*)
(*(*logAveragedWithEstimatedStdDevs=Log[averagedWithEstimatedStdDevs]/. 0->Around[1.0`*^-6,1.0`*^-6];*)
(*logAveragedWithEstimatedStdDevsOnMean=Log[averagedWithEstimatedStdDevsOnMean]/. 0->Around[1.0`*^-6,1.0`*^-6];*)*)


(* ::Input:: *)
(*maxx=Max[averaged[[All,1]]];*)
(*maxy=Max[averaged[[All,2]]];*)
(**)
(*referencePlot=Plot[(x (1.624)-1.4),{x,Log[0+1],Log[maxx]},PlotStyle->{RGBColor[0, 0, 1],Dashed},PlotLegends->Placed[SwatchLegend[{"David Wilson: 1.624"}],Right]];*)
(**)
(* *)
(*Show[{ListPlot[logAveragedWithMaxDev,PlotStyle->{GrayLevel[0],Directive[Opacity[0.3]],PointSize->0.001},AxesLabel->{"Log[L]","Log[N]"}]*)
(*,ListPlot[logAveragedWithErrorsOnMeanPurged,PlotStyle->{RGBColor[0, 0.78, 1],PointSize->0.01},PlotLegends->PointLegend[{"logAveragedWithErrorsOnMeanPurged"},LegendMarkerSize->10,LegendMarkers->Graphics[Disk[]]]]*)
(*,ListPlot[logAveragedWithErrorsOnMean,PlotStyle->{RGBColor[1, 0.55, 1],Directive[Opacity[0.6]],PointSize->0.005},PlotLegends->PointLegend[{"logAveragedWithErrorsOnMean"},LegendMarkerSize->10,LegendMarkers->Graphics[Disk[]]]]*)
(*,referencePlot}*)
(*,PlotLabel->Row[{" b = ",b}],PlotRange->{All,{0,Log[maxy]}},AxesOrigin->{1,0},ImageSize->700]*)


(* ::Input:: *)
(*normalizeWithReference:=Plus[{0,-#[[1]]*1.624+1.4},#]&;*)
(**)
(*logAveragedRefNorm=normalizeWithReference/@logAveraged;*)
(*logAveragedWithErrorsRefNorm=normalizeWithReference/@logAveragedWithErrors;*)
(**)
(*logAveragedWithErrorsOnMeanRefNorm=normalizeWithReference/@logAveragedWithErrorsOnMean;*)
(*logAveragedWithErrorsOnMeanPurgedRefNorm=normalizeWithReference/@logAveragedWithErrorsOnMeanPurged;*)
(**)
(*logAveragedWithMaxDevRefNorm=normalizeWithReference/@logAveragedWithMaxDev;*)
(**)
(*maxx=Max[logAveragedWithMaxDevRefNorm[[All,1]]];*)
(*{miny,maxy}=MinMax[logAveragedWithMaxDevRefNorm[[All,2,1]]];*)
(* *)
(*Show[{(*ListPlot[logAveragedWithMaxDevRefNorm,PlotStyle->{,Directive[Opacity[0.3]],PointSize->0.001}]*)
(*,*)ListPlot[logAveragedWithErrorsOnMeanPurgedRefNorm,PlotStyle->{RGBColor[0, 0.78, 1],PointSize->0.01},PlotLegends->PointLegend[{"logAveragedWithErrorsOnMeanPurgedRefNorm"},LegendMarkerSize->10,LegendMarkers->Graphics[Disk[]]]]*)
(*,ListPlot[logAveragedWithErrorsOnMeanRefNorm,PlotStyle->{RGBColor[1, 0.55, 1],Directive[Opacity[0.6]],PointSize->0.005},PlotLegends->PointLegend[{"logAveragedWithErrorsOnMeanRefNorm"},LegendMarkerSize->10,LegendMarkers->Graphics[Disk[]]]]*)
(*,Plot[((0)),{x,Log[0+1],maxx},PlotStyle->{RGBColor[0, 0, 1],Dashed},PlotLegends->Placed[SwatchLegend[{"David Wilson: 1.624"}],Right]]*)
(*}*)
(*,PlotLabel->Row[{" b = ",b}],AxesLabel->{"Log[L]","Log[N]"},PlotRange->{{0,maxx},{-0.5,maxy}},AxesOrigin->{1,0},ImageSize->700]*)


(* ::Subsection:: *)
(*Take the Log WITH A SHIFT*)


(* ::Subsubsection::Closed:: *)
(*Check for best shift using \[Chi]^2 to test fit *)


(* ::Input:: *)
(*(*shift:=Plus[{+3,0},#]&; (*In the code, the stopping condition is with R-1*)*)
(**)
(*logAveragedWithErrorsOnMeanPurgedShifted=Log[shift/@averagedWithErrorsOnMeanPurged](*/. 0->Around[1.0`*^-6,1.0`*^-6]*);*)
(**)
(*fitFunc=a+c Exp[-x]+df  x*)
(**)
(*fit=Quiet[NonlinearModelFit[logAveragedWithErrorsOnMeanPurgedShifted,fitFunc,{a,c,df(*,{df,1.024}*)},x,MaxIterations->1000,Method->"NMinimize"],NonlinearModelFit::lmnl];*)
(**)
(*fit["ParameterTable"]*)
(*fit["ANOVATable"]*)
(*%[[1,1(*,2,2*)]]*)
(*fit["ANOVATableEntries"]*)
(**)
(*{fit["ParameterTable"][[1,1,-1,2]](*Slope*),*)
(*fit["ParameterTable"][[1,1,-1,3]](*Slope Error*),*)
(*fit["ANOVATableEntries"][[2,2]]/fit["ANOVATableEntries"][[2,1]](*Reduced Chi^2*)}*)
(*Clear[fit]*)*)


(* ::Input:: *)
(*(*Sort data ascending by x*)*)
(*(*dataSorted=SortBy[logAveragedWithErrorsOnMeanPurged,First];*)*)
(*fitFunc=a+0c Exp[-x]+df  x;*)
(*fitPar={a,(*c,*)df} ;*)
(**)
(*(*Scan across cutoff values xMin*)*)
(*scanResults=ParallelTable[With[{shift:=Plus[{-shiftValue,0},#]&},*)
(*With[{shiftedData=Log[Select[shift/@averagedWithErrorsOnMeanPurged,#[[1]]>0&]]},*)
(*Module[*)
(*{fit=Quiet[NonlinearModelFit[shiftedData,fitFunc,fitPar,x,MaxIterations->1000,Method->"NMinimize",VarianceEstimatorFunction->(1&)],NonlinearModelFit::lmnl]},*)
(**)
(*{shiftValue,fit["ParameterTable"][[1,1,-1,2]](*Slope*),*)
(*fit["ParameterTable"][[1,1,-1,3]](*Slope Error*),*)
(*fit["ANOVATableEntries"][[2,2]]/fit["ANOVATableEntries"][[2,1]](*Reduced Chi^2*)}]*)
(*]],*)
(*{shiftValue,1,3,0.1}];*)


(* ::Input:: *)
(*{min\[Chi]position,min\[Chi]}=Flatten@MinimalBy[scanResults[[All,{1,4}]],#[[2]]&]*)
(**)
(*(*1. Plot Reduced Chi^2 vs xMin*)*)
(*ListLinePlot[scanResults[[All,{1,4}]],AxesLabel->{"shift","Reduced Chi^2"},PlotRange->All,GridLines->{{min\[Chi]position},{1}}]*)
(**)
(*(*2. Plot Fitted Slope vs xMin with error bands*)*)
(*ListPlot[Table[{r[[1]],Around[r[[2]],r[[3]]]},{r,scanResults}],AxesLabel->{"shift","Slope"},PlotRange->All,GridLines->{{min\[Chi]position},None}]*)


(* ::Input:: *)
(*MinimalBy[scanResults(*[[All,{1,4}]]*),Last]*)
(**)
(*shift:=Plus[{-MinimalBy[scanResults(*[[All,{1,4}]]*),Last][[1,1]],0},#]&; (*In the code, the stopping condition is with R-1*)*)
(*(*shift:=Plus[{0,0},#]&;*)*)
(**)
(*logAveragedWithMaxDevShifted=Log[shift/@averagedWithMaxDev](*/. 0->Around[1.0`*^-6,1.0`*^-6]*);*)
(*logAveragedWithErrorsOnMeanShifted=Log[shift/@averagedWithErrorsOnMean](*/. 0->Around[1.0`*^-6,1.0`*^-6]*);*)
(*logAveragedWithErrorsOnMeanPurgedShifted=Log[shift/@averagedWithErrorsOnMeanPurged](*/. 0->Around[1.0`*^-6,1.0`*^-6]*);*)
(**)
(*(*fitFunc=a+c Exp[-x]+df  x;*)*)
(**)
(*nlmAveragedWithStdDevsUnconstrainedGlobalPurged=Quiet[NonlinearModelFit[logAveragedWithErrorsOnMeanPurgedShifted,fitFunc,fitPar,x,MaxIterations->1000,Method->"NMinimize"],NonlinearModelFit::lmnl];*)
(**)
(*maxx=Max[averaged[[All,1]]];*)
(*maxy=Max[averaged[[All,2]]];*)
(**)
(*thresholdBelow=0;*)
(*thresholdAbove=maxx-0;*)
(**)
(*Show[{ListPlot[logAveragedWithMaxDevShifted,PlotStyle->{GrayLevel[0],Directive[Opacity[0.3]],PointSize->0.001},AxesLabel->{"Log[L]","Log[N]"}]*)
(*,ListPlot[logAveragedWithErrorsOnMeanPurgedShifted,PlotStyle->{RGBColor[0, 0.78, 1],PointSize->0.01},PlotLegends->PointLegend[{"logAveragedWithErrorsOnMeanPurgedShifted"},LegendMarkerSize->10,LegendMarkers->Graphics[Disk[]]]]*)
(*,ListPlot[logAveragedWithErrorsOnMeanShifted,PlotStyle->{RGBColor[1, 0.55, 1],Directive[Opacity[0.6]],PointSize->0.005},PlotLegends->PointLegend[{"logAveragedWithErrorsOnMeanShifted"},LegendMarkerSize->10,LegendMarkers->Graphics[Disk[]]]]*)
(*,*)
(*Plot[ReleaseHold[#][x],{x,Log[thresholdBelow+1],Log[thresholdAbove]},PlotStyle->{RGBColor[0.24, 0.68, 0.8],Thickness->0.002},PlotLegends->Placed[SwatchLegend[{Row[{#,":\n ",TraditionalForm[ReleaseHold[#][x]]}]}],Right]]&@HoldForm[nlmAveragedWithStdDevsUnconstrainedGlobalPurged]*)
(*,Plot[(x (1.624)-1.4),{x,Log[0+1],Log[maxx]},PlotStyle->{RGBColor[0, 0, 1],Dashed},PlotLegends->Placed[SwatchLegend[{"David Wilson: 1.624"}],Right]]*)
(*}*)
(*,PlotLabel->Row[{" b = ",b}]*)
(*,PlotRange->{All,{0,All}},AxesOrigin->{1,0},ImageSize->700]*)
(**)
(**)


(* ::Input:: *)
(*measuredb1=Around[nlmAveragedWithStdDevsUnconstrainedGlobalPurged["ParameterTable"][[1,1,-1,2]],nlmAveragedWithStdDevsUnconstrainedGlobalPurged["ParameterTable"][[1,1,-1,3]]*4]*)


(* ::Input:: *)
(*ListPlot[Transpose[{logAveragedWithErrorsOnMeanPurged[[All,1]],nlmAveragedWithStdDevsUnconstrainedGlobalPurged["FitResiduals"]}],Filling->Axis,*)
(*AxesLabel->{"x","Residuals (y - y_fit)"},PlotLabel->"FitResiduals - nlmAveragedWithStdDevsUnconstrainedGlobalPurged",ImageSize->Large]*)


(* ::Subsubsection:: *)
(*Check for best shift using \[Chi]^2 to test linearity Dropping some too*)


(* ::Input:: *)
(*(*dataPurged=Delete[SortBy[averagedWithErrorsOnMeanPurged,First],{{1},{2},{3},{4}(*,{5},{6},{7},{8},{9}*)}];*)*)
(*(*dataPurged=Drop[SortBy[averagedWithErrorsOnMeanPurged,First],8];*)*)
(**)
(*fitFunc=a+0c Exp[-x]+df  x;*)
(*fitPar={a,(*c,*)df};*)
(**)
(*averagedWithErrorsOnMeanPurgedSorted=SortBy[averagedWithErrorsOnMeanPurged,First];*)
(*(*Scan across cutoff values xMin*)*)
(*scanResultsRaw=*)
(*ParallelTable[With[{dataPurged=Drop[averagedWithErrorsOnMeanPurgedSorted,dropFirstn]},*)
(*Table[With[{shift:=Plus[{-shiftValue,0},#]&},*)
(*With[{shiftedData=Log[Select[shift/@dataPurged,#[[1]]>0&]](*/. 0->Around[1.0`*^-6,1.0`*^-6]*)},*)
(*Module[*)
(*{fit=LinearModelFit[shiftedData,x,x,Weights->Automatic,VarianceEstimatorFunction->(1&)]},*)
(**)
(*{shiftValue,*)
(*fit["ParameterTable"][[1,1,3,2]](*Slope*),*)
(*fit["ParameterTable"][[1,1,3,3]](*Slope Error*),*)
(*fit["ANOVATableEntries"][[2,2]]/fit["ANOVATableEntries"][[2,1]](*Reduced Chi^2*),*)
(*dropFirstn}]*)
(*]],*)
(*{shiftValue,0,4,0.5}]],*)
(*{dropFirstn,13,18(*Length[averagedWithErrorsOnMeanPurgedSorted]-3*)}];*)
(**)
(*scanResults=Flatten[scanResultsRaw,1];*)


(* ::Input:: *)
(*Mean[Around[#[[1]],#[[2]]*3]&/@(MinimalBy[scanResults(*[[All,{1,4}]]*),Abs[#[[4]]-1]&,4][[All,{2,3}]])]*)


(* ::Input:: *)
(*MinimalBy[scanResults(*[[All,{1,4}]]*),Abs[#[[4]]-1]&,17]*)
(*minBy\[Chi]=%[[3]]*)
(*{min\[Chi]position,associatedSlope,min\[Chi]}=%[[{1,2,4}]](*Flatten@MinimalBy[scanResults[[All,{1,4}]],#[[2]]&]*)*)
(**)
(*(*1. Plot Reduced Chi^2 vs xMin*)*)
(*ListLinePlot[#[[All,All,{1,4}]],AxesLabel->{"shift","Reduced Chi^2"},PlotRange->{All,{0,100}},GridLines->{{min\[Chi]position,Thick},{1,Thick}},PlotLegends->LineLegend[#[[All,1,5]],LegendLabel->"Dropped:"],ScalingFunctions->"Log"(*,PlotLabel->{Row[{"Dropped first ",#[[5]]}]}*)]&@scanResultsRaw*)
(**)
(*(*2. Plot Fitted Slope vs xMin with error bands*)*)
(*ListPlot[Table[{r[[1]],Around[r[[2]],r[[3]]]},{r,#}]&/@#,AxesLabel->{"shift","Slope"},PlotRange->All,GridLines->{{min\[Chi]position},{associatedSlope}},PlotLegends->LineLegend[#[[All,1,5]],LegendLabel->"Dropped:"]]&@scanResultsRaw*)


(* ::Input:: *)
(*(*MinimalBy[scanResults(*[[All,{1,4}]]*),#[[4]]&]*)*)
(**)
(*shift:=Plus[{-minBy\[Chi][[1]],0},#]&; (*In the code, the stopping condition is with R-1*)*)
(**)
(*logAveragedWithMaxDevShifted=Log[shift/@averagedWithMaxDev](*/. 0->Around[1.0`*^-6,1.0`*^-6]*);*)
(*logAveragedWithErrorsOnMeanShifted=Log[shift/@averagedWithErrorsOnMean](*/. 0->Around[1.0`*^-6,1.0`*^-6]*);*)
(**)
(*dataPurged=Drop[SortBy[averagedWithErrorsOnMeanPurged,First],minBy\[Chi][[5]]];*)
(*logAveragedWithErrorsOnMeanPurgedShifted=Log[shift/@dataPurged](*/. 0->Around[1.0`*^-6,1.0`*^-6]*);*)
(**)
(**)
(*fitFunc=a+0c Exp[-x]+df  x;*)
(*fitPar={a,(*c,*)df};*)
(**)
(**)
(*nlmAveragedWithStdDevsUnconstrainedGlobalPurged=Quiet[NonlinearModelFit[logAveragedWithErrorsOnMeanPurgedShifted,fitFunc,fitPar,x,MaxIterations->1000,Method->"NMinimize"],NonlinearModelFit::lmnl];*)
(**)
(*maxx=Max[averaged[[All,1]]];*)
(*maxy=Max[averaged[[All,2]]];*)
(**)
(*thresholdBelow=0;*)
(*thresholdAbove=maxx-0;*)
(**)
(*Show[{ListPlot[logAveragedWithMaxDevShifted,PlotStyle->{GrayLevel[0],Directive[Opacity[0.3]],PointSize->0.001},AxesLabel->{"Log[L]","Log[N]"}]*)
(*,ListPlot[logAveragedWithErrorsOnMeanPurgedShifted,PlotStyle->{RGBColor[0, 0.78, 1],PointSize->0.01},PlotLegends->PointLegend[{"logAveragedWithErrorsOnMeanPurgedShifted"},LegendMarkerSize->10,LegendMarkers->Graphics[Disk[]]]]*)
(*,ListPlot[logAveragedWithErrorsOnMeanShifted,PlotStyle->{RGBColor[1, 0.55, 1],Directive[Opacity[0.6]],PointSize->0.005},PlotLegends->PointLegend[{"logAveragedWithErrorsOnMeanShifted"},LegendMarkerSize->10,LegendMarkers->Graphics[Disk[]]]]*)
(*,*)
(*Plot[ReleaseHold[#][x],{x,Log[thresholdBelow+1],Log[thresholdAbove]},PlotStyle->{RGBColor[0.24, 0.68, 0.8],Thickness->0.002},PlotLegends->Placed[SwatchLegend[{Row[{#,":\n ",TraditionalForm[ReleaseHold[#][x]]}]}],Right]]&@HoldForm[nlmAveragedWithStdDevsUnconstrainedGlobalPurged]*)
(*,referencePlot*)
(*}*)
(*,PlotLabel->Row[{" b = ",b}]*)
(*,PlotRange->{All,{0,All}},AxesOrigin->{1,0},ImageSize->700]*)
(**)
(**)


(* ::Input:: *)
(*measuredb1=Around[nlmAveragedWithStdDevsUnconstrainedGlobalPurged["ParameterTable"][[1,1,-1,2]],nlmAveragedWithStdDevsUnconstrainedGlobalPurged["ParameterTable"][[1,1,-1,3]]*4]*)


(* ::Input:: *)
(*ListPlot[Transpose[{logAveragedWithErrorsOnMeanPurgedShifted[[All,1]],nlmAveragedWithStdDevsUnconstrainedGlobalPurged["FitResiduals"]}],Filling->Axis,*)
(*AxesLabel->{"x","Residuals (y - y_fit)"},PlotLabel->"FitResiduals - nlmAveragedWithStdDevsUnconstrainedGlobalPurged",ImageSize->Large]*)


(* ::Section::Closed:: *)
(*b=3		still needs more statistics: 1.560 \[PlusMinus] 0.016 *)
(*		(Using more estimates and then mean 1.534 \[PlusMinus] 0.006)*)


(* ::Input:: *)
(*b=3;*)
(**)
(*rawData=Import["data3-3d-HaloAndHybrid.mx"];*)
(**)
(*Length[rawData]*)
(*Developer`PackedArrayQ[rawData]*)


(* ::Subsubsection::Closed:: *)
(*Run once to export MX file*)


(* ::Input:: *)
(*rawData=Import["D:\\Offline_Documents\\University\\PhD_Paris\\PhD_work\\Simulations\\bLRW\\b-LRWdata\\3d-FromCluster\\b3-3d-clean_merged_data-HaloAndHybrid.csv","CSV"];*)
(*(*Immediately lock it into a Packed Array*)*)
(*rawData=Developer`ToPackedArray[rawData];*)
(* (* MODIFY FILE NAME *)*)
(**)
(*Length[rawData]*)
(*rawData=Cases[rawData,{_?NumericQ,_?NumericQ}];*)
(*Length[rawData]*)
(*rawData=Developer`ToPackedArray[rawData];*)
(*Developer`PackedArrayQ[rawData]*)


(* ::Input:: *)
(*Export["data3-3d-HaloAndHybrid.mx",rawData,"MX"]*)


(* ::Subsection::Closed:: *)
(*GatherBy x values*)


(* ::Input:: *)
(*(*1. Gather rows by their first element (x) at C-speed*)*)
(*gathered=GatherBy[rawData,First];*)
(**)
(*(*2. Extract the unique X values directly from the gathered groups*)*)
(*xValues=gathered[[All,1,1]];*)
(**)
(*(*3. Extract the Y values for each group*)*)
(*yGroups=gathered[[All,All,2]];*)
(**)
(*(*4. Map Mean and StandardDeviation across the groups in bulk*)*)
(*means=Mean/@yGroups/. 0.->1.0`*^-8;*)
(**)
(*(*Standard deviation throws an error/indeterminacy if length is 1,so we replace Indeterminate with 0 globally at the end*)*)
(*stdDevs=Check[StandardDeviation[#],missing](*/Sqrt[Length[#]]*)&/@yGroups(*/. Indeterminate->1.0`*^-8*);*)


(* ::Input:: *)
(*(*Position[yGroups,_?(Length[#]<50&),1]*)
(*yGroups[[Rest[Flatten@%]]]*)*)


(* ::Input:: *)
(*missingIndices=Flatten@Position[stdDevs,missing]*)
(**)
(*Part[#,missingIndices]&/@{means,stdDevs}*)
(*Times@@%*)
(*stdDevs[[missingIndices]]=%/.missing->Mean[Select[stdDevs/means//N,FreeQ[#,missing]&]]//N*)


(* ::Input:: *)
(*stdDevs=stdDevs/. 0.->1.0`*^-8;*)
(*(* stdDev on mean*)*)
(*stdDevsOnMean=(1/Sqrt[Length[#]]&/@yGroups)*stdDevs;*)
(**)
(*(* Maximum deviation*)*)
(*maxDevsPlus=MapThread[Max[#2-#1]&,{means//N,yGroups}]/. 0.->1.0`*^-8;*)
(*maxDevsMinus=MapThread[Min[#2-#1]&,{means//N,yGroups}]/. 0.->1.0`*^-8;*)
(**)
(*(*5. Combine them using the Threaded Around wrapper*)*)
(*averaged=Transpose[{xValues,means}];*)
(*averagedWithErrors=Transpose[{xValues,MapThread[Around,{means,stdDevs}]}];*)
(*averagedWithErrorsOnMean=Transpose[{xValues,MapThread[Around,{means,stdDevsOnMean}]}];*)
(*averagedWithMaxDev=Transpose[{xValues,MapThread[Around,{means,Transpose[{maxDevsMinus,maxDevsPlus}]}]}];*)
(**)
(*(*Drop points with low statistic*)*)
(*averagedWithErrorsOnMeanPurged=Delete[averagedWithErrorsOnMean,Rest[Position[yGroups,_?(Length[#]<1700&),{1}]]];*)
(*Length@averagedWithErrorsOnMean*)
(*Length@averagedWithErrorsOnMeanPurged*)
(**)
(*Export["averaged-b3.mx",{averaged,averagedWithErrors,averagedWithErrorsOnMean,averagedWithErrorsOnMeanPurged,averagedWithMaxDev,b},"MX"]*)


(* ::Input:: *)
(*(*NOT USING IT*)
(**)
(* Remove the Sqrt[N] factor from the StdDev estimates*)*)
(*(*MapThread[Times[#1,Sqrt[#2]]&,{stdDevs,yGroups}]*)
(**)
(*averagedWithErrors=Transpose[{xValues,MapThread[Around,{means,%}]}];*)*)


(* ::Input:: *)
(*(**)
(*(*Standard deviation with my code (Kay's trick for better estimate)*)*)
(*stdDevsEstimated=StdDevEstimate[#,280,"print"->tTrue]&/@yGroups/. Indeterminate->1.0`*^-8;*)
(*stdDevsEstimated=stdDevsEstimated/. 0.->1.0`*^-8;*)
(**)
(*averagedWithEstimatedStdDevs=Transpose[{xValues,MapThread[Around,{means,stdDevsEstimated}]}];*)*)


(* ::Subsection:: *)
(*Take the Log*)


(* ::Input:: *)
(*{averaged,averagedWithErrors,averagedWithErrorsOnMean,averagedWithErrorsOnMeanPurged,averagedWithMaxDev,b}=Import["averaged-b3.mx"];*)


(* ::Input:: *)
(*(*(*Drop points with low statistic*)*)
(*averagedWithErrorsOnMeanPurged=Delete[averagedWithErrorsOnMean,Rest[Position[yGroups,_?(Length[#]<1700&),{1}]]];*)
(*Length@averagedWithErrorsOnMean*)
(*Length@averagedWithErrorsOnMeanPurged*)*)


(* ::Input:: *)
(*exluded=5;*)
(**)
(*averaged=Select[averaged,#[[1]]=!=""&&#[[1]]>exluded&];*)
(*averagedWithErrors=Select[averagedWithErrors,#[[1]]=!=""&&#[[1]]>exluded&];*)
(**)
(*averagedWithErrorsOnMean=Select[averagedWithErrorsOnMean,#[[1]]=!=""&&#[[1]]>exluded&];*)
(*averagedWithErrorsOnMeanPurged=Select[averagedWithErrorsOnMeanPurged,#[[1]]=!=""&&#[[1]]>exluded&];*)
(**)
(*averagedWithMaxDev=Select[averagedWithMaxDev,#[[1]]=!=""&&#[[1]]>exluded&];*)
(*(*averagedWithEstimatedStdDevs=Select[averagedWithEstimatedStdDevs,#[[1]]=!=""&];*)
(*averagedWithEstimatedStdDevsOnMean=Select[averagedWithEstimatedStdDevsOnMean,#[[1]]=!=""&];*)*)


(* ::Input:: *)
(*logAveraged=Log[averaged];*)
(*logAveragedWithErrors=Log[averagedWithErrors](*/. 0->Around[1.0`*^-6,1.0`*^-6]*);*)
(**)
(*logAveragedWithErrorsOnMean=Log[averagedWithErrorsOnMean](*/. 0->Around[1.0`*^-6,1.0`*^-6]*);*)
(*logAveragedWithErrorsOnMeanPurged=Log[averagedWithErrorsOnMeanPurged](*/. 0->Around[1.0`*^-6,1.0`*^-6]*);*)
(**)
(*logAveragedWithMaxDev=Log[averagedWithMaxDev](*/. 0->Around[1.0`*^-6,1.0`*^-6]*);*)
(*(*logAveragedWithEstimatedStdDevs=Log[averagedWithEstimatedStdDevs]/. 0->Around[1.0`*^-6,1.0`*^-6];*)
(*logAveragedWithEstimatedStdDevsOnMean=Log[averagedWithEstimatedStdDevsOnMean]/. 0->Around[1.0`*^-6,1.0`*^-6];*)*)


(* ::Input:: *)
(*maxx=Max[averaged[[All,1]]];*)
(*maxy=Max[averaged[[All,2]]];*)
(**)
(*referencePlot=Plot[(x (#)-1.42),{x,Log[0+1],Log[maxx]},PlotStyle->{RGBColor[0, 0, 1],Dashed},PlotLegends->Placed[SwatchLegend[{Row[{"Guessed by eye: ",#}]}],Right]]&@1.52;*)
(* *)
(*Show[{ListPlot[logAveragedWithMaxDev,PlotStyle->{GrayLevel[0],Directive[Opacity[0.3]],PointSize->0.001},AxesLabel->{"Log[L]","Log[N]"}]*)
(*,ListPlot[logAveragedWithErrorsOnMeanPurged,PlotStyle->{RGBColor[0, 0.78, 1],PointSize->0.01},PlotLegends->PointLegend[{"logAveragedWithErrorsOnMeanPurged"},LegendMarkerSize->10,LegendMarkers->Graphics[Disk[]]]]*)
(*,ListPlot[logAveragedWithErrorsOnMean,PlotStyle->{RGBColor[1, 0.55, 1],Directive[Opacity[0.6]],PointSize->0.005},PlotLegends->PointLegend[{"logAveragedWithErrorsOnMean"},LegendMarkerSize->10,LegendMarkers->Graphics[Disk[]]]]*)
(*,referencePlot*)
(*}*)
(*,PlotLabel->Row[{" b = ",b}],PlotRange->{All,{0,Log[maxy]}},AxesOrigin->{1,0},ImageSize->700]*)


(* ::Input:: *)
(*normalizeWithReference:=Plus[{0,-#[[1]]*1.52+1.46},#]&;*)
(**)
(*logAveragedRefNorm=normalizeWithReference/@logAveraged;*)
(*logAveragedWithErrorsRefNorm=normalizeWithReference/@logAveragedWithErrors;*)
(**)
(*logAveragedWithErrorsOnMeanRefNorm=normalizeWithReference/@logAveragedWithErrorsOnMean;*)
(*logAveragedWithErrorsOnMeanPurgedRefNorm=normalizeWithReference/@logAveragedWithErrorsOnMeanPurged;*)
(**)
(*logAveragedWithMaxDevRefNorm=normalizeWithReference/@logAveragedWithMaxDev;*)
(**)
(*maxx=Max[logAveragedWithMaxDevRefNorm[[All,1]]];*)
(*{miny,maxy}=MinMax[logAveragedWithMaxDevRefNorm[[All,2,1]]];*)
(* *)
(*Show[{(*ListPlot[logAveragedWithMaxDevRefNorm,PlotStyle->{,Directive[Opacity[0.3]],PointSize->0.001}]*)
(*,*)ListPlot[logAveragedWithErrorsOnMeanPurgedRefNorm,PlotStyle->{RGBColor[0, 0.78, 1],PointSize->0.01},PlotLegends->PointLegend[{"logAveragedWithErrorsOnMeanPurgedRefNorm"},LegendMarkerSize->10,LegendMarkers->Graphics[Disk[]]]]*)
(*,ListPlot[logAveragedWithErrorsOnMeanRefNorm,PlotStyle->{RGBColor[1, 0.55, 1],Directive[Opacity[0.6]],PointSize->0.005},PlotLegends->PointLegend[{"logAveragedWithErrorsOnMeanRefNorm"},LegendMarkerSize->10,LegendMarkers->Graphics[Disk[]]]]*)
(*}*)
(*,PlotLabel->Row[{" b = ",b}],AxesLabel->{"Log[L]","Log[N]"},PlotRange->{{0,maxx},{-0.5,maxy}},AxesOrigin->{1,0},ImageSize->700]*)


(* ::Subsection:: *)
(*Take the Log WITH A SHIFT*)


(* ::Subsubsection::Closed:: *)
(*Check for best shift using \[Chi]^2 to test fit *)


(* ::Input:: *)
(*(*shift:=Plus[{+3,0},#]&; (*In the code, the stopping condition is with R-1*)*)
(**)
(*logAveragedWithErrorsOnMeanPurgedShifted=Log[shift/@averagedWithErrorsOnMeanPurged](*/. 0->Around[1.0`*^-6,1.0`*^-6]*);*)
(**)
(*fitFunc=a+c Exp[-x]+df  x*)
(**)
(*fit=Quiet[NonlinearModelFit[logAveragedWithErrorsOnMeanPurgedShifted,fitFunc,{a,c,df(*,{df,1.024}*)},x,MaxIterations->1000,Method->"NMinimize"],NonlinearModelFit::lmnl];*)
(**)
(*fit["ParameterTable"]*)
(*fit["ANOVATable"]*)
(*%[[1,1(*,2,2*)]]*)
(*fit["ANOVATableEntries"]*)
(**)
(*{fit["ParameterTable"][[1,1,-1,2]](*Slope*),*)
(*fit["ParameterTable"][[1,1,-1,3]](*Slope Error*),*)
(*fit["ANOVATableEntries"][[2,2]]/fit["ANOVATableEntries"][[2,1]](*Reduced Chi^2*)}*)
(*Clear[fit]*)*)


(* ::Input:: *)
(*(*Sort data ascending by x*)*)
(*(*dataSorted=SortBy[logAveragedWithErrorsOnMeanPurged,First];*)*)
(*fitFunc=a+0c Exp[-x]+df  x;*)
(*fitPar={a,(*c,*)df} ;*)
(**)
(*(*Scan across cutoff values xMin*)*)
(*scanResults=ParallelTable[With[{shift:=Plus[{-shiftValue,0},#]&},*)
(*With[{shiftedData=Log[Select[shift/@averagedWithErrorsOnMeanPurged,#[[1]]>0&]]},*)
(*Module[*)
(*{fit=Quiet[NonlinearModelFit[shiftedData,fitFunc,fitPar,x,MaxIterations->1000,Method->"NMinimize",VarianceEstimatorFunction->(1&)],NonlinearModelFit::lmnl]},*)
(**)
(*{shiftValue,fit["ParameterTable"][[1,1,-1,2]](*Slope*),*)
(*fit["ParameterTable"][[1,1,-1,3]](*Slope Error*),*)
(*fit["ANOVATableEntries"][[2,2]]/fit["ANOVATableEntries"][[2,1]](*Reduced Chi^2*)}]*)
(*]],*)
(*{shiftValue,1,3,0.1}];*)


(* ::Input:: *)
(*{min\[Chi]position,min\[Chi]}=Flatten@MinimalBy[scanResults[[All,{1,4}]],#[[2]]&]*)
(**)
(*(*1. Plot Reduced Chi^2 vs xMin*)*)
(*ListLinePlot[scanResults[[All,{1,4}]],AxesLabel->{"shift","Reduced Chi^2"},PlotRange->All,GridLines->{{min\[Chi]position},{1}}]*)
(**)
(*(*2. Plot Fitted Slope vs xMin with error bands*)*)
(*ListPlot[Table[{r[[1]],Around[r[[2]],r[[3]]]},{r,scanResults}],AxesLabel->{"shift","Slope"},PlotRange->All,GridLines->{{min\[Chi]position},None}]*)


(* ::Input:: *)
(*MinimalBy[scanResults(*[[All,{1,4}]]*),Last]*)
(**)
(*shift:=Plus[{-MinimalBy[scanResults(*[[All,{1,4}]]*),Last][[1,1]],0},#]&; (*In the code, the stopping condition is with R-1*)*)
(*(*shift:=Plus[{0,0},#]&;*)*)
(**)
(*logAveragedWithMaxDevShifted=Log[shift/@averagedWithMaxDev](*/. 0->Around[1.0`*^-6,1.0`*^-6]*);*)
(*logAveragedWithErrorsOnMeanShifted=Log[shift/@averagedWithErrorsOnMean](*/. 0->Around[1.0`*^-6,1.0`*^-6]*);*)
(*logAveragedWithErrorsOnMeanPurgedShifted=Log[shift/@averagedWithErrorsOnMeanPurged](*/. 0->Around[1.0`*^-6,1.0`*^-6]*);*)
(**)
(*(*fitFunc=a+c Exp[-x]+df  x;*)*)
(**)
(*nlmAveragedWithStdDevsUnconstrainedGlobalPurged=Quiet[NonlinearModelFit[logAveragedWithErrorsOnMeanPurgedShifted,fitFunc,fitPar,x,MaxIterations->1000,Method->"NMinimize"],NonlinearModelFit::lmnl];*)
(**)
(*maxx=Max[averaged[[All,1]]];*)
(*maxy=Max[averaged[[All,2]]];*)
(**)
(*thresholdBelow=0;*)
(*thresholdAbove=maxx-0;*)
(**)
(*Show[{ListPlot[logAveragedWithMaxDevShifted,PlotStyle->{GrayLevel[0],Directive[Opacity[0.3]],PointSize->0.001},AxesLabel->{"Log[L]","Log[N]"}]*)
(*,ListPlot[logAveragedWithErrorsOnMeanPurgedShifted,PlotStyle->{RGBColor[0, 0.78, 1],PointSize->0.01},PlotLegends->PointLegend[{"logAveragedWithErrorsOnMeanPurgedShifted"},LegendMarkerSize->10,LegendMarkers->Graphics[Disk[]]]]*)
(*,ListPlot[logAveragedWithErrorsOnMeanShifted,PlotStyle->{RGBColor[1, 0.55, 1],Directive[Opacity[0.6]],PointSize->0.005},PlotLegends->PointLegend[{"logAveragedWithErrorsOnMeanShifted"},LegendMarkerSize->10,LegendMarkers->Graphics[Disk[]]]]*)
(*,*)
(*Plot[ReleaseHold[#][x],{x,Log[thresholdBelow+1],Log[thresholdAbove]},PlotStyle->{RGBColor[0.24, 0.68, 0.8],Thickness->0.002},PlotLegends->Placed[SwatchLegend[{Row[{#,":\n ",TraditionalForm[ReleaseHold[#][x]]}]}],Right]]&@HoldForm[nlmAveragedWithStdDevsUnconstrainedGlobalPurged]*)
(*,Plot[(x (1.624)-1.4),{x,Log[0+1],Log[maxx]},PlotStyle->{RGBColor[0, 0, 1],Dashed},PlotLegends->Placed[SwatchLegend[{"David Wilson: 1.624"}],Right]]*)
(*}*)
(*,PlotLabel->Row[{" b = ",b}]*)
(*,PlotRange->{All,{0,All}},AxesOrigin->{1,0},ImageSize->700]*)
(**)
(**)


(* ::Input:: *)
(*measuredb1=Around[nlmAveragedWithStdDevsUnconstrainedGlobalPurged["ParameterTable"][[1,1,-1,2]],nlmAveragedWithStdDevsUnconstrainedGlobalPurged["ParameterTable"][[1,1,-1,3]]*4]*)


(* ::Input:: *)
(*ListPlot[Transpose[{logAveragedWithErrorsOnMeanPurged[[All,1]],nlmAveragedWithStdDevsUnconstrainedGlobalPurged["FitResiduals"]}],Filling->Axis,*)
(*AxesLabel->{"x","Residuals (y - y_fit)"},PlotLabel->"FitResiduals - nlmAveragedWithStdDevsUnconstrainedGlobalPurged",ImageSize->Large]*)


(* ::Subsubsection:: *)
(*Check for best shift using \[Chi]^2 to test linearity Dropping some too*)


(* ::Input:: *)
(*(*dataPurged=Delete[SortBy[averagedWithErrorsOnMeanPurged,First],{{1},{2},{3},{4}(*,{5},{6},{7},{8},{9}*)}];*)*)
(*(*dataPurged=Drop[SortBy[averagedWithErrorsOnMeanPurged,First],8];*)*)
(**)
(*fitFunc=a+0c Exp[-x]+df  x;*)
(*fitPar={a,(*c,*)df};*)
(**)
(*averagedWithErrorsOnMeanPurgedSorted=SortBy[averagedWithErrorsOnMeanPurged,First];*)
(*(*Scan across cutoff values xMin*)*)
(*scanResultsRaw=*)
(*Table[With[{dataPurged=Drop[averagedWithErrorsOnMeanPurgedSorted,dropFirstn]},*)
(*Table[With[{shift:=Plus[{-shiftValue,0},#]&},*)
(*With[{shiftedData=Log[Select[shift/@dataPurged,#[[1]]>0&]](*/. 0->Around[1.0`*^-6,1.0`*^-6]*)},*)
(*Module[*)
(*{fit=LinearModelFit[shiftedData,x,x,Weights->Automatic,VarianceEstimatorFunction->(1&)]},*)
(**)
(*{shiftValue,*)
(*fit["ParameterTable"][[1,1,3,2]](*Slope*),*)
(*fit["ParameterTable"][[1,1,3,3]](*Slope Error*),*)
(*fit["ANOVATableEntries"][[2,2]]/fit["ANOVATableEntries"][[2,1]](*Reduced Chi^2*),*)
(*dropFirstn}]*)
(*]],*)
(*{shiftValue,-10,5,0.5}]],*)
(*{dropFirstn,0,Length[averagedWithErrorsOnMeanPurgedSorted]-3}];*)
(**)
(*scanResults=Flatten[scanResultsRaw,1];*)


(* ::Input:: *)
(*Mean[Around[#[[1]],#[[2]]*3]&/@(MinimalBy[scanResults(*[[All,{1,4}]]*),Abs[#[[4]]-1]&,3][[All,{2,3}]])]*)


(* ::Input:: *)
(*MinimalBy[scanResults(*[[All,{1,4}]]*),Abs[#[[4]]-1]&,20]*)
(*minBy\[Chi]=%[[1]]*)
(*{min\[Chi]position,associatedSlope,min\[Chi]}=%[[{1,2,4}]](*Flatten@MinimalBy[scanResults[[All,{1,4}]],#[[2]]&]*)*)
(**)
(*(*1. Plot Reduced Chi^2 vs xMin*)*)
(*ListLinePlot[#[[All,All,{1,4}]],AxesLabel->{"shift","Reduced Chi^2"},PlotRange->{All,{0,100}},GridLines->{{min\[Chi]position},{1}},PlotLegends->LineLegend[#[[All,1,5]],LegendLabel->"Dropped:"],ScalingFunctions->"Log"(*,PlotLabel->{Row[{"Dropped first ",#[[5]]}]}*)]&@scanResultsRaw*)
(**)
(*(*2. Plot Fitted Slope vs xMin with error bands*)*)
(*ListPlot[Table[{r[[1]],Around[r[[2]],r[[3]]]},{r,#}]&/@#,AxesLabel->{"shift","Slope"},PlotRange->All,GridLines->{{min\[Chi]position},{associatedSlope}},PlotLegends->LineLegend[#[[All,1,5]],LegendLabel->"Dropped:"]]&@scanResultsRaw*)


(* ::Input:: *)
(*(*MinimalBy[scanResults(*[[All,{1,4}]]*),#[[4]]&]*)*)
(**)
(*shift:=Plus[{-minBy\[Chi][[1]],0},#]&; (*In the code, the stopping condition is with R-1*)*)
(**)
(*logAveragedWithMaxDevShifted=Log[shift/@averagedWithMaxDev](*/. 0->Around[1.0`*^-6,1.0`*^-6]*);*)
(*logAveragedWithErrorsOnMeanShifted=Log[shift/@averagedWithErrorsOnMean](*/. 0->Around[1.0`*^-6,1.0`*^-6]*);*)
(**)
(*dataPurged=Drop[SortBy[averagedWithErrorsOnMeanPurged,First],minBy\[Chi][[5]]];*)
(*logAveragedWithErrorsOnMeanPurgedShifted=Log[shift/@dataPurged](*/. 0->Around[1.0`*^-6,1.0`*^-6]*);*)
(**)
(**)
(*fitFunc=a+0c Exp[-x]+df  x;*)
(*fitPar={a,(*c,*)df};*)
(**)
(**)
(*nlmAveragedWithStdDevsUnconstrainedGlobalPurged=Quiet[NonlinearModelFit[logAveragedWithErrorsOnMeanPurgedShifted,fitFunc,fitPar,x,MaxIterations->1000,Method->"NMinimize"],NonlinearModelFit::lmnl];*)
(**)
(*maxx=Max[averaged[[All,1]]];*)
(*maxy=Max[averaged[[All,2]]];*)
(**)
(*thresholdBelow=0;*)
(*thresholdAbove=maxx-0;*)
(**)
(*Show[{ListPlot[logAveragedWithMaxDevShifted,PlotStyle->{GrayLevel[0],Directive[Opacity[0.3]],PointSize->0.001},AxesLabel->{"Log[L]","Log[N]"}]*)
(*,ListPlot[logAveragedWithErrorsOnMeanPurgedShifted,PlotStyle->{RGBColor[0, 0.78, 1],PointSize->0.01},PlotLegends->PointLegend[{"logAveragedWithErrorsOnMeanPurgedShifted"},LegendMarkerSize->10,LegendMarkers->Graphics[Disk[]]]]*)
(*,ListPlot[logAveragedWithErrorsOnMeanShifted,PlotStyle->{RGBColor[1, 0.55, 1],Directive[Opacity[0.6]],PointSize->0.005},PlotLegends->PointLegend[{"logAveragedWithErrorsOnMeanShifted"},LegendMarkerSize->10,LegendMarkers->Graphics[Disk[]]]]*)
(*,*)
(*Plot[ReleaseHold[#][x],{x,Log[thresholdBelow+1],Log[thresholdAbove]},PlotStyle->{RGBColor[0.24, 0.68, 0.8],Thickness->0.002},PlotLegends->Placed[SwatchLegend[{Row[{#,":\n ",TraditionalForm[ReleaseHold[#][x]]}]}],Right]]&@HoldForm[nlmAveragedWithStdDevsUnconstrainedGlobalPurged]*)
(*,referencePlot*)
(*}*)
(*,PlotLabel->Row[{" b = ",b}]*)
(*,PlotRange->{All,{0,All}},AxesOrigin->{1,0},ImageSize->700]*)
(**)
(**)


(* ::Input:: *)
(*measuredb3=Around[nlmAveragedWithStdDevsUnconstrainedGlobalPurged["ParameterTable"][[1,1,-1,2]],nlmAveragedWithStdDevsUnconstrainedGlobalPurged["ParameterTable"][[1,1,-1,3]]*4]*)


(* ::Input:: *)
(*ListPlot[Transpose[{logAveragedWithErrorsOnMeanPurgedShifted[[All,1]],nlmAveragedWithStdDevsUnconstrainedGlobalPurged["FitResiduals"]}],Filling->Axis,*)
(*AxesLabel->{"x","Residuals (y - y_fit)"},PlotLabel->"FitResiduals - nlmAveragedWithStdDevsUnconstrainedGlobalPurged",ImageSize->Large]*)


(* ::Section:: *)
(*b=4		still needs more statistics: 1.478 \[PlusMinus] 0.018*)
(*		(Using more estimates and then mean 1.489 \[PlusMinus] 0.006)*)


(* ::Input:: *)
(*b=4;*)
(**)
(*rawData=Import["data4-3d-HaloAndHybrid.mx"];*)
(**)
(*Length[rawData]*)
(*Developer`PackedArrayQ[rawData]*)


(* ::Subsubsection::Closed:: *)
(*Run once to export MX file*)


(* ::Input:: *)
(*rawData=Import["D:\\Offline_Documents\\University\\PhD_Paris\\PhD_work\\Simulations\\bLRW\\b-LRWdata\\3d-FromCluster\\b4-3d-clean_merged_data-HaloAndHybrid.csv","CSV"];*)
(*(*Immediately lock it into a Packed Array*)*)
(*rawData=Developer`ToPackedArray[rawData];*)
(* (* MODIFY FILE NAME *)*)
(**)
(*Length[rawData]*)
(*rawData=Cases[rawData,{_?NumericQ,_?NumericQ}];*)
(*Length[rawData]*)
(*rawData=Developer`ToPackedArray[rawData];*)
(*Developer`PackedArrayQ[rawData]*)


(* ::Input:: *)
(*Export["data4-3d-HaloAndHybrid.mx",rawData,"MX"]*)


(* ::Subsection::Closed:: *)
(*GatherBy x values*)


(* ::Input:: *)
(*(*1. Gather rows by their first element (x) at C-speed*)*)
(*gathered=GatherBy[rawData,First];*)
(**)
(*(*2. Extract the unique X values directly from the gathered groups*)*)
(*xValues=gathered[[All,1,1]];*)
(**)
(*(*3. Extract the Y values for each group*)*)
(*yGroups=gathered[[All,All,2]];*)
(**)
(*(*4. Map Mean and StandardDeviation across the groups in bulk*)*)
(*means=Mean/@yGroups/. 0.->1.0`*^-8;*)
(**)
(*(*Standard deviation throws an error/indeterminacy if length is 1,so we replace Indeterminate with 0 globally at the end*)*)
(*stdDevs=Check[StandardDeviation[#],missing](*/Sqrt[Length[#]]*)&/@yGroups(*/. Indeterminate->1.0`*^-8*);*)


(* ::Input:: *)
(*(*Position[yGroups,_?(Length[#]<50&),1]*)
(*yGroups[[Rest[Flatten@%]]]*)*)


(* ::Input:: *)
(*missingIndices=Flatten@Position[stdDevs,missing]*)
(**)
(*Part[#,missingIndices]&/@{means,stdDevs}*)
(*Times@@%*)
(*stdDevs[[missingIndices]]=%/.missing->Mean[Select[stdDevs/means//N,FreeQ[#,missing]&]]//N*)


(* ::Input:: *)
(*stdDevs=stdDevs/. 0.->1.0`*^-8;*)
(*(* stdDev on mean*)*)
(*stdDevsOnMean=(1/Sqrt[Length[#]]&/@yGroups)*stdDevs;*)
(**)
(*(* Maximum deviation*)*)
(*maxDevsPlus=MapThread[Max[#2-#1]&,{means//N,yGroups}]/. 0.->1.0`*^-8;*)
(*maxDevsMinus=MapThread[Min[#2-#1]&,{means//N,yGroups}]/. 0.->1.0`*^-8;*)
(**)
(*(*5. Combine them using the Threaded Around wrapper*)*)
(*averaged=Transpose[{xValues,means}];*)
(*averagedWithErrors=Transpose[{xValues,MapThread[Around,{means,stdDevs}]}];*)
(*averagedWithErrorsOnMean=Transpose[{xValues,MapThread[Around,{means,stdDevsOnMean}]}];*)
(*averagedWithMaxDev=Transpose[{xValues,MapThread[Around,{means,Transpose[{maxDevsMinus,maxDevsPlus}]}]}];*)
(**)
(*(*Drop points with low statistic*)*)
(*averagedWithErrorsOnMeanPurged=Delete[averagedWithErrorsOnMean,Rest[Position[yGroups,_?(Length[#]<2500&),{1}]]];*)
(*Length@averagedWithErrorsOnMean*)
(*Length@averagedWithErrorsOnMeanPurged*)
(**)
(*Export["averaged-b4.mx",{averaged,averagedWithErrors,averagedWithErrorsOnMean,averagedWithErrorsOnMeanPurged,averagedWithMaxDev,b},"MX"] *)


(* ::Input:: *)
(*(*NOT USING IT*)
(**)
(* Remove the Sqrt[N] factor from the StdDev estimates*)*)
(*(*MapThread[Times[#1,Sqrt[#2]]&,{stdDevs,yGroups}]*)
(**)
(*averagedWithErrors=Transpose[{xValues,MapThread[Around,{means,%}]}];*)*)


(* ::Input:: *)
(*(**)
(*(*Standard deviation with my code (Kay's trick for better estimate)*)*)
(*stdDevsEstimated=StdDevEstimate[#,280,"print"->tTrue]&/@yGroups/. Indeterminate->1.0`*^-8;*)
(*stdDevsEstimated=stdDevsEstimated/. 0.->1.0`*^-8;*)
(**)
(*averagedWithEstimatedStdDevs=Transpose[{xValues,MapThread[Around,{means,stdDevsEstimated}]}];*)*)


(* ::Subsection::Closed:: *)
(*Take the Log*)


(* ::Input:: *)
(*{averaged,averagedWithErrors,averagedWithErrorsOnMean,averagedWithErrorsOnMeanPurged,averagedWithMaxDev,b}=Import["averaged-b4.mx"];*)


(* ::Input:: *)
(*(*(*Drop points with low statistic*)*)
(*averagedWithErrorsOnMeanPurged=Delete[averagedWithErrorsOnMean,Rest[Position[yGroups,_?(Length[#]<2500&),{1}]]];*)
(*Length@averagedWithErrorsOnMean*)
(*Length@averagedWithErrorsOnMeanPurged*)*)


(* ::Input:: *)
(*exluded=5;*)
(**)
(*averaged=Select[averaged,#[[1]]=!=""&&#[[1]]>exluded&];*)
(*averagedWithErrors=Select[averagedWithErrors,#[[1]]=!=""&&#[[1]]>exluded&];*)
(**)
(*averagedWithErrorsOnMean=Select[averagedWithErrorsOnMean,#[[1]]=!=""&&#[[1]]>exluded&];*)
(*averagedWithErrorsOnMeanPurged=Select[averagedWithErrorsOnMeanPurged,#[[1]]=!=""&&#[[1]]>exluded&];*)
(**)
(*averagedWithMaxDev=Select[averagedWithMaxDev,#[[1]]=!=""&&#[[1]]>exluded&];*)
(*(*averagedWithEstimatedStdDevs=Select[averagedWithEstimatedStdDevs,#[[1]]=!=""&];*)
(*averagedWithEstimatedStdDevsOnMean=Select[averagedWithEstimatedStdDevsOnMean,#[[1]]=!=""&];*)*)


(* ::Input:: *)
(*logAveraged=Log[averaged];*)
(*logAveragedWithErrors=Log[averagedWithErrors](*/. 0->Around[1.0`*^-6,1.0`*^-6]*);*)
(**)
(*logAveragedWithErrorsOnMean=Log[averagedWithErrorsOnMean](*/. 0->Around[1.0`*^-6,1.0`*^-6]*);*)
(*logAveragedWithErrorsOnMeanPurged=Log[averagedWithErrorsOnMeanPurged](*/. 0->Around[1.0`*^-6,1.0`*^-6]*);*)
(**)
(*logAveragedWithMaxDev=Log[averagedWithMaxDev](*/. 0->Around[1.0`*^-6,1.0`*^-6]*);*)
(*(*logAveragedWithEstimatedStdDevs=Log[averagedWithEstimatedStdDevs]/. 0->Around[1.0`*^-6,1.0`*^-6];*)
(*logAveragedWithEstimatedStdDevsOnMean=Log[averagedWithEstimatedStdDevsOnMean]/. 0->Around[1.0`*^-6,1.0`*^-6];*)*)


(* ::Input:: *)
(*maxx=Max[averaged[[All,1]]];*)
(*maxy=Max[averaged[[All,2]]];*)
(**)
(*referencePlot=Plot[(x (#)-1.55),{x,Log[0+1],Log[maxx]},PlotStyle->{RGBColor[0, 0, 1],Dashed},PlotLegends->Placed[SwatchLegend[{Row[{"Guessed by eye: ",#}]}],Right]]&@1.49;*)
(* *)
(*Show[{ListPlot[logAveragedWithMaxDev,PlotStyle->{GrayLevel[0],Directive[Opacity[0.3]],PointSize->0.001},AxesLabel->{"Log[L]","Log[N]"}]*)
(*,ListPlot[logAveragedWithErrorsOnMeanPurged,PlotStyle->{RGBColor[0, 0.78, 1],PointSize->0.01},PlotLegends->PointLegend[{"logAveragedWithErrorsOnMeanPurged"},LegendMarkerSize->10,LegendMarkers->Graphics[Disk[]]]]*)
(*,ListPlot[logAveragedWithErrorsOnMean,PlotStyle->{RGBColor[1, 0.55, 1],Directive[Opacity[0.6]],PointSize->0.005},PlotLegends->PointLegend[{"logAveragedWithErrorsOnMean"},LegendMarkerSize->10,LegendMarkers->Graphics[Disk[]]]]*)
(*,referencePlot*)
(*}*)
(*,PlotLabel->Row[{" b = ",b}],PlotRange->{All,{0,Log[maxy]}},AxesOrigin->{1,0},ImageSize->700]*)


(* ::Input:: *)
(*normalizeWithReference:=Plus[{0,-#[[1]]*1.49+1.5},#]&;*)
(**)
(*logAveragedRefNorm=normalizeWithReference/@logAveraged;*)
(*logAveragedWithErrorsRefNorm=normalizeWithReference/@logAveragedWithErrors;*)
(**)
(*logAveragedWithErrorsOnMeanRefNorm=normalizeWithReference/@logAveragedWithErrorsOnMean;*)
(*logAveragedWithErrorsOnMeanPurgedRefNorm=normalizeWithReference/@logAveragedWithErrorsOnMeanPurged;*)
(**)
(*logAveragedWithMaxDevRefNorm=normalizeWithReference/@logAveragedWithMaxDev;*)
(**)
(*maxx=Max[logAveragedWithMaxDevRefNorm[[All,1]]];*)
(*{miny,maxy}=MinMax[logAveragedWithMaxDevRefNorm[[All,2,1]]];*)
(* *)
(*Show[{(*ListPlot[logAveragedWithMaxDevRefNorm,PlotStyle->{,Directive[Opacity[0.3]],PointSize->0.001}]*)
(*,*)ListPlot[logAveragedWithErrorsOnMeanPurgedRefNorm,PlotStyle->{RGBColor[0, 0.78, 1],PointSize->0.01},PlotLegends->PointLegend[{"logAveragedWithErrorsOnMeanPurgedRefNorm"},LegendMarkerSize->10,LegendMarkers->Graphics[Disk[]]]]*)
(*,ListPlot[logAveragedWithErrorsOnMeanRefNorm,PlotStyle->{RGBColor[1, 0.55, 1],Directive[Opacity[0.6]],PointSize->0.005},PlotLegends->PointLegend[{"logAveragedWithErrorsOnMeanRefNorm"},LegendMarkerSize->10,LegendMarkers->Graphics[Disk[]]]]*)
(*}*)
(*,PlotLabel->Row[{" b = ",b}],AxesLabel->{"Log[L]","Log[N]"},PlotRange->{{0,maxx},{-0.5,maxy}},AxesOrigin->{1,0},ImageSize->700]*)


(* ::Subsection:: *)
(*Take the Log WITH A SHIFT*)


(* ::Subsubsection::Closed:: *)
(*Check for best shift using \[Chi]^2 to test fit *)


(* ::Input:: *)
(*(*shift:=Plus[{+3,0},#]&; (*In the code, the stopping condition is with R-1*)*)
(**)
(*logAveragedWithErrorsOnMeanPurgedShifted=Log[shift/@averagedWithErrorsOnMeanPurged](*/. 0->Around[1.0`*^-6,1.0`*^-6]*);*)
(**)
(*fitFunc=a+c Exp[-x]+df  x*)
(**)
(*fit=Quiet[NonlinearModelFit[logAveragedWithErrorsOnMeanPurgedShifted,fitFunc,{a,c,df(*,{df,1.024}*)},x,MaxIterations->1000,Method->"NMinimize"],NonlinearModelFit::lmnl];*)
(**)
(*fit["ParameterTable"]*)
(*fit["ANOVATable"]*)
(*%[[1,1(*,2,2*)]]*)
(*fit["ANOVATableEntries"]*)
(**)
(*{fit["ParameterTable"][[1,1,-1,2]](*Slope*),*)
(*fit["ParameterTable"][[1,1,-1,3]](*Slope Error*),*)
(*fit["ANOVATableEntries"][[2,2]]/fit["ANOVATableEntries"][[2,1]](*Reduced Chi^2*)}*)
(*Clear[fit]*)*)


(* ::Input:: *)
(*(*Sort data ascending by x*)*)
(*(*dataSorted=SortBy[logAveragedWithErrorsOnMeanPurged,First];*)*)
(*fitFunc=a+0c Exp[-x]+df  x;*)
(*fitPar={a,(*c,*)df} ;*)
(**)
(*(*Scan across cutoff values xMin*)*)
(*scanResults=ParallelTable[With[{shift:=Plus[{-shiftValue,0},#]&},*)
(*With[{shiftedData=Log[Select[shift/@averagedWithErrorsOnMeanPurged,#[[1]]>0&]]},*)
(*Module[*)
(*{fit=Quiet[NonlinearModelFit[shiftedData,fitFunc,fitPar,x,MaxIterations->1000,Method->"NMinimize",VarianceEstimatorFunction->(1&)],NonlinearModelFit::lmnl]},*)
(**)
(*{shiftValue,fit["ParameterTable"][[1,1,-1,2]](*Slope*),*)
(*fit["ParameterTable"][[1,1,-1,3]](*Slope Error*),*)
(*fit["ANOVATableEntries"][[2,2]]/fit["ANOVATableEntries"][[2,1]](*Reduced Chi^2*)}]*)
(*]],*)
(*{shiftValue,1,3,0.1}];*)


(* ::Input:: *)
(*{min\[Chi]position,min\[Chi]}=Flatten@MinimalBy[scanResults[[All,{1,4}]],#[[2]]&]*)
(**)
(*(*1. Plot Reduced Chi^2 vs xMin*)*)
(*ListLinePlot[scanResults[[All,{1,4}]],AxesLabel->{"shift","Reduced Chi^2"},PlotRange->All,GridLines->{{min\[Chi]position},{1}}]*)
(**)
(*(*2. Plot Fitted Slope vs xMin with error bands*)*)
(*ListPlot[Table[{r[[1]],Around[r[[2]],r[[3]]]},{r,scanResults}],AxesLabel->{"shift","Slope"},PlotRange->All,GridLines->{{min\[Chi]position},None}]*)


(* ::Input:: *)
(*MinimalBy[scanResults(*[[All,{1,4}]]*),Last]*)
(**)
(*shift:=Plus[{-MinimalBy[scanResults(*[[All,{1,4}]]*),Last][[1,1]],0},#]&; (*In the code, the stopping condition is with R-1*)*)
(*(*shift:=Plus[{0,0},#]&;*)*)
(**)
(*logAveragedWithMaxDevShifted=Log[shift/@averagedWithMaxDev](*/. 0->Around[1.0`*^-6,1.0`*^-6]*);*)
(*logAveragedWithErrorsOnMeanShifted=Log[shift/@averagedWithErrorsOnMean](*/. 0->Around[1.0`*^-6,1.0`*^-6]*);*)
(*logAveragedWithErrorsOnMeanPurgedShifted=Log[shift/@averagedWithErrorsOnMeanPurged](*/. 0->Around[1.0`*^-6,1.0`*^-6]*);*)
(**)
(*(*fitFunc=a+c Exp[-x]+df  x;*)*)
(**)
(*nlmAveragedWithStdDevsUnconstrainedGlobalPurged=Quiet[NonlinearModelFit[logAveragedWithErrorsOnMeanPurgedShifted,fitFunc,fitPar,x,MaxIterations->1000,Method->"NMinimize"],NonlinearModelFit::lmnl];*)
(**)
(*maxx=Max[averaged[[All,1]]];*)
(*maxy=Max[averaged[[All,2]]];*)
(**)
(*thresholdBelow=0;*)
(*thresholdAbove=maxx-0;*)
(**)
(*Show[{ListPlot[logAveragedWithMaxDevShifted,PlotStyle->{GrayLevel[0],Directive[Opacity[0.3]],PointSize->0.001},AxesLabel->{"Log[L]","Log[N]"}]*)
(*,ListPlot[logAveragedWithErrorsOnMeanPurgedShifted,PlotStyle->{RGBColor[0, 0.78, 1],PointSize->0.01},PlotLegends->PointLegend[{"logAveragedWithErrorsOnMeanPurgedShifted"},LegendMarkerSize->10,LegendMarkers->Graphics[Disk[]]]]*)
(*,ListPlot[logAveragedWithErrorsOnMeanShifted,PlotStyle->{RGBColor[1, 0.55, 1],Directive[Opacity[0.6]],PointSize->0.005},PlotLegends->PointLegend[{"logAveragedWithErrorsOnMeanShifted"},LegendMarkerSize->10,LegendMarkers->Graphics[Disk[]]]]*)
(*,*)
(*Plot[ReleaseHold[#][x],{x,Log[thresholdBelow+1],Log[thresholdAbove]},PlotStyle->{RGBColor[0.24, 0.68, 0.8],Thickness->0.002},PlotLegends->Placed[SwatchLegend[{Row[{#,":\n ",TraditionalForm[ReleaseHold[#][x]]}]}],Right]]&@HoldForm[nlmAveragedWithStdDevsUnconstrainedGlobalPurged]*)
(*,Plot[(x (1.624)-1.4),{x,Log[0+1],Log[maxx]},PlotStyle->{RGBColor[0, 0, 1],Dashed},PlotLegends->Placed[SwatchLegend[{"David Wilson: 1.624"}],Right]]*)
(*}*)
(*,PlotLabel->Row[{" b = ",b}]*)
(*,PlotRange->{All,{0,All}},AxesOrigin->{1,0},ImageSize->700]*)
(**)
(**)


(* ::Input:: *)
(*measuredb1=Around[nlmAveragedWithStdDevsUnconstrainedGlobalPurged["ParameterTable"][[1,1,-1,2]],nlmAveragedWithStdDevsUnconstrainedGlobalPurged["ParameterTable"][[1,1,-1,3]]*4]*)


(* ::Input:: *)
(*ListPlot[Transpose[{logAveragedWithErrorsOnMeanPurged[[All,1]],nlmAveragedWithStdDevsUnconstrainedGlobalPurged["FitResiduals"]}],Filling->Axis,*)
(*AxesLabel->{"x","Residuals (y - y_fit)"},PlotLabel->"FitResiduals - nlmAveragedWithStdDevsUnconstrainedGlobalPurged",ImageSize->Large]*)


(* ::Subsubsection:: *)
(*Check for best shift using \[Chi]^2 to test linearity Dropping some too*)


(* ::Input:: *)
(*(*dataPurged=Delete[SortBy[averagedWithErrorsOnMeanPurged,First],{{1},{2},{3},{4}(*,{5},{6},{7},{8},{9}*)}];*)*)
(*(*dataPurged=Drop[SortBy[averagedWithErrorsOnMeanPurged,First],8];*)*)
(**)
(*fitFunc=a+0c Exp[-x]+df  x;*)
(*fitPar={a,(*c,*)df};*)
(**)
(*averagedWithErrorsOnMeanPurgedSorted=SortBy[averagedWithErrorsOnMeanPurged,First];*)
(*(*Scan across cutoff values xMin*)*)
(*scanResultsRaw=*)
(*ParallelTable[With[{dataPurged=Drop[averagedWithErrorsOnMeanPurgedSorted,dropFirstn]},*)
(*Table[With[{shift:=Plus[{-shiftValue,0},#]&},*)
(*With[{shiftedData=Log[Select[shift/@dataPurged,#[[1]]>0&]](*/. 0->Around[1.0`*^-6,1.0`*^-6]*)},*)
(*Module[*)
(*{fit=LinearModelFit[shiftedData,x,x,Weights->Automatic,VarianceEstimatorFunction->(1&)]},*)
(**)
(*{shiftValue,*)
(*fit["ParameterTable"][[1,1,3,2]](*Slope*),*)
(*fit["ParameterTable"][[1,1,3,3]](*Slope Error*),*)
(*fit["ANOVATableEntries"][[2,2]]/fit["ANOVATableEntries"][[2,1]](*Reduced Chi^2*),*)
(*dropFirstn}]*)
(*]],*)
(*{shiftValue,-4,3,0.5}]],*)
(*{dropFirstn,16,Length[averagedWithErrorsOnMeanPurgedSorted]-4}];*)
(**)
(*scanResults=Flatten[scanResultsRaw,1];*)


(* ::Input:: *)
(*Mean[Around[#[[1]],#[[2]]*3]&/@(MinimalBy[scanResults(*[[All,{1,4}]]*),Abs[#[[4]]-1]&,5][[All,{2,3}]])]*)


(* ::Input:: *)
(*MinimalBy[scanResults(*[[All,{1,4}]]*),Abs[#[[4]]-1]&,20]*)
(*minBy\[Chi]=%[[2]]*)
(*{min\[Chi]position,associatedSlope,min\[Chi]}=%[[{1,2,4}]](*Flatten@MinimalBy[scanResults[[All,{1,4}]],#[[2]]&]*)*)
(**)
(*(*1. Plot Reduced Chi^2 vs xMin*)*)
(*ListLinePlot[#[[All,All,{1,4}]],AxesLabel->{"shift","Reduced Chi^2"},PlotRange->{All,{0,100}},GridLines->{{min\[Chi]position},{1}},PlotLegends->LineLegend[#[[All,1,5]],LegendLabel->"Dropped:"],ScalingFunctions->"Log"(*,PlotLabel->{Row[{"Dropped first ",#[[5]]}]}*)]&@scanResultsRaw*)
(**)
(*(*2. Plot Fitted Slope vs xMin with error bands*)*)
(*ListPlot[Table[{r[[1]],Around[r[[2]],r[[3]]]},{r,#}]&/@#,AxesLabel->{"shift","Slope"},PlotRange->All,GridLines->{{min\[Chi]position},{associatedSlope}},PlotLegends->LineLegend[#[[All,1,5]],LegendLabel->"Dropped:"]]&@scanResultsRaw*)


(* ::Input:: *)
(*(*MinimalBy[scanResults(*[[All,{1,4}]]*),#[[4]]&]*)*)
(**)
(*shift:=Plus[{-minBy\[Chi][[1]],0},#]&; (*In the code, the stopping condition is with R-1*)*)
(**)
(*logAveragedWithMaxDevShifted=Log[shift/@averagedWithMaxDev](*/. 0->Around[1.0`*^-6,1.0`*^-6]*);*)
(*logAveragedWithErrorsOnMeanShifted=Log[shift/@averagedWithErrorsOnMean](*/. 0->Around[1.0`*^-6,1.0`*^-6]*);*)
(**)
(*dataPurged=Drop[SortBy[averagedWithErrorsOnMeanPurged,First],minBy\[Chi][[5]]];*)
(*logAveragedWithErrorsOnMeanPurgedShifted=Log[shift/@dataPurged](*/. 0->Around[1.0`*^-6,1.0`*^-6]*);*)
(**)
(**)
(*fitFunc=a+0c Exp[-x]+df  x;*)
(*fitPar={a,(*c,*)df};*)
(**)
(**)
(*nlmAveragedWithStdDevsUnconstrainedGlobalPurged=Quiet[NonlinearModelFit[logAveragedWithErrorsOnMeanPurgedShifted,fitFunc,fitPar,x,MaxIterations->1000,Method->"NMinimize"],NonlinearModelFit::lmnl];*)
(**)
(*maxx=Max[averaged[[All,1]]];*)
(*maxy=Max[averaged[[All,2]]];*)
(**)
(*thresholdBelow=0;*)
(*thresholdAbove=maxx-0;*)
(**)
(*Show[{ListPlot[logAveragedWithMaxDevShifted,PlotStyle->{GrayLevel[0],Directive[Opacity[0.3]],PointSize->0.001},AxesLabel->{"Log[L]","Log[N]"}]*)
(*,ListPlot[logAveragedWithErrorsOnMeanPurgedShifted,PlotStyle->{RGBColor[0, 0.78, 1],PointSize->0.01},PlotLegends->PointLegend[{"logAveragedWithErrorsOnMeanPurgedShifted"},LegendMarkerSize->10,LegendMarkers->Graphics[Disk[]]]]*)
(*,ListPlot[logAveragedWithErrorsOnMeanShifted,PlotStyle->{RGBColor[1, 0.55, 1],Directive[Opacity[0.6]],PointSize->0.005},PlotLegends->PointLegend[{"logAveragedWithErrorsOnMeanShifted"},LegendMarkerSize->10,LegendMarkers->Graphics[Disk[]]]]*)
(*,*)
(*Plot[ReleaseHold[#][x],{x,Log[thresholdBelow+1],Log[thresholdAbove]},PlotStyle->{RGBColor[0.24, 0.68, 0.8],Thickness->0.002},PlotLegends->Placed[SwatchLegend[{Row[{#,":\n ",TraditionalForm[ReleaseHold[#][x]]}]}],Right]]&@HoldForm[nlmAveragedWithStdDevsUnconstrainedGlobalPurged]*)
(*,referencePlot*)
(*}*)
(*,PlotLabel->Row[{" b = ",b}]*)
(*,PlotRange->{All,{0,All}},AxesOrigin->{1,0},ImageSize->700]*)
(**)
(**)


(* ::Input:: *)
(*measuredb4=Around[nlmAveragedWithStdDevsUnconstrainedGlobalPurged["ParameterTable"][[1,1,-1,2]],nlmAveragedWithStdDevsUnconstrainedGlobalPurged["ParameterTable"][[1,1,-1,3]]*4]*)


(* ::Input:: *)
(*ListPlot[Transpose[{logAveragedWithErrorsOnMeanPurgedShifted[[All,1]],nlmAveragedWithStdDevsUnconstrainedGlobalPurged["FitResiduals"]}],Filling->Axis,*)
(*AxesLabel->{"x","Residuals (y - y_fit)"},PlotLabel->"FitResiduals - nlmAveragedWithStdDevsUnconstrainedGlobalPurged",ImageSize->Large]*)


(* ::Section::Closed:: *)
(*b=15		still needs more statistics: 1.302 \[PlusMinus] 0.017*)
(*		(Using more estimates and then mean 1.323 \[PlusMinus] 0.003)*)


(* ::Input:: *)
(*b=15;*)
(**)
(*rawDataHybrid=Import["data15-3d-HybridSq.mx"];*)
(*Length[rawDataHybrid]*)
(**)
(*rawDataHalo=Import["data15-3d-Halo.mx"];*)
(*Length[rawDataHalo]*)
(**)
(*rawData=Join[rawDataHybrid,rawDataHalo];*)
(*Length[rawData]*)
(*Developer`PackedArrayQ[rawData]*)
(**)
(*rawDataHybrid=.*)
(*rawDataHalo=.*)


(* ::Subsubsection::Closed:: *)
(*Run once to export MX file*)


(* ::Input:: *)
(*rawDataHybrid=Import["D:\\Offline_Documents\\University\\PhD_Paris\\PhD_work\\Simulations\\bLRW\\b-LRWdata\\3d-FromCluster\\b15-3d-clean_merged_data-HybridSq.csv","CSV"];*)
(*(*Immediately lock it into a Packed Array*)*)
(*rawDataHybrid=Developer`ToPackedArray[rawDataHybrid];*)
(* (* MODIFY FILE NAME *)*)
(**)
(*Length[rawDataHybrid]*)
(*rawDataHybrid=Cases[rawDataHybrid,{_?NumericQ,_?NumericQ}];*)
(*Length[rawDataHybrid]*)
(*rawDataHybrid=Developer`ToPackedArray[rawDataHybrid];*)
(*Developer`PackedArrayQ[rawDataHybrid]*)


(* ::Input:: *)
(*Export["data15-3d-HybridSq.mx",rawDataHybrid,"MX"]*)


(* ::Input:: *)
(*rawDataHalo=Import["D:\\Offline_Documents\\University\\PhD_Paris\\PhD_work\\Simulations\\bLRW\\b-LRWdata\\3d-FromCluster\\b15-3d-clean_merged_data-Halo.csv","CSV"];*)
(*(*Immediately lock it into a Packed Array*)*)
(*rawDataHalo=Developer`ToPackedArray[rawDataHalo];*)
(* (* MODIFY FILE NAME *)*)
(**)
(*Length[rawDataHalo]*)
(*rawDataHalo=Cases[rawDataHalo,{_?NumericQ,_?NumericQ}];*)
(*Length[rawDataHalo]*)
(*rawDataHalo=Developer`ToPackedArray[rawDataHalo];*)
(*Developer`PackedArrayQ[rawDataHalo]*)


(* ::Input:: *)
(*Export["data15-3d-Halo.mx",rawDataHalo,"MX"]*)


(* ::Subsection::Closed:: *)
(*GatherBy x values*)


(* ::Input:: *)
(*(*1. Gather rows by their first element (x) at C-speed*)*)
(*gathered=GatherBy[rawData,First];*)
(**)
(*(*2. Extract the unique X values directly from the gathered groups*)*)
(*xValues=gathered[[All,1,1]];*)
(**)
(*(*3. Extract the Y values for each group*)*)
(*yGroups=gathered[[All,All,2]];*)
(**)
(*(*4. Map Mean and StandardDeviation across the groups in bulk*)*)
(*means=Mean/@yGroups/. 0.->1.0`*^-8;*)
(**)
(*(*Standard deviation throws an error/indeterminacy if length is 1,so we replace Indeterminate with 0 globally at the end*)*)
(*stdDevs=Check[StandardDeviation[#],missing](*/Sqrt[Length[#]]*)&/@yGroups(*/. Indeterminate->1.0`*^-8*);*)


(* ::Input:: *)
(*(*Position[yGroups,_?(Length[#]<50&),1]*)
(*yGroups[[Rest[Flatten@%]]]*)*)


(* ::Input:: *)
(*missingIndices=Flatten@Position[stdDevs,missing]*)
(**)
(*Part[#,missingIndices]&/@{means,stdDevs}*)
(*Times@@%*)
(*stdDevs[[missingIndices]]=%/.missing->Mean[Select[stdDevs/means//N,FreeQ[#,missing]&]]//N*)


(* ::Input:: *)
(*stdDevs=stdDevs/. 0.->1.0`*^-8;*)
(*(* stdDev on mean*)*)
(*stdDevsOnMean=(1/Sqrt[Length[#]]&/@yGroups)*stdDevs;*)
(**)
(*(* Maximum deviation*)*)
(*maxDevsPlus=MapThread[Max[#2-#1]&,{means//N,yGroups}]/. 0.->1.0`*^-8;*)
(*maxDevsMinus=MapThread[Min[#2-#1]&,{means//N,yGroups}]/. 0.->1.0`*^-8;*)
(**)
(*(*5. Combine them using the Threaded Around wrapper*)*)
(*averaged=Transpose[{xValues,means}];*)
(*averagedWithErrors=Transpose[{xValues,MapThread[Around,{means,stdDevs}]}];*)
(*averagedWithErrorsOnMean=Transpose[{xValues,MapThread[Around,{means,stdDevsOnMean}]}];*)
(*averagedWithMaxDev=Transpose[{xValues,MapThread[Around,{means,Transpose[{maxDevsMinus,maxDevsPlus}]}]}];*)
(**)
(*(*Drop points with low statistic*)*)
(*averagedWithErrorsOnMeanPurged=Delete[averagedWithErrorsOnMean,Rest[Position[yGroups,_?(Length[#]<1500&),{1}]]];*)
(*Length@averagedWithErrorsOnMean*)
(*Length@averagedWithErrorsOnMeanPurged*)
(**)
(*Export["averaged-b15.mx",{averaged,averagedWithErrors,averagedWithErrorsOnMean,averagedWithErrorsOnMeanPurged,averagedWithMaxDev,b},"MX"]*)


(* ::Input:: *)
(*(*NOT USING IT*)
(**)
(* Remove the Sqrt[N] factor from the StdDev estimates*)*)
(*(*MapThread[Times[#1,Sqrt[#2]]&,{stdDevs,yGroups}]*)
(**)
(*averagedWithErrors=Transpose[{xValues,MapThread[Around,{means,%}]}];*)*)


(* ::Input:: *)
(*(**)
(*(*Standard deviation with my code (Kay's trick for better estimate)*)*)
(*stdDevsEstimated=StdDevEstimate[#,280,"print"->tTrue]&/@yGroups/. Indeterminate->1.0`*^-8;*)
(*stdDevsEstimated=stdDevsEstimated/. 0.->1.0`*^-8;*)
(**)
(*averagedWithEstimatedStdDevs=Transpose[{xValues,MapThread[Around,{means,stdDevsEstimated}]}];*)*)


(* ::Subsection::Closed:: *)
(*Take the Log*)


(* ::Input:: *)
(*{averaged,averagedWithErrors,averagedWithErrorsOnMean,averagedWithErrorsOnMeanPurged,averagedWithMaxDev,b}=Import["averaged-b15.mx"];*)
(*b*)


(* ::Input:: *)
(*(*(*Drop points with low statistic*)*)
(*averagedWithErrorsOnMeanPurged=Delete[averagedWithErrorsOnMean,Rest[Position[yGroups,_?(Length[#]<1500&),{1}]]];*)
(*Length@averagedWithErrorsOnMean*)
(*Length@averagedWithErrorsOnMeanPurged*)*)


(* ::Input:: *)
(*exluded=5;*)
(**)
(*averaged=Select[averaged,#[[1]]=!=""&&#[[1]]>exluded&];*)
(*averagedWithErrors=Select[averagedWithErrors,#[[1]]=!=""&&#[[1]]>exluded&];*)
(**)
(*averagedWithErrorsOnMean=Select[averagedWithErrorsOnMean,#[[1]]=!=""&&#[[1]]>exluded&];*)
(*averagedWithErrorsOnMeanPurged=Select[averagedWithErrorsOnMeanPurged,#[[1]]=!=""&&#[[1]]>exluded&];*)
(**)
(*averagedWithMaxDev=Select[averagedWithMaxDev,#[[1]]=!=""&&#[[1]]>exluded&];*)
(*(*averagedWithEstimatedStdDevs=Select[averagedWithEstimatedStdDevs,#[[1]]=!=""&];*)
(*averagedWithEstimatedStdDevsOnMean=Select[averagedWithEstimatedStdDevsOnMean,#[[1]]=!=""&];*)*)


(* ::Input:: *)
(*logAveraged=Log[averaged];*)
(*logAveragedWithErrors=Log[averagedWithErrors](*/. 0->Around[1.0`*^-6,1.0`*^-6]*);*)
(**)
(*logAveragedWithErrorsOnMean=Log[averagedWithErrorsOnMean](*/. 0->Around[1.0`*^-6,1.0`*^-6]*);*)
(*logAveragedWithErrorsOnMeanPurged=Log[averagedWithErrorsOnMeanPurged](*/. 0->Around[1.0`*^-6,1.0`*^-6]*);*)
(**)
(*logAveragedWithMaxDev=Log[averagedWithMaxDev](*/. 0->Around[1.0`*^-6,1.0`*^-6]*);*)
(*(*logAveragedWithEstimatedStdDevs=Log[averagedWithEstimatedStdDevs]/. 0->Around[1.0`*^-6,1.0`*^-6];*)
(*logAveragedWithEstimatedStdDevsOnMean=Log[averagedWithEstimatedStdDevsOnMean]/. 0->Around[1.0`*^-6,1.0`*^-6];*)*)


(* ::Input:: *)
(*maxx=Max[averaged[[All,1]]];*)
(*maxy=Max[averaged[[All,2]]];*)
(**)
(*referencePlot=Plot[(x (#)-1.4),{x,Log[0+1],Log[maxx]},PlotStyle->{RGBColor[0, 0, 1],Dashed},PlotLegends->Placed[SwatchLegend[{Row[{"Guessed by eye: ",#}]}],Right]]&@1.3;*)
(* *)
(*Show[{ListPlot[logAveragedWithMaxDev,PlotStyle->{GrayLevel[0],Directive[Opacity[0.3]],PointSize->0.001},AxesLabel->{"Log[L]","Log[N]"}]*)
(*,ListPlot[logAveragedWithErrorsOnMeanPurged,PlotStyle->{RGBColor[0, 0.78, 1],PointSize->0.01},PlotLegends->PointLegend[{"logAveragedWithErrorsOnMeanPurged"},LegendMarkerSize->10,LegendMarkers->Graphics[Disk[]]]]*)
(*,ListPlot[logAveragedWithErrorsOnMean,PlotStyle->{RGBColor[1, 0.55, 1],Directive[Opacity[0.6]],PointSize->0.005},PlotLegends->PointLegend[{"logAveragedWithErrorsOnMean"},LegendMarkerSize->10,LegendMarkers->Graphics[Disk[]]]]*)
(*,referencePlot*)
(*}*)
(*,PlotLabel->Row[{" b = ",b}],PlotRange->{All,{0,Log[maxy]}},AxesOrigin->{1,0},ImageSize->700]*)


(* ::Input:: *)
(*normalizeWithReference:=Plus[{0,-#[[1]]*1.3+1.35},#]&;*)
(**)
(*logAveragedRefNorm=normalizeWithReference/@logAveraged;*)
(*logAveragedWithErrorsRefNorm=normalizeWithReference/@logAveragedWithErrors;*)
(**)
(*logAveragedWithErrorsOnMeanRefNorm=normalizeWithReference/@logAveragedWithErrorsOnMean;*)
(*logAveragedWithErrorsOnMeanPurgedRefNorm=normalizeWithReference/@logAveragedWithErrorsOnMeanPurged;*)
(**)
(*logAveragedWithMaxDevRefNorm=normalizeWithReference/@logAveragedWithMaxDev;*)
(**)
(**)
(*maxx=Max[logAveragedWithMaxDevRefNorm[[All,1]]];*)
(*{miny,maxy}=MinMax[logAveragedWithMaxDevRefNorm[[All,2,1]]];*)
(* *)
(*Show[{(*ListPlot[logAveragedWithMaxDevRefNorm,PlotStyle->{,Directive[Opacity[0.3]],PointSize->0.001}]*)
(*,*)ListPlot[logAveragedWithErrorsOnMeanPurgedRefNorm,PlotStyle->{RGBColor[0, 0.78, 1],PointSize->0.01},PlotLegends->PointLegend[{"logAveragedWithErrorsOnMeanPurgedRefNorm"},LegendMarkerSize->10,LegendMarkers->Graphics[Disk[]]]]*)
(*,ListPlot[logAveragedWithErrorsOnMeanRefNorm,PlotStyle->{RGBColor[1, 0.55, 1],Directive[Opacity[0.6]],PointSize->0.005},PlotLegends->PointLegend[{"logAveragedWithErrorsOnMeanRefNorm"},LegendMarkerSize->10,LegendMarkers->Graphics[Disk[]]]]*)
(*}*)
(*,PlotLabel->Row[{" b = ",b}],AxesLabel->{"Log[L]","Log[N]"},PlotRange->{{0,maxx},{-0.5,maxy}},AxesOrigin->{1,0},ImageSize->700]*)


(* ::Subsection:: *)
(*Take the Log WITH A SHIFT	*)


(* ::Subsubsection:: *)
(*Check for best shift using \[Chi]^2 to test linearity Dropping some too*)


(* ::Input:: *)
(*(*dataPurged=Delete[SortBy[averagedWithErrorsOnMeanPurged,First],{{1},{2},{3},{4}(*,{5},{6},{7},{8},{9}*)}];*)*)
(*(*dataPurged=Drop[SortBy[averagedWithErrorsOnMeanPurged,First],8];*)*)
(**)
(*fitFunc=a+0c Exp[-x]+df  x;*)
(*fitPar={a,(*c,*)df};*)
(**)
(*averagedWithErrorsOnMeanPurgedSorted=SortBy[averagedWithErrorsOnMeanPurged,First];*)
(*(*Scan across cutoff values xMin*)*)
(*scanResultsRaw=*)
(*ParallelTable[With[{dataPurged=Drop[averagedWithErrorsOnMeanPurgedSorted,dropFirstn]},*)
(*Table[With[{shift:=Plus[{-shiftValue,0},#]&},*)
(*With[{shiftedData=Log[Select[shift/@dataPurged,#[[1]]>0&]](*/. 0->Around[1.0`*^-6,1.0`*^-6]*)},*)
(*Module[*)
(*{fit=LinearModelFit[shiftedData,x,x,Weights->Automatic,VarianceEstimatorFunction->(1&)]},*)
(**)
(*{shiftValue,*)
(*fit["ParameterTable"][[1,1,3,2]](*Slope*),*)
(*fit["ParameterTable"][[1,1,3,3]](*Slope Error*),*)
(*fit["ANOVATableEntries"][[2,2]]/fit["ANOVATableEntries"][[2,1]](*Reduced Chi^2*),*)
(*dropFirstn}]*)
(*]],*)
(*{shiftValue,-5,10,0.5}]],*)
(*{dropFirstn,19,23(*Length[averagedWithErrorsOnMeanPurgedSorted]-3*)}];*)
(**)
(*scanResults=Flatten[scanResultsRaw,1];*)


(* ::Input:: *)
(*Mean[Around[#[[1]],#[[2]]*3]&/@(MinimalBy[scanResults(*[[All,{1,4}]]*),Abs[#[[4]]-1]&,12][[All,{2,3}]])]*)


(* ::Input:: *)
(*MinimalBy[scanResults(*[[All,{1,4}]]*),Abs[#[[4]]-1]&,20]*)
(*minBy\[Chi]=%[[3]]*)
(*{min\[Chi]position,associatedSlope,min\[Chi]}=%[[{1,2,4}]](*Flatten@MinimalBy[scanResults[[All,{1,4}]],#[[2]]&]*)*)
(**)
(*(*1. Plot Reduced Chi^2 vs xMin*)*)
(*ListLinePlot[#[[All,All,{1,4}]],AxesLabel->{"shift","Reduced Chi^2"},PlotRange->{All,{0,100}},GridLines->{{min\[Chi]position,Thick},{1,Thick}},PlotLegends->LineLegend[#[[All,1,5]],LegendLabel->"Dropped:"],ScalingFunctions->"Log"(*,PlotLabel->{Row[{"Dropped first ",#[[5]]}]}*)]&@scanResultsRaw*)
(**)
(*(*2. Plot Fitted Slope vs xMin with error bands*)*)
(*ListPlot[Table[{r[[1]],Around[r[[2]],r[[3]]]},{r,#}]&/@#,AxesLabel->{"shift","Slope"},PlotRange->All,GridLines->{{min\[Chi]position},{associatedSlope}},PlotLegends->LineLegend[#[[All,1,5]],LegendLabel->"Dropped:"]]&@scanResultsRaw*)


(* ::Input:: *)
(*(*MinimalBy[scanResults(*[[All,{1,4}]]*),#[[4]]&]*)*)
(**)
(*shift:=Plus[{-minBy\[Chi][[1]],0},#]&; (*In the code, the stopping condition is with R-1*)*)
(**)
(*logAveragedWithMaxDevShifted=Log[shift/@averagedWithMaxDev](*/. 0->Around[1.0`*^-6,1.0`*^-6]*);*)
(*logAveragedWithErrorsOnMeanShifted=Log[shift/@averagedWithErrorsOnMean](*/. 0->Around[1.0`*^-6,1.0`*^-6]*);*)
(**)
(*dataPurged=Drop[SortBy[averagedWithErrorsOnMeanPurged,First],minBy\[Chi][[5]]];*)
(*logAveragedWithErrorsOnMeanPurgedShifted=Log[shift/@dataPurged](*/. 0->Around[1.0`*^-6,1.0`*^-6]*);*)
(**)
(**)
(*fitFunc=a+0c Exp[-x]+df  x;*)
(*fitPar={a,(*c,*)df};*)
(**)
(**)
(*nlmAveragedWithStdDevsUnconstrainedGlobalPurged=Quiet[NonlinearModelFit[logAveragedWithErrorsOnMeanPurgedShifted,fitFunc,fitPar,x,MaxIterations->1000,Method->"NMinimize"],NonlinearModelFit::lmnl];*)
(**)
(*maxx=Max[averaged[[All,1]]];*)
(*maxy=Max[averaged[[All,2]]];*)
(**)
(*thresholdBelow=0;*)
(*thresholdAbove=maxx-0;*)
(**)
(*Show[{ListPlot[logAveragedWithMaxDevShifted,PlotStyle->{GrayLevel[0],Directive[Opacity[0.3]],PointSize->0.001},AxesLabel->{"Log[L]","Log[N]"}]*)
(*,ListPlot[logAveragedWithErrorsOnMeanPurgedShifted,PlotStyle->{RGBColor[0, 0.78, 1],PointSize->0.01},PlotLegends->PointLegend[{"logAveragedWithErrorsOnMeanPurgedShifted"},LegendMarkerSize->10,LegendMarkers->Graphics[Disk[]]]]*)
(*,ListPlot[logAveragedWithErrorsOnMeanShifted,PlotStyle->{RGBColor[1, 0.55, 1],Directive[Opacity[0.6]],PointSize->0.005},PlotLegends->PointLegend[{"logAveragedWithErrorsOnMeanShifted"},LegendMarkerSize->10,LegendMarkers->Graphics[Disk[]]]]*)
(*,*)
(*Plot[ReleaseHold[#][x],{x,Log[thresholdBelow+1],Log[thresholdAbove]},PlotStyle->{RGBColor[0.24, 0.68, 0.8],Thickness->0.002},PlotLegends->Placed[SwatchLegend[{Row[{#,":\n ",TraditionalForm[ReleaseHold[#][x]]}]}],Right]]&@HoldForm[nlmAveragedWithStdDevsUnconstrainedGlobalPurged]*)
(*,referencePlot*)
(*}*)
(*,PlotLabel->Row[{" b = ",b}]*)
(*,PlotRange->{All,{0,All}},AxesOrigin->{1,0},ImageSize->700]*)
(**)
(**)


(* ::Input:: *)
(*measuredb15=Around[nlmAveragedWithStdDevsUnconstrainedGlobalPurged["ParameterTable"][[1,1,-1,2]],nlmAveragedWithStdDevsUnconstrainedGlobalPurged["ParameterTable"][[1,1,-1,3]]*4]*)


(* ::Input:: *)
(*ListPlot[Transpose[{logAveragedWithErrorsOnMeanPurgedShifted[[All,1]],nlmAveragedWithStdDevsUnconstrainedGlobalPurged["FitResiduals"]}],Filling->Axis,*)
(*AxesLabel->{"x","Residuals (y - y_fit)"},PlotLabel->"FitResiduals - nlmAveragedWithStdDevsUnconstrainedGlobalPurged",ImageSize->Large]*)


(* ::Section:: *)
(*b=100		TBD: still needs more statistics BUT IT REALLY LOOKS LIKE df=1!!!*)


(* ::Input:: *)
(*b=100;*)
(**)
(*rawData=Import["data100-3d-Halo.mx"];*)
(**)
(*Length[rawData]*)
(*Developer`PackedArrayQ[rawData]*)


(* ::Subsubsection::Closed:: *)
(*Run once to export MX file*)


(* ::Input:: *)
(*rawData=Import["D:\\Offline_Documents\\University\\PhD_Paris\\PhD_work\\Simulations\\bLRW\\b-LRWdata\\3d-FromCluster\\b100-3d-clean_merged_data-Halo.csv","CSV"];*)
(*(*Immediately lock it into a Packed Array*)*)
(*rawData=Developer`ToPackedArray[rawData];*)
(* (* MODIFY FILE NAME *)*)
(**)
(*Length[rawData]*)
(*rawData=Cases[rawData,{_?NumericQ,_?NumericQ}];*)
(*Length[rawData]*)
(*rawData=Developer`ToPackedArray[rawData];*)
(*Developer`PackedArrayQ[rawData]*)
(* *)
(*Length[rawData]*)


(* ::Input:: *)
(*rawData=Pick[rawData,Length/@rawData,2];*)
(*Length[rawData]*)
(*Developer`PackedArrayQ[rawData]*)


(* ::Input:: *)
(*Export["data100-3d-Halo.mx",rawData,"MX"]*)


(* ::Subsection::Closed:: *)
(*GatherBy x values*)


(* ::Input:: *)
(*(*1. Gather rows by their first element (x) at C-speed*)*)
(*gathered=GatherBy[rawData,First];*)
(**)
(*(*2. Extract the unique X values directly from the gathered groups*)*)
(*xValues=gathered[[All,1,1]];*)
(**)
(*(*3. Extract the Y values for each group*)*)
(*yGroups=gathered[[All,All,2]];*)
(**)
(*(*4. Map Mean and StandardDeviation across the groups in bulk*)*)
(*means=Mean/@yGroups/. 0.->1.0`*^-8;*)
(**)
(*(*Standard deviation throws an error/indeterminacy if length is 1,so we replace Indeterminate with 0 globally at the end*)*)
(*stdDevs=Check[StandardDeviation[#],missing](*/Sqrt[Length[#]]*)&/@yGroups(*/. Indeterminate->1.0`*^-8*);*)


(* ::Input:: *)
(*(*Position[yGroups,_?(Length[#]<50&),1]*)
(*yGroups[[Rest[Flatten@%]]]*)*)


(* ::Input:: *)
(*missingIndices=Flatten@Position[stdDevs,missing]*)
(**)
(*Part[#,missingIndices]&/@{means,stdDevs}*)
(*Times@@%*)
(*stdDevs[[missingIndices]]=%/.missing->Mean[Select[stdDevs/means//N,FreeQ[#,missing]&]]//N*)


(* ::Input:: *)
(*stdDevs=stdDevs/. 0.->1.0`*^-8;*)
(*(* stdDev on mean*)*)
(*stdDevsOnMean=(1/Sqrt[Length[#]]&/@yGroups)*stdDevs;*)
(**)
(*(* Maximum deviation*)*)
(*maxDevsPlus=MapThread[Max[#2-#1]&,{means//N,yGroups}]/. 0.->1.0`*^-8;*)
(*maxDevsMinus=MapThread[Min[#2-#1]&,{means//N,yGroups}]/. 0.->1.0`*^-8;*)
(**)
(*(*5. Combine them using the Threaded Around wrapper*)*)
(*averaged=Transpose[{xValues,means}];*)
(*averagedWithErrors=Transpose[{xValues,MapThread[Around,{means,stdDevs}]}];*)
(*averagedWithErrorsOnMean=Transpose[{xValues,MapThread[Around,{means,stdDevsOnMean}]}];*)
(*averagedWithMaxDev=Transpose[{xValues,MapThread[Around,{means,Transpose[{maxDevsMinus,maxDevsPlus}]}]}];*)
(**)
(*(*Drop points with low statistic*)*)
(*averagedWithErrorsOnMeanPurged=Delete[averagedWithErrorsOnMean,Rest[Position[yGroups,_?(Length[#]<2000&),{1}]]];*)
(*Length@averagedWithErrorsOnMean*)
(*Length@averagedWithErrorsOnMeanPurged*)
(**)
(*Export["averaged-b100.mx",{averaged,averagedWithErrors,averagedWithErrorsOnMean,averagedWithErrorsOnMeanPurged,averagedWithMaxDev,b},"MX"]*)


(* ::Input:: *)
(*(*NOT USING IT*)
(**)
(* Remove the Sqrt[N] factor from the StdDev estimates*)*)
(*(*MapThread[Times[#1,Sqrt[#2]]&,{stdDevs,yGroups}]*)
(**)
(*averagedWithErrors=Transpose[{xValues,MapThread[Around,{means,%}]}];*)*)


(* ::Input:: *)
(*(**)
(*(*Standard deviation with my code (Kay's trick for better estimate)*)*)
(*stdDevsEstimated=StdDevEstimate[#,280,"print"->tTrue]&/@yGroups/. Indeterminate->1.0`*^-8;*)
(*stdDevsEstimated=stdDevsEstimated/. 0.->1.0`*^-8;*)
(**)
(*averagedWithEstimatedStdDevs=Transpose[{xValues,MapThread[Around,{means,stdDevsEstimated}]}];*)*)


(* ::Subsection:: *)
(*Take the Log*)


(* ::Input:: *)
(* {averaged,averagedWithErrors,averagedWithErrorsOnMean,averagedWithErrorsOnMeanPurged,averagedWithMaxDev,b}=Import["averaged-b100.mx"];*)


(* ::Input:: *)
(*(*(*Drop points with low statistic*)*)
(*averagedWithErrorsOnMeanPurged=Delete[averagedWithErrorsOnMean,Rest[Position[yGroups,_?(Length[#]<2000&),{1}]]];*)
(*Length@averagedWithErrorsOnMean*)
(*Length@averagedWithErrorsOnMeanPurged*)*)


(* ::Input:: *)
(*exluded=7;*)
(**)
(*averaged=Select[averaged,#[[1]]=!=""&&#[[1]]>exluded&];*)
(*averagedWithErrors=Select[averagedWithErrors,#[[1]]=!=""&&#[[1]]>exluded&];*)
(**)
(*averagedWithErrorsOnMean=Select[averagedWithErrorsOnMean,#[[1]]=!=""&&#[[1]]>exluded&];*)
(*averagedWithErrorsOnMeanPurged=Select[averagedWithErrorsOnMeanPurged,#[[1]]=!=""&&#[[1]]>exluded&];*)
(**)
(*averagedWithMaxDev=Select[averagedWithMaxDev,#[[1]]=!=""&&#[[1]]>exluded&];*)
(*(*averagedWithEstimatedStdDevs=Select[averagedWithEstimatedStdDevs,#[[1]]=!=""&];*)
(*averagedWithEstimatedStdDevsOnMean=Select[averagedWithEstimatedStdDevsOnMean,#[[1]]=!=""&];*)*)


(* ::Input:: *)
(*logAveraged=Log[averaged];*)
(*logAveragedWithErrors=Log[averagedWithErrors](*/. 0->Around[1.0`*^-6,1.0`*^-6]*);*)
(**)
(*logAveragedWithErrorsOnMean=Log[averagedWithErrorsOnMean](*/. 0->Around[1.0`*^-6,1.0`*^-6]*);*)
(*logAveragedWithErrorsOnMeanPurged=Log[averagedWithErrorsOnMeanPurged](*/. 0->Around[1.0`*^-6,1.0`*^-6]*);*)
(**)
(*logAveragedWithMaxDev=Log[averagedWithMaxDev](*/. 0->Around[1.0`*^-6,1.0`*^-6]*);*)
(*(*logAveragedWithEstimatedStdDevs=Log[averagedWithEstimatedStdDevs]/. 0->Around[1.0`*^-6,1.0`*^-6];*)
(*logAveragedWithEstimatedStdDevsOnMean=Log[averagedWithEstimatedStdDevsOnMean]/. 0->Around[1.0`*^-6,1.0`*^-6];*)*)


(* ::Input:: *)
(*maxx=Max[averaged[[All,1]]];*)
(*maxy=Max[averaged[[All,2]]];*)
(**)
(*referencePlot=Plot[(x (#)-1.2),{x,Log[0+1],Log[maxx]},PlotStyle->{RGBColor[0, 0, 1],Dashed},PlotLegends->Placed[SwatchLegend[{Row[{"Guessed by eye: ",#}]}],Right]]&@1.1;*)
(* *)
(*Show[{ListPlot[logAveragedWithMaxDev,PlotStyle->{GrayLevel[0],Directive[Opacity[0.3]],PointSize->0.001},AxesLabel->{"Log[L]","Log[N]"}]*)
(*,ListPlot[logAveragedWithErrorsOnMeanPurged,PlotStyle->{RGBColor[0, 0.78, 1],PointSize->0.01},PlotLegends->PointLegend[{"logAveragedWithErrorsOnMeanPurged"},LegendMarkerSize->10,LegendMarkers->Graphics[Disk[]]]]*)
(*,ListPlot[logAveragedWithErrorsOnMean,PlotStyle->{RGBColor[1, 0.55, 1],Directive[Opacity[0.6]],PointSize->0.005},PlotLegends->PointLegend[{"logAveragedWithErrorsOnMean"},LegendMarkerSize->10,LegendMarkers->Graphics[Disk[]]]]*)
(*,referencePlot*)
(*}*)
(*,PlotLabel->Row[{" b = ",b}],PlotRange->{All,{0,Log[maxy]}},AxesOrigin->{1,0},ImageSize->700]*)


(* ::Input:: *)
(*normalizeWithReference:=Plus[{0,-#[[1]]*1.1+1.4},#]&;*)
(**)
(*logAveragedRefNorm=normalizeWithReference/@logAveraged;*)
(*logAveragedWithErrorsRefNorm=normalizeWithReference/@logAveragedWithErrors;*)
(**)
(*logAveragedWithErrorsOnMeanRefNorm=normalizeWithReference/@logAveragedWithErrorsOnMean;*)
(*logAveragedWithErrorsOnMeanPurgedRefNorm=normalizeWithReference/@logAveragedWithErrorsOnMeanPurged;*)
(**)
(*logAveragedWithMaxDevRefNorm=normalizeWithReference/@logAveragedWithMaxDev;*)
(**)
(*maxx=Max[logAveragedWithMaxDevRefNorm[[All,1]]];*)
(*{miny,maxy}=MinMax[logAveragedWithMaxDevRefNorm[[All,2,1]]];*)
(* *)
(*Show[{(*ListPlot[logAveragedWithMaxDevRefNorm,PlotStyle->{,Directive[Opacity[0.3]],PointSize->0.001}]*)
(*,*)ListPlot[logAveragedWithErrorsOnMeanPurgedRefNorm,PlotStyle->{RGBColor[0, 0.78, 1],PointSize->0.01},PlotLegends->PointLegend[{"logAveragedWithErrorsOnMeanPurgedRefNorm"},LegendMarkerSize->10,LegendMarkers->Graphics[Disk[]]]]*)
(*,ListPlot[logAveragedWithErrorsOnMeanRefNorm,PlotStyle->{RGBColor[1, 0.55, 1],Directive[Opacity[0.6]],PointSize->0.005},PlotLegends->PointLegend[{"logAveragedWithErrorsOnMeanRefNorm"},LegendMarkerSize->10,LegendMarkers->Graphics[Disk[]]]]*)
(*}*)
(*,PlotLabel->Row[{" b = ",b}],AxesLabel->{"Log[L]","Log[N]"},PlotRange->{{0,maxx},{-0.5,maxy}},AxesOrigin->{1,0},ImageSize->700]*)


(* ::Subsection:: *)
(*Take the Log WITH A SHIFT	*)


(* ::Subsubsection:: *)
(*Check for best shift using \[Chi]^2 to test linearity Dropping some too*)


(* ::Input:: *)
(*(*dataPurged=Delete[SortBy[averagedWithErrorsOnMeanPurged,First],{{1},{2},{3},{4}(*,{5},{6},{7},{8},{9}*)}];*)*)
(*(*dataPurged=Drop[SortBy[averagedWithErrorsOnMeanPurged,First],8];*)*)
(**)
(*fitFunc=a+0c Exp[-x]+df  x;*)
(*fitPar={a,(*c,*)df};*)
(**)
(*averagedWithErrorsOnMeanPurgedSorted=SortBy[averagedWithErrorsOnMeanPurged,First];*)
(*(*Scan across cutoff values xMin*)*)
(*scanResultsRaw=*)
(*ParallelTable[With[{dataPurged=Drop[averagedWithErrorsOnMeanPurgedSorted,dropFirstn]},*)
(*Table[With[{shift:=Plus[{-shiftValue,0},#]&},*)
(*With[{shiftedData=Log[Select[shift/@dataPurged,#[[1]]>0&]](*/. 0->Around[1.0`*^-6,1.0`*^-6]*)},*)
(*Module[*)
(*{fit=LinearModelFit[shiftedData,x,x,Weights->Automatic,VarianceEstimatorFunction->(1&)]},*)
(**)
(*{shiftValue,*)
(*fit["ParameterTable"][[1,1,3,2]](*Slope*),*)
(*fit["ParameterTable"][[1,1,3,3]](*Slope Error*),*)
(*fit["ANOVATableEntries"][[2,2]]/fit["ANOVATableEntries"][[2,1]](*Reduced Chi^2*),*)
(*dropFirstn}]*)
(*]],*)
(*{shiftValue,-10,10,0.5}]],*)
(*{dropFirstn,0,Length[averagedWithErrorsOnMeanPurgedSorted]-3}];*)
(**)
(*scanResults=Flatten[scanResultsRaw,1];*)


(* ::Input:: *)
(*Mean[Around[#[[1]],#[[2]]*3]&/@(MinimalBy[scanResults(*[[All,{1,4}]]*),Abs[#[[4]]-1]&,12][[All,{2,3}]])]*)


(* ::Input:: *)
(*MinimalBy[scanResults(*[[All,{1,4}]]*),Abs[#[[4]]-1]&,20]*)
(*minBy\[Chi]=%[[3]]*)
(*{min\[Chi]position,associatedSlope,min\[Chi]}=%[[{1,2,4}]](*Flatten@MinimalBy[scanResults[[All,{1,4}]],#[[2]]&]*)*)
(**)
(*(*1. Plot Reduced Chi^2 vs xMin*)*)
(*ListLinePlot[#[[All,All,{1,4}]],AxesLabel->{"shift","Reduced Chi^2"},PlotRange->{All,{0,100}},GridLines->{{min\[Chi]position,Thick},{1,Thick}},PlotLegends->LineLegend[#[[All,1,5]],LegendLabel->"Dropped:"],ScalingFunctions->"Log"(*,PlotLabel->{Row[{"Dropped first ",#[[5]]}]}*)]&@scanResultsRaw*)
(**)
(*(*2. Plot Fitted Slope vs xMin with error bands*)*)
(*ListPlot[Table[{r[[1]],Around[r[[2]],r[[3]]]},{r,#}]&/@#,AxesLabel->{"shift","Slope"},PlotRange->All,GridLines->{{min\[Chi]position},{associatedSlope}},PlotLegends->LineLegend[#[[All,1,5]],LegendLabel->"Dropped:"]]&@scanResultsRaw*)


(* ::Input:: *)
(*(*MinimalBy[scanResults(*[[All,{1,4}]]*),#[[4]]&]*)*)
(**)
(*shift:=Plus[{-minBy\[Chi][[1]],0},#]&; (*In the code, the stopping condition is with R-1*)*)
(**)
(*logAveragedWithMaxDevShifted=Log[shift/@averagedWithMaxDev](*/. 0->Around[1.0`*^-6,1.0`*^-6]*);*)
(*logAveragedWithErrorsOnMeanShifted=Log[shift/@averagedWithErrorsOnMean](*/. 0->Around[1.0`*^-6,1.0`*^-6]*);*)
(**)
(*dataPurged=Drop[SortBy[averagedWithErrorsOnMeanPurged,First],minBy\[Chi][[5]]];*)
(*logAveragedWithErrorsOnMeanPurgedShifted=Log[shift/@dataPurged](*/. 0->Around[1.0`*^-6,1.0`*^-6]*);*)
(**)
(**)
(*fitFunc=a+0c Exp[-x]+df  x;*)
(*fitPar={a,(*c,*)df};*)
(**)
(**)
(*nlmAveragedWithStdDevsUnconstrainedGlobalPurged=Quiet[NonlinearModelFit[logAveragedWithErrorsOnMeanPurgedShifted,fitFunc,fitPar,x,MaxIterations->1000,Method->"NMinimize"],NonlinearModelFit::lmnl];*)
(**)
(*maxx=Max[averaged[[All,1]]];*)
(*maxy=Max[averaged[[All,2]]];*)
(**)
(*thresholdBelow=0;*)
(*thresholdAbove=maxx-0;*)
(**)
(*Show[{ListPlot[logAveragedWithMaxDevShifted,PlotStyle->{GrayLevel[0],Directive[Opacity[0.3]],PointSize->0.001},AxesLabel->{"Log[L]","Log[N]"}]*)
(*,ListPlot[logAveragedWithErrorsOnMeanPurgedShifted,PlotStyle->{RGBColor[0, 0.78, 1],PointSize->0.01},PlotLegends->PointLegend[{"logAveragedWithErrorsOnMeanPurgedShifted"},LegendMarkerSize->10,LegendMarkers->Graphics[Disk[]]]]*)
(*,ListPlot[logAveragedWithErrorsOnMeanShifted,PlotStyle->{RGBColor[1, 0.55, 1],Directive[Opacity[0.6]],PointSize->0.005},PlotLegends->PointLegend[{"logAveragedWithErrorsOnMeanShifted"},LegendMarkerSize->10,LegendMarkers->Graphics[Disk[]]]]*)
(*,*)
(*Plot[ReleaseHold[#][x],{x,Log[thresholdBelow+1],Log[thresholdAbove]},PlotStyle->{RGBColor[0.24, 0.68, 0.8],Thickness->0.002},PlotLegends->Placed[SwatchLegend[{Row[{#,":\n ",TraditionalForm[ReleaseHold[#][x]]}]}],Right]]&@HoldForm[nlmAveragedWithStdDevsUnconstrainedGlobalPurged]*)
(*,referencePlot*)
(*}*)
(*,PlotLabel->Row[{" b = ",b}]*)
(*,PlotRange->{All,{0,All}},AxesOrigin->{1,0},ImageSize->700]*)
(**)
(**)


(* ::Input:: *)
(*<|Symbol["measuredb"<>ToString[100]]->1|>*)
(*measuredb100/.%*)


(* ::Input:: *)
(*measuredb100*)


(* ::Input:: *)
(*measuredb100=Around[nlmAveragedWithStdDevsUnconstrainedGlobalPurged["ParameterTable"][[1,1,-1,2]],nlmAveragedWithStdDevsUnconstrainedGlobalPurged["ParameterTable"][[1,1,-1,3]]*4]*)


(* ::Input:: *)
(*ListPlot[Transpose[{logAveragedWithErrorsOnMeanPurgedShifted[[All,1]],nlmAveragedWithStdDevsUnconstrainedGlobalPurged["FitResiduals"]}],Filling->Axis,*)
(*AxesLabel->{"x","Residuals (y - y_fit)"},PlotLabel->"FitResiduals - nlmAveragedWithStdDevsUnconstrainedGlobalPurged",ImageSize->Large]*)


(* ::Title:: *)
(*Measured values*)


(* ::Input:: *)
(*{{0.5,measuredb05},{1,measuredb1},{3,measuredb3},{4,measuredb4},{15,measuredb15},{100,measuredb100}}*)
