(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
BeginPackage["DrawGraph`"]


(* ::Input::Initialization:: *)
$DrawGraphVersion::usage="$DrawGraphVersion is the current version of the DrawGraph package.";
$DrawGraphReleaseDate::usage="$DrawGraphReleaseDate is the release date of the current version.";$DrawGraphReleaseDate="2025-11-29";$DrawGraphVersion=StringReplace[FileBaseName[$Input],Except["p"<>DigitCharacter]->"."];


(* ::Input::Initialization:: *)
$DrawGraphPrint::usage="$DrawGraphPrint=True turns on the debug printing of the package.";
If[!ValueQ[$DrawGraphPrint],$DrawGraphPrint=True];


(* ::Input::Initialization:: *)
DrawGraph`Private`MyPrint=If[$DrawGraphPrint,Print[##]]&;


(* ::Input::Initialization:: *)
Print[Style["~~~~~~~~~~~~~~~~ DrawGraph v"<>ToString[$DrawGraphVersion]<>" ~~~~~~~~~~~~~~~~~~~~\n\
Author: Paolo Pisapia.\n\
Release Date: "<>$DrawGraphReleaseDate<>"\n\
Timestamp: "<>DateString[FileDate[$InputFileName]]<>"\nRead from:"<>$InputFileName<>" (CRC32:"<>ToString[FileHash[$InputFileName,"CRC32"]]<>","<>ToString[FileHash[Select[FileNames[$LiteRedHomeDirectory<>"FermatCode/*"],Not@*DirectoryQ],"CRC32"]]<>")\n\nLiteRed stands for ",Style["L",{Lighter@Red}],"oop ",Style["i",{Lighter@Red}],"n",Style["te",{Lighter@Red}],"grals ",Style["Red",{Lighter@Red}],"uction.\n\
The package is designed for drawing nice-looking graphs. \
It takes inspiration from Kay Wiese's implementation.\n\nSee ?DrawGraph`* for a list of functions. ",{Bold,Lighter@Blue}]];


(* ::Input::Initialization:: *)
Begin["Private`"]


(* ::Input::Initialization:: *)
ClearAll[DrawGraph,x];

DrawGraph::usage=(*MODIFY*)"DrawGraph[\!\*
StyleBox[\"expr\", \"TI\"]] draw a graph from tStyleBox[\"expr\", \"TI\"]. \nOptions:\n    \"pointSize\"->0.015 - Set the point size,\n    \"ArrowHeadSize\"->0.05 - Set the Arrow Heads size,\n    \"print\"->False|True - Print for debug,\n    \"ImageSize\"->Medium - Set the Image size,\n    \"export\"->False|True - Exports the Graph,\n    \"exportDirectory\"->\"myFile.pdf\" - Set the export Directory,\n    \"initialIndex\"->1 - Set the index to start the counting of diagrams from.";


(* ::Input::Initialization:: *)
DrawGraph::zero=Style["Your expression is zero.\nAborting...",Red];

Options[DrawGraph]={"pointSize"->0.015,
"ArrowHeadSize"->0.05,
"print"->False,
"ImageSize"->Medium,
"export"->False,
"exportDirectory"->"myFile.pdf",
"initialIndex"->1};


(* ::Input::Initialization:: *)
DrawGraph[exp_List,options:OptionsPattern[]]:=(DrawGraph[#,options]&@(Total@exp));

DrawGraph[exp_,OptionsPattern[]]:=Module[{terms,i,pureProp, weight, dots,plot},


terms=exp;

If[terms==0,Message[DrawGraph::zero]; Abort[]];
(*If[terms==0,
Print[Style["!!ZERO!!",Red]]; 
Abort[];
];*)


terms=List @@ (terms)/.Times->List;


MyPrint[{terms}];

(* I want to check if terms is a list of lists (which means that exp conatained a sum, i.e. multiple diagrams)*)
If[!Head[terms[[1]]] ===List,
(* TRUE: if it is not a List of lists, let's make it so *)

terms={terms};

](*End of IF*);

(*Set up the list variable to store the plots*)
plot={};

For[i=1,i<=Length[terms],i++,

pureProp=DeleteElements[terms[[i]],{-1,b,b^n_?NumericQ,b2,g,\!\(\*OverscriptBox[\(g\), \(~\)]\),Subscript[g, \[Gamma]],\[Gamma],\[Gamma]1,\[Gamma]2,-g,-\!\(\*OverscriptBox[\(g\), \(~\)]\),-Subscript[g, \[Gamma]],-\[Gamma],-\[Gamma]1,-\[Gamma]2,g^n_?NumericQ,\!\(\*OverscriptBox[\(g\), \(~\)]\)^n_?NumericQ,Subscript[g, \[Gamma]]^n_?NumericQ,\[Gamma]^n_?NumericQ,\[Gamma]1^n_?NumericQ,\[Gamma]2^n_?NumericQ}];
pureProp=DeleteCases[pureProp,_?NumericQ];

weight=Times@@DeleteElements[terms[[i]],pureProp];

pureProp=pureProp/.{DD[\[Phi]s[Subscript[x, a_],Subscript[t, c_]] Subscript[F_, \[Chi]][Subscript[x, d_],Subscript[x, b_],Subscript[t, e_]]]:>{\[CapitalDelta][Subscript[x, b-0.1],Subscript[x, b],Subscript[t, e]],Subscript[F, \[Chi]][Subscript[x, d],Subscript[x, b-0.1],Subscript[t, e]],\[Phi]s[Subscript[x, a-0.1],Subscript[t, c]]},
DD[Subscript[F_, \[Phi]][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]\[Chi]s[Subscript[x, d_],A___,Subscript[t, e_]]]:>{\[CapitalDelta][Subscript[x, b-0.1],Subscript[x, b],Subscript[t, c-1]],Subscript[F, \[Phi]][Subscript[x, a],Subscript[x, b-0.1],Subscript[t, c]],\[Chi]s[Subscript[x, d-0.1],A,Subscript[t, e]]},

DD[\[Chi]s[Subscript[x, a_],A___,Subscript[t, c_]]]:>{\[CapitalDelta][Subscript[x, a-0.1],Subscript[x, a],Subscript[t, c]],\[Chi]s[Subscript[x, a-0.1],A,Subscript[t, c]]},
DD[{\[Delta]\[Chi]s[Subscript[x, a_],A___,Subscript[t, c_]],\[Delta]\[Chi]s[Subscript[x, a_],B___,Subscript[t, c_]]}]:>{\[CapitalDelta][Subscript[x, a-0.1],Subscript[x, a],Subscript[t, c]],\[Delta]\[Chi]s[Subscript[x, a-0.1],A,Subscript[t, c]]\[Delta]\[Chi]s[Subscript[x, a-0.1],B,Subscript[t, c]]},
DD[\[Delta]\[Chi]s[Subscript[x, a_],A___,Subscript[t, c_]]]:>{\[CapitalDelta][Subscript[x, a-0.1],Subscript[x, a],Subscript[t, c]],\[Delta]\[Chi]s[Subscript[x, a-0.1],A,Subscript[t, c]]},

DD[Subscript[F_, \[Phi]][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]]:>{\[CapitalDelta][Subscript[x, a+0.2],Subscript[x, a],Subscript[t, c]],Subscript[F, \[Phi]][Subscript[x, a+0.2],Subscript[x, b],Subscript[t, c]]},(* If DD acts of Subscript[G, \[Phi]] it means that it's acting on the past line*)
DD[Subscript[F_, \[Chi]][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]]:>{\[CapitalDelta][Subscript[x, b-0.2],Subscript[x, b],Subscript[t, c]],Subscript[F, \[Chi]][Subscript[x, a],Subscript[x, b-0.2],Subscript[t, c]]}};

pureProp=Flatten@(pureProp/.{\[Delta]\[Chi]s[Subscript[x, a_],___,Subscript[t, c_]]:>\[Delta]\[Chi]s[Subscript[x, a],Subscript[t, c]],
\[Chi]s[Subscript[x, a_],___,Subscript[t, c_]]:>\[Chi]s[Subscript[x, a],Subscript[t, c]],
\[Chi][Subscript[x, a_],___,Subscript[t, c_]]:>\[Chi][Subscript[x, a],Subscript[t, c]]});

MyPrint[{"The propagators are\n ",pureProp}];

(*Print[pureProp];*)

dots=Flatten[pureProp//.{Subscript[F_, \[Chi]][Subscript[x, a_],Subscript[x, a_],Subscript[t, c_]]:>{Style[{a+0.54,c},Disk[{0,0},0.05],White,EdgeForm[None]],Style[{a,c},Disk[{0,0},0.05],Black]},
Subscript[F_, \[Chi]][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]:>{Style[{a,c},Disk[{0,0},0.05],Black],Style[{b,c},Disk[{0,0},0.05],Black]},

\[Chi][Subscript[x, a_],___,Subscript[t, c_]]:>{Style[{a+0.54,c},Disk[{0,0},0.05],White,EdgeForm[None]],Style[{a,c},Disk[{0,0},0.05],Black]},

Subscript[F_, \[Chi]][Subscript[x, a_],Subscript[x, a_],0]:>{Style[{a+0.54,1},Disk[{0,0},0.05],White,EdgeForm[None]],Style[{a,1},Disk[{0,0},0.05],Black]},
Subscript[F_, \[Chi]][Subscript[x, a_],Subscript[x, b_],0]:>{Style[{a,1},Disk[{0,0},0.05],Black],Style[{b,1},Disk[{0,0},0.05],Black],Style[{a,1.5},Disk[{0,0},0.05],White,EdgeForm[None]],Style[{a,0.7},Disk[{0,0},0.05],White,EdgeForm[None]]},

Subscript[F_, \[Phi]][Subscript[x, a_],Subscript[x, 0],Subscript[t, c_]]:>{Style[{a,c},Disk[{0,0},0.05],Black]},
Subscript[F_, \[Phi]][Subscript[x, a_],Subscript[x, a_],Subscript[t, c_]]:>{Style[{a,c},Disk[{0,0},0.05],Black],Style[{a,IntegerPart[c-0.5]},Disk[{0,0},0.05],Black],Style[{a+0.3,c-0.5},Disk[{0,0},0.05],White,EdgeForm[None]]},Subscript[F_, \[Phi]][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]:>{Style[{a,c},Disk[{0,0},0.05],Black],Style[{b,IntegerPart[c-0.5]},Disk[{0,0},0.05],Black]},

Subscript[F_, \[Phi]][Subscript[x, a_],Subscript[x, a_],0]:>{Style[{a+0.54,1},Disk[{0,0},0.05],White,EdgeForm[None]],Style[{a,1},Disk[{0,0},0.05],Black]},
Subscript[F_, \[Phi]][Subscript[x, a_],Subscript[x, b_],0]:>{Style[{a,1},Disk[{0,0},0.05],Black],Style[{b,1},Disk[{0,0},0.05],Black],Style[{a,1.5},Disk[{0,0},0.05],White,EdgeForm[None]],Style[{a,0.7},Disk[{0,0},0.05],White,EdgeForm[None]]},

Subscript[F_, \[Phi]][Subscript[x, a_],Subscript[x, a_],0]:>{Style[{a,1},Disk[{0,0},0.05],Black],Style[{a,1},Disk[{0,0},0.05],Black],Style[{a+0.3,1-0.5},Disk[{0,0},0.05],White,EdgeForm[None]]},Subscript[F_, \[Phi]][Subscript[x, a_],Subscript[x, b_],0]:>{Style[{a,1},Disk[{0,0},0.05],Black],Style[{b,1},Disk[{0,0},0.05],Black]},

\[CapitalDelta][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]:>{Style[{a,c},Disk[{0,0},0.05],Black],Style[{b,c},Disk[{0,0},0.05],Black]},\[Psi]s[Subscript[x, a_],Subscript[t, c_]]:>{Style[{a-0.1,c-0.8},Disk[{0,0},0.05],White,EdgeForm[None]]}}];

pureProp=pureProp/.{Subscript[F_, \[Chi]]^n_[Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]:>Style[FindArc[{b,c},{a,c},n,"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[1]],FindArc[{b,c},{a,c},n,"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[2]],Darker[Green]],
Subscript[F_, \[Chi]][Subscript[x, a_],Subscript[x, a_],Subscript[t, c_]]:>{Style[FindArc[{a+0.5,c},{a,c},4,"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[1]],FindArc[{a+0.5,c},{a,c},4,"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[2]],Darker[Green]],Style[FindArc[{a+0.5,c},{a,c},-4,"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[1]],FindArc[{a+0.5,c},{a,c},-4,"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[2]],Darker[Green]]},
Subscript[F_, \[Chi]][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]:>Style[FindArc[{b,c},{a,c},(b-a-0.2*HeavisideTheta[a-b]),"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[1]],FindArc[{b,c},{a,c},(b-a-0.2*HeavisideTheta[a-b]),"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[2]],Darker[Green]],

Subscript[F_, \[Chi]][Subscript[x, a_],Subscript[x, a_],0]:>{Style[FindArc[{a+0.5,1},{a,1},2,"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[1]],FindArc[{a+0.5,1},{a,1},2,"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[2]],Darker[Green]],Style[FindArc[{a+0.5,1},{a,1},-2,"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[1]],FindArc[{a+0.5,1},{a,1},-2,"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[2]],Darker[Green]]},
Subscript[F_, \[Chi]][Subscript[x, a_],Subscript[x, b_],0]:>Style[FindArc[{b,1},{a,1},1.1(b-a),"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[1]],FindArc[{b,1},{a,1},1.1(b-a),"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[2]],Darker[Green]],

Subscript[F_, \[Phi]][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]^n_:>Style[FindArc[{b,IntegerPart[c-0.5]},{a,c},n,"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[1]],FindArc[{b,IntegerPart[c-0.5]},{a,c},n,"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[2]],Red],
Subscript[F_, \[Phi]][Subscript[x, a_],Subscript[x, 0],Subscript[t, c_]]:>Style[Line[{{a-0.13,c-0.13},{a,c}}],Arrowheads[{0,.03}],Red],
Subscript[F_, \[Phi]][Subscript[x, a_],Subscript[x, a_],Subscript[t, c_]]:>{Style[FindArc[{a,IntegerPart[c-0.5]},{a,c},2,"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[1]],FindArc[{a+0.5,IntegerPart[c-0.5]},{a,c},2,"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[2]],Red]},
Subscript[F_, \[Phi]][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]:>Style[FindArc[{b,IntegerPart[c-0.5]},{a,c},1,"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[1]],FindArc[{b,IntegerPart[c-0.5]},{a,c},1,"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[2]],Red],

Subscript[F_, \[Phi]][Subscript[x, a_],Subscript[x, b_],0]^n_:>Table[Style[FindArc[{b,1},{a,1},(b-a+0.9)(-1)^j,"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[1]],FindArc[{b,1},{a,1},(b-a+0.9)(-1)^j,"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[2]],Red],{j,1,n}],
Subscript[F_, \[Phi]][Subscript[x, a_],Subscript[x, a_],0]:>{Style[FindArc[{a+0.5,1},{a,1},2,"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[1]],FindArc[{a+0.5,1},{a,1},2,"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[2]],Red],Style[FindArc[{a+0.5,1},{a,1},-2,"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[1]],FindArc[{a+0.5,1},{a,1},-2,"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[2]],Red]},
Subscript[F_, \[Phi]][Subscript[x, a_],Subscript[x, b_],0]:>Style[FindArc[{b,1},{a,1},(b-a+0.9),"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[1]],FindArc[{b,1},{a,1},(b-a+0.9),"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[2]],Red],


Subscript[F_, \[Psi]][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]^n_:>Style[FindArc[{a,c-1},{a,c},1,"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[1]],FindArc[{a,c-1},{a,c},1,"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[2]],Blue],
Subscript[F_, \[Psi]][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]:>Style[FindArc[{b,c-1},{b,c},1,"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[1]],FindArc[{b,c-1},{b,c},1,"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[2]],Blue],

\[CapitalDelta][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]:>Style[Line[{{b,c},{a,c}}],Black,Dashed],


\[Chi]s[Subscript[x, a_],___,Subscript[t, c_]]^n_:>Table[Style[Arrow[{{a,c},{a-0.2,c+0.1*Sin[\[Pi] ii/n]}}],Arrowheads[{0,.03}],Darker[Green]],{ii,1,n}],
\[Chi]s[Subscript[x, a_],___,Subscript[t, c_]]:>Style[Arrow[{{a,c},{a-0.2,c}}],Arrowheads[{0,.03}],Darker[Green]],
\[Delta]\[Chi]s[Subscript[x, a_],___,Subscript[t, c_]]:>Style[Arrow[{{a,c},{a-0.2,c}}],Arrowheads[{0,.03}],Darker[Green],Dashed],

\[Delta]\[Chi]s[Subscript[x, a_],___,Subscript[t, c_]]^n_:>Table[Style[Arrow[{{a,c},{a-0.2,c+0.1*Sin[\[Pi] ii/n]}}],Arrowheads[{0,.03}],Darker[Green],Dashed],{ii,1,n}],
\[Chi][Subscript[x, a_],___,Subscript[t, c_]]:>Style[Arrow[{{a+0.2,c},{a,c}}],Arrowheads[{0,0.03,0}],Darker[Green]],

\[Phi]s[Subscript[x, a_],Subscript[t, c_]]:>Style[Arrow[{{a,c-1},{a-0.2,c-1+0.2}}],Arrowheads[{0,.03}],Red],
\[Psi]s[Subscript[x, a_],Subscript[t, c_]]:>Style[Arrow[{{a,IntegerPart[c-1]},{a,IntegerPart[c-1]+OptionValue["\[Psi]sLength"]}}],Arrowheads[{0,.03}],Blue],
\[Delta]\[Psi]s[Subscript[x, a_],Subscript[t, c_]]:>Style[Arrow[{{a,c-1},{a,c-0.7}}],Arrowheads[{0,.03}],Blue,Dashed]};

pureProp=Flatten[pureProp];


MyPrint[{"They will be drawn as\n ",pureProp}];
	(*dots=Flatten[pureProp//.{Style[Arrow[{{a_,c_},{b_,d_}}],___,color_]/;(IntegerQ[a*b*c*d]&&color=!=Blue):>{Style[{a,c},Disk[{0,0},0.05],Black],Style[{b,d},Disk[{0,0},0.05],Black]},Style[Arrow[{{a_,c_},{b_,d_}}],___]/;(!IntegerQ[a*b*c*d]):>{Style[{b-0.1,d},Disk[{0,0},0.05],White,EdgeForm[None]]},
Style[Line[{{a_,c_},{b_,c_}}],Black,Dashed]:>{Style[{a,c},Disk[{0,0},0.05],Black],Style[{b,c},Disk[{0,0},0.05],Black]}}];*)

AppendTo[plot,ListPlot[dots,
PlotLabel-> Row[{ToString[i+OptionValue["initialIndex"]-1]<>": ",weight}],
Axes->False,
Frame->False,
Mesh->Full,
AxesOrigin->{1,1}-0.2,
PlotStyle->{PointSize[OptionValue["pointSize"]]},
Prolog->pureProp,
ImagePadding->{{10,10},{10,10}},
PlotRangeClipping->False,
ImageSize->OptionValue["ImageSize"]]
];

];(*End of Loop*)


If[OptionValue["export"],
Export[OptionValue["exportDirectory"],plot(*Row[plot,"\n"]*)];
];

Return[Row[plot]];
]
