(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
BeginPackage["WickContraction`"]


(* ::Input::Initialization:: *)
$WickContractionVersion::usage="$WickContractionVersion is the current version of the WickContraction package.";
$WickContractionReleaseDate::usage="$WickContractionReleaseDate is the release date of the current version.";$WickContractionReleaseDate="2025-11-29";$WickContractionVersion=StringReplace[FileBaseName[$Input],{"p"->"."(*,Except[DigitCharacter]->""*)}];
(*$WickContractionVersion=StringReplace[FileBaseName[NotebookFileName[]],{"p"->".",Except[DigitCharacter]->""}];*)


(* ::Input::Initialization:: *)
$WickContractionPrint::usage="$WickContractionPrint=True turns on the debug printing of the package.";
If[!ValueQ[$WickContractionPrint],$WickContractionPrint=True];


(* ::Input::Initialization:: *)
WickContraction`Private`MyPrint=If[$WickContractionPrint,Print[##]]&;


(* ::Input::Initialization:: *)
Print[Style["~~~~~~~~~~~~~~~~ WickContraction v"<>ToString[$WickContractionVersion]<>" ~~~~~~~~~~~~~~~~~~~~\n\
Author: Paolo Pisapia.\n\
Release Date: "<>$WickContractionReleaseDate<>"\n\
Timestamp: "<>DateString[FileDate[$InputFileName]]<>"\nRead from:"<>$InputFileName<>" (CRC32:"<>ToString[FileHash[$InputFileName,"CRC32"]]<>","<>ToString[FileHash[Select[FileNames[$LiteRedHomeDirectory<>"FermatCode/*"],Not@*DirectoryQ],"CRC32"]]<>")\n\nLiteRed stands for ",Style["L",{Lighter@Red}],"oop ",Style["i",{Lighter@Red}],"n",Style["te",{Lighter@Red}],"grals ",Style["Red",{Lighter@Red}],"uction.\n\
The package is designed for performing Wick contractions. \
\n\nSee ?WickContraction`* for a list of functions. ",{Bold,Lighter@Blue}]];


(* ::Input::Initialization:: *)
Begin["Private`"]


(* ::Input::Initialization:: *)
ClearAll[DD];

(*Remove[DD];*)
DD /:DD[0]:=0;
DD /:DD'[(\[Kappa]*A_+B_)C_.]:=DD[A*C]/(A*C);
(*DD /:DD'[(\[Kappa]*A_+B_)]:=DD[A]/(A);*)
DD /:DD'[(\[Kappa]*A_)]:=DD[A]/(A);
(*DD'[a_[x_] b_[y_]]:=1;
DD[a_[x_]*b_[y_]]:=DD[a[x]]*b[y]+DD[b[y]]*a[x]+2\[Del]a[x]*\[Del]b[y];*)

DD /:DD'[0]=1;


(* ::Input::Initialization:: *)
ClearAll[V];

V/:V[1.]:=1.;
V/:V[1]:=1;
V/:V[0]:=0;
(*V/:V'[DD[a__]]:=DD[a]/a;(*(ToExpression["\[Delta]"<>ToString[a]]);*)*)
V/:V'[a_]:=1;
V/:V''[a_]:=0;
V/:V'''[a_]:=0;


(* ::Input::Initialization:: *)
ClearAll[\[CapitalSigma]\[Delta]rule,\[Delta]];

SetAttributes[\[Delta],Orderless];

\[Delta]/:\[Delta][a_,b_]^n_/;(!NumericQ[b]&& !MatchQ[b,Subscript[1, __]]):=\[Delta][a,b]^(n-2) \[Delta][a,a];
\[Delta]/:\[Delta][b_,a_]\[Delta][c_,b_]/;(!NumericQ[b] && !MatchQ[b,Subscript[1, __]]):=\[Delta][c,a];\[Delta]/:\[Delta][a_i,a_i]/;(a=!=Subscript[i, s]):=Subscript[n, \[Chi]];
\[Delta]/:\[Delta][a_\[Alpha],a_\[Alpha]]:=Subscript[n, \[Alpha]];

\[CapitalSigma]\[Delta]rule={\[Delta][a_,b_]^n_/;(!NumericQ[b]&& !MatchQ[b,Subscript[1, __]]):>\[Delta][a,b]^(n-2) \[Delta][a,a],
\[Delta][b_,a_]\[Delta][c_,b_]/;(!NumericQ[b] && !MatchQ[b,Subscript[1, __]]):>\[Delta][c,a],
\[Delta][a_,b_]\[Delta][c_,b_]/;(!NumericQ[b]&& !MatchQ[b,Subscript[1, __]]):>\[Delta][a,c],

\[Delta][a_,a_]/;(MatchQ[a,Subscript[i, __]])/;(a=!=Subscript[i, s]):>Subscript[n, \[Chi]],
\[Delta][a_,a_]/;(MatchQ[a,Subscript[\[Alpha], __]]):>Subscript[n, \[Alpha]]};


(* ::Input::Initialization:: *)
ClearAll[\[Delta]ruleExternal];(*Not defined*)


(* ::Input::Initialization:: *)
ClearAll[FieldsNamesGenerator];

FieldsNamesGenerator::usage="FieldsNamesGenerator[\!\*
StyleBox[\"fields_List\", \"TI\"]] takes a list of field variable names and returns a list of the modified names needed by WickContraction[]. The modified names are StyleBox[\"starFields\", \"TI\"], StyleBox[\"deltaFields\", \"TI\"] and StyleBox[\"deltaStarFields\", \"TI\"] .";

FieldsNamesGenerator[fields_List]:=Block[{locFields={},starFields={},deltaFields={},deltaStarFields={}},Module[{l},

locFields=fields;

For[l=1,l<=Length[locFields],l++,
AppendTo[starFields, ToExpression[ToString[locFields[[l]]] <> "s"]];
AppendTo[deltaFields, ToExpression["\[Delta]"<>ToString[locFields[[l]]] ]];
AppendTo[deltaStarFields,ToExpression["\[Delta]"<> ToString[starFields[[l]]] ]];
];(*End of loop to define the fields*)

Return[{locFields,starFields,deltaFields,deltaStarFields}]
];
];


(* ::Input::Initialization:: *)
ClearAll[WickContraction,x];

WickContraction::usage=(*MODIFY*)"WickContraction[\!\*
StyleBox[\"expr\", \"TI\"]] draw a graph from tStyleBox[\"expr\", \"TI\"]. \nOptions:\n    \"pointSize\"->0.015 - Set the point size,\n    \"ArrowHeadSize\"->0.05 - Set the Arrow Heads size,\n    \"print\"->False|True - Print for debug,\n    \"ImageSize\"->Medium - Set the Image size,\n    \"export\"->False|True - Exports the Graph,\n    \"exportDirectory\"->\"myFile.pdf\" - Set the export Directory,\n    \"initialIndex\"->1 - Set the index to start the counting of diagrams from.";


(* ::Input::Initialization:: *)
WickContraction::zero=Style["Your expression is zero.\nAborting...",Red];

Options[WickContraction]={"pointSize"->0.015,
"ArrowHeadSize"->0.05,
"print"->False,
"ImageSize"->Medium,
"export"->False,
"exportDirectory"->"myFile.pdf",
"initialIndex"->1};


(* ::Input::Initialization:: *)
ClearAll[WickContraction];

Options[WickContraction]={
"print"->False,
"fields"->FieldsNamesGenerator[{\[Phi],\[Chi],\[Psi]}], 
"startingTime"->1, 
"endTime"->1,
"#vertices"->10,
"\[Delta]rule"->True,
"\[Delta]ruleExternal"->True,
"\!\(\*SubscriptBox[\(n\), \(\[Chi]\)]\)"->(-1),
"\!\(\*SubscriptBox[\(n\), \(\[Alpha]\)]\)"->(0),
"maxContractions"->5,
"kill\[Psi]"->True,
"SimplifyPropagators"->True,
"SimplifyG\[Psi]"->True,
"ReturnJustAction"->False,
"FreeAction"->FreeAction};


(* ::Input::Initialization:: *)
WickContraction[A_ +B_,opts:OptionsPattern[]]:=WickContraction[A,opts]+WickContraction[B,opts];

WickContraction[A_?NumericQ,OptionsPattern[]]:=A;

WickContraction[V[A_] *B_, OptionsPattern[]]:=Module[{interactionPermutations={},locFields={}, starFields={}, deltaFields={},deltaStarFields={},contributions=0,z,zTemp1,zTemp2,jj,l,timeIndex,ii,ss,DDflag=False},

z=V[A]*B;

If[(!FreeQ[z,DD[___]]),DDflag=True;];

If[OptionValue["ReturnJustAction"],Return[z];];


locFields=OptionValue["fields"][[1]];
starFields=OptionValue["fields"][[2]];
deltaFields=OptionValue["fields"][[3]];
deltaStarFields=OptionValue["fields"][[4]];

(*Start the REAL loop over time*)
For[timeIndex=OptionValue["startingTime"],timeIndex<=(OptionValue["endTime"]),timeIndex++,

(* The addition of Hold[0] is used to make sure that Head[z]=Sum. This way we can specify Reaplace[...,{1}]*)
z=z*(OptionValue["FreeAction"][timeIndex])+Hold[0]; 

(*Start of loop over fields*)
For[l=1,l<=Length[locFields],l++,

MyPrint["################## Contracting ",locFields[[l]][x_,Subscript[t, timeIndex]]," ##################"];

(*ZEROTH contribution*)

(* Is Replace faster??*)
zTemp1=Replace[z,{locFields[[l]][___,Subscript[t, timeIndex]]->0},{1,7}];

contributions=zTemp1;
MyPrint["Zeroth contribution: ",contributions];

zTemp1=z;

ii=0;

While[(!FreeQ[zTemp1,locFields[[l]][___,Subscript[t, timeIndex]]]||!FreeQ[zTemp1,deltaFields[[l]][___,Subscript[t, timeIndex]]])&& ii<OptionValue["maxContractions"],
	
	zTemp1=z;
	
	ii++;
	
	MyPrint["Contraction order ",ii,": "];
	
	For[ss=1,ss<=ii,ss++,
	
	(* To have the possibility of \[Delta]-fields directly inside vertices, I separate the splitting and the introduction of \[Kappa] in front of \[Delta]Fields*)
	(*zTemp2=zTemp1/. starFields[[l]][a___,Subscript[t, timeIndex]]->starFields[[l]][a,Subscript[t, timeIndex]]+\[Kappa] *deltaStarFields[[l]][a,Subscript[t, timeIndex]];*)
	
	(* Is Replace faster??*)
	zTemp2=Replace[zTemp1,{ starFields[[l]][a___,Subscript[t, timeIndex]]->starFields[[l]][a,Subscript[t, timeIndex]]+deltaStarFields[[l]][a,Subscript[t, timeIndex]]},{1,7}];
	zTemp2=Replace[zTemp2,{ deltaStarFields[[l]][a___,Subscript[t, timeIndex]]->\[Kappa] *deltaStarFields[[l]][a,Subscript[t, timeIndex]]},{1,8}];
	
	
	If[zTemp2-zTemp1===0 ,
	(* zTemp1-zTemp2==0: TRUE *)
	zTemp1 =0;
	Break[];
	,
	
	(* zTemp1-zTemp2==0: FALSE *)
	(*zTemp1=1/Factorial[ii]D[zTemp2,{\[Kappa],ii}]/.\[Kappa]->0;*)
	
	zTemp1=(*1/ss*)D[zTemp2,{\[Kappa]}]/.\[Kappa]->0;
	
	MyPrint["Extraction of ",deltaStarFields[[l]]," #",ss," at order ",ii,":\n ",zTemp1];
	];
	
	
	(*zTemp2=zTemp1/. locFields[[l]][a___,Subscript[t, timeIndex]]->locFields[[l]][a,Subscript[t, timeIndex]]+\[Kappa] *deltaFields[[l]][a,Subscript[t, timeIndex]];*)
	
	(* Is Replace faster??*)
	zTemp2=Replace[zTemp1,{ locFields[[l]][a___,Subscript[t, timeIndex]]->locFields[[l]][a,Subscript[t, timeIndex]]+deltaFields[[l]][a,Subscript[t, timeIndex]]},{1,7}];
	zTemp2=Replace[zTemp2,{ deltaFields[[l]][a___,Subscript[t, timeIndex]]->\[Kappa] *deltaFields[[l]][a,Subscript[t, timeIndex]]},{1,7}];
	
	MyPrint["Replacement: ", locFields[[l]]->locFields[[l]]+\[Kappa] deltaFields[[l]],":\n ",zTemp2];
	
	
	If[zTemp1-zTemp2===0,
	(* zTemp1-zTemp2==0: TRUE *)
	zTemp1 =0;
	Break[];
	,
	
	(* zTemp1-zTemp2==0: False *)
	(*zTemp1=1/Factorial[ii]D[zTemp1,{\[Kappa],ii}]/.\[Kappa]->0;*)
	
	zTemp1=1/ss D[zTemp2,{\[Kappa]}];
	
	MyPrint["Extraction of ",deltaFields[[l]]," #",ss," at order ",ii,":\n ",zTemp1];
	
	zTemp1=zTemp1/.\[Kappa]->0;
	
	MyPrint[zTemp1];
	];
	
	
	
	(*MyPrint[zTemp1,"\n"];*)
	If[zTemp1=!=0,
	
	(* CONTRACTION *)
	zTemp1=Expand[zTemp1];
	
	(* Is Replace faster?? *)
	zTemp2=Replace[(zTemp1),{Times[f___,deltaFields[[l]][x_,a___,Subscript[t, timeIndex]]*deltaStarFields[[l]][y_,b___,Subscript[t, timeIndex]],g___]->Times[f,Subscript[G, locFields[[l]]][x,y,Subscript[t, timeIndex]],\[Delta][{a},{b}],g]},{0,1}];
	
	(*zTemp2=zTemp1//.deltaFields[[l]][x_,a___,Subscript[t, timeIndex]]*deltaStarFields[[l]][y_,b___,Subscript[t, timeIndex]](*/;(!NumericQ[a*b])->*)->Subscript[G, locFields[[l]]][x,y,Subscript[t, timeIndex]]*\[Delta][{a},{b}]; (*G is the propagator*)*)
	
	MyPrint["Contraction of ",deltaFields[[l]],deltaStarFields[[l]],"\n ",zTemp2];
	
	If[DDflag, zTemp2 = ReplaceRepeated[zTemp2, Part[deltaStarFields, l][Pattern[x, Blank[]], Pattern[a, BlankNullSequence[]], Subscript[t, timeIndex]] DD[Part[deltaFields, l][Pattern[y, Blank[]], Pattern[b, BlankNullSequence[]], Subscript[t, timeIndex]]] :> DD[Subscript[G, Part[locFields, l]][y, x, Subscript[t, timeIndex]]] \[Delta][{a}, {b}]]; zTemp2 = ReplaceRepeated[zTemp2, Part[deltaFields, l][Pattern[x, Blank[]], Pattern[a, BlankNullSequence[]], Subscript[t, timeIndex]] DD[Part[deltaStarFields, l][Pattern[y, Blank[]], Pattern[b, BlankNullSequence[]], Subscript[t, timeIndex]]] :> DD[Subscript[G, Part[locFields, l]][x, y, Subscript[t, timeIndex]]] \[Delta][{a}, {b}]]; Null];(* If on DDflag *)
	
	zTemp1=Replace[zTemp2,{ (*Times[___,locFields[[l]][___,Subscript[t, timeIndex]],___]*)deltaFields[[l]][___,Subscript[t, timeIndex]]->0,deltaStarFields[[l]][___,Subscript[t, timeIndex]]->0},{1,5}];
	
	];(*END of If on zTemp1=!=0*)
	];(* END OF "FOR" ON DERIVATIONS+CONTRACTIONS*)
	
	zTemp2=zTemp1/.locFields[[l]][___,Subscript[t, timeIndex]]->0;
	(*z=z/.starFields[[l]][___,Subscript[t, timeIndex]]->0;*)
	(*zTemp2=Replace[zTemp1,{ (*Times[___,locFields[[l]][___,Subscript[t, timeIndex]],___]*)locFields[[l]][___,Subscript[t, timeIndex]]->0},{1,5}];*)
	
	If[(contributions-zTemp2=!=0) && (zTemp2=!=0) ,
		
		contributions+=zTemp2;
		MyPrint["Contribution #",ii,": ",zTemp2];
	];
	
];(* END OF WHILE*)

z=contributions;


MyPrint["Overall contributions: ",contributions,"
################################################################################################"];

contributions=0;

(*];(*End of loop over number of vertices*)*)

(*z=z/.locFields[[l]][___,Subscript[t, timeIndex]]->0;*)
(*z=z/.starFields[[l]][___,Subscript[t, timeIndex]]->0;*)
(* Is Replace faster??*)
z=Replace[z,{ locFields[[l]][___,Subscript[t, timeIndex]]->0,deltaFields[[l]][___,Subscript[t, timeIndex]]->0},{1,5}];
z=Replace[z,{ deltaStarFields[[l]][___,Subscript[t, timeIndex]]->0},{1,5}];



(* Expansion of the \[Delta]'s *)
z=z//.\[Delta][{a_,c___},{b_,d___}]->\[Delta][a,b]\[Delta][{c},{d}]//.\[Delta][{},{}]->1;


MyPrint["Expansion of the \[Delta]'s: ",z,"
################################################################################################"];

(* Is Replace faster?? CANNOT BE USED HERE*)
(*z=Replace[z,{ \[Delta][{a_,c___},{b_,d___}]->\[Delta][a,b]\[Delta][{c},{d}],\[Delta][{},{}]->1},{0,4}];*)


If[OptionValue["\[Delta]rule"],
	z=z//.\[CapitalSigma]\[Delta]rule;
	
	
	MyPrint["Application of the \[Delta]rule: ",z,"
################################################################################################"]];
];

If[OptionValue["\[Delta]ruleExternal"],
	(* Contraction of the indices *)
	z=z//.\[Delta][a_,b_]starFields[[l]][c___,a_,d___,Subscript[t, timeIndex]]/;(NumericQ[b] && !NumericQ[a]):>\[Delta][a,b]starFields[[l]][c,b,d,Subscript[t, timeIndex]]/.\[Delta][a_,b_]/;(NumericQ[b] && !NumericQ[a]):>1;
	z=z//.\[Delta][a_,b_]starFields[[l]][c___,b_,d___,Subscript[t, timeIndex]]/;(NumericQ[a] && !NumericQ[b]):>\[Delta][a,b]starFields[[l]][c,a,d,Subscript[t, timeIndex]]/.\[Delta][a_,b_]/;(NumericQ[a] && !NumericQ[b]):>1;
	z=z//.\[Delta][a_,a_]->1;
	
	MyPrint["Application of the \[Delta]ruleExternal: ",z,"
################################################################################################"];
];

(*z=z/.Subscript[n, \[Chi]]->OptionValue["Subscript[n, \[Chi]]"];
z=z/.Subscript[n, \[Alpha]]->OptionValue["Subscript[n, \[Alpha]]"];*)
z=Replace[(z),{Subscript[n, \[Chi]]->OptionValue["\!\(\*SubscriptBox[\(n\), \(\[Chi]\)]\)"],Subscript[n, \[Alpha]]->OptionValue["\!\(\*SubscriptBox[\(n\), \(\[Alpha]\)]\)"]},{2}];

];(*End of loop over fields*)

(*z=z/.Subscript[G, \[Psi]][Subscript[x, a_],Subscript[x, b_],__]/;(!FreeQ[a,action]&&!FreeQ[a,action]):>0/.Subscript[G, \[Phi]][a_,a_,b_] ->0/.Subscript[G, \[Chi]][a_,a_,b_] ->0;*) (* Eliminate loops*)


z=Replace[(z),{Subscript[G, \[Psi]][Subscript[x, a_],Subscript[x, b_],__]/;(!FreeQ[a,action]&&!FreeQ[a,action]):>0,Subscript[G, \[Phi]][a_,a_,b_] ->0},{2}];

If[OptionValue["kill\[Psi]"] ,
z=z/.\[Psi]s[___,Subscript[t, a_]]/;(a<=timeIndex):>0/.\[Delta]\[Psi]s[___,Subscript[t, a_]]/;(a<=timeIndex):>0;
(*z=Replace[(z),{\[Psi]s[___,Subscript[t, a_]]/;(a<=timeIndex):>0,\[Delta]\[Psi]s[___,Subscript[t, a_]]/;(a<=timeIndex):>0},{1,4}];*)
];

(* This releases dummy=0 *)
z=ReleaseHold[z];

];(*End of loop over time*)


Clear[locFields, starFields, deltaFields,deltaStarFields,contributions,zTemp1,zTemp2,\[Kappa],jj,l,timeIndex,ii,ss];


MyPrint["Final result:\n ",z];

If[OptionValue["SimplifyPropagators"],
z=SimplifyPropagators[z,"SimplifyG\[Psi]"->OptionValue["SimplifyG\[Psi]"]]];

SystemOpen[LogFile]];

Return[z]
];
