(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



SetOptions[$FrontEndSession,NotebookAutoSave->True]
NotebookSave[]
InitializationValue[$Initialization] = Hold[$HistoryLength = 2];


(* ::Input::Initialization:: *)
Clear[MyGraph];
Options[MyGraph]={"undirected" ->True,"label" ->False};
MyGraph[edges__,root_,source_,OptionsPattern[]]:={Module[{locEdges={},i,locWeights={},locRoot=root,locSource=source,p},
Clear[\[Beta]];

For[i=1, i<=(Dimensions@edges)[[1]],i++,
If[OptionValue["undirected"] && edges[[i,2]] =!=locSource && edges[[i,2]] =!=edges[[i,1]] ,
AppendTo[locEdges,edges[[i,2]]->edges[[i,1]]];
AppendTo[locWeights,\[Beta][edges[[i,2]],edges[[i,1]]] ]
];

If[edges[[i,1]]==locSource,Continue[]];

AppendTo[locEdges,edges[[i,1]]->edges[[i,2]]];
AppendTo[locWeights,\[Beta][edges[[i,1]],edges[[i,2]]] ]
];

locEdges=Sort[locEdges,(#1[[1]]<=#2[[1]] &&#1[[2]]<=#2[[1]])||(#1[[1]]<#2[[2]] &&#1[[2]]<=#2[[2]]) &];

p[\[Beta][a_,b_],\[Beta][c_,d_]]:=1/;(a<=c&&b<=c);
p[\[Beta][a_,b_],\[Beta][c_,d_]]:=-1/;(c<=a&&d<=a);
p[\[Beta][a_,b_],\[Beta][c_,d_]]:=1/;(a<d&&b<=d);
p[\[Beta][a_,b_],\[Beta][c_,d_]]:=-1/;(c<b&&d<=b);
locWeights=Sort[locWeights,p];

(*Print[locEdges];
Print[locWeights]*);

If[ OptionValue["label"],
(*True*)Graph[locEdges,EdgeWeight->locWeights, EdgeStyle->Blue, VertexLabels->{locRoot->ToString[locRoot]<>", ROOT",locSource->ToString[locSource]<>", SOURCE","Name"}, EdgeLabels->"EdgeWeight", VertexStyle->{locRoot->Red,locSource->Green,Blue},EdgeShapeFunction->"FilledArrow"],
(*False*)Graph[locEdges,EdgeWeight->locWeights, EdgeStyle->Blue, VertexLabels->{locRoot->ToString[locRoot]<>", ROOT",locSource->ToString[locSource]<>", SOURCE","Name"}, VertexStyle->{locRoot->Red,locSource->Green,Blue},EdgeShapeFunction->"FilledArrow"]]
],
root(*Root*),source(*Source*)}


(* ::Input::Initialization:: *)
myFavoriteEdges={{1,2},{1,5},{2,3},{2,5},{5,4},{3,4}};
myFavoriteRoot=1;
myFavoriteSource=4;
myFavoriteGraph=MyGraph[myFavoriteEdges,myFavoriteRoot,myFavoriteSource][[1]];


(* ::Input::Initialization:: *)
Clear[DrawOnGraph];
Options[DrawOnGraph]={"drawOthers"-> True};
DrawOnGraph[graph_,path__,OptionsPattern[]]:=Module[{locEdges,locPathStyle={},locRoot,locSource,i},
locEdges = EdgeList@graph;
locRoot = 
 Select[(List@@@PropertyValue[graph,VertexLabels])[[2;;]],StringMatchQ[#[[2]],___~~"ROOT"]&][[All,1]][[1]];
locSource = 
 Select[(List@@@PropertyValue[graph,VertexLabels])[[2;;]],StringMatchQ[#[[2]],___~~"SOURCE"]&][[All,1]][[1]];

For[i=1, i<=Length[path],i++,
AppendTo[locPathStyle,{path[[i,1]]\[DirectedEdge]path[[i,2]]->path[[i,3]]}];
(*Print[locPathStyle]*)
];
If[OptionValue["drawOthers"],
(*True*)Graph[locEdges,EdgeStyle->Flatten@{locPathStyle,Blue}, VertexLabels->{locRoot->ToString[locRoot]",ROOT",locSource->ToString[locSource]",SOURCE","Name"}, VertexStyle->{locRoot->Red,locSource->Green,Blue},EdgeShapeFunction->"FilledArrow"],
(*False*)Graph[locEdges,EdgeStyle->Flatten@{locPathStyle,White}, VertexLabels->{locRoot->ToString[locRoot]",ROOT",locSource->ToString[locSource]",SOURCE","Name"}, VertexStyle->{locRoot->Red,locSource->Green,Blue},EdgeShapeFunction->"FilledArrow"]
]
]


Clear[DrawFromExpression];
Options[DrawFromExpression]={"graph"->g,"drawOthers"->False};

DrawFromExpression[exp_,OptionsPattern[]]:=Module[{terms,graphs={},i},
terms=exp//.R[a_,b_,c_]^n_->R[a,b,c]//Expand;
terms=List @@ (terms+Zeta[3]);
terms=terms//.\[Beta][__]->1;
terms=DeleteElements[terms,{Zeta[3]}];
terms=Outer[List,terms];
terms=terms//.Times->List;
terms=monoFlatten@@@terms;
terms=terms//.R[a_,b_,c_]->{a,b,c};
(*For[i=1,i<=Length[terms],i++,
terms[[i]]=DeleteElements[terms[[i]],{a_?NumericQ}];
];*)
Print[terms];

For[i=1,i<=Length[terms],i++,
AppendTo[graphs,DrawOnGraph[OptionValue["graph"],terms[[i,2;;]],"drawOthers"->OptionValue["drawOthers"]]];
Print[graphs[[i]]];
Print[Weight ==terms[[i,1]]];
];
]


(* ::Input::Initialization:: *)
Clear[AugmentedGraph];
AugmentedGraph[graph_]:=Module[{locVertices,locEdges,locPathStyle={},locRoot,locSource,newSource,oldSourceNeighbors,graphPlus,i},

locVertices = VertexList@graph;
locEdges = EdgeList@graph/.DirectedEdge->List;
locRoot = 
 Select[(List@@@PropertyValue[graph,VertexLabels])[[2;;]],StringMatchQ[#[[2]],___~~"ROOT"]&][[All,1]][[1]];
locSource = 
 Select[(List@@@PropertyValue[graph,VertexLabels])[[2;;]],StringMatchQ[#[[2]],___~~"SOURCE"]&][[All,1]][[1]];

newSource=locVertices[[-1]]+1;

(*Add the edge from the oldSource to the newSource*)
AppendTo[locEdges,{locSource,newSource}];

(*Add all the edges from the oldSource to its neighbors*)
oldSourceNeighbors=Select[locEdges, #[[2]]==locSource &];

For[i=1,i<=Length[oldSourceNeighbors],i++,
AppendTo[locEdges,{locSource,oldSourceNeighbors[[i,1]]}]
];

graphPlus =MyGraph[locEdges,locRoot,newSource,"undirected"->False][[1]];

Return[{graphPlus,locSource,newSource}]
]


(* ::Input::Initialization:: *)
Clear[monoFlatten];
(*monoFlatten[a_?NumericQ]:={};*)
monoFlatten[a_]:={a};
monoFlatten[{a__}]:={{a}};
monoFlatten[{a__,b__}]:={a,b};


Clear[ExtractPaths];
ExtractPaths[exp_]:=Module[{terms,paths={},i},

terms=exp//Expand;
terms=List @@Collect[terms,R[__,Red]];
terms=Outer[List,terms];

For[i=1,i<=Length[terms],i++,
If[MatchQ[terms[[i,1]],R[__,Red]*A_],
AppendTo[paths,terms[[i]]]
]
];
terms=paths//.R[__,Blue]->1//FullSimplify;

Return[terms]
]


(* ::Input::Initialization:: *)
Clear[FieldsNamesGenerator];
FieldsNamesGenerator[fields_]:=
FieldsNamesGenerator[fields]=Block[{locFields={},starFields={},deltaFields={},deltaStarFields={},l},

locFields=fields;

For[l=1,l<=Length[locFields],l++,
AppendTo[starFields, ToExpression[ToString[locFields[[l]]] <> "s"]];
AppendTo[deltaFields, ToExpression["\[Delta]"<>ToString[locFields[[l]]] ]];
AppendTo[deltaStarFields,ToExpression["\[Delta]"<> ToString[starFields[[l]]] ]];
];(*End of loop to define the fields*)

Return[{locFields,starFields,deltaFields,deltaStarFields}]
]


(* ::Input::Initialization:: *)
Clear[WickContractionBlock];
Options[WickContractionBlock]={"print"->False,"fields"->FieldsNamesGenerator[{\[Chi]}], "endTime"->1,"#vertices"->10,"MAXnumberOfDer"->3};

WickContractionBlock[A_ +B_,opts:OptionsPattern[]]:=WickContractionBlock[A,opts]+WickContractionBlock[B,opts];

WickContractionBlock[Op[A_ +B_]*C_,opts:OptionsPattern[]]:=WickContractionBlock[Op[A]C,opts]+WickContractionBlock[Op[B]C,opts];

WickContractionBlock[A_?NumericQ,OptionsPattern[]]:=A;

(*################################################################################
									Partition Function                             
##############################################################################*)
(*There are two possible contributions for each field: 1) it is not contracted: \[Chi]->0; 2) it is contracted*)

WickContractionBlock[V[A_] *B_., OptionsPattern[]]:=Block[{locFields={}, starFields={}, deltaFields={},deltaStarFields={},contributions=0,z,zTemp1,zTemp2,\[Kappa],jj,l,timeIndex,numberOfDer},

z=V[A]B;

locFields=OptionValue["fields"][[1]];
starFields=OptionValue["fields"][[2]];
deltaFields=OptionValue["fields"][[3]];
deltaStarFields=OptionValue["fields"][[4]];


(*Start a loop over time*)
For[timeIndex=0,timeIndex<=(OptionValue["endTime"]-1),timeIndex++,

z=z//.f_[x_,Subscript[t, (timeIndex+1)],a_]->f[x,a];

(*Start of loop over fields*)
For[l=1,l<=Length[locFields],l++,

(*Start of loop over space*)
For[jj=1,jj<=OptionValue["#vertices"],jj++,

(*First contribution*)
zTemp1=z//.locFields[[l]][jj,a_]->0//.starFields[[l]][jj,a_]->0;
If[zTemp1-z=!=0,
contributions=zTemp1;
(*Print["First contribution: ",zTemp1];*)
];

(* N E W  P A R T  O N  M U L T I P L E  C O N T R A C T I O N S *)
For[numberOfDer=1,numberOfDer<=OptionValue["MAXnumberOfDer"],numberOfDer++,
zTemp1=z/. locFields[[l]][jj,a_]->locFields[[l]][jj,a]+\[Kappa] *deltaFields[[l]][jj,a];
If[zTemp1-z=!=0,
zTemp1= D[zTemp1,{\[Kappa],numberOfDer}]/(numberOfDer!)/.\[Kappa]->0(*,
Continue[]*);
];
		
		zTemp2=zTemp1/. starFields[[l]][jj,a_]->starFields[[l]][jj,a]+deltaStarFields[[l]][jj,a];
		zTemp2=zTemp2/. deltaStarFields[[l]][jj,a_]->\[Kappa] *deltaStarFields[[l]][jj,a];

		If[zTemp2-zTemp1=!=0,
		zTemp1=D[zTemp2,{\[Kappa],numberOfDer}]/.\[Kappa]->0(*,
		Continue[]*);
		];
		
		zTemp1=Expand[zTemp1];
		zTemp2=zTemp1//.deltaFields[[l]][jj,a_]^n_.*deltaStarFields[[l]][jj,b_]^n_.(*/;(!NumericQ[a*b]):>*)->\[Delta][a,b]^n;
		(*zTemp2=zTemp1//.deltaFields[[l]][jj,a_]*deltaStarFields[[l]][jj,b_]*deltaFields[[l]][jj,a_]*deltaStarFields[[l]][jj,b_](*/;(!NumericQ[a*b]):>*)->\[Delta][a,b]*\[Delta][a,b];*)
		
		zTemp1=zTemp2/.deltaFields[[l]][jj,a_]->0/.deltaStarFields[[l]][jj,b_]->0;
		
		If[contributions-zTemp1=!=0,
		contributions+=zTemp1;
		(*Print["Third contribution: ",zTemp1];*)
		];
];

(*  E N D  O F  C O N T R I B U T I O N S  *)
z=contributions;

contributions=0;

(* N E W  P A R T:  FIELDS SET TO 0 EARLIER *)

z=z/.locFields[[l]][jj,a_]->0;
z=z/.starFields[[l]][jj,a_]->0;
z=z/.deltaStarFields[[l]][jj,b_]->0;
];(*End of loop over space*)


];(*End of loop over fields*)

z=z//.\[CapitalSigma]\[Delta]rule;

];(*End of loop over time*)

Return[z]
];


(* ::Input::Initialization:: *)
Clear[ExpectationValueBlock];
Options[ExpectationValueBlock]={"operator"->1,"print"->False, "fields"->FieldsNamesGenerator[{\[Chi]}],"endTime"->1,"draw"->False,"graph"->g, "Rrule"->{R[__]->1},"external\[Delta]"->True,"n\[Chi]"->-1,"n\[Alpha]"->0,"MAXnumberOfDer"->3};

ExpectationValueBlock[Z_,OptionsPattern[]]:=Block[{Nvertices,z,terms,graphs={},i},

Nvertices=Length[VertexList@OptionValue["graph"]];

If[OptionValue["operator"]===1,
(*True*)z=WickContractionBlock[Z,
"print"->OptionValue["print"], 
"fields"->OptionValue["fields"],
"endTime"->OptionValue["endTime"],
"#vertices"->Nvertices,
"MAXnumberOfDer"->OptionValue["MAXnumberOfDer"]
],
(*False*)z=WickContractionBlock[Z*Op[OptionValue["operator"]],
"print"->OptionValue["print"], 
"fields"->OptionValue["fields"],
"endTime"->OptionValue["endTime"],
"#vertices"->Nvertices,
"MAXnumberOfDer"->OptionValue["MAXnumberOfDer"]
]/WickContractionBlock[Z, "fields"->OptionValue["fields"],"endTime"->OptionValue["endTime"],
"#vertices"->Nvertices,
"MAXnumberOfDer"->OptionValue["MAXnumberOfDer"]]
];

If[OptionValue["external\[Delta]"],
z=z//.\[Delta]ruleExternal
];

z=z/.n->OptionValue["n\[Chi]"];
z=z/.m->0;

If[OptionValue["draw"],
(*True*)
z=z//.R[a_,b_,c_]^n_->R[a,b,c];
terms=List @@ (z+Zeta[3]);
terms=terms//.\[Beta][__]->1;
terms=DeleteElements[terms,{Zeta[3]}];
terms=Outer[List,terms];
terms=terms//.Times->List;
terms=monoFlatten@@@terms;
terms=terms//.R[a_,b_,c_]->{a,b,c};
(*For[i=1,i<=Length[terms],i++,
terms[[i]]=DeleteElements[terms[[i]],{a_?NumericQ}];
];*)
Print[terms];
z=z/.R[___]->1;
(*
For[i=1,i<=Length[terms],i++,
AppendTo[graphs,DrawOnGraph[OptionValue["graph"],terms[[i,2;;]],"drawOthers"->False]];
Print[graphs[[i]]];
Print[Weight ==terms[[i,1]]];
]*);,

(*False*)z=z/.OptionValue["Rrule"]];

Return[z]]


(* ::Input::Initialization:: *)
Clear[LERWtransitionProb];
Options[LERWtransitionProb]={"draw"->False,"print"->False};

LERWtransitionProb[graph_,path__,OptionsPattern[]]:=Module[{locSource,locRoot,locWeights,totWeights,locVertices,denominator,prob=1, Z,numerator},
locWeights=WeightedAdjacencyMatrix[graph]//Normal;
totWeights =Total[locWeights,{2}];

locVertices=VertexList@graph;

locRoot = 
 Select[(List@@@PropertyValue[graph,VertexLabels])[[2;;]],StringMatchQ[#[[2]],___~~"ROOT"]&][[All,1]][[1]];
locSource = 
 Select[(List@@@PropertyValue[graph,VertexLabels])[[2;;]],StringMatchQ[#[[2]],___~~"SOURCE"]&][[All,1]][[1]];

If[locRoot =!= path[[1,1]], Print["####  WRONG ROOT  ####"]; Return[NULL]];
If[locSource =!= path[[-1,2]], Print["####  WRONG SOURCE  ####"];Return[NULL]];

Module[{locBC={{},{}},\[Phi],i=1,j},
locBC={{\[Phi][locSource]==1},{locSource}};

For[i=1,i<=Length[path],i++,

Z=VertexAssignment[graph, "excludedVertices"->locBC[[2]]];
Z=ExpectationValueBlock[Z*\[Chi]s[path[[i,1]],1]];

If[OptionValue["print"],
Print["#####  Previous Partition Function  #####"];
Print[Z]
];

denominator=Z//FullSimplify;


(*Then we need to solve it again with updated BC at the current step*)

AppendTo[locBC[[1]],\[Phi][path[[i,1]]]==0];
AppendTo[locBC[[2]],path[[i,1]]];
(*Print[locBC]*);


Z=VertexAssignment[graph, "excludedVertices"->locBC[[2]],"sourceBC"->denominator^-1];
Z=ExpectationValueBlock[Z*\[Chi]s[path[[i,2]],1] ];

If[OptionValue["print"],
Print["#####  Current Partition Function  #####"];
Print[Z]
];

numerator=locWeights[[path[[i,1]],path[[i,2]]]]/totWeights[[path[[i,1]]]]*Z//FullSimplify;

Print["#####  Transition probability "<>ToString[path[[i,1]]]<>" to "<>ToString[path[[i,2]]]<>"  #####"];
Print[numerator/.\[Beta][_,_]->1//FullSimplify];

prob*=numerator//FullSimplify;
]
];
If[OptionValue["draw"],Print[DrawOnGraph[graph,path]]];
Return[prob]
]


(* ::Input::Initialization:: *)
Clear[V];
V[1.]:=1.;
V[1]:=1;
V[0]:=0;
V'[a_]:=1


(* ::Input::Initialization:: *)
Clear[VertexAssignment];
Options[VertexAssignment]={"system"->"LERW","print"->False,"excludedVertices"->{},"sourceBC"->1};

VertexAssignment[graph_,OptionsPattern[]]:=Module[{locVertices,locWeights,totWeights,locSource,action,x,y},
Clear[i];
locVertices=VertexList@graph;
locWeights=WeightedAdjacencyMatrix[graph]//Normal;
totWeights =Total[locWeights,{2}];
locSource = 
 Select[(List@@@PropertyValue[graph,VertexLabels])[[2;;]],StringMatchQ[#[[2]],___~~"SOURCE"]&][[All,1]][[1]];

(*LERW*)
If[OptionValue["system"]=="LERW",
If[OptionValue["print"],Print["#####   "<>OptionValue["system"]<>"   #####"]];
action = Product[ If[totWeights[[x]]===0 || MemberQ[OptionValue["excludedVertices"],x],1,V[(1+ Sum[locWeights[[x,y]]/totWeights[[x]] \[Chi]s[y,Subscript[i, x]]\[Chi][x,Subscript[i, x]],{y,Length[locVertices]}] ) ]],{x,Length[locVertices]}];
action*=V[(1+ OptionValue["sourceBC"] \[Chi][locSource,Subscript[i, s]])];(*This is the BC*)
Return[action]];

(*DLA*)
If[OptionValue["system"]=="DLA",If[OptionValue["print"],Print["#####   "<>OptionValue["system"]<>"   #####"]];
Return[
Product[ If[totWeights[[x]]===0 || MemberQ[OptionValue["excludedVertices"],x],1,V[(1+ Product[1+locWeights[[x,y]]/totWeights[[x]] \[Chi]s[y,Subscript[i, x]],{y,Length[locVertices]}] \[Chi][x,Subscript[i, x]]+ Sum[locWeights[[x,y]]/totWeights[[x]] \[Phi]s[y,Subscript[j, x]]\[Phi][x,Subscript[j, x]],{y,Length[locVertices]}])] ],{x,Length[locVertices]}]
]]
]


(* ::Input::Initialization:: *)
ClearAll[\[CapitalSigma]\[Delta]rule];
\[CapitalSigma]\[Delta]rule={\[Delta][a_,b_]^n_/;(!NumericQ[b]&& !MatchQ[b,Subscript[1, __]]):>\[Delta][a,b]^(n-2) \[Delta][a,a],
\[Delta][b_,a_]\[Delta][c_,b_]/;(!NumericQ[b] && !MatchQ[b,Subscript[1, __]]):>\[Delta][c,a],
\[Delta][a_,b_]\[Delta][c_,b_]/;(!NumericQ[b]&& !MatchQ[b,Subscript[1, __]]):>\[Delta][a,c],
\[Delta][a_,a_]/;(MatchQ[a,Subscript[i, __]])/;(a=!=Subscript[i, s]):>n,
\[Delta][a_,a_]/;(MatchQ[a,Subscript[j, __]])/;(a=!=Subscript[j, s]):>n,
\[Delta][a_,a_]/;(MatchQ[a,Subscript[k, _]]):>1,
\[Delta][a_,a_]/;(MatchQ[a,Subscript[l, _]]):>1,
\[Delta][a_,a_]/;(MatchQ[a,Subscript[ll, _]]):>1};


(* ::Input::Initialization:: *)
ClearAll[\[Delta]ruleExternal];
\[Delta]ruleExternal={\[Delta][a_,a_]/;(NumericQ[a] || a==Subscript[i, s] || MatchQ[a,Subscript[j, __]]|| MatchQ[a,Subscript[1, __]]|| MatchQ[a,Subscript[jjj, __]] ||MatchQ[a,Subscript[k, _]]):>1,
\[Delta][a_,b_]/;(NumericQ[a] ||MatchQ[a,Subscript[k, _]]|| MatchQ[a,Subscript[j, __]]|| MatchQ[a,Subscript[1, _]]|| MatchQ[a,Subscript[jjj, __]] )/;(a=!=b):>0,
\[Delta][a_,b_]/;(NumericQ[b] ||MatchQ[b,Subscript[k, _]]|| MatchQ[b,Subscript[j, __]]|| MatchQ[a,Subscript[1, _]]|| MatchQ[a,Subscript[jjj, __]] )/;(a=!=b):>0 };


(* ::Input::Initialization:: *)
Clear[Op];
Op[1]:=1;
Op[0]:=0;
Op'[_]:=1


(* ::Input::Initialization:: *)
Clear[LRWaction];
Options[LRWaction]={"sourceBC"->1,"excludedVertices"->{},"graph"->g,"startingTime"->1,"endTime"->10};

LRWaction[OptionsPattern[]]:=Module[{locGraph,locStartingTime,locEndTime,locSource,locRoot,locWeights,totWeights,locVertices,actionTimeSlice,action},
Clear[i,k,j,\[Gamma]];


locGraph=OptionValue["graph"];
locStartingTime =OptionValue["startingTime"];
locEndTime =OptionValue["endTime"];

locWeights=WeightedAdjacencyMatrix[locGraph]//Normal;
totWeights =Total[locWeights,{2}];

locVertices=VertexList@locGraph;

locRoot = 
 Select[(List@@@PropertyValue[locGraph,VertexLabels])[[2;;]],StringMatchQ[#[[2]],___~~"ROOT"]&][[All,1]][[1]];
locSource = 
 Select[(List@@@PropertyValue[locGraph,VertexLabels])[[2;;]],StringMatchQ[#[[2]],___~~"SOURCE"]&][[All,1]][[1]];


actionTimeSlice [T_]:= Product[
If[totWeights[[x]]===0  || MemberQ[OptionValue["excludedVertices"],x],1,
(*FALSE*)V[(1+\[Gamma] Sum[locWeights[[x,y]](R[x,y,Red]\[Phi]s[y,Subscript[t, T+1],Subscript[k, y]]\[Psi]s[x,Subscript[t, T+1],Subscript[ll, x]]-\[Phi]s[x,Subscript[t, T+1],Subscript[k, x]])\[Chi]s[y,Subscript[t, T],1]*\[Phi][x,Subscript[t, T],Subscript[k, x]],{y,Length[locVertices]}]+Sum[locWeights[[x,y]]/totWeights[[x]] R[x,y,Blue]\[Chi]s[y,Subscript[t, T],Subscript[i, x]]\[Chi][x,Subscript[t, T],Subscript[i, x]],{y,Length[locVertices]}]
+(*COPY \[Phi]*) \[Phi]s[x,Subscript[t, T+1],Subscript[k, x]]*\[Phi][x,Subscript[t, T],Subscript[k, x]]
+(*COPY \[Psi]*) \[Psi]s[x,Subscript[t, T+1],Subscript[ll, x]]*\[Psi][x,Subscript[t, T],Subscript[ll, x]]) ]
],{x,Length[locVertices]}]
V[(1+ \[Phi]s[locSource,Subscript[t, T+1],Subscript[k, locSource]]\[Phi][locSource,Subscript[t, T],Subscript[k, locSource]]+\[Chi][locSource,Subscript[t, T],1])];

action=Product[actionTimeSlice[T],{T,locEndTime}];

Return[action]

]


(* ::Input::Initialization:: *)
fields=FieldsNamesGenerator[{\[Phi],\[Chi],\[Psi]}];
g=myFavoriteGraph;
endTime=1;
ZZ=LRWaction["graph"->g,"endTime"->endTime]/.\[Beta][__]->1;
ZZ0=ZZ/.\[Gamma]->0;


(* ::Input::Initialization:: *)
Clear[bLRWaction];
Options[bLRWaction]={"sourceBC"->1,"excludedVertices"->{},"graph"->g,"startingTime"->1,"endTime"->10};

bLRWaction[OptionsPattern[]]:=Module[{locGraph,locStartingTime,locEndTime,locSource,locRoot,locWeights,totWeights,locVertices,actionTimeSlice,action},
Clear[i,k,j,\[Gamma]];


locGraph=OptionValue["graph"];
locStartingTime =OptionValue["startingTime"];
locEndTime =OptionValue["endTime"];

locWeights=WeightedAdjacencyMatrix[locGraph]//Normal;
totWeights =Total[locWeights,{2}];

locVertices=VertexList@locGraph;

locRoot = 
 Select[(List@@@PropertyValue[locGraph,VertexLabels])[[2;;]],StringMatchQ[#[[2]],___~~"ROOT"]&][[All,1]][[1]];
locSource = 
 Select[(List@@@PropertyValue[locGraph,VertexLabels])[[2;;]],StringMatchQ[#[[2]],___~~"SOURCE"]&][[All,1]][[1]];


actionTimeSlice [T_]:= Product[
If[totWeights[[x]]===0  || MemberQ[OptionValue["excludedVertices"],x],1,
(*FALSE*)V[(\[Gamma] Sum[locWeights[[x,y]](R[x,y,Red]\[Phi]s[y,Subscript[t, T+1],Subscript[k, y]]\[Psi]s[x,Subscript[t, T+1],Subscript[ll, x]]-\[Phi]s[x,Subscript[t, T+1],Subscript[k, x]])\[Chi]s[y,Subscript[t, T],1]\[Xi]s[y,Subscript[t, T],1]*\[Phi][x,Subscript[t, T],Subscript[k, x]],{y,Length[locVertices]}]+(1+Sum[locWeights[[x,y]]/totWeights[[x]] R[x,y,Blue]\[Chi]s[y,Subscript[t, T],Subscript[i, x]]\[Chi][x,Subscript[t, T],Subscript[i, x]],{y,Length[locVertices]}])(1+Sum[locWeights[[x,y]]/totWeights[[x]] R[x,y,Blue]\[Xi]s[y,Subscript[t, T],Subscript[j, x]]\[Xi][x,Subscript[t, T],Subscript[j, x]],{y,Length[locVertices]}])
+(*COPY \[Phi]*) \[Phi]s[x,Subscript[t, T+1],Subscript[k, x]]*\[Phi][x,Subscript[t, T],Subscript[k, x]]
+(*COPY \[Psi]*) \[Psi]s[x,Subscript[t, T+1],Subscript[ll, x]]*\[Psi][x,Subscript[t, T],Subscript[ll, x]]) ]
],{x,Length[locVertices]}]
V[( \[Phi]s[locSource,Subscript[t, T+1],Subscript[k, locSource]]\[Phi][locSource,Subscript[t, T],Subscript[k, locSource]]+(1+\[Chi][locSource,Subscript[t, T],1])*(1+\[Xi][locSource,Subscript[t, T],1]))];

action=Product[actionTimeSlice[T],{T,locEndTime}];

Return[action]

]


(* ::Input::Initialization:: *)
Clear[Znorm];
Options[Znorm]={"graph"->g,"fieldsToExclude"->{\[Phi]s,\[Psi]s},"theory"->"LERW","\[Beta]rule"->{\[Beta][__]->1}};

Znorm[expression_,OptionsPattern[]]:=Block[{locZnorm,excludedVertices,token,index},

excludedVertices=(expression * 2)/.R[__]->1/.\[Gamma]->1//Expand;
excludedVertices=List @@excludedVertices;
excludedVertices=excludedVertices[[2;;]]; (*Gets rid of the numerical coefficient*)

For[index=1,index<=Length[OptionValue["fieldsToExclude"]],index++,
excludedVertices=excludedVertices/.OptionValue["fieldsToExclude"][[index]][a_,__]->a;
];
(*excludedVertices=excludedVertices/.\[Psi]s[a_,__]->a;
excludedVertices=excludedVertices/.\[Psi]s[a_,__]\[Psi]s[a_,__]->a;
excludedVertices=excludedVertices/.\[Xi]s[a_,__]->a;
excludedVertices=excludedVertices/.\[Xi]s[a_,__]\[Xi]s[a_,__]->a;*)

locZnorm=VertexAssignment[OptionValue["graph"],"system"->"LERW","excludedVertices"->excludedVertices]/.OptionValue["\[Beta]rule"];

ExpectationValueBlock[locZnorm * token,"graph"->OptionValue["graph"],"fields"->FieldsNamesGenerator[{\[Phi],\[Chi]}]]/.token->1
]


(* ::Input::Initialization:: *)
Clear[ZnormGeneral];
Options[ZnormGeneral]={"graph"->g,
"endTime"->endTime,
"fieldsToExclude"->{\[Phi]s,\[Psi]s},
"theory"->LRWaction,
"\[Beta]rule"->{\[Beta][__]->1},
"fields"->FieldsNamesGenerator[{\[Phi],\[Chi],\[Psi]}],
"MAXnumberOfDer"->3};

ZnormGeneral[expression_,OptionsPattern[]]:=Block[{locZnorm,excludedVertices,token,index},

excludedVertices=(expression * 2)/.R[__]->1/.\[Gamma]->1//Expand;
excludedVertices=List @@excludedVertices;
excludedVertices=excludedVertices[[2;;]]; (*Gets rid of the numerical coefficient*)

For[index=1,index<=Length[OptionValue["fieldsToExclude"]],index++,
	excludedVertices=excludedVertices/.OptionValue["fieldsToExclude"][[index]][a_,__]->a;
];
(*excludedVertices=excludedVertices/.\[Psi]s[a_,__]->a;
excludedVertices=excludedVertices/.\[Psi]s[a_,__]\[Psi]s[a_,__]->a;
excludedVertices=excludedVertices/.\[Xi]s[a_,__]->a;
excludedVertices=excludedVertices/.\[Xi]s[a_,__]\[Xi]s[a_,__]->a;*)

locZnorm=OptionValue["theory"]["graph"->g,"endTime"->OptionValue["endTime"],"excludedVertices"->excludedVertices]/.OptionValue["\[Beta]rule"];(*VertexAssignment[OptionValue["graph"],"system"->"LERW","excludedVertices"->excludedVertices]/.OptionValue["\[Beta]rule"];*)

ExpectationValueBlock[locZnorm *token,"endTime"->OptionValue["endTime"],"fields"->OptionValue["fields"],"draw"->False,"Rrule"->{R[__,Blue]->1},"external\[Delta]"->True,"graph"->OptionValue["graph"],"MAXnumberOfDer"->OptionValue["MAXnumberOfDer"]]/.token->1
(*ExpectationValueBlock[locZnorm * token,"graph"->OptionValue["graph"],"fields"->FieldsNamesGenerator[{\[Phi],\[Chi],\[Xi]}]]/.token->1*)
]


(* ::Input::Initialization:: *)
Clear[ConvergenceGeneral];
Options[ConvergenceGeneral]={"graph"->g,
"fields"->FieldsNamesGenerator[{\[Phi],\[Psi],\[Chi]}],
"steps"->10,
"precision"->10^-9,
"gammaValue"->0.1,
"theory"->LRWaction,
"MAXnumberOfDer"->1};

ConvergenceGeneral[operator_,OptionsPattern[]]:=Module[{ZZ,locOperator,locPrecision,loc\[Gamma],exp,i,temp,token},

i=1;

ZZ=OptionValue["theory"]["graph"->OptionValue[ "graph"],"endTime"->1]/.\[Beta][__]->1;

locOperator= operator /ZnormGeneral[operator,"graph"->OptionValue[ "graph"],"endTime"->1,"\[Beta]rule"->{\[Beta][__]->1},"fields"->OptionValue["fields"],"theory"->OptionValue["theory"],"MAXnumberOfDer"->OptionValue["MAXnumberOfDer"]];

locPrecision=OptionValue["precision"];
loc\[Gamma]=OptionValue["gammaValue"];

exp=ExpectationValueBlock[ZZ locOperator,"endTime"->1,"fields"->OptionValue["fields"],"Rrule"->{R[__,Blue]->1},"graph"->OptionValue[ "graph"],"n\[Chi]"->(-1),"MAXnumberOfDer"->OptionValue["MAXnumberOfDer"]];
exp=exp/.Subscript[t, a_]->Subscript[t, a-1];
exp=exp/.\[Gamma]->loc\[Gamma];

(*Print["########## i="<>ToString[i]<>", "<>ToString[(Coefficient[exp, \[Phi]s[1,Subscript[t, 1],Subscript[k, 1]]]/.R[__]->0)]<>" ############"];*)

For[i=2,i<=OptionValue["steps"] && (Coefficient[exp,  \[Phi]s[1,Subscript[t, 1],Subscript[k, 1]]]/.R[__]->0/.\[Gamma]->loc\[Gamma])>=locPrecision,i++,

exp=Replace[exp,a_/;(!NumericQ[a]):>a/(ZnormGeneral[a,"graph"->OptionValue[ "graph"],"endTime"->1,"\[Beta]rule"->{\[Beta][__]->1},"fields"->OptionValue["fields"],"theory"->OptionValue["theory"],"MAXnumberOfDer"->OptionValue["MAXnumberOfDer"]]),1];

exp=ExpectationValueBlock[ZZ exp,"endTime"->1,"fields"->OptionValue["fields"],"Rrule"->{R[__,Blue]->1},"graph"->OptionValue[ "graph"],"n\[Chi]"->(-1),"MAXnumberOfDer"->OptionValue["MAXnumberOfDer"]];
exp=exp/.Subscript[t, a_]->Subscript[t, a-1];
exp=exp/.\[Gamma]->loc\[Gamma];

];


Print["########## i=",i-1,", ",(Coefficient[exp, \[Phi]s[1,Subscript[t, 1],Subscript[k, 1]]]/.R[__]->0)," ############"];

Return[exp];
]


Clear[bLRWnorm];
Options[bLRWnorm]={"graph"->g,"endTime"->endTime,"fieldsToExclude"->{\[Phi]s,\[Psi]s},"theory"->"LERW","\[Beta]rule"->{\[Beta][__]->1.},"fields"->FieldsNamesGenerator[{\[Phi],\[Chi],\[Xi],\[Psi]}]};

bLRWnorm[expression_,OptionsPattern[]]:=Block[{locZnorm,excludedVertices,token,index},

excludedVertices=(expression * 2)/.R[__]->1/.\[Gamma]->1//Expand;
excludedVertices=List @@excludedVertices;
excludedVertices=excludedVertices[[2;;]]; (*Gets rid of the numerical coefficient*)

For[index=1,index<=Length[OptionValue["fieldsToExclude"]],index++,
excludedVertices=excludedVertices/.OptionValue["fieldsToExclude"][[index]][a_,__]->a;
];
(*excludedVertices=excludedVertices/.\[Psi]s[a_,__]->a;
excludedVertices=excludedVertices/.\[Psi]s[a_,__]\[Psi]s[a_,__]->a;
excludedVertices=excludedVertices/.\[Xi]s[a_,__]->a;
excludedVertices=excludedVertices/.\[Xi]s[a_,__]\[Xi]s[a_,__]->a;*)

locZnorm=bLRWaction["graph"->g,"endTime"->OptionValue["endTime"],"excludedVertices"->excludedVertices]/.OptionValue["\[Beta]rule"];(*VertexAssignment[OptionValue["graph"],"system"->"LERW","excludedVertices"->excludedVertices]/.OptionValue["\[Beta]rule"];*)

ExpectationValueBlock[locZnorm *token,"endTime"->OptionValue["endTime"],"fields"->OptionValue["fields"],"draw"->False,"Rrule"->{R[__,Blue]->1},"external\[Delta]"->True,"graph"->OptionValue["graph"]]/.token->1
(*ExpectationValueBlock[locZnorm * token,"graph"->OptionValue["graph"],"fields"->FieldsNamesGenerator[{\[Phi],\[Chi],\[Xi]}]]/.token->1*)
]


Clear[ConvergencebLRW];
Options[ConvergencebLRW]={"graph"->g,"fields"->FieldsNamesGenerator[{\[Phi],\[Psi],\[Xi],\[Chi]}],"steps"->10,"precision"->10^-9,"gammaValue"->0.1};

ConvergencebLRW[operator_,OptionsPattern[]]:=Module[{ZZ,locOperator,locPrecision,loc\[Gamma],exp,i,temp,token},

i=1;

ZZ=bLRWaction["graph"->OptionValue[ "graph"],"endTime"->1]/.\[Beta][__]->1;

locOperator= operator /bLRWnorm[operator,"graph"->OptionValue[ "graph"],"endTime"->1,"\[Beta]rule"->{\[Beta][__]->1},"fields"->OptionValue["fields"]];

locPrecision=OptionValue["precision"];
loc\[Gamma]=OptionValue["gammaValue"];

exp=ExpectationValueBlock[ZZ locOperator,"endTime"->1,"fields"->OptionValue["fields"],"Rrule"->{R[__,Blue]->1},"graph"->OptionValue[ "graph"],"n\[Chi]"->(-1)];
exp=exp/.Subscript[t, a_]->Subscript[t, a-1];
exp=exp/.\[Gamma]->loc\[Gamma];

(*Print["########## i="<>ToString[i]<>", "<>ToString[(Coefficient[exp, \[Phi]s[1,Subscript[t, 1],Subscript[k, 1]]]/.R[__]->0)]<>" ############"];*)

For[i=2,i<=OptionValue["steps"] (*&& (Coefficient[exp,  \[Phi]s[1,Subscript[t, 1],Subscript[k, 1]]]/.R[__]->0/.\[Gamma]->loc\[Gamma])>=locPrecision*),i++,

exp=Replace[exp,a_/;(!NumericQ[a]):>a/(bLRWnorm[a,"graph"->OptionValue[ "graph"],"endTime"->1,"\[Beta]rule"->{\[Beta][__]->1},"fields"->OptionValue["fields"]]),1];

exp=ExpectationValueBlock[ZZ exp,"endTime"->1,"fields"->OptionValue["fields"],"Rrule"->{R[__,Blue]->1},"graph"->OptionValue[ "graph"],"n\[Chi]"->(-1)];
exp=exp/.Subscript[t, a_]->Subscript[t, a-1];
exp=exp/.\[Gamma]->loc\[Gamma];

];


Print["########## i=",i-1,", ",(Coefficient[exp, \[Phi]s[1,Subscript[t, 1],Subscript[k, 1]]]/.R[__]->0)," ############"];

Return[exp];
]


(* ::Input::Initialization:: *)
fields=FieldsNamesGenerator[{\[Phi],\[Chi],\[Xi],\[Psi]}];
g=myFavoriteGraph;
endTime=1;
ZZb=bLRWaction["graph"->g,"endTime"->endTime]/.\[Beta][__]->1;
ZZb0=ZZ/.\[Gamma]->0;


Clear[LaplaceEqSolver];
Options[LaplaceEqSolver]={"BC"->{{},{}} , "selectSolution"->0};

LaplaceEqSolver[graph_,OptionsPattern[]]:=Module[{locVertices,locWeights,totWeights,locRoot,locSource,locBC,equations,variables={},x,solution},
Clear[\[CapitalPhi]];

locVertices = VertexList@graph;
locWeights=WeightedAdjacencyMatrix[graph]//Normal;
totWeights =Total[locWeights,{2}];

locRoot = 
 Select[(List@@@PropertyValue[graph,VertexLabels])[[2;;]],StringMatchQ[#[[2]],___~~"ROOT"]&][[All,1]][[1]];
locSource = 
 Select[(List@@@PropertyValue[graph,VertexLabels])[[2;;]],StringMatchQ[#[[2]],___~~"SOURCE"]&][[All,1]][[1]];

locBC=OptionValue["BC"];

If[locBC=!={{},{}},

AppendTo[locBC[[1]],\[CapitalPhi][locSource]== 1];
AppendTo[locBC[[1]],\[CapitalPhi][locRoot]==0];

AppendTo[locBC[[2]],locSource];
AppendTo[locBC[[2]],locRoot];
];

equations =locBC[[1]] ;

For[x=1,x<=Length[locVertices],x++,
AppendTo[variables,\[CapitalPhi][x]];
If[MemberQ[locBC[[2]],x],Continue[]];
AppendTo[equations, \[CapitalPhi][x]==FullSimplify[Sum[locWeights[[x,y]]/totWeights[[x]] \[CapitalPhi][y],{y,Length[locVertices]}]]]];
(*Print[equations];
Print[variables];*)
solution=Flatten@Solve[equations,variables]/. Rule->List;

If[OptionValue["selectSolution"]!=0,(*True*)
solution=Select[solution,#[[1]]==\[CapitalPhi][OptionValue["selectSolution"]] &][[1,2]]
];

Return[solution]
]


Clear[bLaplacianRW];
Options[bLaplacianRW]={"draw"->False,"print"->False};
bLaplacianRW[graph_,path__,b_,OptionsPattern[]]:=Module[{locSource,locRoot,locWeights,locVertices,denominator,prob=1},
locWeights=WeightedAdjacencyMatrix[graph]/.\[Beta][__]->1//Normal;
locVertices=VertexList@graph;
locRoot = 
 Select[(List@@@PropertyValue[graph,VertexLabels])[[2;;]],StringMatchQ[#[[2]],___~~"ROOT"]&][[All,1]][[1]];
locSource = 
 Select[(List@@@PropertyValue[graph,VertexLabels])[[2;;]],StringMatchQ[#[[2]],___~~"SOURCE"]&][[All,1]][[1]];

If[locRoot =!= path[[1,1]], Print["####  WRONG ROOT  ####"]; Abort[]];
If[locSource =!= path[[-1,2]], Print["####  WRONG SOURCE  ####"];Abort[]];

Module[{locBC={{},{}},\[Phi],i,\[Phi]sol},

AppendTo[locBC[[1]],\[CapitalPhi][locSource]==1];
AppendTo[locBC[[2]],locSource];

For[i=1,i<=Length[path],i++,
AppendTo[locBC[[1]],\[CapitalPhi][path[[i,1]]]==0];
AppendTo[locBC[[2]],path[[i,1]]];

(*Print[locBC];*)

\[Phi]sol=LaplaceEqSolver[graph,"BC"->locBC]/.\[Beta][__]->1;
(*Print[\[Phi]sol];*)

(*Print[" ##### OK SO FAR ##### "];*)

denominator=Sum[locWeights[[path[[i,1]],y]]*(Select[\[Phi]sol,#[[1]]==\[CapitalPhi][y] &][[1,2]])^b,{y,Length[locVertices]}];
(*Print[denominator]*);

If[OptionValue["print"],
Print["#####  Transition probability "<>ToString[path[[i,1]]]<>" to "<>ToString[path[[i,2]]]<>"  #####"];

Print[(locWeights[[path[[i,1]],path[[i,2]]]]*(Select[\[Phi]sol,#[[1]]==\[CapitalPhi][path[[i,2]]] &][[1,2]])^b)/denominator/.\[Beta][_,_]->1//FullSimplify];
];

prob*=(locWeights[[path[[i,1]],path[[i,2]]]]*(Select[\[Phi]sol,#[[1]]==\[CapitalPhi][path[[i,2]]] &][[1,2]])^b)/denominator/.\[Beta][__]->1//FullSimplify;
Clear[\[Phi]sol];
];(*END OF FOR*)
];(*END OF MODULE*)

If[OptionValue["draw"],Print[DrawOnGraph[graph,path]]];
Return[prob]
]



Clear[PathFinder];

PathFinder[graph_]:=Module[{pathList={{}}},
Step[subgraph_]:=Module[{locEdges,locVertices,locWeights,locRoot,locSource,locMoves,newEdges, newRoot,smallerGraph,i},
locEdges = EdgeList@subgraph/.DirectedEdge->List;
locVertices=VertexList@subgraph;
If[Length[locVertices]==1,Return[NULL]];
locWeights=WeightedAdjacencyMatrix[subgraph]//Normal;
locRoot = 
 Select[(List@@@PropertyValue[subgraph,VertexLabels])[[2;;]],StringMatchQ[#[[2]],___~~"ROOT"]&][[All,1]][[1]];
locSource = 
 Select[(List@@@PropertyValue[subgraph,VertexLabels])[[2;;]],StringMatchQ[#[[2]],___~~"SOURCE"]&][[All,1]][[1]];
locMoves=Select[locEdges,#[[1]]==locRoot &][[All]];

(*Print["###  LocMoves  ####"];
Print[locMoves];*);

For[i=1, i<=Length[locMoves],i++,

If[i ==Length[locMoves],
(*True*)If[locMoves[[i,2]]==locSource,
 (*Ture*)pathList=Append[pathList[[2;;]],Append[pathList[[1]],locMoves[[i]]]]; Continue[],
 (*False*)pathList=Prepend[pathList[[2;;]],Append[pathList[[1]],locMoves[[i]]]]
],
(*False*)
If[locMoves[[i,2]]==locSource,
 (*True*)pathList=Append[pathList,Append[pathList[[1]],locMoves[[i]]]];Continue[],
 (*False*)pathList=Prepend[pathList,Append[pathList[[1]],locMoves[[i]]]]
]];

(*Print["###  pathList  ####"];
Print[pathList];*);

newEdges=Select[locEdges,#[[1]]=!=locRoot && #[[2]]=!=locRoot &][[All]];
newRoot = locMoves[[i,2]];
If[Length[newEdges] <= 0,Continue[]];
smallerGraph=MyGraph[newEdges,newRoot,locSource,"undirected"->False][[1]];

(*Print[smallerGraph];*);

Step[smallerGraph]
]
];

Step[graph];
Return[pathList]
]


Clear[AllbLaplacianRWs]

Options[AllbLaplacianRWs]={"draw"->False,"print"->False};

AllbLaplacianRWs[graph_,b_,OptionsPattern[]]:=Module[{possibleLRW,i,probabilityLRW={}},
possibleLRW=PathFinder[graph];
For[i=1, i<= Length[possibleLRW],i++,
AppendTo[probabilityLRW,bLaplacianRW[graph,possibleLRW[[i]],b,"draw"->OptionValue["draw"]]];

If[OptionValue["print"],Print[i,") Laplacian RW ",possibleLRW[[i]]," with probability " ,probabilityLRW[[i]]]
]
];

possibleLRW=
Replace[possibleLRW,{a_?NumberQ,c_?NumberQ}:>R[a,c,RGBColor[1, 0, 0]],3];

Return[{possibleLRW,probabilityLRW}]
]


Clear[b];


Clear[AllbLaplacianRWs]

Options[AllbLaplacianRWs]={"draw"->False,"print"->False};

AllbLaplacianRWs[graph_,b_,OptionsPattern[]]:=Module[{possibleLRW,i,probabilityLRW={}},
possibleLRW=PathFinder[graph];
For[i=1, i<= Length[possibleLRW],i++,
AppendTo[probabilityLRW,bLaplacianRW[graph,possibleLRW[[i]],b,"draw"->OptionValue["draw"]]];

If[OptionValue["print"],Print[i,") Laplacian RW ",possibleLRW[[i]]," with probability " ,probabilityLRW[[i]]]
]
];
Return[{possibleLRW,probabilityLRW}]
]
