(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
(* Collapse all *)
FrontEndTokenExecute["SelectAll"]
FrontEndTokenExecute["SelectionCloseAllGroups"]


(* ::Input::Initialization:: *)
(* standard abbreviations *)
FS:=FullSimplify
PE:=PowerExpand
TF:=TeXForm


(* ::Input::Initialization:: *)
(* font selection for plotting *)
If[!NumberQ[Kayplotfontsize],Kayplotfontsize=13];
Kayplotfont="Times";
SetOptions[Plot,BaseStyle->{FontFamily->Kayplotfont,FontSize->Kayplotfontsize,AxesStyle->Directive[Black,Kayplotfontsize]}];
(* SetOptions[Show,BaseStyle\[Rule]{FontFamily\[Rule]Kayplotfont,FontSize\[Rule]Kayplotfontsize,AxesStyle\[Rule]Directive[Black,Kayplotfontsize]}];*)
SetOptions[ListPlot,BaseStyle->{FontFamily->Kayplotfont,FontSize->Kayplotfontsize,AxesStyle->Directive[Black,Kayplotfontsize]}];
SetOptions[ListLinePlot,BaseStyle->{FontFamily->Kayplotfont,FontSize->Kayplotfontsize,AxesStyle->Directive[Black,Kayplotfontsize]}];
SetOptions[LogLogPlot,BaseStyle->{FontFamily->Kayplotfont,FontSize->Kayplotfontsize,AxesStyle->Directive[Black,Kayplotfontsize]}];
SetOptions[ListLogLogPlot,BaseStyle->{FontFamily->Kayplotfont,FontSize->Kayplotfontsize,AxesStyle->Directive[Black,Kayplotfontsize]}];
SetOptions[DiscretePlot,BaseStyle->{FontFamily->Kayplotfont,FontSize->Kayplotfontsize,AxesStyle->Directive[Black,Kayplotfontsize]}];
SetOptions[ParametricPlot,BaseStyle->{FontFamily->Kayplotfont,FontSize->Kayplotfontsize,AxesStyle->Directive[Black,Kayplotfontsize]}];
SetOptions[LogPlot ,BaseStyle->{FontFamily->Kayplotfont,FontSize->Kayplotfontsize,AxesStyle->Directive[Black,Kayplotfontsize]}];
SetOptions[ LogLinearPlot,BaseStyle->{FontFamily->Kayplotfont,FontSize->Kayplotfontsize,AxesStyle->Directive[Black,Kayplotfontsize]}];
SetOptions[PolarPlot ,BaseStyle->{FontFamily->Kayplotfont,FontSize->Kayplotfontsize,AxesStyle->Directive[Black,Kayplotfontsize]}];
SetOptions[ Plot3D,BaseStyle->{FontFamily->Kayplotfont,FontSize->Kayplotfontsize,AxesStyle->Directive[Black,Kayplotfontsize]}];
SetOptions[ ListPlot3D,BaseStyle->{FontFamily->Kayplotfont,FontSize->Kayplotfontsize,AxesStyle->Directive[Black,Kayplotfontsize]}];
SetOptions[ ContourPlot,BaseStyle->{FontFamily->Kayplotfont,FontSize->Kayplotfontsize,AxesStyle->Directive[Black,Kayplotfontsize]}];
SetOptions[ Graphics,BaseStyle->{FontFamily->Kayplotfont,FontSize->Kayplotfontsize,AxesStyle->Directive[Black,Kayplotfontsize]}];


(* set directories *)
Module[{notebookdirectory=NotebookDirectory[]},
Print["Directory for read/write is \""<>notebookdirectory<>"\""];
SetDirectory[notebookdirectory];
]


(* ::Input::Initialization:: *)
ClearAll[PPrint];
SetAttributes[PPrint,HoldAll];


Paolofontsize=16;
Paolofont="Times";

Options[PPrint]={"style"->{FontFamily->Paolofont,FontSize->Paolofontsize}};

PPrint[textReplaceable_,var_,textToKeep_:"",OptionsPattern[]]:=Module[{varName,evalVar,textReplaced,textKept,prevInput},

evalVar=var;

varName=Which[(*If a regular named symbol is passed*)
MatchQ[Unevaluated[var],_Symbol],SymbolName[Unevaluated[var]],

(*If % is passed,extract the assigned variable name from previous input line*)
MatchQ[Unevaluated[var],Unevaluated[%]],((InString[$Line-1]//ToExpression)/.RowBox->List//Flatten)[[1]]
];

textReplaced=Unevaluated[Unevaluated[textReplaceable]/. HoldPattern[var]->varName];

textKept=If[textToKeep==="",evalVar,textToKeep];
Print[Style[Row[Flatten@{textReplaced,textKept}],OptionValue["style"]]]
];

(*With[{textReplaced=textReplaceable/.var->SymbolName[Unevaluated[var]],textKept=If[textToKeep=="",var,textToKeep]},Print[Row[Flatten@{textReplaced,textKept}]]];*)
