(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



SetOptions[$FrontEndSession,NotebookAutoSave->True]
NotebookSave[]


(* ::Input::Initialization:: *)
Needs["Notation`"]
Notation[NotationTemplateTag[Subscript[\[Beta], a__]] \[DoubleLongLeftRightArrow] NotationTemplateTag[\[Beta][a__]]]
Notation[NotationTemplateTag[Subscript[R, a__]] \[DoubleLongLeftRightArrow] NotationTemplateTag[R[a__]]]
Notation[NotationTemplateTag[Subscript[\[Phi], a__]] \[DoubleLongLeftRightArrow] NotationTemplateTag[\[Phi][a__]]]
Notation[NotationTemplateTag[Subscript[\[Chi], a__]] \[DoubleLongLeftRightArrow] NotationTemplateTag[\[Chi][a__]]]
Notation[NotationTemplateTag[Subscript[\[Psi], a__]] \[DoubleLongLeftRightArrow] NotationTemplateTag[\[Psi][a__]]]
Notation[NotationTemplateTag[Subscript[\[Xi], a__]] \[DoubleLongLeftRightArrow] NotationTemplateTag[\[Xi][a__]]]
Notation[NotationTemplateTag[Subscript[\[Pi], a__]] \[DoubleLongLeftRightArrow] NotationTemplateTag[\[Pi][a__]]]

Notation[NotationTemplateTag[Subscript[\!\(\*OverscriptBox[\(\[Phi]\), \(~\)]\), a__]] \[DoubleLongLeftRightArrow] NotationTemplateTag[\[Phi]s[a__]]]
Notation[NotationTemplateTag[Subscript[\!\(\*OverscriptBox[\(\[Chi]\), \(~\)]\), a__]] \[DoubleLongLeftRightArrow] NotationTemplateTag[\[Chi]s[a__]]]
Notation[NotationTemplateTag[Subscript[\!\(\*OverscriptBox[\(\[Psi]\), \(~\)]\), a__]] \[DoubleLongLeftRightArrow] NotationTemplateTag[\[Psi]s[a__]]]
Notation[NotationTemplateTag[Subscript[\!\(\*OverscriptBox[\(\[Pi]\), \(~\)]\), a__]] \[DoubleLongLeftRightArrow] NotationTemplateTag[\[Pi]s[a__]]]

Notation[NotationTemplateTag[Subscript[\!\(\*OverscriptBox[\(\[Delta]\[Phi]\), \(~\)]\), a__]] \[DoubleLongLeftRightArrow] NotationTemplateTag[\[Delta]\[Phi]s[a__]]]
Notation[NotationTemplateTag[Subscript[\!\(\*OverscriptBox[\(\[Delta]\[Chi]\), \(~\)]\), a__]] \[DoubleLongLeftRightArrow] NotationTemplateTag[\[Delta]\[Chi]s[a__]]]
Notation[NotationTemplateTag[Subscript[\!\(\*OverscriptBox[\(\[Delta]\[Psi]\), \(~\)]\), a__]] \[DoubleLongLeftRightArrow] NotationTemplateTag[\[Delta]\[Psi]s[a__]]]
Notation[NotationTemplateTag[Subscript[\!\(\*OverscriptBox[\(\[CapitalDelta]\[Phi]\), \(~\)]\), a__]] \[DoubleLongLeftRightArrow] NotationTemplateTag[\[CapitalDelta]\[Phi]s[a__]]]
Notation[NotationTemplateTag[Subscript[\!\(\*OverscriptBox[\(\[CapitalDelta]\[Chi]\), \(~\)]\), a__]] \[DoubleLongLeftRightArrow] NotationTemplateTag[\[CapitalDelta]\[Chi]s[a__]]]
Notation[NotationTemplateTag[Subscript[\!\(\*OverscriptBox[\(\[CapitalDelta]\[Pi]\), \(~\)]\), a__]] \[DoubleLongLeftRightArrow] NotationTemplateTag[\[CapitalDelta]\[Pi]s[a__]]]

Notation[NotationTemplateTag[\!\(\*OverscriptBox[\(\[Phi]\), \(~\)]\)] \[DoubleLongLeftRightArrow] NotationTemplateTag[\[Phi]s]]
Notation[NotationTemplateTag[\!\(\*OverscriptBox[\(\[Chi]\), \(~\)]\)] \[DoubleLongLeftRightArrow] NotationTemplateTag[\[Chi]s]]



