(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)

ClearAll[V\[Gamma]1,V\[Gamma]1\[Delta],V\[Gamma]1\[Delta]1,V\[Gamma]1\[Delta]2,V\[Gamma]1Minus,V\[Gamma]g,V\[Gamma]1g\[Chi]Minus,V\[Gamma]1g\[Psi],V\[Gamma]1g\[Psi]Minus,V\[Gamma]2,V\[Gamma]21,V\[Gamma]22,V\[Gamma]2Minus,V\[Gamma]2Minus1,V\[Gamma]2Minus2,V\[Gamma]2g\[Chi],V\[Gamma]2g\[Chi]Minus,V\[Gamma]2g\[Psi],V\[Gamma]2g\[Psi]Minus,V\[Psi]\[Psi],V\[Psi]\[Chi],V\[Delta]\[Psi]\[Chi],V\[Chi]\[Chi],g,b];

V\[Gamma]1[space_,time_]:= V[\[Gamma]  \[Phi][Subscript[x, space],Subscript[t, time]](1)\[Phi]s[Subscript[x, space],Subscript[t, time+1]]\[Psi]s[Subscript[x, space],Subscript[t, time]]];

(*V\[Gamma]21[space_,time_]:= V[\[Gamma]2 DD[\[Phi][space,Subscript[t, time]]] \[Chi]s[space,1,1,Subscript[t, time]]\[Phi]s[space,Subscript[t, time+1]]];
V\[Gamma]22[space_,time_]:= V[-\[Gamma]2 DD[\[Phi][space,Subscript[t, time]]](\[Chi]s[space,1,1,Subscript[t, time]]\[Chi]s[space,2,2,Subscript[t, time]])\[Phi]s[space,Subscript[t, time+1]]];*)

V\[Gamma]2[space_,time_]:= V[\[Gamma]2 DD[\[Phi][Subscript[x, space],Subscript[t, time]]](\[Chi]s[Subscript[x, space],1,2,Subscript[t, time]]+\[Chi]s[Subscript[x, space],2,2,Subscript[t, time]])\[Phi]s[Subscript[x, space],Subscript[t, time+1]]]; (*NOTICE THAT WE HAVE TWO POSSIBILITIES OF \[Chi]s*)

V\[Gamma]2Minus1[space_,time_]:= V[-\[Gamma]2 \[Phi][Subscript[x, space],Subscript[t, time]]b DD[\[Chi]s[Subscript[x, space],1,2,Subscript[t, time]]]\[Phi]s[Subscript[x, space],Subscript[t, time+1]]]*
V\[Psi]\[Chi][space-1.25,time+0.25];
V\[Gamma]2Minus2[space_,time_]:= V[-\[Gamma]2 \[Phi][Subscript[x, space],Subscript[t, time]] b2/2 DD[\[Chi]s[Subscript[x, space],1,1,Subscript[t, time]],\[Chi]s[Subscript[x, space],2,2,Subscript[t, time]]]\[Phi]s[Subscript[x, space],Subscript[t, time+1]]]*
V\[Psi]\[Chi]\[Delta][space-1.25,time+0.25]V\[Psi]\[Chi]\[Delta][space-2.25,time-0.25];

V\[Psi]\[Chi][space_,time_]:= Module[{r},r=RandomInteger[{1,100000}];V[-g \[Psi][Subscript[x, space],Subscript[t, time]]\[Chi][Subscript[x, space],Subscript[i, r],Subscript[\[Alpha], r],Subscript[t, time]]]
];
V\[Psi]\[Chi]\[Delta][space_,time_]:= Module[{r},r=RandomInteger[{1,100000}];V[-g \[Psi][Subscript[x, space],Subscript[t, time]]\[Chi][Subscript[x, space],Subscript[i, r],Subscript[\[Alpha], r],Subscript[t, time]]\[Chi]s[Subscript[x, space],Subscript[i, r],Subscript[\[Alpha], r],Subscript[t, time]]]
];

V\[Gamma]g[space_,time_]:= Module[{r},r=RandomInteger[{1,100000}]; V[\[Gamma]g g b \[Phi][Subscript[x, space],Subscript[t, time]]\[Chi]s[Subscript[x, space],1,2,Subscript[t, time]]\[Phi]s[Subscript[x, space],Subscript[t, time+1]]\[Chi][Subscript[x, space],1,Subscript[\[Alpha], r],Subscript[t, time]](*\[Chi]s[space,1,Subscript[\[Alpha], r],Subscript[t, time]]*)]
];


(* ::Input::Initialization:: *)
ClearAll[EvaluateVertices];
Options[EvaluateVertices]={"print"->False
, "n\[Gamma]1\[Delta]"->0
, "n\[Gamma]2"->0
,"n\[Gamma]2Minus"->0
,"\[Delta]fields"->False
,"endTime"->0
,"initialTime"->0
,"evaluate"->True
,"Append\[Phi]0"->False};


EvaluateVertices[vertexList_,OptionsPattern[]]:= Module[ {i,j,el,locVertexList, endTime,evaluatedVertexList={} ,skipFirst=0},

(* Start by checking that vertexList is a List of Lists *)
If[Head[vertexList]=!=List || Head[vertexList[[1]]]=!=List,
Print[Style[" PLEASE, PROVIDE A LIST OF LISTS ",Red]];
Abort[]];



(* Loop over vertexList elements*)
For[el=1,el<=Length[vertexList],el++,


locVertexList=vertexList[[el]];

(* Then define the endTime variable if not provided by the user *)
If[ OptionValue["endTime"]==0,
(*TRUE*)
endTime =Length[locVertexList],
(*FALSE*)
endTime = OptionValue["endTime"];
];

skipFirst=0;

(* Loop over the elements of locVertexList and assign the (x,t) arguments *)
For[j=1,j<=Length[locVertexList],j++,

If[NumericQ[locVertexList[[j]]],
skipFirst=1;Continue[];
];

If[MatchQ[locVertexList[[j]],-_],
(*TRUE*)
locVertexList[[j]]=-(-locVertexList[[j]])[(*Subscript[x, j+OptionValue["initialTime"]]*)j+OptionValue["initialTime"]-skipFirst,j+OptionValue["initialTime"]-skipFirst],
(*FALSE*)
locVertexList[[j]]=locVertexList[[j]][(*Subscript[x, j+OptionValue["initialTime"]]*)j+OptionValue["initialTime"]-skipFirst,j+OptionValue["initialTime"]-skipFirst];
];
];(*End of For over j*)

AppendTo[evaluatedVertexList,If[OptionValue["Append\[Phi]0"],V[\[Phi]s[Subscript[x, 0],Subscript[t, 1]]],1](Times@@locVertexList)];

];(*End of For over el*)

Return[evaluatedVertexList];
];


(* ::Input::Initialization:: *)
ClearAll[SpreadInteractions];
Options[SpreadInteractions]={"print"->False, "\[Delta]\[Psi]\[Chi]"->False,"V\[Gamma]2\[Delta]"->False,"endTime"->0};

SpreadInteractions[nInt_,OptionsPattern[]]:=Module[{comps,maxLen,padded,interactionVertices,i,jj,endTime,V\[Gamma]2correction=0},

If[nInt==0, Return[1]];

If[OptionValue["endTime"]==0,endTime=nInt+1,endTime=OptionValue["endTime"];];

If[OptionValue["V\[Gamma]2\[Delta]"],V\[Gamma]2correction=1,V\[Gamma]2correction=0];

interactionVertices=0;

For[jj=1,jj<=nInt,jj++,

comps=Join@@Permutations/@IntegerPartitions[jj];

If[OptionValue["print"],
Print[" The compositions of ", j, " are :\n ",comps]];

maxLen=Max[Length/@comps];
maxLen=endTime;

padded=PadRight[#,maxLen,0]&/@comps;
padded=DeleteDuplicates[Flatten[Permutations/@padded,1]];
(*padded=DeleteDuplicates[Select[padded,First[#]=!=0&]];*)

If[OptionValue["print"],
Print[" After padding with Zeros and removing leading zeros :\n ",padded]];

If[OptionValue["\[Delta]\[Psi]\[Chi]"],interactionVertices=Sum[Product[1/Factorial[ Abs[padded[[i,j]]-V\[Gamma]2correction] ] Product[V\[Delta]\[Psi]\[Chi][Subscript[x, ToExpression[ToString[j]<>ToString[nIndex]]],endTime-j+1],{nIndex,1,padded[[i,j]] }],{j,1,nInt(*this is equal to Length[padded[[i]]]*)}],
{i,1,Length[padded]}];
Return[interactionVertices];
];

interactionVertices+=Sum[Product[1/Factorial[ Abs[padded[[i,j]]-V\[Gamma]2correction] ] Product[V\[Psi]\[Chi][Subscript[x, ToExpression[ToString[j]<>ToString[nIndex]]],endTime-j+1],{nIndex,1,padded[[i,j]] }],{j,1,maxLen(*this is equal to Length[padded[[i]]]*)}],
{i,1,Length[padded]}]
];
Return[interactionVertices];
];


(* ::Input::Initialization:: *)
ClearAll[Spread\[Gamma]];
Options[Spread\[Gamma]]={"print"->False, "n\[Gamma]1\[Delta]"->0, "n\[Gamma]2"->0,"n\[Gamma]2Minus"->0,"n\[Gamma]2Minus2"->0,"n\[Gamma]g"->0,"\[Delta]fields"->True,"endTime"->0,"initialTime"->0,"evaluate"->True,"observable"->"psi"};

Spread\[Gamma][n\[Gamma]1_,OptionsPattern[]]:=Module[{vertexList={},i,j,endTime},

If[OptionValue["endTime"]==0,endTime=n\[Gamma]1+OptionValue["n\[Gamma]1\[Delta]"]+OptionValue["n\[Gamma]2"]+OptionValue["n\[Gamma]2Minus"],endTime=OptionValue["endTime"];];

If[OptionValue["\[Delta]fields"],
(* WITH \[Delta]fields *)
vertexList=
Join[PadRight[{},(n\[Gamma]1-OptionValue["n\[Gamma]1\[Delta]"]),V\[Gamma]1]
(*,PadRight[{},OptionValue["n\[Gamma]1\[Delta]"],V\[Gamma]1\[Delta]]*)
,PadRight[{},OptionValue["n\[Gamma]2"],V\[Gamma]2\[Delta]]
,PadRight[{},OptionValue["n\[Gamma]2Minus"],V\[Gamma]2Minus1]
,PadRight[{},OptionValue["n\[Gamma]g"],V\[Gamma]g]
,PadRight[{},Floor[OptionValue["n\[Gamma]2Minus2"]],V\[Gamma]2Minus2]
];
,
(* WITHOUT \[Delta]fields*)
vertexList=Join[PadRight[{},(n\[Gamma]1-OptionValue["n\[Gamma]1\[Delta]"]),V\[Gamma]1],(*PadRight[{},OptionValue["n\[Gamma]1\[Delta]"],V\[Gamma]1\[Delta]],*)PadRight[{},OptionValue["n\[Gamma]2"],V\[Gamma]2],PadRight[{},OptionValue["n\[Gamma]2Minus"],V\[Gamma]2Minus]];
];

If[OptionValue["print"],
Print[" The vertices are :\n ",vertexList]];



(* REMOVE STRINGS CONTAINING \[Gamma]s IN THE WRONG PLACES *)
vertexList=DeleteDuplicates[Select[Permutations@vertexList,Last[#]=!=V\[Gamma]1(*&&First[#]=!=V\[Gamma]1\[Delta]&&First[#]=!=V\[Gamma]2&&First[#]=!=V\[Gamma]2Minus*)&&First[#]=!=V\[Gamma]2Minus1&&First[#]=!=V\[Gamma]2Minus2&&First[#]=!=V\[Gamma]g&&First[#]=!=V\[Gamma]2\[Delta]&&First[#]=!=V\[Gamma]2Minus\[Delta]&]];


If[OptionValue["print"],
Print[" After permutations and removing leading \[Delta]\[Chi]s's:\n ",vertexList]];


If[OptionValue["n\[Gamma]2Minus"]>1,
vertexList=Prepend[#,1/OptionValue["n\[Gamma]2Minus"]!]&/@vertexList;
];

If[OptionValue["evaluate"]==False,
Return[vertexList]];


For[i=1,i<=endTime,i++,

For[j=1,j<=Length[vertexList],j++,
vertexList[[j,i]]=vertexList[[j,i]][Subscript[x, i+OptionValue["initialTime"]],i+OptionValue["initialTime"]];
];
];


vertexList=Plus@@Apply[Times,vertexList,1];


Return[vertexList];

];


(* ::Input::Initialization:: *)
ClearAll[Spread\[Gamma]New];
Options[Spread\[Gamma]New]={"print"->False,"observable"->"prop"};

Spread\[Gamma]New[nLoop_,OptionsPattern[]]:=Module[{vertexList={},string={},i,j,k,combFact},
(*Special Case: nLoop=1 *)
If[nLoop==1,
string={V\[Gamma]1};

If[OptionValue["observable"]=="psi",
AppendTo[string,V\[Gamma]1],
AppendTo[vertexList,{V\[Gamma]g}]
];

AppendTo[string,V\[Gamma]2Minus1];

AppendTo[vertexList,string];

Return[vertexList];
];

(*General case: n\[Gamma]>1*)

For[i=0,i<=Floor[(nLoop)/2],i++,(*Number of \[Gamma]2Minus2''s*)

For[j=0,j<=(nLoop-HeavisideTheta[0.5-i]-2i),j++,(*Number of \[Gamma]g's*)

For[k=(nLoop-j-2*i)*HeavisideTheta[0.5-j-2*i](*It must be maximal if the others are 0*),k<=(nLoop-j-2*i),k++,(*Number of \[Gamma]2Minus1''s*)

combFact=1/(i!j!k!);

string=Flatten[(
Join[
PadRight[{},k,V\[Gamma]2Minus1],
PadRight[{},i,V\[Gamma]2Minus2],
PadRight[{},j,V\[Gamma]g],
PadLeft[{},(nLoop-j),V\[Gamma]1]
])
,2];

string=DeleteDuplicates[
Select[Permutations@string,
Last[#]=!=V\[Gamma]1
&&First[#]==V\[Gamma]1
&&If[j==0,#[[2]]==V\[Gamma]1,True]
&&#[[2]]=!=V\[Gamma]2Minus1
&&#[[2]]=!=V\[Gamma]2Minus2
&&If[#[[-1]]===V\[Gamma]2Minus1,#[[-2]]=!=V\[Gamma]1,True]
&&If[(k+2i)==(nLoop-j),#[[-1]]=!=V\[Gamma]g,True]&]
];

string=Prepend[#,combFact]&/@string;

AppendTo[vertexList,string];

];(*End of For over i*)
];(*End of For over j*)
];(*End of For over k*)

vertexList=Flatten[vertexList,1];

vertexList=Replace[#,a__/;((Count[#,V\[Gamma]1]-Count[#,V\[Gamma]2Minus1]-2*Count[#,V\[Gamma]2Minus2])>0&&Count[#,V\[Gamma]2Minus2]>0):>Sequence[a,a/.V\[Gamma]2Minus2:>Sequence[V\[Gamma]2Minus2,V\[Gamma]2]],{0}]&/@vertexList;


If[OptionValue["observable"]=="psi",
vertexList=DeleteDuplicates[Table[Insert[#,V\[Gamma]1,i],{i,2,Length@#}]]&/@vertexList;
vertexList=Flatten[vertexList,1];
];



Return[vertexList];

];


(* ::Input::Initialization:: *)
ClearAll[exhaustiveReplace,exhaustiveReplaceOld]
(*

exhaustiveReplaceOld[expr_Plus,rules_]:=exhaustiveReplace[#,rules]&/@(expr);

exhaustiveReplaceOld[expr_,rules_]:=Module[{exprList,count=0,results,junk},

exprList=DeleteElements[List@@(expr+junk),{junk}];

results=Total@FixedPoint[
(count++;
DeleteElements[List@@(Total[Join@@Table[With[{replaced=Level[ReplaceList[e,rules],{1}]},If[replaced==={},{e},replaced]],{e,#}]]+junk),{junk}])&
,exprList,10];

Expand[results/(1*(count-1)!)]
]
*)


exhaustiveReplace[expr_Plus,rules_]:=exhaustiveReplace[#,rules]&/@(expr);

exhaustiveReplace[expr_,rules_]:=Module[{exprList,count=0,results,junk},

exprList=ReleaseHold[List@@(expr+Hold[0])];

results=Total@FixedPoint[
(count++;
ReleaseHold[List@@(Total[Join@@Table[With[{replaced=Level[ReplaceList[e,rules],{1}]},If[replaced==={},{e},replaced]],{e,#}]]+Hold[0])])&
,exprList,10];

Expand[results/(count-1)!]
]


(* ::Input::Initialization:: *)
ClearAll[RemoveGaps];

RemoveGaps[expr_]:=Module[{i,terms,temp1},
terms=expr;
For[i=1,i<=10,i++,
While[(FreeQ[terms,Subscript[x, i]]),
temp1=terms/.Subscript[x, a_]/;(a>i):>Subscript[x, a-1];
If[temp1===terms, Break[],terms=temp1]
];
];
For[i=1,i<=10,i++,
While[(FreeQ[terms,Subscript[t, i]]),
temp1=terms/.Subscript[t, a_]/;(a>i):>Subscript[t, a-1];
If[temp1===terms, Break[],terms=temp1]
];
];

terms
]


(* ::Input::Initialization:: *)
ClearAll[DDeatsG];

DDeatsG[exp_]:=Module[{terms,tlist,temp1,i},


If[Head[exp]=!=Times,
Print[Style["NOT A PRODUCT OF TERMS",Red]];
Return[0];
];

(*terms=exp//.DD[Subscript[G, \[Phi]][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]]->-1/\[Gamma]2\[Delta][Subscript[x, a],Subscript[x, b]]\[Delta]t[Subscript[t, c]]//.DD[Subscript[G, \[Chi]][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]]->-\[Delta][Subscript[x, a],Subscript[x, b]]
//.Subscript[G, \[Psi]][A___]\[Delta][Subscript[x, a_],Subscript[x, b_]]/;(!FreeQ[{A},Subscript[x, b]]):>\[Delta][Subscript[x, a],Subscript[x, b]]
//.F_[A___,Subscript[x, a_],B___]\[Delta][Subscript[x, a_],Subscript[x, b_]]->F[A,Subscript[x, b],B]\[Delta][Subscript[x, a],Subscript[x, b]]
/.\[Delta][__]->1;*)


terms=exp//.A_. DD[Subscript[G, \[Phi]][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]]:>ReleaseHold[Hold[-((A \[Delta]t[Subscript[t, c]])/\[Gamma]2)/.Subscript[x, b]->Subscript[x, a]]]//.A_. DD[Subscript[G, \[Chi]][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]]:>ReleaseHold[Hold[-A \[Delta]t[Subscript[t, c]]/.Subscript[x, b]->Subscript[x, a]]](*
//.\[Delta][Subscript[x, a_],Subscript[x, b_],C___] F_[A___,Subscript[x, a_],B___]\[Rule]F[A,Subscript[x, b],B] \[Delta][Subscript[x, a],Subscript[x, b],C]//.\[Delta][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]] Subscript[G, \[Psi]][A___]/;!FreeQ[{A},Subscript[x, b]]&&!FreeQ[{A},Subscript[t, c]]\[RuleDelayed]\[Delta][Subscript[x, a],Subscript[x, b],Subscript[t, c]]
/.\[Delta][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]\[Rule]\[Delta][Subscript[x, a],Subscript[x, b]] \[Delta]t[Subscript[t, c]]/.\[Delta][__]->1*);

(* Why do I need this?
If[!FreeQ[terms,\[Delta]t],
tlist=Select[List@@terms,Head[#]==\[Delta]t&];
tlist=Union[tlist/.\[Delta]t[Subscript[t, a_]]->a];
];


Print[terms];
For[i=Length[tlist],i>=1,i--,
terms=terms/.Subscript[t, a_]/;a>=tlist[[i]]:>Subscript[t, a-1];

Print[terms];
];*)

terms=terms/.\[Delta]t[__]->1/.Subscript[G, \[Psi]][A___]^n_->Subscript[G, \[Psi]][A];

(* Eliminate useless gaps *)
For[i=1,i<=5,i++,
While[(FreeQ[terms,Subscript[x, i]]),
temp1=terms/.Subscript[x, a_]/;(a>i):>Subscript[x, a-1];
If[temp1===terms, Break[],terms=temp1]
];
];(* END OF FOR*)

Return[terms];
];



