(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
SetOptions[$FrontEndSession,NotebookAutoSave->True]
NotebookSave[]


(* ::Input::Initialization:: *)
ClearAll[LogMessage]
LogFile=FileNameJoin[{NotebookDirectory[],"debug.nb"}];  (*Or just "debug.log"*)

LogMessage[msg_]:=Module[{},
Quiet[
PutAppend[Row[{StringJoin[DateString[{"Hour",":","Minute",":","Second"}]," \n "],
(*StringJoin[(*DateString[{"Hour",":","Minute",":","Second"}]," | ",*)ToString[msg(*,InputForm,OutputForm*)]]*)Row[msg]}],LogFile]
]
];


(* ::Input::Initialization:: *)
ClearAll[DrawFromContraction,x];
Options[DrawFromContraction]={"pointSize"->0.015,"ArrowHeadSize"->0.05,"\[Psi]sLength"->0.4,"print"->False,"showEndLines"->False,"ImageSize"->Medium,"export"->False,"exportDirectory"->"myFile.pdf","initialIndex"->1};

DrawFromContraction[exp_List,OptionsPattern[]]:=DrawFromContraction[Plus@@exp,"pointSize"->OptionValue["pointSize"],"ArrowHeadSize"->OptionValue["ArrowHeadSize"],"print"->OptionValue["print"],"showEndLines"->OptionValue["showEndLines"],"ImageSize"->OptionValue["ImageSize"],"export"->OptionValue["export"],"exportDirectory"->OptionValue["exportDirectory"],"initialIndex"->OptionValue["initialIndex"],"\[Psi]sLength"->OptionValue["\[Psi]sLength"]];

DrawFromContraction[exp_,OptionsPattern[]]:=Module[{terms,i,pureProp, weight, dots,plot},

If[OptionValue["print"],DeleteFile[LogFile]];  (*Place at the top of the notebook*)

terms=exp;

If[terms==0,
Print[Style["!!ZERO!!",Red]]; 
Abort[];
];

If[!OptionValue["showEndLines"], 
terms=terms/.\[Chi]s[__]->1;
];

terms=List @@ (terms)/.Times->List;

If[OptionValue["print"],
LogMessage[{terms}]];

(* I want to check if terms is a list of lists (which means that exp conatained a sum, i.e. multiple diagrams)*)
If[!Head[terms[[1]]] ===List,
(* TRUE: if it is not a List of lists, let's make it so *)

terms={terms};

](*End of IF*);

plot={};

For[i=1,i<=Length[terms],i++,

pureProp=DeleteElements[terms[[i]],{-1,b,b^n_?NumericQ,g,\!\(\*OverscriptBox[\(g\), \(~\)]\),Subscript[g, \[Gamma]],\[Gamma],\[Gamma]1,\[Gamma]2,-g,-\!\(\*OverscriptBox[\(g\), \(~\)]\),-Subscript[g, \[Gamma]],-\[Gamma],-\[Gamma]1,-\[Gamma]2,g^n_?NumericQ,\!\(\*OverscriptBox[\(g\), \(~\)]\)^n_?NumericQ,Subscript[g, \[Gamma]]^n_?NumericQ,\[Gamma]^n_?NumericQ,\[Gamma]1^n_?NumericQ,\[Gamma]2^n_?NumericQ}];
pureProp=DeleteCases[pureProp,_?NumericQ];
(*Print["pureProp:", pureProp];*)

weight=Times@@DeleteElements[terms[[i]],pureProp];

pureProp=pureProp/.{DD[\[Phi]s[Subscript[x, a_],Subscript[t, c_]] Subscript[F_, \[Chi]][Subscript[x, d_],Subscript[x, b_],Subscript[t, e_]]]:>{\[CapitalDelta][Subscript[x, b-0.1],Subscript[x, b],Subscript[t, e]],Subscript[F, \[Chi]][Subscript[x, d],Subscript[x, b-0.1],Subscript[t, e]],\[Phi]s[Subscript[x, a-0.1],Subscript[t, c]]},
DD[Subscript[F_, \[Phi]][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]\[Chi]s[Subscript[x, d_],A___,Subscript[t, e_]]]:>{\[CapitalDelta][Subscript[x, b-0.1],Subscript[x, b],Subscript[t, c-1]],Subscript[F, \[Phi]][Subscript[x, a],Subscript[x, b-0.1],Subscript[t, c]],\[Chi]s[Subscript[x, d-0.1],A,Subscript[t, e]]},
DD[\[Chi]s[Subscript[x, a_],A___,Subscript[t, c_]]]:>{\[CapitalDelta][Subscript[x, a-0.1],Subscript[x, a],Subscript[t, c]],\[Chi]s[Subscript[x, a-0.1],A,Subscript[t, c]]},

DD[Subscript[F_, \[Phi]][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]]:>{\[CapitalDelta][Subscript[x, a+0.2],Subscript[x, a],Subscript[t, c]],Subscript[F, \[Phi]][Subscript[x, a+0.2],Subscript[x, b],Subscript[t, c]]},(* If DD acts of Subscript[G, \[Phi]] it means that it's acting on the past line*)
DD[Subscript[F_, \[Chi]][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]]:>{\[CapitalDelta][Subscript[x, b-0.2],Subscript[x, b],Subscript[t, c]],Subscript[F, \[Chi]][Subscript[x, a],Subscript[x, b-0.2],Subscript[t, c]]}};
pureProp=Flatten@pureProp;

If[OptionValue["print"],
LogMessage[{"The propagators are\n ",pureProp}]];

(*Print[pureProp];*)

dots=Flatten[pureProp//.{Subscript[F_, \[Chi]][Subscript[x, a_],Subscript[x, a_],Subscript[t, c_]]:>{Style[{a+0.54,c},Disk[{0,0},0.05],White,EdgeForm[None]],Style[{a,c},Disk[{0,0},0.05],Black]},
Subscript[F_, \[Chi]][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]:>{Style[{a,c},Disk[{0,0},0.05],Black],Style[{b,c},Disk[{0,0},0.05],Black]},

Subscript[F_, \[Chi]][Subscript[x, a_],Subscript[x, a_],0]:>{Style[{a+0.54,1},Disk[{0,0},0.05],White,EdgeForm[None]],Style[{a,1},Disk[{0,0},0.05],Black]},
Subscript[F_, \[Chi]][Subscript[x, a_],Subscript[x, b_],0]:>{Style[{a,1},Disk[{0,0},0.05],Black],Style[{b,1},Disk[{0,0},0.05],Black],Style[{a,1.5},Disk[{0,0},0.05],White,EdgeForm[None]],Style[{a,0.7},Disk[{0,0},0.05],White,EdgeForm[None]]},

Subscript[F_, \[Phi]][Subscript[x, a_],Subscript[x, 0],Subscript[t, c_]]:>{Style[{a,c},Disk[{0,0},0.05],Black]},
Subscript[F_, \[Phi]][Subscript[x, a_],Subscript[x, a_],Subscript[t, c_]]:>{Style[{a,c},Disk[{0,0},0.05],Black],Style[{a,IntegerPart[c-0.5]},Disk[{0,0},0.05],Black],Style[{a+0.3,c-0.5},Disk[{0,0},0.05],White,EdgeForm[None]]},Subscript[F_, \[Phi]][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]:>{Style[{a,c},Disk[{0,0},0.05],Black],Style[{b,IntegerPart[c-0.5]},Disk[{0,0},0.05],Black]},

Subscript[F_, \[Phi]][Subscript[x, a_],Subscript[x, a_],0]:>{Style[{a+0.54,1},Disk[{0,0},0.05],White,EdgeForm[None]],Style[{a,1},Disk[{0,0},0.05],Black]},
Subscript[F_, \[Phi]][Subscript[x, a_],Subscript[x, b_],0]:>{Style[{a,1},Disk[{0,0},0.05],Black],Style[{b,1},Disk[{0,0},0.05],Black],Style[{a,1.5},Disk[{0,0},0.05],White,EdgeForm[None]],Style[{a,0.7},Disk[{0,0},0.05],White,EdgeForm[None]]},

Subscript[F_, \[Phi]][Subscript[x, a_],Subscript[x, a_],0]:>{Style[{a,1},Disk[{0,0},0.05],Black],Style[{a,1},Disk[{0,0},0.05],Black],Style[{a+0.3,1-0.5},Disk[{0,0},0.05],White,EdgeForm[None]]},Subscript[F_, \[Phi]][Subscript[x, a_],Subscript[x, b_],0]:>{Style[{a,1},Disk[{0,0},0.05],Black],Style[{b,1},Disk[{0,0},0.05],Black]},

\[CapitalDelta][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]:>{Style[{a,c},Disk[{0,0},0.05],Black],Style[{b,c},Disk[{0,0},0.05],Black]},\[Psi]s[Subscript[x, a_],Subscript[t, c_]]:>{Style[{a-0.1,c-0.8},Disk[{0,0},0.05],White,EdgeForm[None]]}}];

pureProp=pureProp/.{Subscript[F_, \[Chi]]^n_[Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]:>Style[FindArc[{b,c},{a,c},n,"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[1]],FindArc[{b,c},{a,c},n,"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[2]],Darker[Green]],
Subscript[F_, \[Chi]][Subscript[x, a_],Subscript[x, a_],Subscript[t, c_]]:>{Style[FindArc[{a+0.5,c},{a,c},2,"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[1]],FindArc[{a+0.5,c},{a,c},2,"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[2]],Darker[Green]],Style[FindArc[{a+0.5,c},{a,c},-2,"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[1]],FindArc[{a+0.5,c},{a,c},-2,"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[2]],Darker[Green]]},
Subscript[F_, \[Chi]][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]:>Style[FindArc[{b,c},{a,c},(b-a),"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[1]],FindArc[{b,c},{a,c},(b-a),"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[2]],Darker[Green]],

Subscript[F_, \[Chi]][Subscript[x, a_],Subscript[x, a_],0]:>{Style[FindArc[{a+0.5,1},{a,1},2,"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[1]],FindArc[{a+0.5,1},{a,1},2,"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[2]],Darker[Green]],Style[FindArc[{a+0.5,1},{a,1},-2,"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[1]],FindArc[{a+0.5,1},{a,1},-2,"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[2]],Darker[Green]]},
Subscript[F_, \[Chi]][Subscript[x, a_],Subscript[x, b_],0]:>Style[FindArc[{b,1},{a,1},1.1(b-a),"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[1]],FindArc[{b,1},{a,1},1.1(b-a),"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[2]],Darker[Green]],

Subscript[F_, \[Phi]][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]^n_:>Style[FindArc[{b,IntegerPart[c-0.5]},{a,c},n,"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[1]],FindArc[{b,IntegerPart[c-0.5]},{a,c},n,"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[2]],Red],
Subscript[F_, \[Phi]][Subscript[x, a_],Subscript[x, 0],Subscript[t, c_]]:>Style[Line[{{a-0.13,c-0.13},{a,c}}],Arrowheads[{0,.03}],Red],
Subscript[F_, \[Phi]][Subscript[x, a_],Subscript[x, a_],Subscript[t, c_]]:>{Style[FindArc[{a,IntegerPart[c-0.5]},{a,c},2,"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[1]],FindArc[{a+0.5,IntegerPart[c-0.5]},{a,c},2,"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[2]],Red]},
Subscript[F_, \[Phi]][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]:>Style[FindArc[{b,IntegerPart[c-0.5]},{a,c},1,"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[1]],FindArc[{b,IntegerPart[c-0.5]},{a,c},1,"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[2]],Red],

Subscript[F_, \[Phi]][Subscript[x, a_],Subscript[x, b_],0]^n_:>Table[Style[FindArc[{b,1},{a,1},(b-a+0.9)(-1)^j,"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[1]],FindArc[{b,1},{a,1},(b-a+0.9)(-1)^j,"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[2]],Red],{j,1,n}],
Subscript[F_, \[Phi]][Subscript[x, a_],Subscript[x, a_],0]:>{Style[FindArc[{a+0.5,1},{a,1},2,"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[1]],FindArc[{a+0.5,1},{a,1},2,"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[2]],Red],Style[FindArc[{a+0.5,1},{a,1},-2,"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[1]],FindArc[{a+0.5,1},{a,1},-2,"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[2]],Red]},
Subscript[F_, \[Phi]][Subscript[x, a_],Subscript[x, b_],0]:>Style[FindArc[{b,1},{a,1},(b-a+0.9),"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[1]],FindArc[{b,1},{a,1},(b-a+0.9),"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[2]],Red],


Subscript[F_, \[Psi]][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]^n_:>Style[FindArc[{a,c-1},{a,c},1,"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[1]],FindArc[{a,c-1},{a,c},1,"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[2]],Blue],
Subscript[F_, \[Psi]][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]:>Style[FindArc[{b,c-1},{b,c},1,"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[1]],FindArc[{b,c-1},{b,c},1,"ArrowHeadSize"->OptionValue["ArrowHeadSize"]][[2]],Blue],

\[CapitalDelta][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]:>Style[Line[{{b,c},{a,c}}],Black,Dashed],

\[Chi]s[Subscript[x, a_],__,Subscript[t, c_]]^n_:>Table[Style[Arrow[{{a,c},{a-0.2,c+0.1*Sin[\[Pi] ii/n]}}],Arrowheads[{0,.03}],Darker[Green]],{ii,1,n}],
\[Chi]s[Subscript[x, a_],__,Subscript[t, c_]]:>Style[Arrow[{{a,c},{a-0.2,c}}],Arrowheads[{0,.03}],Darker[Green]],
\[Delta]\[Chi]s[Subscript[x, a_],__,Subscript[t, c_]]:>Style[Arrow[{{a,c},{a-0.2,c}}],Arrowheads[{0,.03}],Darker[Green],Dashed],\[Delta]\[Chi]s[Subscript[x, a_],__,Subscript[t, c_]]^n_:>Table[Style[Arrow[{{a,c},{a-0.2,c+0.1*Sin[\[Pi] ii/n]}}],Arrowheads[{0,.03}],Darker[Green],Dashed],{ii,1,n}],
\[Phi]s[Subscript[x, a_],Subscript[t, c_]]:>Style[Arrow[{{a,c-1},{a-0.2,c-1+0.2}}],Arrowheads[{0,.03}],Red],
\[Psi]s[Subscript[x, a_],Subscript[t, c_]]:>Style[Arrow[{{a,IntegerPart[c-1]},{a,IntegerPart[c-1]+OptionValue["\[Psi]sLength"]}}],Arrowheads[{0,.03}],Blue],
\[Delta]\[Psi]s[Subscript[x, a_],Subscript[t, c_]]:>Style[Arrow[{{a,c-1},{a,c-0.7}}],Arrowheads[{0,.03}],Blue,Dashed]};

pureProp=Flatten[pureProp];

If[OptionValue["print"],
LogMessage[{"They will be drawn as\n ",pureProp}]];
	(*dots=Flatten[pureProp//.{Style[Arrow[{{a_,c_},{b_,d_}}],___,color_]/;(IntegerQ[a*b*c*d]&&color=!=Blue):>{Style[{a,c},Disk[{0,0},0.05],Black],Style[{b,d},Disk[{0,0},0.05],Black]},Style[Arrow[{{a_,c_},{b_,d_}}],___]/;(!IntegerQ[a*b*c*d]):>{Style[{b-0.1,d},Disk[{0,0},0.05],White,EdgeForm[None]]},
Style[Line[{{a_,c_},{b_,c_}}],Black,Dashed]:>{Style[{a,c},Disk[{0,0},0.05],Black],Style[{b,c},Disk[{0,0},0.05],Black]}}];*)

AppendTo[plot,ListPlot[dots,
PlotLabel-> Row[{ToString[i+OptionValue["initialIndex"]-1]<>": ",weight}],
Axes->False,
Frame->False,
Mesh->Full,
AxesOrigin->{1,1}-0.2,
PlotStyle->{PointSize[OptionValue["pointSize"]]},
Prolog->pureProp,
ImagePadding->{{10,10},{10,10}},
PlotRangeClipping->False,
ImageSize->OptionValue["ImageSize"]]
];

];(*End of Loop*)

If[OptionValue["print"],SystemOpen[LogFile]];

If[OptionValue["export"],
Export[OptionValue["exportDirectory"],plot(*Row[plot,"\n"]*)];
];

Return[Row[plot]];
]


(* ::Input::Initialization:: *)
ClearAll[FindArc];
Options[FindArc]={"ArrowHeadSize"->0.05};

FindArc[dot1__,dot2__,order_,OptionsPattern[]]:=Module[{sub,px,py,qx,qy,cx,cy,r,radius,centerCoord,c,startAngle,endAngle,circle},

If[order==1 || order==-1,
Return[{Arrow[{dot1,dot2}],Arrowheads[{0,OptionValue["ArrowHeadSize"],0}]}]
];

sub={px:>dot1[[1]],py:>dot1[[2]],qx:>dot2[[1]],qy:>dot2[[2]]};

radius=EuclideanDistance[{px,py},{qx,qy}]/(1.07)^(order)/.sub;

AppendTo[sub,r:>radius];

centerCoord=NSolve[{(px-cx)^2+(py-cy)^2==r^2,(qx-cx)^2+(qy-cy)^2==r^2}/.sub,{cx,cy}(*,Assumptions->r>0*)];
(*centerCoord=centerCoord/.sub;*)


c={cx,cy}/.centerCoord[[-Sign[order]]];


startAngle=ArcTan[px-c[[1]],py-c[[2]]]/.sub;

endAngle=ArcTan[qx-c[[1]],qy-c[[2]]]/.sub;

circle=Circle[c,radius,{startAngle,endAngle}];

Return[{Arrow[circle],Arrowheads[{0,OptionValue["ArrowHeadSize"],0}]}];
]


(* ::Input::Initialization:: *)
ClearAll[pdfImage];
Options[pdfImage]={"ImageResolution"->600,"ImageSize"->150,"directory"->"D:\\Offline_Documents\\University\\PhD_Paris\\PhD_work\\Simulations\\MathematicaFiles-LRW-DLA\\Diagrams\\DiagramIcons\\"};

pdfImage[fileName_,OptionsPattern[]]:=Module[{},

If[Head[fileName]=!=String,
Print[Style["PROVIDE A STRING!\n filename: ",Red],fileName]; 
Return[Abort[]];
];


If[fileName=="NONE",
Print[Style["Unkown diagram!",Red]]; 
Return[Abort[]];
];

Show[Import[OptionValue["directory"]<>fileName<>".pdf",ImageResolution->OptionValue["ImageResolution"]][[1]],ImageSize->OptionValue["ImageSize"]]
];


(* ::Input::Initialization:: *)
ClearAll[NONE];

NONE[a_]:=1;


(* ::Input::Initialization:: *)
ClearAll[DD];
(*Remove[DD];*)
DD[0]:=0;
DD'[(\[Kappa]*A_+B_)C_]:=DD[A*C]/(A*C);
DD'[(\[Kappa]*A_+B_)]:=DD[A]/(A);
DD'[(\[Kappa]*A_)]:=DD[A]/(A);
(*DD'[a_[x_] b_[y_]]:=1;
DD[a_[x_]*b_[y_]]:=DD[a[x]]*b[y]+DD[b[y]]*a[x]+2\[Del]a[x]*\[Del]b[y];*)

DD'[0]=1;


(* ::Input::Initialization:: *)
ClearAll[V];
V[1.]:=1.;
V[1]:=1;
V[0]:=0;
(*V'[DD[a__]]:=DD[a]/a;(*(ToExpression["\[Delta]"<>ToString[a]]);*)*)
V'[a_]:=1;
V''[a_]:=0;
V'''[a_]:=0;


(* ::Input::Initialization:: *)
ClearAll[\[CapitalSigma]\[Delta]rule];
\[CapitalSigma]\[Delta]rule={\[Delta][a_,b_]^n_/;(!NumericQ[b]&& !MatchQ[b,Subscript[1, __]]):>\[Delta][a,b]^(n-2) \[Delta][a,a],
\[Delta][b_,a_]\[Delta][c_,b_]/;(!NumericQ[b] && !MatchQ[b,Subscript[1, __]]):>\[Delta][c,a],
\[Delta][a_,b_]\[Delta][c_,b_]/;(!NumericQ[b]&& !MatchQ[b,Subscript[1, __]]):>\[Delta][a,c],

\[Delta][a_,a_]/;(MatchQ[a,Subscript[i, __]])/;(a=!=Subscript[i, s]):>Subscript[n, \[Chi]],
\[Delta][a_,a_]/;(MatchQ[a,Subscript[\[Alpha], __]]):>Subscript[n, \[Alpha]]};


(* ::Input::Initialization:: *)
ClearAll[\[Delta]ruleExternal]
(*\[Delta]ruleExternal={\[Delta][a_,a_]/;(NumericQ[a] || a==Subscript[i, s] || MatchQ[a,Subscript[j, __]]|| MatchQ[a,Subscript[jj, __]] || MatchQ[a,Subscript[1, __]]||MatchQ[a,Subscript[k, _]]):>1,
\[Delta][a_,b_]/;(NumericQ[a] ||MatchQ[a,Subscript[k, _]]|| MatchQ[a,Subscript[j, __]]|| MatchQ[a,Subscript[jj, __]] || MatchQ[a,Subscript[1, _]])/;(a=!=b):>0,
\[Delta][a_,b_]/;(NumericQ[b] ||MatchQ[b,Subscript[k, _]]|| MatchQ[b,Subscript[j, __]]|| MatchQ[a,Subscript[jj, __]] || MatchQ[b,Subscript[1, _]])/;(a=!=b):>0 };*)



(* ::Input::Initialization:: *)
Clear[FieldsNamesGenerator];
FieldsNamesGenerator[fields_]:=
FieldsNamesGenerator[fields]=Block[{locFields={},starFields={},deltaFields={},deltaStarFields={},l},

locFields=fields;

For[l=1,l<=Length[locFields],l++,
AppendTo[starFields, ToExpression[ToString[locFields[[l]]] <> "s"]];
AppendTo[deltaFields, ToExpression["\[Delta]"<>ToString[locFields[[l]]] ]];
AppendTo[deltaStarFields,ToExpression["\[Delta]"<> ToString[starFields[[l]]] ]];
];(*End of loop to define the fields*)

Return[{locFields,starFields,deltaFields,deltaStarFields}]
]


(* ::Input::Initialization:: *)
ClearAll[FreeAction];

FreeAction[time_]:=V[1+Sum[Product[ 1/index1 \[Psi]s[Subscript[x, ToExpression["action"<>ToString[ time]<>ToString[ index1]]],Subscript[t, time+1]]\[Psi][Subscript[x, ToExpression["action"<>ToString[ time]<>ToString[ index1]]],Subscript[t, time]],{index1,1,index2}],{index2,1,time}]
];

(*FreeAction[endTime_]:=
Product[V[Normal@(Series[
Exp[Sum[p *\[Psi]s[Subscript[x, ToExpression["action"<>ToString[ index2]<>ToString[ index1]]],Subscript[t, index2+1]]
\[Psi][Subscript[x, ToExpression["action"<>ToString[ index2]<>ToString[ index1]]],Subscript[t, index2]],{index1,1,index2}]
],{p,0,endTime}])/.p->1
]
,{index2,1,endTime}];*)


(* ::Input::Initialization:: *)
ClearAll[V\[Gamma]1,V\[Gamma]1Minus,V\[Gamma]1g\[Chi],V\[Gamma]1g\[Chi]Minus,V\[Gamma]1g\[Psi],V\[Gamma]1g\[Psi]Minus,V\[Gamma]2,V\[Gamma]2Minus,V\[Gamma]2g\[Chi],V\[Gamma]2g\[Chi]Minus,V\[Gamma]2g\[Psi],V\[Gamma]2g\[Psi]Minus,V\[Psi]\[Psi],V\[Psi]\[Chi],V\[Delta]\[Psi]\[Chi],V\[Chi]\[Chi],g];

V\[Gamma]1[space_,time_]:= V[\[Gamma] Subscript[g, \[Gamma]] \[Phi][space,Subscript[t, time]]\[Chi]s[space,1,2,Subscript[t, time]]\[Phi]s[space,Subscript[t, time+1]]\[Psi]s[space,Subscript[t, time+1]]];

V\[Gamma]2[space_,time_]:= V[\[Gamma]2 DD[\[Phi][space,Subscript[t, time]]]\[Chi]s[space,1,2,Subscript[t, time]]\[Phi]s[space,Subscript[t, time+1]]];
V\[Gamma]2Minus[space_,time_]:= V[-\[Gamma]2 \[Phi][space,Subscript[t, time]]DD[\[Chi]s[space,1,2,Subscript[t, time]]]\[Phi]s[space,Subscript[t, time+1]]];

V\[Psi]\[Chi][space_,time_]:= Module[{r},r=RandomInteger[{1,100000}];V[-\!\(\*OverscriptBox[\(g\), \(~\)]\) \[Psi][space,Subscript[t, time]]\[Chi][space,Subscript[i, r],Subscript[\[Alpha], r],Subscript[t, time]]\[Chi]s[space,Subscript[i, r],Subscript[\[Alpha], r],Subscript[t, time]]]
];

(*V\[Chi]\[Chi][space_,time_]:= V[-g/2 \[Chi][space,Subscript[i, 1],Subscript[\[Alpha], 1],Subscript[t, time]]\[Chi][space,Subscript[i, 2],Subscript[\[Alpha], 2],Subscript[t, time]]\[Chi]s[space,Subscript[i, 1],Subscript[\[Alpha], 1],Subscript[t, time]]\[Chi]s[space,Subscript[i, 2],Subscript[\[Alpha], 2],Subscript[t, time]]];*)


(* ::Input::Initialization:: *)
ClearAll[V\[Gamma]1\[Delta],V\[Gamma]1Minus,V\[Gamma]1g\[Chi],V\[Gamma]1g\[Chi]Minus,V\[Gamma]1g\[Psi],V\[Gamma]1g\[Psi]Minus,V\[Gamma]2\[Delta],V\[Gamma]2Minus\[Delta],V\[Gamma]2g\[Chi],V\[Gamma]2g\[Chi]Minus,V\[Gamma]2g\[Psi],V\[Gamma]2g\[Psi]Minus,V\[Psi]\[Psi],V\[Delta]\[Psi]\[Chi],V\[Chi]\[Chi],g ];

V\[Gamma]1\[Delta][space_,time_]:= V[\[Gamma] Subscript[g, \[Gamma]] \[Phi][space,Subscript[t, time]]\[Chi]s[space,1,2,Subscript[t, time]]\[Phi]s[space,Subscript[t, time+1]]\[Delta]\[Psi]s[space,Subscript[t, time+1]]];

V\[Gamma]2\[Delta][space_,time_]:= V[\[Gamma]2 DD[\[Phi][space,Subscript[t, time]]]\[Delta]\[Chi]s[space,1,2,Subscript[t, time]]\[Phi]s[space,Subscript[t, time+1]]];
V\[Gamma]2Minus\[Delta][space_,time_]:= V[-\[Gamma]2 \[Phi][space,Subscript[t, time]]DD[\[Delta]\[Chi]s[space,1,2,Subscript[t, time]]]\[Phi]s[space,Subscript[t, time+1]]];

V\[Delta]\[Psi]\[Chi][space_,time_]:= V[-\!\(\*OverscriptBox[\(g\), \(~\)]\) \[Psi][space,Subscript[t, time]]\[Delta]\[Psi]s[space,Subscript[t, time+1]]\[Chi][space,Subscript[i, 1],Subscript[\[Alpha], 1],Subscript[t, time]]\[Chi]s[space,Subscript[i, 1],Subscript[\[Alpha], 1],Subscript[t, time]]];

(*V\[Chi]\[Chi][space_,time_]:= V[-g/2 \[Chi][space,Subscript[i, 1],Subscript[\[Alpha], 1],Subscript[t, time]]\[Chi][space,Subscript[i, 2],Subscript[\[Alpha], 2],Subscript[t, time]]\[Chi]s[space,Subscript[i, 1],Subscript[\[Alpha], 1],Subscript[t, time]]\[Chi]s[space,Subscript[i, 2],Subscript[\[Alpha], 2],Subscript[t, time]]];*)


(* ::Input::Initialization:: *)
ClearAll[CombinatorialFactor];

CombinatorialFactor[A_+B___,max_,time_]:=CombinatorialFactor[A,max,time]+CombinatorialFactor[(Plus@@{B}),max,time];

CombinatorialFactor[expr_,max_,time_]:=Module[{factors,chis,others,n},
If[Head[expr]===Times,
(* TRUE *)
factors=List@@expr;
chis=Select[factors,(*!FreeQ[#,Overscript[g, ~]]&&!FreeQ[#,Subscript[t, time]]*)!FreeQ[#,\[Chi][__,Subscript[t, time]]]&];
others=Complement[factors,chis];(*conservatively:remove \[Chi]s only*)
n=Length[chis];
If[n>0&&n<=max,
Return[1/Factorial[n]*Times@@chis*Times@@others],
Return[expr]],

(* ELSE *)
Return[expr]
]; (* END OF FIRST IF*)
];(* END OF MODULE*)



(* ::Input::Initialization:: *)
ClearAll[SpreadInteractions];
Options[SpreadInteractions]={"print"->False, "\[Delta]\[Psi]\[Chi]"->False,"V\[Gamma]2\[Delta]"->False,"endTime"->0};

SpreadInteractions[nInt_,OptionsPattern[]]:=Module[{comps,maxLen,padded,interactionVertices,i,endTime,V\[Gamma]2correction=0},

If[OptionValue["endTime"]==0,endTime=nInt+1,endTime=OptionValue["endTime"];];

If[OptionValue["V\[Gamma]2\[Delta]"],V\[Gamma]2correction=1,V\[Gamma]2correction=0];

comps=Join@@Permutations/@IntegerPartitions[nInt];

If[OptionValue["print"],
Print[" The compositions of ", nInt, " are :\n ",comps]];

maxLen=Max[Length/@comps];
maxLen=endTime;

padded=PadRight[#,maxLen,0]&/@comps;
padded=DeleteDuplicates[Flatten[Permutations/@padded,1]];
(*padded=DeleteDuplicates[Select[padded,First[#]=!=0&]];*)

If[OptionValue["print"],
Print[" After padding with Zeros and removing leading zeros :\n ",padded]];

If[OptionValue["\[Delta]\[Psi]\[Chi]"],interactionVertices=Sum[Product[1/Factorial[ Abs[padded[[i,j]]-V\[Gamma]2correction] ] Product[V\[Delta]\[Psi]\[Chi][Subscript[x, ToExpression[ToString[j]<>ToString[nIndex]]],endTime-j+1],{nIndex,1,padded[[i,j]] }],{j,1,nInt(*this is equal to Length[padded[[i]]]*)}],
{i,1,Length[padded]}];
Return[interactionVertices];
];

interactionVertices=Sum[Product[1/Factorial[ Abs[padded[[i,j]]-V\[Gamma]2correction] ] Product[V\[Psi]\[Chi][Subscript[x, ToExpression[ToString[j]<>ToString[nIndex]]],endTime-j+1],{nIndex,1,padded[[i,j]] }],{j,1,maxLen(*this is equal to Length[padded[[i]]]*)}],
{i,1,Length[padded]}]
];


(* ::Input::Initialization:: *)
ClearAll[Spread\[Gamma]];
Options[Spread\[Gamma]]={"print"->False, "n\[Gamma]2"->0,"n\[Gamma]2Minus"->0,"\[Delta]fields"->False,"endTime"->0};

Spread\[Gamma][n\[Gamma]1_,OptionsPattern[]]:=Module[{vertexList={},i,j,endTime},

If[OptionValue["endTime"]==0,endTime=n\[Gamma]1+OptionValue["n\[Gamma]2"]+OptionValue["n\[Gamma]2Minus"],endTime=OptionValue["endTime"];];

If[OptionValue["\[Delta]fields"],
(* WITH \[Delta]fields *)
vertexList=Join[PadRight[{},n\[Gamma]1,V\[Gamma]1],PadRight[{},OptionValue["n\[Gamma]2"],V\[Gamma]2\[Delta]],PadRight[{},OptionValue["n\[Gamma]2Minus"],V\[Gamma]2Minus\[Delta]]];,
(* WITHOUT \[Delta]fields*)
vertexList=Join[PadRight[{},n\[Gamma]1,V\[Gamma]1],PadRight[{},OptionValue["n\[Gamma]2"],V\[Gamma]2],PadRight[{},OptionValue["n\[Gamma]2Minus"],V\[Gamma]2Minus]];
];

If[OptionValue["print"],
Print[" The vertices are :\n ",vertexList]];

vertexList=DeleteDuplicates[Select[Permutations@vertexList,First[#]=!=V\[Gamma]2&&First[#]=!=V\[Gamma]2Minus&&First[#]=!=V\[Gamma]2\[Delta]&&First[#]=!=V\[Gamma]2Minus\[Delta]&]];

If[OptionValue["print"],
Print[" After permutations and removing leading V\[Gamma]2's:\n ",vertexList]];

For[i=1,i<=endTime,i++,
For[j=1,j<=Length[vertexList],j++,
vertexList[[j,i]]=vertexList[[j,i]][Subscript[x, i],i];
];
];

vertexList=Plus@@Apply[Times,vertexList,1];

Return[vertexList];

];


(* ::Input::Initialization:: *)
ClearAll[WickContractionSpaceVerticesMOD];
Options[WickContractionSpaceVerticesMOD]={"print"->False,"fields"->FieldsNamesGenerator[{\[Phi],\[Chi],\[Psi]}], "endTime"->1,"#vertices"->10,"\[Delta]rule"->True,"\[Delta]ruleExternal"->True,"\!\(\*SubscriptBox[\(n\), \(\[Chi]\)]\)"->(-1),"\!\(\*SubscriptBox[\(n\), \(\[Alpha]\)]\)"->(0),"maxContractions"->5,"kill\[Psi]"->True,"SimplifyPropagators"->True,"SimplifyG\[Psi]"->True,"ReturnJustAction"->False};

WickContractionSpaceVerticesMOD[A_ +B_,OptionsPattern[]]:=WickContractionSpaceVerticesMOD[A,"print"->OptionValue["print"],"fields"->OptionValue["fields"], "endTime"->OptionValue["endTime"],"#vertices"->OptionValue["#vertices"],"\[Delta]rule"->OptionValue["\[Delta]rule"],"\[Delta]ruleExternal"->OptionValue["\[Delta]ruleExternal"],"\!\(\*SubscriptBox[\(n\), \(\[Chi]\)]\)"->OptionValue["\!\(\*SubscriptBox[\(n\), \(\[Chi]\)]\)"],"\!\(\*SubscriptBox[\(n\), \(\[Alpha]\)]\)"->OptionValue["\!\(\*SubscriptBox[\(n\), \(\[Alpha]\)]\)"],"maxContractions"->OptionValue["maxContractions"],"kill\[Psi]"->OptionValue["kill\[Psi]"]]+
WickContractionSpaceVerticesMOD[B,"print"->OptionValue["print"],"fields"->OptionValue["fields"], "endTime"->OptionValue["endTime"],"#vertices"->OptionValue["#vertices"],"\[Delta]rule"->OptionValue["\[Delta]rule"],"\[Delta]ruleExternal"->OptionValue["\[Delta]ruleExternal"],"\!\(\*SubscriptBox[\(n\), \(\[Chi]\)]\)"->OptionValue["\!\(\*SubscriptBox[\(n\), \(\[Chi]\)]\)"],"\!\(\*SubscriptBox[\(n\), \(\[Alpha]\)]\)"->OptionValue["\!\(\*SubscriptBox[\(n\), \(\[Alpha]\)]\)"],"maxContractions"->OptionValue["maxContractions"],"kill\[Psi]"->OptionValue["kill\[Psi]"]];


WickContractionSpaceVerticesMOD[A_?NumericQ,OptionsPattern[]]:=A;

(*################################################################################
									Partition Function                             
##############################################################################*)
(*There are two possible contributions for each field: 1) it is not contracted: \[Chi]->0; 2) it is contracted*)

WickContractionSpaceVerticesMOD[V[A_] *B_, OptionsPattern[]]:=Module[{interactionPermutations={},locFields={}, starFields={}, deltaFields={},deltaStarFields={},contributions=0,z,zTemp1,zTemp2,jj,l,timeIndex,ii,ss},

If[OptionValue["print"],DeleteFile[LogFile]];  (*Place at the top of the notebook*)

z=V[A]*B;

(*If[!FreeQ[z,Overscript[g, ~]],
(* TRUE *)

interactionPermutations=Join@@Permutations/@IntegerPartitions["#vertices"];


If[OptionValue["print"],LogMessage[{"TRUE: z before =", z}]];

(*z=z//.V\[Psi]\[Chi][Subscript[x, a_],t]->(Sum[V\[Psi]\[Chi][Subscript[x, a],timeIndex],{timeIndex,(a-100),OptionValue["endTime"]}])//Expand;*)

(* Is Replace faster??*)

z=Replace[z,{V\[Psi]\[Chi][Subscript[x, a_],t]->(Sum[V\[Psi]\[Chi][Subscript[x, a],timeIndex],{timeIndex,(a-100),OptionValue["endTime"]}]),V\[Delta]\[Psi]\[Chi][Subscript[x, a_],t]->(Sum[V\[Delta]\[Psi]\[Chi][Subscript[x, a],timeIndex],{timeIndex,(a-100),OptionValue["endTime"]}])
},{0,1}]//Expand;
(*a_ must be given as 100+(Natural Numbers)*)

(* NEW BIT *)

For[timeIndex=1,timeIndex<=(OptionValue["endTime"]),timeIndex++,

z=CombinatorialFactor[z,OptionValue["endTime"],timeIndex];
];

If[OptionValue["print"],LogMessage[{"z after =",z}]];
];*)

If[OptionValue["ReturnJustAction"],Return[z];];


(* Gamma2 spreading *)
(*If[!FreeQ[z,\[Gamma]2],
(* TRUE *)

If[OptionValue["print"],
LogMessage[{"TRUE: z before spreading Subscript[\[Gamma], 2] =", z}]];
(* Is Replace faster??*)
z=Replace[z,{V\[Gamma]2[Subscript[x, a_],t]->(Sum[V\[Gamma]2[Subscript[x, a],timeIndex],{timeIndex,1,OptionValue["endTime"]}]),V\[Gamma]2Minus[Subscript[x, a_],t]->(Sum[V\[Gamma]2Minus[Subscript[x, a],timeIndex],{timeIndex,1,OptionValue["endTime"]}])},{0,4}]//Expand;


If[OptionValue["print"],LogMessage[{"z after spreading Subscript[\[Gamma], 2] =",z}]];
];*)



locFields=OptionValue["fields"][[1]];
starFields=OptionValue["fields"][[2]];
deltaFields=OptionValue["fields"][[3]];
deltaStarFields=OptionValue["fields"][[4]];

(* z=z*FreeActionMOD[OptionValue["endTime"]]; MODIFICATION *)

(*Start the REAL loop over time*)
For[timeIndex=1,timeIndex<=(OptionValue["endTime"]),timeIndex++,

z=z*(FreeAction[timeIndex]); 

(*Start of loop over fields*)
For[l=1,l<=Length[locFields],l++,

If[OptionValue["print"],LogMessage[{"################## Contracting ",locFields[[l]][x_,Subscript[t, timeIndex]]," ##################"}]];

(*ZEROTH contribution*)

(* Is Replace faster??*)
zTemp1=Replace[z,{locFields[[l]][___,Subscript[t, timeIndex]]->0},{0,6}];


(*zTemp1=zTemp1//.starFields[[l]][___,Subscript[t, timeIndex]]->0;
If[zTemp1-z=!=0,
contributions=zTemp1;
If[OptionValue["print"],LogMessage["First contribution: ",zTemp1]];
];*)

contributions=zTemp1;
If[OptionValue["print"],LogMessage[{"Zeroth contribution: ",contributions}]];

zTemp1=z;

ii=0;

While[!FreeQ[zTemp1,locFields[[l]][___,Subscript[t, timeIndex]]]&& ii<OptionValue["maxContractions"],
zTemp1=z;

ii++;

If[OptionValue["print"],LogMessage[{"Contraction order ",ii,": "}]];

(* EXTRA MODIFICATION: instead of derivating n times and the contract, I think it is better to derivate once, contract, and the iterate n times. This is what I implement now*)
For[ss=1,ss<=ii,ss++,

(*zTemp2=zTemp1/. locFields[[l]][a___,Subscript[t, timeIndex]]->locFields[[l]][a,Subscript[t, timeIndex]]+\[Kappa] *deltaFields[[l]][a,Subscript[t, timeIndex]];*)

(* Is Replace faster??*)
zTemp2=Replace[zTemp1,{ locFields[[l]][a___,Subscript[t, timeIndex]]->locFields[[l]][a,Subscript[t, timeIndex]]+\[Kappa] *deltaFields[[l]][a,Subscript[t, timeIndex]]},{0,6}];

If[OptionValue["print"],LogMessage[{"Replacement: ", locFields[[l]]->locFields[[l]]+\[Kappa] deltaFields[[l]],":\n ",zTemp2}]];


If[zTemp1-zTemp2===0,
(* zTemp1-zTemp2==0: TRUE *)
zTemp1 =0;
Break[];
,

(* zTemp1-zTemp2==0: False *)
(*zTemp1=1/Factorial[ii]D[zTemp1,{\[Kappa],ii}]/.\[Kappa]->0;*)

zTemp1=1/ss D[zTemp2,{\[Kappa]}];

If[OptionValue["print"],LogMessage[{"Extraction of ",deltaFields[[l]]," #",ss," at order ",ii,":\n ",zTemp1}]];

zTemp1=zTemp1/.\[Kappa]->0;

];


(* To have the possibility of \[Delta]-fields directly inside vertices, I separate the splitting and the introduction of \[Kappa] in front of \[Delta]Fields*)
(*zTemp2=zTemp1/. starFields[[l]][a___,Subscript[t, timeIndex]]->starFields[[l]][a,Subscript[t, timeIndex]]+\[Kappa] *deltaStarFields[[l]][a,Subscript[t, timeIndex]];*)

(* Is Replace faster??*)
zTemp2=Replace[zTemp1,{ starFields[[l]][a___,Subscript[t, timeIndex]]->starFields[[l]][a,Subscript[t, timeIndex]]+deltaStarFields[[l]][a,Subscript[t, timeIndex]]},{0,7}];
zTemp2=Replace[zTemp2,{ deltaStarFields[[l]][a___,Subscript[t, timeIndex]]->\[Kappa] *deltaStarFields[[l]][a,Subscript[t, timeIndex]]},{0,7}];

If[OptionValue["print"],LogMessage[{"Replacement: ", starFields[[l]]->starFields[[l]]+\[Kappa] deltaStarFields[[l]],":\n ",zTemp2}]];
(*zTemp2=zTemp1/. starFields[[l]][a___,Subscript[t, timeIndex]]->starFields[[l]][a,Subscript[t, timeIndex]]+\[Kappa] *deltaStarFields[[l]][a,Subscript[t, timeIndex]];*)

(* Is Replace faster??*)
(*zTemp2=Replace[zTemp1,{ starFields[[l]][a___,Subscript[t, timeIndex]]->starFields[[l]][a,Subscript[t, timeIndex]]+\[Kappa] *deltaStarFields[[l]][a,Subscript[t, timeIndex]]},{0,6}];
*)

If[zTemp2-zTemp1===0,
(* zTemp1-zTemp2==0: TRUE *)
zTemp1 =0;
Break[];
,

(* zTemp1-zTemp2==0: FALSE *)
(*zTemp1=1/Factorial[ii]D[zTemp2,{\[Kappa],ii}]/.\[Kappa]->0;*)

zTemp1=(*1/ss*)D[zTemp2,{\[Kappa]}]/.\[Kappa]->0;

If[OptionValue["print"],LogMessage[{"Extraction of ",deltaStarFields[[l]]," #",ss," at order ",ii,":\n ",zTemp1}]];
];


(*LogMessage[zTemp1,"\n"];*)
If[zTemp1=!=0,

(* CONTRACTION *)
zTemp1=Expand[zTemp1];
zTemp2=zTemp1//.deltaFields[[l]][x_,a___,Subscript[t, timeIndex]]*deltaStarFields[[l]][y_,b___,Subscript[t, timeIndex]](*/;(!NumericQ[a*b])->*)->Subscript[G, locFields[[l]]][x,y,Subscript[t, timeIndex]]*\[Delta][{a},{b}]; (*G is the propagator*)
If[OptionValue["print"],LogMessage[{"Contraction of ",deltaFields[[l]],deltaStarFields[[l]],"\n ",zTemp2}]];

(* Is Replace faster?? NO DOESN'T WORK HERE*)
(*zTemp2=Replace[zTemp1,{ deltaFields[[l]][x_,a___,Subscript[t, timeIndex]]*deltaStarFields[[l]][y_,b___,Subscript[t, timeIndex]](*/;(!NumericQ[a*b])->*)->Subscript[G, locFields[[l]]][x,y,Subscript[t, timeIndex]]*\[Delta][{a},{b}]},{0,Infinity}];*)

(* LAPLACIANS *)

(*zTemp2=zTemp2//.deltaFields[[l]][x_,a___,Subscript[t, timeIndex]]*DD[deltaStarFields[[l]][y_,b___,Subscript[t, timeIndex]]*C_](*/;(!NumericQ[a*b])->*)->DD[Subscript[G, locFields[[l]]][x,y,Subscript[t, timeIndex]]C]\[Delta][{a},{b}]; (*DD is the laplacian*)*)

zTemp2=zTemp2//.deltaStarFields[[l]][x_,a___,Subscript[t, timeIndex]]*DD[deltaFields[[l]][y_,b___,Subscript[t, timeIndex]]](*/;(!NumericQ[a*b])->*):>DD[Subscript[G, locFields[[l]]][y,x,Subscript[t, timeIndex]]]\[Delta][{a},{b}]; (*DD is the laplacian*)

(*If[OptionValue["print"],LogMessage[{"Contraction of ",DD[deltaFields[[l]]],deltaStarFields[[l]],"\n ",zTemp2}]];*)


zTemp2=zTemp2//.deltaFields[[l]][x_,a___,Subscript[t, timeIndex]]*DD[deltaStarFields[[l]][y_,b___,Subscript[t, timeIndex]]](*/;(!NumericQ[a*b])->*):>DD[Subscript[G, locFields[[l]]][x,y,Subscript[t, timeIndex]]]\[Delta][{a},{b}]; (*DD is the laplacian*)

(*If[OptionValue["print"],LogMessage[{"Contraction of ",deltaFields[[l]],DD[deltaStarFields[[l]]],"\n ",zTemp2}]];*)

zTemp1=zTemp2/.deltaFields[[l]][___,Subscript[t, timeIndex]]->0/.deltaStarFields[[l]][___,Subscript[t, timeIndex]]->0;
];


];(* END OF "FOR" ON DERIVATIONS+CONTRACTIONS*)

zTemp2=zTemp1/.locFields[[l]][___,Subscript[t, timeIndex]]->0;
(*z=z/.starFields[[l]][___,Subscript[t, timeIndex]]->0;*)

If[contributions-zTemp2=!=0 && zTemp2=!=0 ,

contributions+=zTemp2;
If[OptionValue["print"],LogMessage[{"Contribution #",ii,": ",zTemp2}]];
];

];(* END OF WHILE*)

z=contributions;

If[OptionValue["print"],
LogMessage[{"Overall contributions: ",contributions}];
LogMessage[{"################################################################################################"}]];

contributions=0;

(*z=z/.locFields[[l]][___,Subscript[t, timeIndex]]->0;*)
(*z=z/.starFields[[l]][___,Subscript[t, timeIndex]]->0;*)
(* Is Replace faster??*)
z=Replace[z,{ locFields[[l]][___,Subscript[t, timeIndex]]->0,deltaStarFields[[l]][___,Subscript[t, timeIndex]]->0},{0,4}];


(* Contraction of the indices *)
z=z//.\[Delta][{a_,c___},{b_,d___}]->\[Delta][a,b]\[Delta][{c},{d}]//.\[Delta][{},{}]->1;

(* Is Replace faster?? CANNOT BE USED HERE*)
(*z=Replace[z,{ \[Delta][{a_,c___},{b_,d___}]->\[Delta][a,b]\[Delta][{c},{d}],\[Delta][{},{}]->1},{0,4}];*)


If[OptionValue["\[Delta]rule"],z=z//.\[CapitalSigma]\[Delta]rule];
If[OptionValue["\[Delta]ruleExternal"],z=z//.\[Delta][a_,b_]starFields[[l]][c___,a_,d___,Subscript[t, timeIndex]]/;(NumericQ[b] && !NumericQ[a]):>\[Delta][a,b]starFields[[l]][c,b,d,Subscript[t, timeIndex]]/.\[Delta][a_,b_]/;(NumericQ[b] && !NumericQ[a]):>1;
z=z//.\[Delta][a_,b_]starFields[[l]][c___,b_,d___,Subscript[t, timeIndex]]/;(NumericQ[a] && !NumericQ[b]):>\[Delta][a,b]starFields[[l]][c,a,d,Subscript[t, timeIndex]]/.\[Delta][a_,b_]/;(NumericQ[a] && !NumericQ[b]):>1
];

z=z/.Subscript[n, \[Chi]]->OptionValue["\!\(\*SubscriptBox[\(n\), \(\[Chi]\)]\)"];
z=z/.Subscript[n, \[Alpha]]->OptionValue["\!\(\*SubscriptBox[\(n\), \(\[Alpha]\)]\)"];

];(*End of loop over fields*)

z=z/.Subscript[G, \[Psi]][Subscript[x, a_],Subscript[x, b_],__]/;(!FreeQ[a,action]&&!FreeQ[a,action]):>0/.Subscript[G, \[Phi]][a_,a_,b_] ->0/.Subscript[G, \[Chi]][a_,a_,b_] ->0; (* Eliminate loops*)

];(*End of loop over time*)

If[OptionValue["kill\[Psi]"],
z=z/.\[Psi]s[___,Subscript[t, a_]]/;(a<=OptionValue["endTime"]):>0(*/.\[Delta]\[Psi]s[___,Subscript[t, a_]]/;(a<=OptionValue["endTime"]):>0*);
];

Clear[locFields, starFields, deltaFields,deltaStarFields,contributions,zTemp1,zTemp2,\[Kappa],jj,l,timeIndex,ii,ss];

If[OptionValue["print"],
LogMessage[{"Final result:\n ",z}];];

If[OptionValue["SimplifyPropagators"],
z=SimplifyPropagators[z,"SimplifyG\[Psi]"->OptionValue["SimplifyG\[Psi]"]]];

If[OptionValue["print"],SystemOpen[LogFile]];

Return[z]
];


(* ::Input::Initialization:: *)
ClearAll[WickContractionSpaceVerticesMODfaster];
Options[WickContractionSpaceVerticesMODfaster]={"print"->False,"fields"->FieldsNamesGenerator[{\[Phi],\[Chi],\[Psi]}], "startingTime"->1, "endTime"->1,"#vertices"->10,"\[Delta]rule"->True,"\[Delta]ruleExternal"->True,"\!\(\*SubscriptBox[\(n\), \(\[Chi]\)]\)"->(-1),"\!\(\*SubscriptBox[\(n\), \(\[Alpha]\)]\)"->(0),"maxContractions"->5,"kill\[Psi]"->True,"SimplifyPropagators"->True,"SimplifyG\[Psi]"->True,"ReturnJustAction"->False,"FreeAction"->FreeAction};

WickContractionSpaceVerticesMODfaster[A_ +B_,OptionsPattern[]]:=WickContractionSpaceVerticesMODfaster[A,"print"->OptionValue["print"],"fields"->OptionValue["fields"], "startingTime"->OptionValue["startingTime"],"endTime"->OptionValue["endTime"],"#vertices"->OptionValue["#vertices"],"\[Delta]rule"->OptionValue["\[Delta]rule"],"\[Delta]ruleExternal"->OptionValue["\[Delta]ruleExternal"],"\!\(\*SubscriptBox[\(n\), \(\[Chi]\)]\)"->OptionValue["\!\(\*SubscriptBox[\(n\), \(\[Chi]\)]\)"],"\!\(\*SubscriptBox[\(n\), \(\[Alpha]\)]\)"->OptionValue["\!\(\*SubscriptBox[\(n\), \(\[Alpha]\)]\)"],"maxContractions"->OptionValue["maxContractions"],"kill\[Psi]"->OptionValue["kill\[Psi]"]]+
WickContractionSpaceVerticesMODfaster[B,"print"->OptionValue["print"],"fields"->OptionValue["fields"], "startingTime"->OptionValue["startingTime"],"endTime"->OptionValue["endTime"],"#vertices"->OptionValue["#vertices"],"\[Delta]rule"->OptionValue["\[Delta]rule"],"\[Delta]ruleExternal"->OptionValue["\[Delta]ruleExternal"],"\!\(\*SubscriptBox[\(n\), \(\[Chi]\)]\)"->OptionValue["\!\(\*SubscriptBox[\(n\), \(\[Chi]\)]\)"],"\!\(\*SubscriptBox[\(n\), \(\[Alpha]\)]\)"->OptionValue["\!\(\*SubscriptBox[\(n\), \(\[Alpha]\)]\)"],"maxContractions"->OptionValue["maxContractions"],"kill\[Psi]"->OptionValue["kill\[Psi]"]];


WickContractionSpaceVerticesMODfaster[A_?NumericQ,OptionsPattern[]]:=A;

(*################################################################################
									Partition Function                             
##############################################################################*)
(*There are two possible contributions for each field: 1) it is not contracted: \[Chi]->0; 2) it is contracted*)

WickContractionSpaceVerticesMODfaster[V[A_] *B_, OptionsPattern[]]:=Module[{interactionPermutations={},locFields={}, starFields={}, deltaFields={},deltaStarFields={},contributions=0,z,zTemp1,zTemp2,jj,l,timeIndex,ii,ss,DDflag=False},

If[OptionValue["print"],DeleteFile[LogFile]];  (*Place at the top of the notebook*)

z=V[A]*B;

If[(!FreeQ[z,DD[___]]),DDflag=True;];

If[OptionValue["ReturnJustAction"],Return[z];];


locFields=OptionValue["fields"][[1]];
starFields=OptionValue["fields"][[2]];
deltaFields=OptionValue["fields"][[3]];
deltaStarFields=OptionValue["fields"][[4]];

(*Start the REAL loop over time*)
For[timeIndex=OptionValue["startingTime"],timeIndex<=(OptionValue["endTime"]),timeIndex++,

(* The addition of Hold[0] is used to make sure that Head[z]=Sum. This way we can specify Reaplace[...,{1}]*)
z=z*(OptionValue["FreeAction"][timeIndex])+Hold[0]; 

(*Start of loop over fields*)
For[l=1,l<=Length[locFields],l++,

If[OptionValue["print"],LogMessage[{"################## Contracting ",locFields[[l]][x_,Subscript[t, timeIndex]]," ##################"}]];

(*ZEROTH contribution*)

(* Is Replace faster??*)
zTemp1=Replace[z,{locFields[[l]][___,Subscript[t, timeIndex]]->0},{1,7}];

contributions=zTemp1;
If[OptionValue["print"],LogMessage[{"Zeroth contribution: ",contributions}]];

zTemp1=z;

ii=0;

While[(!FreeQ[zTemp1,locFields[[l]][___,Subscript[t, timeIndex]]]||!FreeQ[zTemp1,deltaFields[[l]][___,Subscript[t, timeIndex]]])&& ii<OptionValue["maxContractions"],
zTemp1=z;

ii++;

If[OptionValue["print"],LogMessage[{"Contraction order ",ii,": "}]];

For[ss=1,ss<=ii,ss++,

(* To have the possibility of \[Delta]-fields directly inside vertices, I separate the splitting and the introduction of \[Kappa] in front of \[Delta]Fields*)
(*zTemp2=zTemp1/. starFields[[l]][a___,Subscript[t, timeIndex]]->starFields[[l]][a,Subscript[t, timeIndex]]+\[Kappa] *deltaStarFields[[l]][a,Subscript[t, timeIndex]];*)

(* Is Replace faster??*)
zTemp2=Replace[zTemp1,{ starFields[[l]][a___,Subscript[t, timeIndex]]->starFields[[l]][a,Subscript[t, timeIndex]]+deltaStarFields[[l]][a,Subscript[t, timeIndex]]},{1,7}];
zTemp2=Replace[zTemp2,{ deltaStarFields[[l]][a___,Subscript[t, timeIndex]]->\[Kappa] *deltaStarFields[[l]][a,Subscript[t, timeIndex]]},{1,7}];


If[zTemp2-zTemp1===0 ,
(* zTemp1-zTemp2==0: TRUE *)
zTemp1 =0;
Break[];
,

(* zTemp1-zTemp2==0: FALSE *)
(*zTemp1=1/Factorial[ii]D[zTemp2,{\[Kappa],ii}]/.\[Kappa]->0;*)

zTemp1=(*1/ss*)D[zTemp2,{\[Kappa]}]/.\[Kappa]->0;

If[OptionValue["print"],LogMessage[{"Extraction of ",deltaStarFields[[l]]," #",ss," at order ",ii,":\n ",zTemp1}]];
];


(*zTemp2=zTemp1/. locFields[[l]][a___,Subscript[t, timeIndex]]->locFields[[l]][a,Subscript[t, timeIndex]]+\[Kappa] *deltaFields[[l]][a,Subscript[t, timeIndex]];*)

(* Is Replace faster??*)
zTemp2=Replace[zTemp1,{ locFields[[l]][a___,Subscript[t, timeIndex]]->locFields[[l]][a,Subscript[t, timeIndex]]+deltaFields[[l]][a,Subscript[t, timeIndex]]},{1,7}];
zTemp2=Replace[zTemp2,{ deltaFields[[l]][a___,Subscript[t, timeIndex]]->\[Kappa] *deltaFields[[l]][a,Subscript[t, timeIndex]]},{1,7}];

If[OptionValue["print"],LogMessage[{"Replacement: ", locFields[[l]]->locFields[[l]]+\[Kappa] deltaFields[[l]],":\n ",zTemp2}]];


If[zTemp1-zTemp2===0,
(* zTemp1-zTemp2==0: TRUE *)
zTemp1 =0;
Break[];
,

(* zTemp1-zTemp2==0: False *)
(*zTemp1=1/Factorial[ii]D[zTemp1,{\[Kappa],ii}]/.\[Kappa]->0;*)

zTemp1=1/ss D[zTemp2,{\[Kappa]}];

If[OptionValue["print"],LogMessage[{"Extraction of ",deltaFields[[l]]," #",ss," at order ",ii,":\n ",zTemp1}]];

zTemp1=zTemp1/.\[Kappa]->0;

If[OptionValue["print"],LogMessage[{zTemp1}]];
];



(*LogMessage[zTemp1,"\n"];*)
If[zTemp1=!=0,

(* CONTRACTION *)
zTemp1=Expand[zTemp1];

(* Is Replace faster?? *)
zTemp2=Replace[(zTemp1),{Times[f___,deltaFields[[l]][x_,a___,Subscript[t, timeIndex]]*deltaStarFields[[l]][y_,b___,Subscript[t, timeIndex]],g___]->Times[f,Subscript[G, locFields[[l]]][x,y,Subscript[t, timeIndex]],\[Delta][{a},{b}],g]},{0,1}];

(*zTemp2=zTemp1//.deltaFields[[l]][x_,a___,Subscript[t, timeIndex]]*deltaStarFields[[l]][y_,b___,Subscript[t, timeIndex]](*/;(!NumericQ[a*b])->*)->Subscript[G, locFields[[l]]][x,y,Subscript[t, timeIndex]]*\[Delta][{a},{b}]; (*G is the propagator*)*)

If[OptionValue["print"],LogMessage[{"Contraction of ",deltaFields[[l]],deltaStarFields[[l]],"\n ",zTemp2}]];

If[DDflag, zTemp2 = ReplaceRepeated[zTemp2, Part[deltaStarFields, l][Pattern[x, Blank[]], Pattern[a, BlankNullSequence[]], Subscript[t, timeIndex]] DD[Part[deltaFields, l][Pattern[y, Blank[]], Pattern[b, BlankNullSequence[]], Subscript[t, timeIndex]]] :> DD[Subscript[G, Part[locFields, l]][y, x, Subscript[t, timeIndex]]] \[Delta][{a}, {b}]]; zTemp2 = ReplaceRepeated[zTemp2, Part[deltaFields, l][Pattern[x, Blank[]], Pattern[a, BlankNullSequence[]], Subscript[t, timeIndex]] DD[Part[deltaStarFields, l][Pattern[y, Blank[]], Pattern[b, BlankNullSequence[]], Subscript[t, timeIndex]]] :> DD[Subscript[G, Part[locFields, l]][x, y, Subscript[t, timeIndex]]] \[Delta][{a}, {b}]]; Null];(* If on DDflag *)

zTemp1=Replace[zTemp2,{ (*Times[___,locFields[[l]][___,Subscript[t, timeIndex]],___]*)deltaFields[[l]][___,Subscript[t, timeIndex]]->0,deltaStarFields[[l]][___,Subscript[t, timeIndex]]->0},{1,5}];

];(*END of If on zTemp1=!=0*)
];(* END OF "FOR" ON DERIVATIONS+CONTRACTIONS*)

zTemp2=zTemp1/.locFields[[l]][___,Subscript[t, timeIndex]]->0;
(*z=z/.starFields[[l]][___,Subscript[t, timeIndex]]->0;*)
(*zTemp2=Replace[zTemp1,{ (*Times[___,locFields[[l]][___,Subscript[t, timeIndex]],___]*)locFields[[l]][___,Subscript[t, timeIndex]]->0},{1,5}];*)

If[(contributions-zTemp2=!=0) && (zTemp2=!=0) ,

contributions+=zTemp2;
If[OptionValue["print"],LogMessage[{"Contribution #",ii,": ",zTemp2}]];
];

];(* END OF WHILE*)

z=contributions;

If[OptionValue["print"],
LogMessage[{"Overall contributions: ",contributions}];
LogMessage[{"################################################################################################"}]];

contributions=0;

(*];(*End of loop over number of vertices*)*)

(*z=z/.locFields[[l]][___,Subscript[t, timeIndex]]->0;*)
(*z=z/.starFields[[l]][___,Subscript[t, timeIndex]]->0;*)
(* Is Replace faster??*)
z=Replace[z,{ locFields[[l]][___,Subscript[t, timeIndex]]->0,deltaFields[[l]][___,Subscript[t, timeIndex]]->0},{1,5}];


(* Expansion of the \[Delta]'s *)
z=z//.\[Delta][{a_,c___},{b_,d___}]->\[Delta][a,b]\[Delta][{c},{d}]//.\[Delta][{},{}]->1;

(* Is Replace faster?? CANNOT BE USED HERE*)
(*z=Replace[z,{ \[Delta][{a_,c___},{b_,d___}]->\[Delta][a,b]\[Delta][{c},{d}],\[Delta][{},{}]->1},{0,4}];*)


If[OptionValue["\[Delta]rule"],z=z//.\[CapitalSigma]\[Delta]rule];
If[OptionValue["\[Delta]ruleExternal"],
(* Contraction of the indices *)
z=z//.\[Delta][a_,b_]starFields[[l]][c___,a_,d___,Subscript[t, timeIndex]]/;(NumericQ[b] && !NumericQ[a]):>\[Delta][a,b]starFields[[l]][c,b,d,Subscript[t, timeIndex]]/.\[Delta][a_,b_]/;(NumericQ[b] && !NumericQ[a]):>1;
z=z//.\[Delta][a_,b_]starFields[[l]][c___,b_,d___,Subscript[t, timeIndex]]/;(NumericQ[a] && !NumericQ[b]):>\[Delta][a,b]starFields[[l]][c,a,d,Subscript[t, timeIndex]]/.\[Delta][a_,b_]/;(NumericQ[a] && !NumericQ[b]):>1;
];

(*z=z/.Subscript[n, \[Chi]]->OptionValue["Subscript[n, \[Chi]]"];
z=z/.Subscript[n, \[Alpha]]->OptionValue["Subscript[n, \[Alpha]]"];*)
z=Replace[(z),{Subscript[n, \[Chi]]->OptionValue["\!\(\*SubscriptBox[\(n\), \(\[Chi]\)]\)"],Subscript[n, \[Alpha]]->OptionValue["\!\(\*SubscriptBox[\(n\), \(\[Alpha]\)]\)"]},{2}];

];(*End of loop over fields*)

(*z=z/.Subscript[G, \[Psi]][Subscript[x, a_],Subscript[x, b_],__]/;(!FreeQ[a,action]&&!FreeQ[a,action]):>0/.Subscript[G, \[Phi]][a_,a_,b_] ->0/.Subscript[G, \[Chi]][a_,a_,b_] ->0;*) (* Eliminate loops*)


z=Replace[(z),{Subscript[G, \[Psi]][Subscript[x, a_],Subscript[x, b_],__]/;(!FreeQ[a,action]&&!FreeQ[a,action]):>0,Subscript[G, \[Phi]][a_,a_,b_] ->0,Subscript[G, \[Chi]][a_,a_,b_] ->0},{2}];

If[OptionValue["kill\[Psi]"] ,
z=z/.\[Psi]s[___,Subscript[t, a_]]/;(a<=timeIndex):>0/.\[Delta]\[Psi]s[___,Subscript[t, a_]]/;(a<=timeIndex):>0;
(*z=Replace[(z),{\[Psi]s[___,Subscript[t, a_]]/;(a<=timeIndex):>0,\[Delta]\[Psi]s[___,Subscript[t, a_]]/;(a<=timeIndex):>0},{1,4}];*)
];

(* This releases dummy=0 *)
z=ReleaseHold[z];

];(*End of loop over time*)


Clear[locFields, starFields, deltaFields,deltaStarFields,contributions,zTemp1,zTemp2,\[Kappa],jj,l,timeIndex,ii,ss];

If[OptionValue["print"],
LogMessage[{"Final result:\n ",z}];];

If[OptionValue["SimplifyPropagators"],
z=SimplifyPropagators[z,"SimplifyG\[Psi]"->OptionValue["SimplifyG\[Psi]"]]];

If[OptionValue["print"],SystemOpen[LogFile]];

Return[z]
];


(* ::Input::Initialization:: *)
ClearAll[WickContractionSpaceVerticesMODfasterFor\[Delta]Fields];
Options[WickContractionSpaceVerticesMODfasterFor\[Delta]Fields]={"print"->False,"printStartingAtTimeslice"->(1),"fields"->FieldsNamesGenerator[{\[Phi],\[Chi],\[Psi]}], "endTime"->1,"#vertices"->10,"\[Delta]rule"->True,"\[Delta]ruleExternal"->True,"\!\(\*SubscriptBox[\(n\), \(\[Chi]\)]\)"->(-1),"\!\(\*SubscriptBox[\(n\), \(\[Alpha]\)]\)"->(0),"maxContractions"->5,"kill\[Psi]"->True,"SimplifyPropagators"->True,"SimplifyG\[Psi]"->True,"ReturnJustAction"->False,"FreeAction"->FreeAction};

WickContractionSpaceVerticesMODfasterFor\[Delta]Fields[A_ +B_,OptionsPattern[]]:=WickContractionSpaceVerticesMODfasterFor\[Delta]Fields[A,"print"->OptionValue["print"],"fields"->OptionValue["fields"], "endTime"->OptionValue["endTime"],"#vertices"->OptionValue["#vertices"],"\[Delta]rule"->OptionValue["\[Delta]rule"],"\[Delta]ruleExternal"->OptionValue["\[Delta]ruleExternal"],"\!\(\*SubscriptBox[\(n\), \(\[Chi]\)]\)"->OptionValue["\!\(\*SubscriptBox[\(n\), \(\[Chi]\)]\)"],"\!\(\*SubscriptBox[\(n\), \(\[Alpha]\)]\)"->OptionValue["\!\(\*SubscriptBox[\(n\), \(\[Alpha]\)]\)"],"maxContractions"->OptionValue["maxContractions"],"kill\[Psi]"->OptionValue["kill\[Psi]"]]+
WickContractionSpaceVerticesMODfasterFor\[Delta]Fields[B,"print"->OptionValue["print"],"fields"->OptionValue["fields"], "endTime"->OptionValue["endTime"],"#vertices"->OptionValue["#vertices"],"\[Delta]rule"->OptionValue["\[Delta]rule"],"\[Delta]ruleExternal"->OptionValue["\[Delta]ruleExternal"],"\!\(\*SubscriptBox[\(n\), \(\[Chi]\)]\)"->OptionValue["\!\(\*SubscriptBox[\(n\), \(\[Chi]\)]\)"],"\!\(\*SubscriptBox[\(n\), \(\[Alpha]\)]\)"->OptionValue["\!\(\*SubscriptBox[\(n\), \(\[Alpha]\)]\)"],"maxContractions"->OptionValue["maxContractions"],"kill\[Psi]"->OptionValue["kill\[Psi]"]];


WickContractionSpaceVerticesMODfasterFor\[Delta]Fields[A_?NumericQ,OptionsPattern[]]:=A;

(*################################################################################
									Partition Function                             
##############################################################################*)
(*There are two possible contributions for each field: 1) it is not contracted: \[Chi]->0; 2) it is contracted*)

WickContractionSpaceVerticesMODfasterFor\[Delta]Fields[V[A_] *B_, OptionsPattern[]]:=Module[{interactionPermutations={},locFields={}, starFields={}, deltaFields={},deltaStarFields={},contributions=0,z,zTemp1,zTemp2,jj,l,timeIndex,ii,ss,DDflag=False},

If[OptionValue["print"],DeleteFile[LogFile]];  (*Place at the top of the notebook*)

z=V[A]*B;

If[(!FreeQ[z,DD[___]]),DDflag=True;];

If[OptionValue["ReturnJustAction"],Return[z];];


locFields=OptionValue["fields"][[1]];
starFields=OptionValue["fields"][[2]];
deltaFields=OptionValue["fields"][[3]];
deltaStarFields=OptionValue["fields"][[4]];

(*Start the REAL loop over time*)
For[timeIndex=1,timeIndex<=(OptionValue["endTime"]),timeIndex++,

(* The addition of Hold[0] is used to make sure that Head[z]=Sum. This way we can specify Reaplace[...,{1}]*)
z=z*(OptionValue["FreeAction"][timeIndex])+Hold[0]; 

(*Start of loop over fields*)
For[l=1,l<=Length[locFields],l++,

If[OptionValue["print"] && timeIndex>=OptionValue["printStartingAtTimeslice"],LogMessage[{"################## Contracting ",locFields[[l]][x_,Subscript[t, timeIndex]]," ##################"}]];

(*ZEROTH contribution*)

(* Is Replace faster??*)
zTemp1=Replace[z,{locFields[[l]][___,Subscript[t, timeIndex]]->0(*,starFields[[l]][___,Subscript[t, timeIndex]]->0*)},{1,7}];

contributions=zTemp1;
If[OptionValue["print"] && timeIndex>=OptionValue["printStartingAtTimeslice"],LogMessage[{"Zeroth contribution: ",contributions}]];

zTemp1=z;

ii=0;

While[(*(!FreeQ[zTemp1,locFields[[l]][___,Subscript[t, timeIndex]]]||!FreeQ[zTemp1,deltaFields[[l]][___,Subscript[t, timeIndex]]])&&*) ii<OptionValue["maxContractions"],

zTemp1=z;

ii++;

If[OptionValue["print"] && timeIndex>=OptionValue["printStartingAtTimeslice"],LogMessage[{"Contraction order ",ii,": "}]];

(*For[ss=1,ss<=ii,ss++,*)

(* To have the possibility of \[Delta]-fields directly inside vertices, I separate the splitting and the introduction of \[Kappa] in front of \[Delta]Fields*)
(*zTemp2=zTemp1/. starFields[[l]][a___,Subscript[t, timeIndex]]->starFields[[l]][a,Subscript[t, timeIndex]]+\[Kappa] *deltaStarFields[[l]][a,Subscript[t, timeIndex]];*)

(* Is Replace faster??*)
zTemp2=Replace[zTemp1,{ starFields[[l]][a___,Subscript[t, timeIndex]]->starFields[[l]][a,Subscript[t, timeIndex]]+deltaStarFields[[l]][a,Subscript[t, timeIndex]]},{1,7}];
zTemp2=Replace[zTemp2,{ deltaStarFields[[l]][a___,Subscript[t, timeIndex]]->\[Kappa] *deltaStarFields[[l]][a,Subscript[t, timeIndex]]},{1,7}];


If[zTemp2-zTemp1===0 ,
(* zTemp1-zTemp2==0: TRUE *)
zTemp1 =0;
Continue[];
,

(* zTemp1-zTemp2==0: FALSE *)
zTemp1=1/Factorial[ii] D[zTemp2,{\[Kappa],ii}]/.\[Kappa]->0;

(*zTemp1=(*1/ss*)D[zTemp2,{\[Kappa]}]/.\[Kappa]->0;*)

If[OptionValue["print"] && timeIndex>=OptionValue["printStartingAtTimeslice"],LogMessage[{"Extraction of ",deltaStarFields[[l]]," at order ",ii,":\n ",zTemp1}]];

];


(*zTemp2=zTemp1/. locFields[[l]][a___,Subscript[t, timeIndex]]->locFields[[l]][a,Subscript[t, timeIndex]]+\[Kappa] *deltaFields[[l]][a,Subscript[t, timeIndex]];*)

(* Is Replace faster??*)
zTemp2=Replace[zTemp1,{ locFields[[l]][a___,Subscript[t, timeIndex]]->locFields[[l]][a,Subscript[t, timeIndex]]+ deltaFields[[l]][a,Subscript[t, timeIndex]]},{1,7}];
zTemp2=Replace[zTemp2,{ deltaFields[[l]][a___,Subscript[t, timeIndex]]->\[Kappa] *deltaFields[[l]][a,Subscript[t, timeIndex]]},{1,7}];

If[OptionValue["print"] && timeIndex>=OptionValue["printStartingAtTimeslice"],LogMessage[{"Replacement: ", locFields[[l]]->locFields[[l]]+\[Kappa] deltaFields[[l]],":\n ",zTemp2}]];


If[zTemp1-zTemp2===0,
(* zTemp1-zTemp2==0: TRUE *)
zTemp1 =0;
Continue[];
,

(* zTemp1-zTemp2==0: False *)
zTemp1=1/Factorial[ii] D[zTemp2,{\[Kappa],ii}]/.\[Kappa]->0;

(*zTemp1=1/ssD[zTemp2,{\[Kappa]}]/.\[Kappa]->0;*)

If[OptionValue["print"] && timeIndex>=OptionValue["printStartingAtTimeslice"],LogMessage[{"Extraction of ",deltaFields[[l]]," at order ",ii,":\n ",zTemp1}]];

(*If[OptionValue["print"],LogMessage[{zTemp1}]];*)
];


If[zTemp1=!=0,

(* CONTRACTION *)
zTemp1=Expand[zTemp1];

(* Is Replace faster?? *)

If[OptionValue["print"] && timeIndex>=OptionValue["printStartingAtTimeslice"],LogMessage[{"Contraction of ",deltaFields[[l]],deltaStarFields[[l]],"\n "}]];

(* Under chat's advice I use ReplaceList to get the possible permutations!*)

zTemp2=ReplaceList[(zTemp1+Hold[0]),{Times[f___,deltaFields[[l]][x_,a___,Subscript[t, timeIndex]]*deltaStarFields[[l]][y_,b___,Subscript[t, timeIndex]]]+g_->Times[f,Subscript[G, locFields[[l]]][x,y,Subscript[t, timeIndex]],\[Delta][{a},{b}]]+g}];

If[OptionValue["print"] && timeIndex>=OptionValue["printStartingAtTimeslice"],LogMessage[{"Contraction #1 out of ",ii,"\n ",zTemp2}]];


For[ss=1,ss<=ii-1,ss++,

(*zTemp2=Flatten[ReplaceList[#,{(Times[f___,deltaFields[[l]][x_,a___,Subscript[t, timeIndex]]*deltaStarFields[[l]][y_,b___,Subscript[t, timeIndex]]]+g_)->(Times[f,Subscript[G, locFields[[l]]][x,y,Subscript[t, timeIndex]],\[Delta][{a},{b}]]+g)}]&/@(zTemp2)];
*)

zTemp2=ReplaceList[(Plus@@zTemp2),{(Times[f___,deltaFields[[l]][x_,a___,Subscript[t, timeIndex]]*deltaStarFields[[l]][y_,b___,Subscript[t, timeIndex]]]+g_)->(Times[f,Subscript[G, locFields[[l]]][x,y,Subscript[t, timeIndex]],\[Delta][{a},{b}]]+g)}];

If[OptionValue["print"] && timeIndex>=OptionValue["printStartingAtTimeslice"],LogMessage[{"Contraction #",(ss+1)," out of ",ii,"\n ",zTemp2}]];

];

(*If[ii>=2,

zTemp2=ReplaceAll[#,{(Times[f___,deltaFields[[l]][x_,a___,Subscript[t, timeIndex]]*deltaStarFields[[l]][y_,b___,Subscript[t, timeIndex]]]+g_)->(Times[f,Subscript[G, locFields[[l]]][x,y,Subscript[t, timeIndex]],\[Delta][{a},{b}]]+g)}]&/@(zTemp2);

If[OptionValue["print"],LogMessage[{"Contraction #",(ii)," out of ",ii,"\n ",zTemp2}]];
];*)

zTemp2=Plus@@ReleaseHold[1/Factorial[ii] zTemp2];

(*zTemp2=zTemp1//.deltaFields[[l]][x_,a___,Subscript[t, timeIndex]]*deltaStarFields[[l]][y_,b___,Subscript[t, timeIndex]](*/;(!NumericQ[a*b])->*)->Subscript[G, locFields[[l]]][x,y,Subscript[t, timeIndex]]*\[Delta][{a},{b}]; (*G is the propagator*)*)


If[DDflag, zTemp2 = ReplaceRepeated[zTemp2, Part[deltaStarFields, l][Pattern[x, Blank[]], Pattern[a, BlankNullSequence[]], Subscript[t, timeIndex]] DD[Part[deltaFields, l][Pattern[y, Blank[]], Pattern[b, BlankNullSequence[]], Subscript[t, timeIndex]]] :> DD[Subscript[G, Part[locFields, l]][y, x, Subscript[t, timeIndex]]] \[Delta][{a}, {b}]]; zTemp2 = ReplaceRepeated[zTemp2, Part[deltaFields, l][Pattern[x, Blank[]], Pattern[a, BlankNullSequence[]], Subscript[t, timeIndex]] DD[Part[deltaStarFields, l][Pattern[y, Blank[]], Pattern[b, BlankNullSequence[]], Subscript[t, timeIndex]]] :> DD[Subscript[G, Part[locFields, l]][x, y, Subscript[t, timeIndex]]] \[Delta][{a}, {b}]]; Null];(* If on DDflag *)

zTemp2=zTemp2//.{deltaFields[[l]][___,Subscript[t, timeIndex]]->0,deltaStarFields[[l]][___,Subscript[t, timeIndex]]->0};
(*zTemp2=Replace[zTemp2,{ (*Times[___,locFields[[l]][___,Subscript[t, timeIndex]],___]*)deltaFields[[l]][___,Subscript[t, timeIndex]]->0,deltaStarFields[[l]][___,Subscript[t, timeIndex]]->0},{0,5}];*)

zTemp1=zTemp2;

];(*END of If on zTemp1=!=0*)

(*];(* END OF "FOR" ON DERIVATIONS+CONTRACTIONS*)*)


zTemp2=zTemp2/.locFields[[l]][___,Subscript[t, timeIndex]]->0;
(*z=z/.starFields[[l]][___,Subscript[t, timeIndex]]->0;*)
(*zTemp2=Replace[zTemp1,{ (*Times[___,locFields[[l]][___,Subscript[t, timeIndex]],___]*)locFields[[l]][___,Subscript[t, timeIndex]]->0},{1,5}];*)

If[(contributions-zTemp2=!=0) && (zTemp2=!=0) ,

contributions+=zTemp2;
If[OptionValue["print"] && timeIndex>=OptionValue["printStartingAtTimeslice"],LogMessage[{"Contribution #",ii,": ",zTemp2}]];
];


If[OptionValue["print"] && timeIndex>=OptionValue["printStartingAtTimeslice"],LogMessage[{"End of While #",ii,", zTemp1 is: ",zTemp1}]];

];(* END OF WHILE*)

z=contributions;

If[OptionValue["print"] && timeIndex>=OptionValue["printStartingAtTimeslice"],
LogMessage[{"Overall contributions: ",contributions}];
LogMessage[{"################################################################################################"}]];

contributions=0;

(*];(*End of loop over number of vertices*)*)

(*z=z/.locFields[[l]][___,Subscript[t, timeIndex]]->0;*)
(*z=z/.starFields[[l]][___,Subscript[t, timeIndex]]->0;*)
(* Is Replace faster??*)
z=Replace[z,{ locFields[[l]][___,Subscript[t, timeIndex]]->0,deltaFields[[l]][___,Subscript[t, timeIndex]]->0},{1,5}];


(* Expansion of the \[Delta]'s *)
z=z//.\[Delta][{a_,c___},{b_,d___}]->\[Delta][a,b]\[Delta][{c},{d}]//.\[Delta][{},{}]->1;

(* Is Replace faster?? CANNOT BE USED HERE*)
(*z=Replace[z,{ \[Delta][{a_,c___},{b_,d___}]->\[Delta][a,b]\[Delta][{c},{d}],\[Delta][{},{}]->1},{0,4}];*)


If[OptionValue["\[Delta]rule"],z=z//.\[CapitalSigma]\[Delta]rule];
If[OptionValue["\[Delta]ruleExternal"],
(* Contraction of the indices *)
z=z//.\[Delta][a_,b_]starFields[[l]][c___,a_,d___,Subscript[t, timeIndex]]/;(NumericQ[b] && !NumericQ[a]):>\[Delta][a,b]starFields[[l]][c,b,d,Subscript[t, timeIndex]]/.\[Delta][a_,b_]/;(NumericQ[b] && !NumericQ[a]):>1;
z=z//.\[Delta][a_,b_]starFields[[l]][c___,b_,d___,Subscript[t, timeIndex]]/;(NumericQ[a] && !NumericQ[b]):>\[Delta][a,b]starFields[[l]][c,a,d,Subscript[t, timeIndex]]/.\[Delta][a_,b_]/;(NumericQ[a] && !NumericQ[b]):>1;
];

(*z=z/.Subscript[n, \[Chi]]->OptionValue["Subscript[n, \[Chi]]"];
z=z/.Subscript[n, \[Alpha]]->OptionValue["Subscript[n, \[Alpha]]"];*)
z=Replace[(z),{Subscript[n, \[Chi]]->OptionValue["\!\(\*SubscriptBox[\(n\), \(\[Chi]\)]\)"],Subscript[n, \[Alpha]]->OptionValue["\!\(\*SubscriptBox[\(n\), \(\[Alpha]\)]\)"]},{2}];

];(*End of loop over fields*)

(*z=z/.Subscript[G, \[Psi]][Subscript[x, a_],Subscript[x, b_],__]/;(!FreeQ[a,action]&&!FreeQ[a,action]):>0/.Subscript[G, \[Phi]][a_,a_,b_] ->0/.Subscript[G, \[Chi]][a_,a_,b_] ->0; (* Eliminate loops*)*)

z=Replace[(z),{Subscript[G, \[Psi]][Subscript[x, a_],Subscript[x, b_],__]/;(!FreeQ[a,action]&&!FreeQ[a,action]):>0,Subscript[G, \[Phi]][a_,a_,b_] ->0,Subscript[G, \[Chi]][a_,a_,b_] ->0},{2}];


If[OptionValue["kill\[Psi]"] ,
z=z/.\[Psi]s[___,Subscript[t, a_]]/;(a<=timeIndex):>0/.\[Delta]\[Psi]s[___,Subscript[t, a_]]/;(a<=timeIndex):>0;
(*z=Replace[(z),{\[Psi]s[___,Subscript[t, a_]]/;(a<=timeIndex):>0,\[Delta]\[Psi]s[___,Subscript[t, a_]]/;(a<=timeIndex):>0},{1,4}];*)
];

(* This releases dummy=0 *)
z=ReleaseHold[z];

];(*End of loop over time*)

Clear[locFields, starFields, deltaFields,deltaStarFields,contributions,zTemp1,zTemp2,\[Kappa],jj,l,timeIndex,ii,ss];

If[OptionValue["print"],
LogMessage[{"Final result:\n ",z}];];

If[OptionValue["SimplifyPropagators"],
z=SimplifyPropagators[z,"SimplifyG\[Psi]"->OptionValue["SimplifyG\[Psi]"]]];

(*
If[OptionValue["print"],SystemOpen[LogFile]];*)

Return[z]
];


(* ::Input::Initialization:: *)
ClearAll[SimplifyPropagators];

Options[SimplifyPropagators]={"SimplifyG\[Psi]"->True};

SimplifyPropagators[exp_,OptionsPattern[]]:=Module[{terms,i,pureProp, weight, dots,plot},
terms=exp//.F_[A___,Subscript[x, a_],B___]Subscript[G, \[Psi]][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]->F[A,Subscript[x, b],B]Subscript[G, \[Psi]][Subscript[x, a],Subscript[x, b],Subscript[t, c]]
//.DD[F_[A___,Subscript[x, a_],B___]]Subscript[G, \[Psi]][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]->DD[F[A,Subscript[x, b],B]]Subscript[G, \[Psi]][Subscript[x, a],Subscript[x, b],Subscript[t, c]]
//.DD[F_[Subscript[x, a_],A___]]Subscript[G, \[Psi]][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]->DD[F[Subscript[x, b],B]]Subscript[G, \[Psi]][Subscript[x, a],Subscript[x, b],Subscript[t, c]]
//.DD[F_[A___,Subscript[x, a_],B___]H_[C___,Subscript[x, a_],D___]]Subscript[G, \[Psi]][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]->DD[F[A,Subscript[x, b],B]H[C,Subscript[x, b],D]]Subscript[G, \[Psi]][Subscript[x, a],Subscript[x, b],Subscript[t, c]]
//.DD[F_[A___,Subscript[x, d_],B___]H_[C___,Subscript[x, a_],D___]]Subscript[G, \[Psi]][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]->DD[F[A,Subscript[x, d],B]H[C,Subscript[x, b],D]]Subscript[G, \[Psi]][Subscript[x, a],Subscript[x, b],Subscript[t, c]]
/.Subscript[G, \[Chi]][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]Subscript[G, \[Chi]][Subscript[x, b_],Subscript[x, a_],Subscript[t, c_]]->0;

If[OptionValue["SimplifyG\[Psi]"],
terms=terms/.Subscript[G, \[Psi]][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]->Subscript[G, \[Psi]][Subscript[x, b],Subscript[x, b],Subscript[t, c]]
];

Return[terms];
]


(* ::Input::Initialization:: *)
(*OLD*)

ClearAll[DDeatsG];

DDeatsG[exp_]:=Module[{terms,tlist,temp1,i},

If[Head[exp]=!=Times,
Print[Style["NOT A PRODUCT OF TERMS",Red]];
Return[0];
];

(*terms=exp//.DD[Subscript[G, \[Phi]][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]]->-1/\[Gamma]2\[Delta][Subscript[x, a],Subscript[x, b]]\[Delta]t[Subscript[t, c]]//.DD[Subscript[G, \[Chi]][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]]->-\[Delta][Subscript[x, a],Subscript[x, b]]
//.Subscript[G, \[Psi]][A___]\[Delta][Subscript[x, a_],Subscript[x, b_]]/;(!FreeQ[{A},Subscript[x, b]]):>\[Delta][Subscript[x, a],Subscript[x, b]]
//.F_[A___,Subscript[x, a_],B___]\[Delta][Subscript[x, a_],Subscript[x, b_]]->F[A,Subscript[x, b],B]\[Delta][Subscript[x, a],Subscript[x, b]]
/.\[Delta][__]->1;*)

terms=exp//.DD[Subscript[G, \[Phi]][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]]->-(\[Delta][Subscript[x, a],Subscript[x, b],Subscript[t, c]]/\[Gamma]2)//.DD[Subscript[G, \[Chi]][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]]->-\[Delta][Subscript[x, a],Subscript[x, b]]
//.\[Delta][Subscript[x, a_],Subscript[x, b_],C___] F_[A___,Subscript[x, a_],B___]->F[A,Subscript[x, b],B] \[Delta][Subscript[x, a],Subscript[x, b],C]//.\[Delta][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]] Subscript[G, \[Psi]][A___]/;!FreeQ[{A},Subscript[x, b]]&&!FreeQ[{A},Subscript[t, c]]:>\[Delta][Subscript[x, a],Subscript[x, b],Subscript[t, c]]
/.\[Delta][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]->\[Delta][Subscript[x, a],Subscript[x, b]] \[Delta]t[Subscript[t, c]]
/.\[Delta][__]->1;

If[!FreeQ[terms,\[Delta]t],
tlist=Select[List@@terms,Head[#]==\[Delta]t&];
tlist=Union[tlist/.\[Delta]t[Subscript[t, a_]]->a];
];

For[i=Length[tlist],i>=1,i--,
terms=terms/.Subscript[t, a_]/;a>=tlist[[i]]:>Subscript[t, a-1];
];

terms=terms/.\[Delta]t[__]->1/.Subscript[G, \[Psi]][A___]^n_->Subscript[G, \[Psi]][A];

(* Eliminate useless gaps *)
For[i=1,i<=5,i++,
While[(FreeQ[terms,Subscript[x, i]]),
temp1=terms/.Subscript[x, a_]/;(a>i):>Subscript[x, a-1];
If[temp1===terms, Break[],terms=temp1]
];
];(* END OF FOR*)

Return[terms];
];


(* ::Input::Initialization:: *)
(*NEW*)
ClearAll[DDeatsG];

DDeatsG[exp_]:=Module[{terms,tlist,temp1,i},


If[Head[exp]=!=Times,
Print[Style["NOT A PRODUCT OF TERMS",Red]];
Return[0];
];

(*terms=exp//.DD[Subscript[G, \[Phi]][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]]->-1/\[Gamma]2\[Delta][Subscript[x, a],Subscript[x, b]]\[Delta]t[Subscript[t, c]]//.DD[Subscript[G, \[Chi]][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]]->-\[Delta][Subscript[x, a],Subscript[x, b]]
//.Subscript[G, \[Psi]][A___]\[Delta][Subscript[x, a_],Subscript[x, b_]]/;(!FreeQ[{A},Subscript[x, b]]):>\[Delta][Subscript[x, a],Subscript[x, b]]
//.F_[A___,Subscript[x, a_],B___]\[Delta][Subscript[x, a_],Subscript[x, b_]]->F[A,Subscript[x, b],B]\[Delta][Subscript[x, a],Subscript[x, b]]
/.\[Delta][__]->1;*)


terms=exp//.A_. DD[Subscript[G, \[Phi]][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]]:>ReleaseHold[Hold[-((A \[Delta]t[Subscript[t, c]])/\[Gamma]2)/.Subscript[x, b]->Subscript[x, a]]]//.A_. DD[Subscript[G, \[Chi]][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]]:>ReleaseHold[Hold[-A \[Delta]t[Subscript[t, c]]/.Subscript[x, b]->Subscript[x, a]]](*
//.\[Delta][Subscript[x, a_],Subscript[x, b_],C___] F_[A___,Subscript[x, a_],B___]\[Rule]F[A,Subscript[x, b],B] \[Delta][Subscript[x, a],Subscript[x, b],C]//.\[Delta][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]] Subscript[G, \[Psi]][A___]/;!FreeQ[{A},Subscript[x, b]]&&!FreeQ[{A},Subscript[t, c]]\[RuleDelayed]\[Delta][Subscript[x, a],Subscript[x, b],Subscript[t, c]]
/.\[Delta][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]\[Rule]\[Delta][Subscript[x, a],Subscript[x, b]] \[Delta]t[Subscript[t, c]]/.\[Delta][__]->1*);

(* Why do I need this?
If[!FreeQ[terms,\[Delta]t],
tlist=Select[List@@terms,Head[#]==\[Delta]t&];
tlist=Union[tlist/.\[Delta]t[Subscript[t, a_]]->a];
];


Print[terms];
For[i=Length[tlist],i>=1,i--,
terms=terms/.Subscript[t, a_]/;a>=tlist[[i]]:>Subscript[t, a-1];

Print[terms];
];*)

terms=terms/.\[Delta]t[__]->1/.Subscript[G, \[Psi]][A___]^n_->Subscript[G, \[Psi]][A];

(* Eliminate useless gaps *)
For[i=1,i<=5,i++,
While[(FreeQ[terms,Subscript[x, i]]),
temp1=terms/.Subscript[x, a_]/;(a>i):>Subscript[x, a-1];
If[temp1===terms, Break[],terms=temp1]
];
];(* END OF FOR*)

Return[terms];
];


(* ::Input::Initialization:: *)
ClearAll[Skeletonization];

Options[Skeletonization]={"print"->False,"endTime"->4};

Skeletonization[exp_,OptionsPattern[]]:=Module[{temp,temp1,i},
(*temp=exp//.Subscript[G, \[Psi]][a__,Subscript[t, b_]]Subscript[G, \[Psi]][a__,c_]->Subscript[G, \[Psi]][a,Subscript[t, b]+c]/.Subscript[G, \[Psi]][a__,c_/;!FreeQ[c,t]]:>WannaBeDiracDelta[c];*)
temp=exp//.Subscript[G, \[Psi]][a__,Subscript[t, b_]]->DiracDelta[Subscript[t, b]];

If[OptionValue["print"],
Print[Style["\n\t Setting up the integral over time: ",{Blue}],Style[" \n",{Blue}],temp]
];

For[i=OptionValue["endTime"],i>1,i--,
(*If[(!FreeQ[temp,WannaBeDiracDelta[a_/;!FreeQ[a,Subscript[t, i]]]]),

temp=temp/.WannaBeDiracDelta[a_]/;(!FreeQ[a,Subscript[t, i]] ):>DiracDelta[a];
temp=temp//.DiracDelta[a_]DiracDelta[b_]/;(!FreeQ[a,Subscript[t, i]] && !FreeQ[b,Subscript[t, i]]):>WannaBeDiracDelta[a]DiracDelta[b];

temp=Integrate[temp ,{Subscript[t, i],-\[Infinity],\[Infinity]},GenerateConditions->False],

(*ELSE: no WannaBeDiracDelta[a_/;!FreeQ[a,Subscript[t, i]]]*)
Continue[];

];*)
If[(!FreeQ[temp,DiracDelta[a_/;!FreeQ[a,Subscript[t, i]]]]),

temp=temp//.DiracDelta[a_]^n_->DiracDelta[a];

temp=Integrate[temp ,{Subscript[t, i],-\[Infinity],\[Infinity]},GenerateConditions->False],

(*ELSE: no WannaBeDiracDelta[a_/;!FreeQ[a,Subscript[t, i]]]*)
Continue[];

];
];(* END OF FOR*)

If[OptionValue["print"],
Print[Style["\n\t After integration: ",{Blue}],Style[" \n",{Blue}],temp]
];


temp=Replace[temp,{ G_[a__,-Subscript[t, b_]]:> G[a,Subscript[t, b]]},{1,2}];

If[FreeQ[temp,Subscript[G, \[Phi]][__,Subscript[t, a_]/;(a>1)],{0,1}],

temp=Replace[temp,{ \[Phi]s[a_,Subscript[t, _]]-> \[Phi]s[a,Subscript[t, 2]], \[Psi]s[a_,Subscript[t, _]]-> \[Psi]s[a,Subscript[t, 2]]},{1,2}];,

(* ELSE *)
temp=Replace[temp,{ G_[a__,Subscript[t, _]]/;FreeQ[{a},Subscript[x, 0]]:> G[a,Subscript[t, 2]]},{1,2}]/.{ \[Phi]s[a_,Subscript[t, _]]-> \[Phi]s[a,Subscript[t, 3]], \[Psi]s[a_,Subscript[t, _]]-> \[Psi]s[a,Subscript[t, 3]]};

];

(* Eliminate useless gaps *)
For[i=1,i<=5,i++,
While[(FreeQ[temp,Subscript[x, i]]),
temp1=temp/.Subscript[x, a_]/;(a>i):>Subscript[x, a-1];
If[temp1===temp, Break[],temp=temp1]
];
];(* END OF FOR*)

(*For[i=1,i<=OptionValue["endTime"],i++,
If[(FreeQ[temp,Subscript[x, i]]),
temp=temp/.Subscript[x, a_]/;(a>i):>Subscript[x, a-1];
];
];(* END OF FOR*)*)


Return[temp];
];


(* ::Input::Initialization:: *)
ClearAll[ToMomentumSpace];
Options[ToMomentumSpace]={"print"->False,"m\[Chi]"->m2\[Chi],"m\[Phi]"->m2\[Phi],"amputateLegs"->{\[Chi]s},"origins"->False};

ToMomentumSpace[exp_,OptionsPattern[]]:=Module[{terms,pureProp,externalLegs,weight,momentumExp,i,j,m2\[Chi],m2\[Phi],ptot},
ptot=0;
m2\[Chi]=OptionValue["m\[Chi]"];
m2\[Phi]=OptionValue["m\[Phi]"];

If[OptionValue["print"],
Print[Style["\t Mass values: ",{Blue}],"m\[Chi] = ",OptionValue["m\[Chi]"],", m\[Phi] = ",OptionValue["m\[Phi]"] ]
];


(*terms=exp//.F_[A___,Subscript[x, a_],B___]Subscript[G, \[Psi]][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]:>F[A,Subscript[x, b],B]Subscript[G, \[Psi]][Subscript[x, a],Subscript[x, b],Subscript[t, c]]
//.DD[F_[A___,Subscript[x, a_],B___]]Subscript[G, \[Psi]][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]:>DD[F[A,Subscript[x, b],B]]Subscript[G, \[Psi]][Subscript[x, a],Subscript[x, b],Subscript[t, c]]
//.DD[F_[A___,Subscript[x, a_],B___]H_[C___,Subscript[x, a_],D___]]Subscript[G, \[Psi]][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]:>DD[F[A,Subscript[x, b],B]H[C,Subscript[x, b],D]]Subscript[G, \[Psi]][Subscript[x, a],Subscript[x, b],Subscript[t, c]]
//.DD[F_[A___,Subscript[x, d_],B___]H_[C___,Subscript[x, a_],D___]]Subscript[G, \[Psi]][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]:>DD[F[A,Subscript[x, d],B]H[C,Subscript[x, b],D]]Subscript[G, \[Psi]][Subscript[x, a],Subscript[x, b],Subscript[t, c]]
/.Subscript[G, \[Psi]][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]:>Subscript[G, \[Psi]][Subscript[x, b],Subscript[x, b],Subscript[t, c]];
terms=List @@ (terms);*)
terms=List@@(exp);

pureProp=DeleteElements[terms,{-1,g,\!\(\*OverscriptBox[\(g\), \(~\)]\),Subscript[g, \[Gamma]],\[Gamma],\[Gamma]1,\[Gamma]2,-g,-\!\(\*OverscriptBox[\(g\), \(~\)]\),-Subscript[g, \[Gamma]],-\[Gamma],-\[Gamma]1,-\[Gamma]2,g^n_?NumericQ,\!\(\*OverscriptBox[\(g\), \(~\)]\)^n_?NumericQ,Subscript[g, \[Gamma]]^n_?NumericQ,\[Gamma]^n_?NumericQ,\[Gamma]1^n_?NumericQ,\[Gamma]2^n_?NumericQ}];

externalLegs= DeleteElements[pureProp,{Subscript[G, _][___],DD[Subscript[G, _][___]],DD[F_[___]Subscript[G, _][___]]}];

weight=Times@@DeleteElements[terms,pureProp];

For[i=1, i<=Length[pureProp],i++,
pureProp[[i]]=pureProp[[i]]/.{Subscript[F_, \[Phi]]^n_[Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]:>(1/(\[Gamma]2(s[Subscript[p, i]]+m2\[Phi])))^n \[Delta][Subscript[p, i],Subscript[x, a],Subscript[t, c]]\[Delta][-Subscript[p, i],Subscript[x, b],Subscript[t, c-1]],
Subscript[F_, \[Phi]][Subscript[x, a_],Subscript[x, 0],Subscript[t, c_]]:>\[Phi][k]\[Delta][k,Subscript[x, a],Subscript[t, c]],
Subscript[F_, \[Phi]][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]:>1/(\[Gamma]2(s[Subscript[p, i]]+m2\[Phi])) \[Delta][Subscript[p, i],Subscript[x, a],Subscript[t, c]]\[Delta][-Subscript[p, i],Subscript[x, b],Subscript[t, c-1]],

Subscript[F_, \[Chi]]^n_[Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]:>(1/(s[Subscript[p, i]]+m2\[Chi]))^n \[Delta][Subscript[p, i],Subscript[x, a],Subscript[t, c]]\[Delta][-Subscript[p, i],Subscript[x, b],Subscript[t, c]],
Subscript[F_, \[Chi]][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]:>1/(s[Subscript[p, i]]+m2\[Chi]) \[Delta][Subscript[p, i],Subscript[x, a],Subscript[t, c]]\[Delta][-Subscript[p, i],Subscript[x, b],Subscript[t, c]],

Subscript[F_, \[Psi]]^n_[Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]:>\[Delta][Subscript[p, i],Subscript[x, a],Subscript[t, c]]\[Delta][-Subscript[p, i],Subscript[x, b],Subscript[t, c-1]],
Subscript[F_, \[Psi]][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]:>\[Delta][Subscript[p, i],Subscript[x, a],Subscript[t, c]]\[Delta][-Subscript[p, i],Subscript[x, b],Subscript[t, c-1]],

\[Chi]s[Subscript[x, a_],___,Subscript[t, c_]]:>\[Chi]s[Subscript[p, i]]\[Delta][Subscript[p, i],Subscript[x, a],Subscript[t, c]],
\[Phi]s[Subscript[x, a_],Subscript[t, c_]]:>\[Phi]s[Subscript[p, i]]\[Delta][Subscript[p, i],Subscript[x, a],Subscript[t, c-1]],
\[Psi]s[Subscript[x, a_],Subscript[t, c_]]:>\[Psi]s[Subscript[p, i]]\[Delta][Subscript[p, i],Subscript[x, a],Subscript[t, c-1]],

DD[\[Phi]s[Subscript[x, a_],Subscript[t, c_]] Subscript[F_, \[Chi]][Subscript[x, d_],Subscript[x, b_],Subscript[t, e_]]]:>-s[Subscript[p, i]+Subscript[q, i]]\[Phi]s[Subscript[p, i]]\[Delta][Subscript[p, i],Subscript[x, a],Subscript[t, c-1]] 1/(s[Subscript[q, i]]+m2\[Chi]) \[Delta][Subscript[q, i],Subscript[x, d],Subscript[t, e]]\[Delta][-Subscript[q, i],Subscript[x, b],Subscript[t, e]],
DD[Subscript[F_, \[Phi]][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]\[Chi]s[Subscript[x, d_],___,Subscript[t, e_]]]:>-s[Subscript[p, i]+Subscript[q, i]]\[Chi]s[Subscript[q, i]]\[Delta][Subscript[q, i],Subscript[x, d],Subscript[t, e]] 1/(\[Gamma]2(s[Subscript[p, i]]+m2\[Phi])) \[Delta][Subscript[p, i],Subscript[x, a],Subscript[t, c]]\[Delta][-Subscript[p, i],Subscript[x, b],Subscript[t, c-1]],
DD[\[Chi]s[Subscript[x, a_],___,Subscript[t, c_]]]:>-s[Subscript[p, i]]\[Chi]s[Subscript[p, i]]\[Delta][Subscript[p, i],Subscript[x, a],Subscript[t, c]],

DD[Subscript[F_, \[Chi]][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]]:>-s[Subscript[p, i]] 1/(s[Subscript[p, i]]+m2\[Chi]) \[Delta][Subscript[p, i],Subscript[x, a],Subscript[t, c]]\[Delta][-Subscript[p, i],Subscript[x, b],Subscript[t, c]]};
ptot+=Subscript[p, i];
];


momentumExp = Times@@pureProp;


For[i=1, i<=Length[pureProp],i++,
(*If[OptionValue["origins"],
If[!FreeQ[momentumExp,\[Chi]s[Subscript[p, i]]],
Print[]
]
];*)
If[!FreeQ[momentumExp,Subscript[q, i]],
ptot+=Subscript[q, i]];
];

(*momentumExp=momentumExp*WannaBeDiracDelta[ptot+k];*)

If[OptionValue["print"],
Print[Style["\n\t Expression in momentum space, not yet integrated:\n",{Blue}],momentumExp ]
];


(* VERTEX MOMENTUM CONSERVATION *)

momentumExp=momentumExp//.\[Delta][ Subscript[p, b_],Subscript[x, c_],Subscript[t, d_]]\[Delta][-Subscript[p, b_],Subscript[x, c_],Subscript[t, d_]]:>\[Delta][0,Subscript[x, c],Subscript[t, d]]//.\[Delta][ Subscript[p, b_],Subscript[x, c_],Subscript[t, d_]]\[Delta][a_,Subscript[x, c_],Subscript[t, d_]]:>\[Delta][a+ Subscript[p, b],Subscript[x, c],Subscript[t, d]]//.\[Delta][-Subscript[p, b_],Subscript[x, c_],Subscript[t, d_]]\[Delta][a_,Subscript[x, c_],Subscript[t, d_]]:>\[Delta][a- Subscript[p, b],Subscript[x, c],Subscript[t, d]];
momentumExp=momentumExp//.\[Delta][a_,Subscript[x, c_],Subscript[t, d_]]\[Delta][ Subscript[q, b_],Subscript[x, c_],Subscript[t, d_]]:>\[Delta][a+ Subscript[q, b],Subscript[x, c],Subscript[t, d]]//.\[Delta][a_,Subscript[x, c_],Subscript[t, d_]]\[Delta][- Subscript[q, b_],Subscript[x, c_],Subscript[t, d_]]:>\[Delta][a- Subscript[q, b],Subscript[x, c],Subscript[t, d]];
momentumExp=momentumExp/.\[Delta][a_+Subscript[p, b_],A___]:>DiracDelta[a+ Subscript[p, b]](*\[DifferentialD]Subscript[p, b]*)/.\[Delta][a_-Subscript[p, b_],A___]:>DiracDelta[a- Subscript[p, b]](*\[DifferentialD]Subscript[p, b]*);

If[OptionValue["print"],
Print[Style["\n\t Setting up momentum conservation\n",{Blue}],momentumExp ]
];

(* Attempt to make everything faster by reducing the replacements: instead of using \[DifferentialD]p, I just look inside DiracDelta *)
(*While[!FreeQ[momentumExp,\[DifferentialD]Subscript[p, a_]],
For[i=1, i<=Length[pureProp],i++,
If[!FreeQ[momentumExp,\[DifferentialD]Subscript[p, i]],
If[FreeQ[momentumExp,DiracDelta[Subscript[p, i]+A__]DiracDelta[Subscript[p, i]+B__]] && FreeQ[momentumExp,DiracDelta[-Subscript[p, i]+A__]DiracDelta[Subscript[p, i]+B__]] &&FreeQ[momentumExp,DiracDelta[-Subscript[p, i]+A__]DiracDelta[-Subscript[p, i]+B__]]  ,
momentumExp=Integrate[momentumExp /.\[DifferentialD]Subscript[p, i]->1,{Subscript[p, i],-\[Infinity],\[Infinity]},GenerateConditions->False],
(*ELSE*)
Continue[];
];
];
];
];*)
For[i=1, i<=Length[pureProp],i++,
If[(!FreeQ[momentumExp,DiracDelta[a_/;!FreeQ[a,Subscript[p, i]]]]) && (FreeQ[momentumExp,DiracDelta[c_/;!FreeQ[c,Subscript[p, i]]]*DiracDelta[b_/;!FreeQ[b,Subscript[p, i]]] ])  ,

momentumExp=Integrate[momentumExp ,{Subscript[p, i],-\[Infinity],\[Infinity]},GenerateConditions->False],
(*ELSE*)
Continue[];

];
];

If[OptionValue["print"],
Print[Style["\n\t Implementing momentum conservation at vertices\n",{Blue}],momentumExp ]
];
(*
(* TOTAL MOMENTUM CONSERVATION *)
momentumExp=momentumExp/.WannaBeDiracDelta[a_+Subscript[p, b_]]:>DiracDelta[a+Subscript[p, b]]\[DifferentialD]Subscript[p, b];

If[OptionValue["print"],
Print[Style["\n\t Setting up TOTAL momentum conservation\n",{Blue}],momentumExp ]
];

For[i=1, i<=Length[pureProp],i++,
If[!FreeQ[momentumExp,\[DifferentialD]Subscript[p, i]],
momentumExp=Integrate[momentumExp /.\[DifferentialD]Subscript[p, i]->1,{Subscript[p, i],-\[Infinity],\[Infinity]},GenerateConditions->False];
]
];

If[OptionValue["print"],
Print[Style["\n\t Implementing TOTAL momentum conservation\n",{Blue}],momentumExp ]
];
*)

(* MOMENTA REORDERING *)

j=Length[pureProp];

For[i=1, i<=Length[externalLegs],i++,
If[FreeQ[momentumExp,Subscript[p, i]],
momentumExp=momentumExp/.Subscript[q, i]->Subscript[p, i];
];
];

For[i=1, i<=Length[externalLegs],i++,
While[FreeQ[momentumExp,Subscript[p, i]],
momentumExp=momentumExp/.Subscript[p, j]->Subscript[p, i];
j--;
];
];

If[OptionValue["print"],
Print[Style["\n\t Reordering momenta\n",{Blue}],momentumExp ]
];

(* LEG AMPUTATION *)
If[Length[OptionValue["amputateLegs"]]=!=0,
For[i=1, i<=Length[OptionValue["amputateLegs"]],i++,

(* Attempt to make everything faster by reducing the replacements: instead of using \[DifferentialD]p, I just look inside WannaBeDiracDelta *)
(*momentumExp=momentumExp/.{OptionValue["amputateLegs"][[i]][a_+Subscript[p, b_]]:>OptionValue["amputateLegs"][[i]][a+Subscript[p, b]]WannaBeDiracDelta[a+Subscript[p, b]]\[DifferentialD]Subscript[p, b],
OptionValue["amputateLegs"][[i]][a_-Subscript[p, b_]]:>OptionValue["amputateLegs"][[i]][a-Subscript[p, b]]WannaBeDiracDelta[a-Subscript[p, b]]\[DifferentialD]Subscript[p, b]}
/.OptionValue["amputateLegs"][[i]][Subscript[p, b_]]:>OptionValue["amputateLegs"][[i]][Subscript[p, b]]WannaBeDiracDelta[Subscript[p, b]]\[DifferentialD]Subscript[p, b];


momentumExp=momentumExp/.WannaBeDiracDelta[a_+c_ Subscript[p, b_]+d_ Subscript[p, e_]](\[DifferentialD]Subscript[p, b_])^2:> WannaBeDiracDelta[a+ c Subscript[p, b]+d Subscript[p, e]]\[DifferentialD]Subscript[p, e] \[DifferentialD]Subscript[p, b]
/.WannaBeDiracDelta[c_ Subscript[p, b_]+d_ Subscript[p, e_]](\[DifferentialD]Subscript[p, b_])^2:> WannaBeDiracDelta[c Subscript[p, b]+d Subscript[p, e]]\[DifferentialD]Subscript[p, e] \[DifferentialD]Subscript[p, b]
/.WannaBeDiracDelta[a_+ Subscript[p, b_]+d_ Subscript[p, e_]](\[DifferentialD]Subscript[p, b_])^2:> WannaBeDiracDelta[a+ Subscript[p, b]+ d Subscript[p, e]]\[DifferentialD]Subscript[p, e] \[DifferentialD]Subscript[p, b]
/.WannaBeDiracDelta[ Subscript[p, b_]+d_ Subscript[p, e_]](\[DifferentialD]Subscript[p, b_])^2:> WannaBeDiracDelta[ Subscript[p, b]+d Subscript[p, e]]\[DifferentialD]Subscript[p, e] \[DifferentialD]Subscript[p, b]
/.WannaBeDiracDelta[a_+ d_ Subscript[p, b_]+ Subscript[p, e_]](\[DifferentialD]Subscript[p, b_])^2:> WannaBeDiracDelta[a+ d Subscript[p, b]+  Subscript[p, e]]\[DifferentialD]Subscript[p, e] \[DifferentialD]Subscript[p, b]
/.WannaBeDiracDelta[ d_ Subscript[p, b_]+ Subscript[p, e_]](\[DifferentialD]Subscript[p, b_])^2:> WannaBeDiracDelta[d Subscript[p, b]+ Subscript[p, e]]\[DifferentialD]Subscript[p, e] \[DifferentialD]Subscript[p, b]
/.WannaBeDiracDelta[a_+ Subscript[p, b_]+ Subscript[p, e_]](\[DifferentialD]Subscript[p, b_])^2:> WannaBeDiracDelta[a+  Subscript[p, b]+  Subscript[p, e]]\[DifferentialD]Subscript[p, e] \[DifferentialD]Subscript[p, b]
/.WannaBeDiracDelta[  Subscript[p, b_]+ Subscript[p, e_]](\[DifferentialD]Subscript[p, b_])^2:> WannaBeDiracDelta[ Subscript[p, b]+ Subscript[p, e]]\[DifferentialD]Subscript[p, e] \[DifferentialD]Subscript[p, b];*)

momentumExp=momentumExp/.OptionValue["amputateLegs"][[i]][a_/;!FreeQ[a,p]]:>OptionValue["amputateLegs"][[i]][a]WannaBeDiracDelta[a];
(*{OptionValue["amputateLegs"][[i]][a_+Subscript[p, b_]]:>OptionValue["amputateLegs"][[i]][a+Subscript[p, b]]WannaBeDiracDelta[a+Subscript[p, b]],
OptionValue["amputateLegs"][[i]][a_-Subscript[p, b_]]:>OptionValue["amputateLegs"][[i]][a-Subscript[p, b]]WannaBeDiracDelta[a-Subscript[p, b]]}
/.OptionValue["amputateLegs"][[i]][Subscript[p, b_]]:>OptionValue["amputateLegs"][[i]][Subscript[p, b]]WannaBeDiracDelta[Subscript[p, b]]*)


If[OptionValue["print"],
Print[Style["\n\t Setting up the amputation of the field ",{Blue}],Style[OptionValue["amputateLegs"][[i]],{Blue}],"\n",momentumExp,"\n"];
];
];(* END OF FOR OVER AMPUTATE LEGS*)

For[j=1, j<=Length[pureProp],j++,
(*If[!FreeQ[momentumExp,\[DifferentialD]Subscript[p, j]],

momentumExp=momentumExp /.{WannaBeDiracDelta[a_]/;(!FreeQ[a,Subscript[p, j]] ):>DiracDelta[a],\[DifferentialD]Subscript[p, j]->1}//.DiracDelta[a_]DiracDelta[b_]/;(!FreeQ[a,Subscript[p, j]] && !FreeQ[b,Subscript[p, j]]):>WannaBeDiracDelta[a]DiracDelta[b];
If[FreeQ[Numerator[momentumExp],Subscript[p, j]],
(* TRUE: Numerator[momentumExp] is Free of Subscript[p, j]: *)
Continue[],
(* FALSE: Numerator[momentumExp] is NOT Free of Subscript[p, j]: *)
momentumExp=Integrate[momentumExp,{Subscript[p, j],-\[Infinity],\[Infinity]},GenerateConditions->False];
];


If[OptionValue["print"],
Print[Style["\n\t Integration over ",{Blue}],Style[\[DifferentialD]Subscript[p, j],{Blue}],Style[" \n",{Blue}],momentumExp ]
];

];*)

If[!FreeQ[momentumExp,WannaBeDiracDelta[a_/;!FreeQ[a,Subscript[p, j]]]],

momentumExp=momentumExp /.{WannaBeDiracDelta[a_]/;(!FreeQ[a,Subscript[p, j]] ):>DiracDelta[a]}//.DiracDelta[a_]DiracDelta[b_]/;(!FreeQ[a,Subscript[p, j]] && !FreeQ[b,Subscript[p, j]]):>WannaBeDiracDelta[a]DiracDelta[b];
momentumExp=Integrate[momentumExp,{Subscript[p, j],-\[Infinity],\[Infinity]},GenerateConditions->False];

];


];(* END OF FOR OVER MOMENTA *)
];(* END OF IF OVER AMPUTATION*)


Return[momentumExp*weight];
]


(* ::Input::Initialization:: *)
ClearAll[OnePI];

Options[OnePI]={"print"->False,"print-onePIlist"->False};

OnePI[exp_,OptionsPattern[]]:=Module[{terms,dummy,temp,i,j,onePIlist={}},

If[OptionValue["print"],DeleteFile[LogFile]];  (*Place at the top of the notebook*)

terms =DeleteElements[ List@@(exp+dummy),{dummy}];
terms=terms/.{-1->1,\[Gamma]->1,\[Gamma]2->1,\!\(\*OverscriptBox[\(g\), \(~\)]\)->1,Subscript[g, \[Gamma]]->1,\[Gamma]->1,\[Phi]s[__]->1,\[Psi]s[__]->1,\[Chi]s[__]->1,DD[A_]->A};

terms=terms/.{Subscript[G, \[Chi]][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]:>G[{b,c},{a,c}],
Subscript[G, \[Phi]][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]:>Subscript[G, \[Phi]][{b,c-1},{a,c}],
Subscript[G, \[Psi]][Subscript[x, a_],Subscript[x, b_],Subscript[t, c_]]:>G[{b,c-1},{b,c}]};

terms=Apply[List, terms,1];

If[OptionValue["print"],LogMessage[{terms}]];

For[i=1,i<=Length[terms] ,i++,

If[OptionValue["print"],LogMessage[{"Considering the term #",i}]];

AppendTo[onePIlist,True];

j=1;

While[j<=Length[terms[[i]]]&& onePIlist[[i]],

If[Head[terms[[i,j]]]===Subscript[G, \[Phi]],

temp=Times@@(terms[[i]]/.terms[[i,j]]->Subscript[G, \[Phi]][terms[[i,j]][[2]]]);

If[OptionValue["print"],LogMessage[{"Removing ",terms[[i,j]],":\n",temp}]];

temp=temp//.F_[a___]H_[b___]/;(!FreeQ[F,G]&&!FreeQ[H,G]&&(Intersection [{a},{b}])=!={}):>G[Level[Union[{a},{b}],1,Hold]//ReleaseHold];

If[Head[temp]===G,
(*TRUE: 1PI*)
If[OptionValue["print"],LogMessage[{temp,"\n"}]];

j++;
Continue[],
(*FALSE: non-1PI*)
If[OptionValue["print"],LogMessage[{temp,"\n"}]];

onePIlist[[i]]=False;
];(*End of If on the 1PI check*)

];(*End of If on Subscript[G, \[Phi]] check*)

j++;
];(*End of While*)

];(*End of For*)


(*Print[terms];*)

terms=Pick[DeleteElements[ List@@(exp+dummy),{dummy}],onePIlist];

If[OptionValue["print"] || OptionValue["print-onePIlist"],LogMessage[{onePIlist,"\n"}]];

If[OptionValue["print-onePIlist"],Print[onePIlist,"\n"]];

If[OptionValue["print"],SystemOpen[LogFile]];

Return[terms];
];


(* ::Input::Initialization:: *)
ClearAll[pOperation];

pOperation[exp_]:=Module[{terms,dummy,tlist,i,endTime,temp1},

terms=exp;

If[Head[terms]=!=Times,
Print[Style["NOT A PRODUCT OF TERMS",Red]];
Return[0];
];

terms=terms//.Subscript[G, \[Chi]][a_,b_,Subscript[t, c_]]Subscript[G, \[Phi]][d_,b_,Subscript[t, e_]]/;(e-c==1):>Subscript[G, \[Chi]][a,b,Subscript[t, c]]Subscript[G, \[Phi]][d,a,Subscript[t, e]]
//.Subscript[G, \[Chi]][a_,b_,Subscript[t, c_]]\[Phi]s[b_,Subscript[t, e_]]/;(e-c==1):> Subscript[G, \[Chi]][a,b,Subscript[t, c]]\[Phi]s[a,Subscript[t, e]];

(*If[!FreeQ[terms,\[Delta]t],
tlist=Select[List@@terms,Head[#]==\[Delta]t&];
tlist=Union[tlist/.\[Delta]t[Subscript[t, a_]]->a];
];

For[i=1,i<=Length[tlist],i++,
terms=terms/.Subscript[t, a_]/;a>=tlist[[i]]:>Subscript[t, a+0.99999];
];

terms=terms/.\[Delta]t[__]->1;

endTime=Select[List@@terms,Head[#]==\[Phi]s&];
endTime=Plus@@(endTime/.\[Phi]s[_,Subscript[t, a_]]->a);

(* Eliminate useless gaps *)
For[i=1,i<=endTime,i++,
While[(FreeQ[terms,Subscript[t, a_]/;IntegerPart[a]==i]),
temp1=terms/.Subscript[t, a_]/;(a>i):>Subscript[t, a-0.99999];
If[temp1===terms, Break[],terms=temp1]
];
];(* END OF FOR*)
*)
Return[terms];
];


(* ::Input::Initialization:: *)
ClearAll[pOperation];

pOperation[exp_]:=Module[{terms,dummy,tlist,i,endTime,temp1},

terms=exp;

If[Head[terms]=!=Times,
Print[Style["NOT A PRODUCT OF TERMS",Red]];
Return[0];
];

terms=terms//.Subscript[G, \[Chi]][a_,b_,Subscript[t, c_]]Subscript[G, \[Phi]][d_,b_,Subscript[t, e_]]/;(e-c==1):>Subscript[G, \[Phi]][a,b,Subscript[t, c+0.0000001]]Subscript[G, \[Phi]][d,a,Subscript[t, e]]\[Delta]t[Subscript[t, c]]
(*//.Subscript[G, \[Chi]][a_,b_,Subscript[t, c_]]\[Phi]s[b_,Subscript[t, e_]]/;(e-c==1):>  Subscript[G, \[Phi]][a,b,Subscript[t, c+0.0000001]]\[Phi]s[a,Subscript[t, e]]\[Delta]t[Subscript[t, c]]*);

If[!FreeQ[terms,\[Delta]t],
tlist=Select[List@@terms,Head[#]==\[Delta]t&];
tlist=Union[tlist/.\[Delta]t[Subscript[t, a_]]->a];
];


For[i=1,i<=Length[tlist],i++,
terms=terms/.Subscript[t, a_]/;a>tlist[[i]]:>Subscript[t, a+1];
];

terms=terms/.\[Delta]t[__]->1;

endTime=Select[List@@terms,Head[#]==\[Phi]s&];
endTime=Plus@@(endTime/.\[Phi]s[_,Subscript[t, a_]]->a);

(* Eliminate useless gaps *)
For[i=1,i<=endTime,i++,
While[(FreeQ[terms,Subscript[t, a_]/;Round[a]==i]),
temp1=terms/.Subscript[t, a_]/;(a>i):>Subscript[t, a-1];
If[temp1===terms, Break[],terms=temp1]
];
];(* END OF FOR*)

Return[terms];
];


(* ::Input::Initialization:: *)
ClearAll[pOperation];

pOperation[exp_Plus]:=pOperation/@(exp);
pOperation[exp_List]:=pOperation/@(exp);

pOperation[exp_Times]:=Module[{terms,dummy,tlist,i,endTime,temp1,s},

terms=exp;

If[Head[terms]=!=Times,
Print[Style["NOT A PRODUCT OF TERMS",Red]];
Return[Abort[]];
];

While[!FreeQ[terms,Subscript[G, \[Chi]]],

temp1=terms/.Subscript[G, \[Phi]][b_,x_,Subscript[t, c_]]Subscript[G, \[Chi]][a_,b_,Subscript[t, c_]]Subscript[G, \[Phi]][d_,b_,Subscript[t, e_]]\[Psi]s[b_,Subscript[t, e_]]/;(e-c==1):>Subscript[G, \[Phi]][b,x,Subscript[t, c-0.001]]Subscript[G, \[Phi]][a,b,Subscript[t, c]]Subscript[PlaceHolderG, \[Psi]][a,a,c]Subscript[PlaceHolderG, \[Psi]][a,a,e] Subscript[G, \[Phi]][d,a,Subscript[t, e]]\[Psi]s[b,e]\[Delta]t[Subscript[t, c]];

If[temp1==terms,
temp1=terms/.Subscript[G, \[Phi]][b_,x_,Subscript[t, c_]]Subscript[G, \[Chi]][a_,b_,Subscript[t, c_]]Subscript[G, \[Phi]][d_,b_,Subscript[t, e_]]/;(e-c==1):> Subscript[G, \[Phi]][b,x,Subscript[t, c-0.001]]Subscript[G, \[Phi]][a,b,Subscript[t, c]]Subscript[G, \[Phi]][d,a,Subscript[t, e]]Subscript[PlaceHolderG, \[Psi]][a,a,c]Subscript[PlaceHolderG, \[Psi]][a,a,e] \[Delta]t[Subscript[t, c]];

If[temp1==terms,
temp1=terms/.Subscript[G, \[Phi]][b_,d_,Subscript[t, c_]]Subscript[G, \[Chi]][a_,b_,Subscript[t, c_]]\[Phi]s[b_,Subscript[t, e_]] \[Psi]s[b_,Subscript[t, e_]]/;(e-c==1):> Subscript[G, \[Phi]][b,d,Subscript[t, c-0.001]] Subscript[G, \[Phi]][a,b,Subscript[t, c]]\[Phi]s[a,Subscript[t, e]] \[Psi]s[b,e]Subscript[PlaceHolderG, \[Psi]][a,a,c]Subscript[PlaceHolderG, \[Psi]][a,a,e] \[Delta]t[Subscript[t, c]];

If[temp1==terms,
temp1=terms/.Subscript[G, \[Phi]][b_,d_,Subscript[t, c_]]Subscript[G, \[Chi]][a_,b_,Subscript[t, c_]]\[Phi]s[b_,Subscript[t, e_]]/;(e-c==1):> Subscript[G, \[Phi]][b,d,Subscript[t, c-0.001]] Subscript[G, \[Phi]][a,b,Subscript[t, c]]\[Phi]s[a,Subscript[t, e]]Subscript[PlaceHolderG, \[Psi]][a,a,c]Subscript[PlaceHolderG, \[Psi]][a,a,e] \[Delta]t[Subscript[t, c]];
];(* Innermost If*)

]; (* Mediummost If*)

];(* Outermost If *)

terms=temp1;

tlist=Select[List@@terms,Head[#]==\[Delta]t&];
tlist=Union[tlist/.\[Delta]t[Subscript[t, a_]]->a];

terms=terms/.Subscript[t, a_]/;a>=tlist[[1]]:>Subscript[t, a+1];

terms=terms/.Subscript[G, \[Psi]][A__,Subscript[t, a_]]/;a==tlist[[1]]+1:>Subscript[G, \[Psi]][A,Subscript[t, a-1]];
terms=terms/.Subscript[G, \[Psi]][A__,Subscript[t, a_]]/;a==tlist[[1]]+2:>Subscript[G, \[Psi]][A,Subscript[t, a-1]];

terms=terms/.\[Delta]t[__]->1;

];(*End of While*)


endTime=Select[List@@terms,Head[#]==\[Phi]s&];
endTime=Plus@@(endTime/.\[Phi]s[_,Subscript[t, a_]]->a);

(* Eliminate useless gaps *)
For[i=1,i<=endTime,i++,
While[(FreeQ[terms,Subscript[t, a_]/;Round[a]==i]),
temp1=terms/.Subscript[t, a_]/;(Round[a]>i):>Subscript[t, a-1];
If[temp1===terms, Break[],terms=temp1]
];
];(* END OF FOR*)

terms=terms/.\[Psi]s[a_,b_]->\[Psi]s[a,Subscript[t, b]]/.Subscript[PlaceHolderG, \[Psi]][a_,a_,e_] ->Subscript[G, \[Psi]][a,a,Subscript[t, e]];
terms=terms/.Subscript[G, \[Psi]][A__,Subscript[t, a_]]/;(!FreeQ[terms,Subscript[G, \[Psi]][A,Subscript[t, b_/;b>a]]]):>Subscript[G, \[Psi]][A,Subscript[t, a]]Subscript[G, \[Psi]][A,Subscript[t, a+1]];
terms=terms/.Subscript[G, \[Psi]][A__,Subscript[t, a_]]/;(!FreeQ[terms,Subscript[G, \[Psi]][A,Subscript[t, b_/;b>a]]]):>Subscript[G, \[Psi]][A,Subscript[t, a]]Subscript[G, \[Psi]][A,Subscript[t, a+1]];

Return[terms];
];


(* ::Input::Initialization:: *)
ClearAll[DiagramList];

DiagramList[exp_List]:=DiagramList[Sort/@exp];

(* 1-Loop *)
DiagramList[{{Subscript[x, 1],Subscript[x, 2]},{Subscript[x, 1],Subscript[x, 2]}}]="I1";

(* 2-Loop *)
(DiagramList[#]="3pt2loopamp1")&/@(Flatten[Table[Permutations[Sort/@{{Subscript[x, Mod[a,3]+1],Subscript[x, Mod[a+1,3]+1]},{Subscript[x, Mod[#,3]&@(a+1)+1],Subscript[x, Mod[#,3]&@(a+2)+1]},{Subscript[x, Mod[#,3]&@(a+2)+1],Subscript[x, Mod[#,3]&@(a+1)+1]},{Subscript[x, Mod[#,3]&@(a+1)+1],Subscript[x, Mod[a,3]+1]}}],{a,1,3}],1]);

(DiagramList[#]="3pt2loopamp2")&/@(Flatten[Table[Permutations[Sort/@{{Subscript[x, Mod[a,3]+1],Subscript[x, Mod[a+1,3]+1]},{Subscript[x, Mod[#,3]&@(a+1)+1],Subscript[x, Mod[#,3]&@(a+2)+1]},{Subscript[x, Mod[#,3]&@(a+2)+1],Subscript[x, Mod[#,3]&@(a)+1]},{Subscript[x, Mod[#,3]&@(a+1)+1],Subscript[x, Mod[a,3]+1]}}],{a,1,3}],1]);

(* 3-Loop *)
(DiagramList[#]:="3pt3loopamp1")&/@(Flatten[Table[
p=Sort/@{{Subscript[x, Mod[#,4]&@(a)+1],Subscript[x, Mod[#,4]&@(a+1)+1]},{Subscript[x, Mod[#,4]&@(a+1)+1],Subscript[x, Mod[#,4]&@(a+2)+1]},{Subscript[x, Mod[#,4]&@(a+2)+1],Subscript[x, Mod[#,4]&@(a+3)+1]},{Subscript[x, Mod[#,4]&@(a+3)+1],Subscript[x, Mod[#,4]&@(a+2)+1]},{Subscript[x, Mod[#,4]&@(a+2)+1],Subscript[x, Mod[#,4]&@(a+1)+1]},{Subscript[x, Mod[#,4]&@(a+1)+1],Subscript[x, Mod[#,4]&@(a)+1]}};
q=Sort/@(p/.Subscript[x, b_]->Subscript[x, Mod[#,4]&@(-b)+1]);
r=Sort/@(p/.Subscript[x, 1]->y/.Subscript[x, 2]->Subscript[x, 1]/.y->Subscript[x, 2]);
s=Sort/@(p/.Subscript[x, 1]->y/.Subscript[x, 4]->Subscript[x, 1]/.y->Subscript[x, 4]);
Union[Permutations[p],Permutations[q],Permutations[r],Permutations[s]]
,{a,1,4}],1]);


(DiagramList[#]:="3pt3loopamp2")&/@(Flatten[Table[
p=Sort/@{{Subscript[x, Mod[#,4]&@(a)+1],Subscript[x, Mod[#,4]&@(a+1)+1]},{Subscript[x, Mod[#,4]&@(a+1)+1],Subscript[x, Mod[#,4]&@(a+2)+1]},{Subscript[x, Mod[#,4]&@(a+2)+1],Subscript[x, Mod[#,4]&@(a+3)+1]},{Subscript[x, Mod[#,4]&@(a+3)+1],Subscript[x, Mod[#,4]&@(a)+1]},{Subscript[x, Mod[#,4]&@(a)+1],Subscript[x, Mod[#,4]&@(a+1)+1]},{Subscript[x, Mod[#,4]&@(a+1)+1],Subscript[x, Mod[#,4]&@(a+2)+1]}};
q=Sort/@(p/.Subscript[x, b_]->Subscript[x, Mod[#,4]&@(-b)+1]);
r=Sort/@(p/.Subscript[x, 1]->y/.Subscript[x, 2]->Subscript[x, 1]/.y->Subscript[x, 2]);
s=Sort/@(p/.Subscript[x, 1]->y/.Subscript[x, 4]->Subscript[x, 1]/.y->Subscript[x, 4]);
Union[Permutations[p],Permutations[q],Permutations[r],Permutations[s]]
,{a,1,4}],1]);

(DiagramList[#]:="3pt3loopamp3")&/@(Flatten[Table[
p=Sort/@{{Subscript[x, Mod[#,4]&@(a)+1],Subscript[x, Mod[#,4]&@(a+1)+1]},{Subscript[x, Mod[#,4]&@(a+1)+1],Subscript[x, Mod[#,4]&@(a+2)+1]},{Subscript[x, Mod[#,4]&@(a+2)+1],Subscript[x, Mod[#,4]&@(a+3)+1]},{Subscript[x, Mod[#,4]&@(a+3)+1],Subscript[x, Mod[#,4]&@(a)+1]},{Subscript[x, Mod[#,4]&@(a)+1],Subscript[x, Mod[#,4]&@(a+2)+1]},{Subscript[x, Mod[#,4]&@(a+2)+1],Subscript[x, Mod[#,4]&@(a)+1]}};
q=Sort/@(p/.Subscript[x, b_]->Subscript[x, Mod[#,4]&@(-b)+1]);
r=Sort/@(p/.Subscript[x, 1]->y/.Subscript[x, 2]->Subscript[x, 1]/.y->Subscript[x, 2]);
s=Sort/@(p/.Subscript[x, 1]->y/.Subscript[x, 4]->Subscript[x, 1]/.y->Subscript[x, 4]);
Union[Permutations[p],Permutations[q],Permutations[r],Permutations[s]]
,{a,1,4}],1]);

(DiagramList[#]:="3pt3loopamp4")&/@(Flatten[Table[
p=Sort/@{{Subscript[x, Mod[#,4]&@(a)+1],Subscript[x, Mod[#,4]&@(a+1)+1]},{Subscript[x, Mod[#,4]&@(a+1)+1],Subscript[x, Mod[#,4]&@(a+2)+1]},{Subscript[x, Mod[#,4]&@(a+2)+1],Subscript[x, Mod[#,4]&@(a+3)+1]},{Subscript[x, Mod[#,4]&@(a+3)+1],Subscript[x, Mod[#,4]&@(a)+1]},{Subscript[x, Mod[#,4]&@(a)+1],Subscript[x, Mod[#,4]&@(a+2)+1]},{Subscript[x, Mod[#,4]&@(a+1)+1],Subscript[x, Mod[#,4]&@(a)+1]}};
q=Sort/@(p/.Subscript[x, b_]->Subscript[x, Mod[#,4]&@(-b)+1]);
r=Sort/@(p/.Subscript[x, 1]->y/.Subscript[x, 2]->Subscript[x, 1]/.y->Subscript[x, 2]);
s=Sort/@(p/.Subscript[x, 1]->y/.Subscript[x, 4]->Subscript[x, 1]/.y->Subscript[x, 4]);
Union[Permutations[p],Permutations[q],Permutations[r],Permutations[s]]
,{a,1,4}],1]);

(DiagramList[#]:="3pt3loopamp5")&/@(Flatten[Table[
p=Sort/@{{Subscript[x, Mod[#,4]&@(a)+1],Subscript[x, Mod[#,4]&@(a+1)+1]},{Subscript[x, Mod[#,4]&@(a+1)+1],Subscript[x, Mod[#,4]&@(a+2)+1]},{Subscript[x, Mod[#,4]&@(a+2)+1],Subscript[x, Mod[#,4]&@(a+3)+1]},{Subscript[x, Mod[#,4]&@(a+3)+1],Subscript[x, Mod[#,4]&@(a+2)+1]},{Subscript[x, Mod[#,4]&@(a+3)+1],Subscript[x, Mod[#,4]&@(a+1)+1]},{Subscript[x, Mod[#,4]&@(a+1)+1],Subscript[x, Mod[#,4]&@(a)+1]}};
q=Sort/@(p/.Subscript[x, b_]->Subscript[x, Mod[#,4]&@(-b)+1]);
r=Sort/@(p/.Subscript[x, 1]->y/.Subscript[x, 2]->Subscript[x, 1]/.y->Subscript[x, 2]);
s=Sort/@(p/.Subscript[x, 1]->y/.Subscript[x, 4]->Subscript[x, 1]/.y->Subscript[x, 4]);
Union[Permutations[p],Permutations[q],Permutations[r],Permutations[s]]
,{a,1,4}],1]);


DiagramList[unknown_]:=Abort[];

ClearAll[p,q,r,s];


(* ::Input::Initialization:: *)
 ClearAll[ExtractDiagram];

ExtractDiagram[exp_Plus]:=ExtractDiagram/@(exp);

ExtractDiagram[exp_List]:=ExtractDiagram/@(exp);

ExtractDiagram[exp_Times]:=Module[{terms},

terms=Select[List@@(exp),Head[#]==Subscript[G, \[Phi]]&&FreeQ[#,Subscript[x, 0]]&];

terms=terms/.Subscript[G, \[Phi]][a_,b_,c_]->{a,b};

(*Return[terms];*)

pdfImage[DiagramList[terms]]
];

