(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
<<PaoloInitialization`
??PaoloInitialization`*


(* ::Input::Initialization:: *)
SetOptions[EvaluationNotebook[],CommonDefaultFormatTypes->{"Output"->StandardForm}];


(* ::Input::Initialization:: *)
Clear[LaplaceEqSolver];
Options[LaplaceEqSolver]={"BC"->{{},{}} , "selectSolution"->0,"drawSolution"->False,"print"->False};

LaplaceEqSolver[graph_,OptionsPattern[]]:=Module[{locVertices,locIndices,locWeights,totWeights,locRoot,locSource,locBC,equations,variables={},x,solution,solutionLabels,i,n},
Clear[\[CapitalPhi]];


locVertices = VertexList@graph;
locIndices=Table[i,{i,Length[locVertices]}];
locWeights=WeightedAdjacencyMatrix[graph]//Normal;
totWeights =Total[locWeights,{2}];

(*Print[Row[{"locVertices=",locVertices," locWeights=",Normal[locWeights]," totWeights=",totWeights}]];*)


locRoot = 
 Select[(List@@@PropertyValue[graph,VertexLabels])[[2;;]],StringMatchQ[#[[2]],___~~"ROOT"]&][[All,1]][[1]];
locSource = 
 Select[(List@@@PropertyValue[graph,VertexLabels])[[2;;]],StringMatchQ[#[[2]],___~~"SOURCE"]&][[All,1]];


locBC=OptionValue["BC"];
(*
If[OptionValue["n"]>0,
locVertices=Map[#[[1]]*n+#[[2]]&,locVertices];
locRoot=Map[#[[1]]*n+#[[2]]&,{locRoot}][[1]];
locSource=Flatten[Map[#[[1]]*n+#[[2]]&,locSource],1];
];*)

If[Head[locSource]==List,
For[i=1,i<=Length[locSource],i++,

If[MemberQ[locBC[[2]],locSource[[i]]],Continue[]];
AppendTo[locBC[[1]],\[CapitalPhi][locSource[[i]]]== 1];
AppendTo[locBC[[2]],locSource[[i]]];

]
,(*FALSE*)
If[MemberQ[locBC[[2]],locSource],Continue[]];
AppendTo[locBC[[1]],\[CapitalPhi][locSource]== 1];
AppendTo[locBC[[2]],locSource];

];

AppendTo[locBC[[1]],\[CapitalPhi][locRoot]==0];
AppendTo[locBC[[2]],locRoot];

equations =locBC[[1]] ;


Do[
AppendTo[variables,\[CapitalPhi][locVertices[[x]]]];
If[MemberQ[locBC[[2]],locVertices[[x]]],Continue[]];
AppendTo[equations, \[CapitalPhi][locVertices[[x]]]==FullSimplify[Sum[locWeights[[x,y]]/totWeights[[x]] \[CapitalPhi][locVertices[[y]]],{y,Length[locIndices]}]]]
,{x,locIndices}];

If[OptionValue["print"],
Print[" ##### Equations to be solved: \n",equations];
Print[" ##### Equations to be solved: \n",variables];
];

solution=Flatten@Solve[equations,{}(*variables*)];

solutionLabels=N[solution]/.\[CapitalPhi][a_]->Floor[a];

solution=solution/. Rule->List;

If[OptionValue["drawSolution"],
Print[Graph[graph,VertexLabels->solutionLabels]]
];


If[OptionValue["selectSolution"]!=0,(*True*)
solution=Select[solution,#[[1]]==\[CapitalPhi][OptionValue["selectSolution"]] &][[1,2]]
];

Return[solution]
]


(* ::Input::Initialization:: *)
ClearAll[bLaplacianRW];
Options[bLaplacianRW]={"draw"->False,"print"->tTrue};


bLaplacianRW[graph_,path__,OptionsPattern[],b_:1,n_:n]:=Module[{locSource,locRoot,locWeights,locVertices,
locIndices,denominator,tempProb,prob=1},

locWeights=WeightedAdjacencyMatrix[graph]/.\[Beta][__]->1//Normal;
locVertices=VertexList@graph;

locIndices=Table[i,{i,Length[locVertices]}];

(*Print[locVertices];*)

locRoot = 
 Select[(List@@@PropertyValue[graph,VertexLabels])[[2;;]],StringMatchQ[#[[2]],___~~"ROOT"]&][[All,1]][[1]];
locSource = 
 Select[(List@@@PropertyValue[graph,VertexLabels])[[2;;]],StringMatchQ[#[[2]],___~~"SOURCE"]&][[All,1]];

If[locRoot =!= path[[1,1]], Print[Style["####  WRONG ROOT  ####",RGBColor[1, 0, 0]]]; Return[NULL]];
If[!MemberQ[locSource,path[[-1,2]]], Print[Style["####  WRONG SOURCE  ####",RGBColor[1, 0, 0]]];Return[NULL]];

Module[{locBC={{},{}},i,\[Phi]sol},
If[Head[locSource]==List,
For[i=1,i<=Length[locSource],i++,
AppendTo[locBC[[1]],\[CapitalPhi][locSource[[i]]]== 1];
AppendTo[locBC[[2]],locSource[[i]]];
]
,(*FALSE*)
AppendTo[locBC[[1]],\[CapitalPhi][locSource]== 1];
AppendTo[locBC[[2]],locSource];
];

For[i=1,i<=Length[path],i++,
AppendTo[locBC[[1]],\[CapitalPhi][path[[i,1]]]==0];
AppendTo[locBC[[2]],path[[i,1]]];

If[OptionValue["print"],
Print["locBC=",Sort/@locBC];
];


\[Phi]sol=LaplaceEqSolver[graph,"BC"->locBC(*,\[Phi]*)];

If[OptionValue["print"],
Print["#####  Laplace solution for transition "<>ToString[path[[i,1]]]<>" to "<>ToString[path[[i,2]]]<>"  #####"];
Print[\[Phi]sol];
];
(*Return[\[Phi]sol];*)
(*Return["good up to LaplaceEqSolver"];*)

denominator=Sum[locWeights[[Position[locVertices,path[[i,1]]][[1,1]],y]]*(Select[\[Phi]sol,#[[1]]==\[CapitalPhi][locVertices[[y]]] &][[1,2]])^b,{y,Length[locIndices]}];
(*Print[denominator];*)

tempProb=1/denominator locWeights[[Position[locVertices,path[[i,1]]][[1,1]],Position[locVertices,path[[i,2]]][[1,1]]]]*(Select[\[Phi]sol,#[[1]]==\[CapitalPhi][path[[i,2]]] &][[1,2]])^b//FullSimplify;

If[OptionValue["print"],
Print["#####  Transition probability "<>ToString[path[[i,1]]]<>" to "<>ToString[path[[i,2]]]<>"  #####"];
Print[tempProb];
];

prob*=tempProb;
Clear[\[Phi]sol];
]
];
(*If[OptionValue["draw"],Print[DrawOnGraph[graph,path]]];*)
Return[prob]
]

(*
bLaplacianRW[graph_,path__,options:OptionsPattern[]]:=bLaplacianRW[graph,path,options,1];*)


(* ::Input::Initialization:: *)
ClearAll[bLaplacianRWlogBC];
Options[bLaplacianRWlogBC]={"draw"->False,"print"->tTrue};


bLaplacianRWlogBC[graph_,path__,OptionsPattern[],b_:1,n_:n]:=Module[{locSource,locRoot,locWeights,locVertices,
locIndices,denominator,tempProb,prob=1},

locWeights=WeightedAdjacencyMatrix[graph]/.\[Beta][__]->1//Normal;
locVertices=VertexList@graph;

locIndices=Table[i,{i,Length[locVertices]}];

(*Print[locVertices];*)

locRoot = 
 Select[(List@@@PropertyValue[graph,VertexLabels])[[2;;]],StringMatchQ[#[[2]],___~~"ROOT"]&][[All,1]][[1]];
locSource = 
 Select[(List@@@PropertyValue[graph,VertexLabels])[[2;;]],StringMatchQ[#[[2]],___~~"SOURCE"]&][[All,1]];

If[locRoot =!= path[[1,1]], Print[Style["####  WRONG ROOT  ####",RGBColor[1, 0, 0]]]; Return[NULL]];
If[!MemberQ[locSource,path[[-1,2]]], Print[Style["####  WRONG SOURCE  ####",RGBColor[1, 0, 0]]];Return[NULL]];

Module[{locBC={{},{}},i,\[Phi]sol},
If[Head[locSource]==List,
For[i=1,i<=Length[locSource],i++,
AppendTo[locBC[[1]],\[CapitalPhi][locSource[[i]]]== With[{x=Floor[(locSource[[i]]-1)/n]-Floor[n/2],y=Mod[(locSource[[i]]-1),n] -(Floor[n/2])},
(Log[x^2+y^2 ](*/Log[x^2+y^2 ]*)//N)]];
AppendTo[locBC[[2]],locSource[[i]]];
]
,(*FALSE*)
AppendTo[locBC[[1]],\[CapitalPhi][locSource]== 1];
AppendTo[locBC[[2]],locSource];
];

For[i=1,i<=Length[path],i++,
AppendTo[locBC[[1]],\[CapitalPhi][path[[i,1]]]==0];
AppendTo[locBC[[2]],path[[i,1]]];

If[OptionValue["print"],
Print["locBC=",Sort/@locBC];
];


\[Phi]sol=LaplaceEqSolver[graph,"BC"->locBC(*,\[Phi]*)];

If[OptionValue["print"],
Print["#####  Laplace solution for transition "<>ToString[path[[i,1]]]<>" to "<>ToString[path[[i,2]]]<>"  #####"];
Print[\[Phi]sol];
];
(*Return[\[Phi]sol];*)
(*Return["good up to LaplaceEqSolver"];*)

denominator=Sum[locWeights[[Position[locVertices,path[[i,1]]][[1,1]],y]]*(Select[\[Phi]sol,#[[1]]==\[CapitalPhi][locVertices[[y]]] &][[1,2]])^b,{y,Length[locIndices]}];
(*Print[denominator];*)

tempProb=1/denominator locWeights[[Position[locVertices,path[[i,1]]][[1,1]],Position[locVertices,path[[i,2]]][[1,1]]]]*(Select[\[Phi]sol,#[[1]]==\[CapitalPhi][path[[i,2]]] &][[1,2]])^b//FullSimplify;

If[OptionValue["print"],
Print["#####  Transition probability "<>ToString[path[[i,1]]]<>" to "<>ToString[path[[i,2]]]<>"  #####"];
Print[tempProb];
];

prob*=tempProb;
Clear[\[Phi]sol];
]
];
(*If[OptionValue["draw"],Print[DrawOnGraph[graph,path]]];*)
Return[prob]
]

(*
bLaplacianRW[graph_,path__,options:OptionsPattern[]]:=bLaplacianRW[graph,path,options,1];*)


(* ::Input::Initialization:: *)
ClearAll[bLaplacianRW3dBC];
Options[bLaplacianRW3dBC]={"draw"->False,"print"->tTrue};

(*bLaplacianRW3dBC[graph_,path__,options:OptionsPattern[]]:=bLaplacianRW3dBC[graph,path,options,1,n];*)

bLaplacianRW3dBC[graph_,path__,OptionsPattern[],b_:1,n_:n]:=Module[{locSource,locRoot,locWeights,locVertices,
locIndices,denominator,tempProb,prob=1},

locWeights=WeightedAdjacencyMatrix[graph]/.\[Beta][__]->1//Normal;
locVertices=VertexList@graph;

locIndices=Table[i,{i,Length[locVertices]}];

(*Print[locVertices];*)

locRoot = 
 Select[(List@@@PropertyValue[graph,VertexLabels])[[2;;]],StringMatchQ[#[[2]],___~~"ROOT"]&][[All,1]][[1]];
locSource = 
 Select[(List@@@PropertyValue[graph,VertexLabels])[[2;;]],StringMatchQ[#[[2]],___~~"SOURCE"]&][[All,1]];

If[locRoot =!= path[[1,1]], Print[Style["####  WRONG ROOT  ####",RGBColor[1, 0, 0]]]; Return[NULL]];
If[!MemberQ[locSource,path[[-1,2]]], Print[Style["####  WRONG SOURCE  ####",RGBColor[1, 0, 0]]];Return[NULL]];

Module[{locBC={{},{}},i,\[Phi]sol},
If[Head[locSource]==List,
For[i=1,i<=Length[locSource],i++,
AppendTo[locBC[[1]],\[CapitalPhi][locSource[[i]]]== 
With[{x=Floor[(locSource[[i]]-1)/n^2]-Floor[n/2],y=Mod[Floor[(locSource[[i]]-1)/n],n] -(Floor[n/2]),z=Mod[(locSource[[i]]-1),n] -(Floor[n/2])},
(Floor[n/2]/Sqrt[x^2+y^2+z^2]*(Sqrt[x^2+y^2+z^2]-0.9)/(Floor[n/2]-0.9))]
];
AppendTo[locBC[[2]],locSource[[i]]];
]
,(*FALSE*)
AppendTo[locBC[[1]],\[CapitalPhi][locSource]== 1];
AppendTo[locBC[[2]],locSource];
];

For[i=1,i<=Length[path],i++,
AppendTo[locBC[[1]],\[CapitalPhi][path[[i,1]]]==0];
AppendTo[locBC[[2]],path[[i,1]]];

If[OptionValue["print"],
Print["locBC=",Sort/@locBC];
];


\[Phi]sol=LaplaceEqSolver[graph,"BC"->locBC(*,\[Phi]*)];

If[OptionValue["print"],
Print["#####  Laplace solution for transition "<>ToString[path[[i,1]]]<>" to "<>ToString[path[[i,2]]]<>"  #####"];
Print[\[Phi]sol];
];
(*Return[\[Phi]sol];*)
(*Return["good up to LaplaceEqSolver"];*)

denominator=Sum[locWeights[[Position[locVertices,path[[i,1]]][[1,1]],y]]*(Select[\[Phi]sol,#[[1]]==\[CapitalPhi][locVertices[[y]]] &][[1,2]])^b,{y,Length[locIndices]}];
(*Print[denominator];*)

tempProb=1/denominator locWeights[[Position[locVertices,path[[i,1]]][[1,1]],Position[locVertices,path[[i,2]]][[1,1]]]]*(Select[\[Phi]sol,#[[1]]==\[CapitalPhi][path[[i,2]]] &][[1,2]])^b//FullSimplify;

If[OptionValue["print"],
Print["#####  Transition probability "<>ToString[path[[i,1]]]<>" to "<>ToString[path[[i,2]]]<>"  #####"];
Print[tempProb];
];

prob*=tempProb;
Clear[\[Phi]sol];
]
];
(*If[OptionValue["draw"],Print[DrawOnGraph[graph,path]]];*)
Return[prob]
]

(*
bLaplacianRW[graph_,path__,options:OptionsPattern[]]:=bLaplacianRW[graph,path,options,1];*)



