(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
ParallelMap[Plus,{1,2}]


(* ::Input::Initialization:: *)
ClearAll[Rotate90,ReflectX,GetSymmetryFamily];

(*Rotates 90\[Degree] counter-clockwise around the first point of the path*)Rotate90[path_List]:=With[{center=path[[1]]},Map[({-(#[[2]]-center[[2]])+center[[1]],(#[[1]]-center[[1]])+center[[2]]})&,path]]

(*Reflects horizontally across the vertical line passing through the first point (x->-x)*)
ReflectX[path_List]:=With[{center=path[[1]]},Map[({-(#[[1]]-center[[1]])+center[[1]],#[[2]]})&,path]]

(*Generates all 8 unique rotation and reflection variants of a path*)GetSymmetryFamily[path_List]:=With[{rotations=NestList[Rotate90,path,3]},
Join[rotations,Map[ReflectX,rotations]]]


(* ::Input::Initialization:: *)
ClearAll[AnalyzeSymmetricPaths]

(*Comparison test:Returns True if path2 is a valid symmetry transformation of path1*)AreSymmetricQ[path1_List,path2_List]:=MemberQ[GetSymmetryFamily[path1],path2];

(*The master function to process your paths array*)
AnalyzeSymmetricPaths[allPaths_List]:=Module[{grouped,tally},(*Group identical paths under rotation/reflection*)grouped=Gather[allPaths,AreSymmetricQ];
(*Return a structured dataset:{Unique Representative Path,Family Occurrence Count}*)tally=Table[{First[g],Length[g]},{g,grouped}];

Reverse[SortBy[tally,Last]]
];


(* ::Input::Initialization:: *)
MergeTwoTallies[tally1_List,tally2_List]:=Module[{combined=tally1,matched,path2,count2},
Do[(*Extract components explicitly using Pattern Matching*)
path2=item[[1]];
count2=item[[2]];
(*Your existing logic*)
matched=Position[combined,_?(AreSymmetricQ[#[[1]],path2]&),{1},1]//Quiet;

If[Length[matched]>0,
combined[[matched[[1,1]],2]]+=count2,
AppendTo[combined,{path2,count2}]
],

{item,tally2} (*Loops through each full pair in tally2*)];

combined
];


(* ::Input::Initialization:: *)
IterativeSymmetricTally[allPaths_List,batchSize_Integer:100]:=Module[{batches,currentTallies},
DistributeDefinitions[AnalyzeSymmetricPaths,MergeTwoTallies,AreSymmetricQ];
(*1. Initial Step: partition and analyze individual batches*)
batches=Partition[allPaths,UpTo[batchSize]];
currentTallies=ParallelMap[AnalyzeSymmetricPaths,batches];

(*2. Reduction Loop: merge pairs of batches until only 1 master tally is left*)
While[Length[currentTallies]>1,

currentTallies=If[OddQ[Length[currentTallies]],

(*If odd number of batches,hold the last one and merge the pairs*)Append[Map[Apply[MergeTwoTallies],Partition[Drop[currentTallies,-1],2]],Last[currentTallies]],

(*If even,merge all pairs straight across*)
Map[Apply[MergeTwoTallies],Partition[currentTallies,2]]
];
Print["Remaining batch blocks to merge: ",Length[currentTallies]];
];
(*3. Final Sort by count in descending order*)
Reverse[SortBy[First[currentTallies],Last]]
];


(* ::Input::Initialization:: *)
Clear[LaplaceEqSolver];
Options[LaplaceEqSolver]={"BC"->{{},{}} , "selectSolution"->0,"drawSolution"->False};

LaplaceEqSolver[graph_,OptionsPattern[]]:=Module[{locVertices,locWeights,totWeights,locRoot,locSource,locBC,equations,variables={},x,solution,solutionLabels,i,n},
Clear[\[CapitalPhi]];


locVertices = VertexList@graph;
locWeights=WeightedAdjacencyMatrix[graph]//Normal;
totWeights =Total[locWeights,{2}];

(*Print[Row[{"locVertices=",locVertices," locWeights=",Normal[locWeights]," totWeights=",totWeights}]];*)


locRoot = 
 Select[(List@@@PropertyValue[graph,VertexLabels])[[2;;]],StringMatchQ[#[[2]],___~~"ROOT"]&][[All,1]][[1]];
locSource = 
 Select[(List@@@PropertyValue[graph,VertexLabels])[[2;;]],StringMatchQ[#[[2]],___~~"SOURCE"]&][[All,1]];


locBC=OptionValue["BC"];
(*
If[OptionValue["n"]>0,
locVertices=Map[#[[1]]*n+#[[2]]&,locVertices];
locRoot=Map[#[[1]]*n+#[[2]]&,{locRoot}][[1]];
locSource=Flatten[Map[#[[1]]*n+#[[2]]&,locSource],1];
];*)

If[Head[locSource]==List,
For[i=1,i<=Length[locSource],i++,
AppendTo[locBC[[1]],\[CapitalPhi][locSource[[i]]]== 1];
AppendTo[locBC[[2]],locSource[[i]]];
]
,(*FALSE*)
AppendTo[locBC[[1]],\[CapitalPhi][locSource]== 1];
AppendTo[locBC[[2]],locSource];
];

AppendTo[locBC[[1]],\[CapitalPhi][locRoot]==0];
AppendTo[locBC[[2]],locRoot];

equations =locBC[[1]] ;


Do[
AppendTo[variables,\[CapitalPhi][x]];
If[MemberQ[locBC[[2]],x],Continue[]];
AppendTo[equations, \[CapitalPhi][x]==FullSimplify[Sum[locWeights[[x,y]]/totWeights[[x]] \[CapitalPhi][y],{y,Length[locVertices]}]]]
,{x,locVertices}];

(*
Print[equations];
Print[variables];*)
solution=Flatten@Solve[equations,{}(*variables*)];

solutionLabels=N[solution]/.\[CapitalPhi][a_]->Floor[a];

solution=solution/. Rule->List;

If[OptionValue["drawSolution"],
Print[Graph[graph,VertexLabels->solutionLabels]]
];


If[OptionValue["selectSolution"]!=0,(*True*)
solution=Select[solution,#[[1]]==\[CapitalPhi][OptionValue["selectSolution"]] &][[1,2]]
];

Return[solution]
]


(* ::Input::Initialization:: *)
Clear[bLaplacianRW];
Options[bLaplacianRW]={"draw"->False};
bLaplacianRW[graph_,path__,b_:1,OptionsPattern[]]:=Module[{locSource,locRoot,locWeights,locVertices,denominator,prob=1},

locWeights=WeightedAdjacencyMatrix[graph]/.\[Beta][__]->1//Normal;
locVertices=VertexList@graph;

(*Print[locVertices];*)

locRoot = 
 Select[(List@@@PropertyValue[graph,VertexLabels])[[2;;]],StringMatchQ[#[[2]],___~~"ROOT"]&][[All,1]][[1]];
locSource = 
 Select[(List@@@PropertyValue[graph,VertexLabels])[[2;;]],StringMatchQ[#[[2]],___~~"SOURCE"]&][[All,1]];

If[locRoot =!= path[[1,1]], Print[Style["####  WRONG ROOT  ####",RGBColor[1, 0, 0]]]; Return[NULL]];
If[!MemberQ[locSource,path[[-1,2]]], Print[Style["####  WRONG SOURCE  ####",RGBColor[1, 0, 0]]];Return[NULL]];

Module[{locBC={{},{}},i,\[Phi]sol},
If[Head[locSource]==List,
For[i=1,i<=Length[locSource],i++,
AppendTo[locBC[[1]],\[CapitalPhi][locSource[[i]]]== 1];
AppendTo[locBC[[2]],locSource[[i]]];
]
,(*FALSE*)
AppendTo[locBC[[1]],\[CapitalPhi][locSource]== 1];
AppendTo[locBC[[2]],locSource];
];
For[i=1,i<=Length[path],i++,
AppendTo[locBC[[1]],\[CapitalPhi][path[[i,1]]]==0];
AppendTo[locBC[[2]],path[[i,1]]];

(*Print["locBC=",locBC];*)



\[Phi]sol=LaplaceEqSolver[graph,"BC"->locBC(*,\[Phi]*)];

(*Print[\[Phi]sol];*)
(*Return["good up to LaplaceEqSolver"];*)

denominator=Sum[locWeights[[path[[i,1]],y]]*(Select[\[Phi]sol,#[[1]]==\[CapitalPhi][y] &][[1,2]])^b,{y,Length[locVertices]}];
(*Print[denominator];*)


Print["#####  Transition probability "<>ToString[path[[i,1]]]<>" to "<>ToString[path[[i,2]]]<>"  #####"];
Print[(locWeights[[path[[i,1]],path[[i,2]]]]*(Select[\[Phi]sol,#[[1]]==\[CapitalPhi][path[[i,2]]] &][[1,2]])^b)/denominator/.\[Beta][_,_]->1//FullSimplify];

prob*=(locWeights[[path[[i,1]],path[[i,2]]]]*(Select[\[Phi]sol,#[[1]]==\[CapitalPhi][path[[i,2]]] &][[1,2]])^b)/denominator//FullSimplify;
Clear[\[Phi]sol];
]
];
(*If[OptionValue["draw"],Print[DrawOnGraph[graph,path]]];*)
Return[prob]
]


(* ::Input::Initialization:: *)
Clear[PathFinder];

PathFinder[graph_]:=Module[{pathList={{}}},
Step[subgraph_]:=Module[{locEdges,locVertices,locWeights,locRoot,locSource,locMoves,newEdges, newRoot,smallerGraph,i},
locEdges = EdgeList@subgraph/.DirectedEdge->List;
locVertices=VertexList@subgraph;
If[Length[locVertices]==1,Return[NULL]];
locWeights=WeightedAdjacencyMatrix[subgraph]//Normal;
locRoot = 
 Select[(List@@@PropertyValue[subgraph,VertexLabels])[[2;;]],StringMatchQ[#[[2]],___~~"ROOT"]&][[All,1]][[1]];
locSource = 
 Select[(List@@@PropertyValue[subgraph,VertexLabels])[[2;;]],StringMatchQ[#[[2]],___~~"SOURCE"]&][[All,1]][[1]];
locMoves=Select[locEdges,#[[1]]==locRoot || #[[2]]==locRoot&][[All]];

Print["###  LocMoves  ####"];
Print[locMoves];

For[i=1, i<=Length[locMoves],i++,

If[i ==Length[locMoves],
(*True*)If[locMoves[[i,2]]==locSource,
 (*Ture*)pathList=Append[pathList[[2;;]],Append[pathList[[1]],locMoves[[i]]]]; Continue[],
 (*False*)pathList=Prepend[pathList[[2;;]],Append[pathList[[1]],locMoves[[i]]]]
],
(*False*)
If[locMoves[[i,2]]==locSource,
 (*True*)pathList=Append[pathList,Append[pathList[[1]],locMoves[[i]]]];Continue[],
 (*False*)pathList=Prepend[pathList,Append[pathList[[1]],locMoves[[i]]]]
]];

(*Print["###  pathList  ####"];
Print[pathList];*);

newEdges=Select[locEdges,#[[1]]=!=locRoot && #[[2]]=!=locRoot &][[All]];
newRoot = locMoves[[i,2]];
If[Length[newEdges] <= 0,Continue[]];
smallerGraph=MyGraph[newEdges,newRoot,locSource,"undirected"->False][[1]];

(*Print[smallerGraph];*);

Step[smallerGraph]
]
];

Step[graph];
Return[pathList]
]


(* ::Input::Initialization:: *)
Clear[AllLaplacianRWs]

Options[AllLaplacianRWs]={"draw"->False,"print"->False};

AllLaplacianRWs[graph_,OptionsPattern[]]:=Module[{possibleLRW,i,probabilityLRW={}},
possibleLRW=PathFinder[graph];
For[i=1, i<= Length[possibleLRW],i++,
AppendTo[probabilityLRW,LaplacianRW[graph,possibleLRW[[i]],OptionValue["draw"]]];
If[OptionValue["print"],Print[i,") Laplacian RW ",possibleLRW[[i]]," with probability " ,probabilityLRW[[i]]]
]
];
Return[{possibleLRW,probabilityLRW}]
]



