(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
(*SetOptions[$FrontEndSession,NotebookAutoSave->True]*)
(*With[{nb=EvaluationNotebook[]},RunScheduledTask[If["ModifiedInMemory"/. NotebookInformation[nb],NotebookSave[nb]],300]]
NotebookSave[]*)
FS=FullSimplify;
<<"D:\\Offline_Documents\\University\\PhD_Paris\\PhD_work\\Simulations\\Kay-initialization.m"


(* ::Input::Initialization:: *)
ClearAll[\[Beta]Function];

Options[\[Beta]Function]={"print"->False,"g0Order"->0};

\[Beta]Function[coupling_,OptionsPattern[]]:=Module[{gr,\[Beta]f,nLoop,i},
Clear[g,g0,\[Mu],\[Epsilon]];

nLoop=OptionValue["g0Order"];
If[nLoop==0,nLoop=Exponent[coupling,g0]];

gr=Normal@Series[coupling,{g0,0,nLoop}];

If[OptionValue["print"],
Print["Initial effective couling:\n ",gr,"\n"];];

\[Beta]f=-\[Mu] D[gr,\[Mu]]//Expand;
If[OptionValue["print"],
Print["\n\[Beta]-function with bare coupling: ", \[Beta]f,"\n"];];

gr=g-coupling+g0 \[Mu]^-\[Epsilon];

If[OptionValue["print"],
Print[" Bare coupling= \n ",gr,"\n"];];

(* Invert g(g0) *)
Do[\[Beta]f=\[Beta]f/.g0^n_ \[Mu]^(-n_ \[Epsilon]):>(gr)^n \[Mu]^(n \[Epsilon])//Expand;
\[Beta]f=\[Beta]f/.(g0 ):>(gr)\[Mu]^ \[Epsilon]//Expand;
(*\[Beta]f=Series[\[Beta]f,{g0,0,nLoop}]//Expand;*)
\[Beta]f=\[Beta]f/.g0^n_/;n>nLoop:>0;
\[Beta]f=\[Beta]f/.g0^n_/;n==nLoop:>(g \[Mu]^\[Epsilon])^n//Expand;
If[OptionValue["print"],
Print[\[Beta]f//FullSimplify,"\n"];];
,{i,1,nLoop}];

(*For[i=1,i<=nLoop,i++,
\[Beta]f=\[Beta]f/.g0^n_ \[Mu]^(n_ \[Epsilon]):>(gr)^n//Expand;
\[Beta]f=\[Beta]f/.(g0 \[Mu]^\[Epsilon]):>(gr)//Expand;
];*)

\[Beta]f=Normal[\[Beta]f]/.g0^n_ :>(g \[Mu]^\[Epsilon])^n//Expand;
\[Beta]f=\[Beta]f/.(g0 ):>(g \[Mu]^\[Epsilon])//Expand;
\[Beta]f=Series[\[Beta]f,{g,0,nLoop}]//Map[Expand,#]&;
(*Print[\[Beta]f];*)
(*\[Beta]f=Normal[\[Beta]f];*)
Return[\[Beta]f//FullSimplify]]


(* ::Input::Initialization:: *)
ClearAll[\[Beta]FunctionFromZ];

Options[\[Beta]FunctionFromZ]={"print"->False};

\[Beta]FunctionFromZ[Zg_,LoopOrder_:0,gg_:{g},OptionsPattern[]]:=Module[{z,\[Beta]f,nLoop,i},
Clear[g,g0,\[Mu],\[Epsilon]];

z=Expand[Zg];

nLoop=LoopOrder;
If[nLoop==0,nLoop=Exponent[z,gg[[1]]]+1];

z=Normal@Series[Zg,Sequence@@({#,0,nLoop}&/@gg)];

If[OptionValue["print"],
Print["RG factor:\n ",z,"\n"];];

\[Beta]f=\[Epsilon] gg[[1]] 1/(1+gg[[1]] D[Log[z],gg[[1]]]);

\[Beta]f=Series[\[Beta]f,Sequence@@({#,0,nLoop}&/@gg)]//Map[Expand,#]&;

If[OptionValue["print"],
Print["\n\[Beta]-function: ", \[Beta]f,"\n"];];

Return[Map[Expand,\[Beta]f]]]


(* ::Input::Initialization:: *)
ClearAll[\[Gamma]Function];


Options[\[Gamma]Function]={"print"->False,"g0Order"->0};


\[Gamma]Function[observable_,bareCoupling_, OptionsPattern[]]:=Module[{U,gr,\[Gamma]f,nLoop,i},
Clear[g,g0,\[Mu],\[Epsilon]];


nLoop=OptionValue["g0Order"];
If[nLoop==0,nLoop=Exponent[bareCoupling,g0]-1];
(*Print[nLoop]*);

gr=Normal@Series[bareCoupling,{g0,0,nLoop}];

U=Normal@Series[observable,{g0,0,nLoop}];

\[Gamma]f=-\[Mu] D[Log[U],\[Mu]]//Expand;
If[OptionValue["print"],
Print[" \[Gamma]f(\!\(\*SubscriptBox[
StyleBox[\"g\",\nBackground->RGBColor[0.9, 1, 1]], \(0\)]\))= \n ",\[Gamma]f];];


gr=g-gr+g0 \[Mu]^-\[Epsilon];

If[OptionValue["print"],
Print[" Bare coupling= \n ",gr];];

Do[\[Gamma]f=\[Gamma]f/.g0^n_ :>(gr)^n \[Mu]^(n \[Epsilon])//Expand;
\[Gamma]f=\[Gamma]f/.(g0 ):>(gr)\[Mu]^\[Epsilon]//Expand;
\[Gamma]f=\[Gamma]f/.g0^n_/;n>nLoop:>0;
\[Gamma]f=\[Gamma]f/.g0^n_/;n==nLoop:>(g \[Mu]^\[Epsilon])^n//Expand;
,{i,1,nLoop}];

(*For[i=1,i<=nLoop,i++,
\[Gamma]f=\[Gamma]f/.g0^n_ \[Mu]^(n_ \[Epsilon]):>(gr)^n//Expand;
\[Gamma]f=\[Gamma]f/.(g0 \[Mu]^\[Epsilon]):>(gr)//Expand;
];*)

\[Gamma]f=\[Gamma]f/.g0^n_ :>(g)^n \[Mu]^(n \[Epsilon])//Expand;
\[Gamma]f=\[Gamma]f/.(g0 ):>(g)\[Mu]^\[Epsilon]//Expand;
(*
If[OptionValue["print"],
Print[" \[Gamma]f(g)= \n ",\[Gamma]f];];*)

\[Gamma]f=Series[\[Gamma]f,{g,0,nLoop}]//Expand;
\[Gamma]f=Factor@Simplify/@\[Gamma]f;
(*Print[\[Gamma]f];*)
(*\[Gamma]f=Normal[\[Gamma]f];*)
Return[\[Gamma]f]]


(* ::Input::Initialization:: *)
(*Don't use the List feature, it is not the correct operation!*)
ClearAll[\[Gamma]FunctionFromZ];

Options[\[Gamma]FunctionFromZ]={"print"->False,"gstar"->True};

\[Gamma]FunctionFromZ[Zobservable_List,ZCoupling_,options:OptionsPattern[]]:=
\[Gamma]FunctionFromZ[Zobservable,ZCoupling,options,0]

\[Gamma]FunctionFromZ[Zobservable_List,ZCoupling_,OptionsPattern[],LoopOrder_:0]:=Module[{U,gr,\[Gamma]f,\[Beta],factor,eq,gstar,nLoop,i},
Clear[g,g0,\[Mu],\[Epsilon]];

U=Zobservable;
factor=Length[U];
U=Times@@U;

nLoop=LoopOrder;
If[nLoop==0,nLoop=Exponent[U,g]];
(*Print[nLoop]*);

gr=Normal@Series[ZCoupling,{g,0,nLoop}];

U=Series[U,{g,0,nLoop}];

\[Gamma]f=- D[Log[U],g]//Expand;
If[OptionValue["print"],
Print[Style[" - dLogZ/dg= ",{RGBColor[0, 0, 1],Bold}],\[Gamma]f];];

\[Beta]=\[Beta]FunctionFromZ[gr];
If[OptionValue["print"],
Print[Style[" \[Beta]= ",{RGBColor[0, 0, 1],Bold}],\[Beta]];];
If[OptionValue["gstar"],
gstar=Select[Flatten@SolveValues[Simplify[Normal[\[Beta]]]==0,g],#=!=0&];

If[OptionValue["print"],
Print[Style[" Possible \!\(\*SuperscriptBox[\(g\), \(*\)]\)s= ",{RGBColor[0, 0, 1],Bold}],gstar];];

gstar=Series[gstar,{\[Epsilon],0,nLoop},Assumptions->b>0]//Expand;
gstar=Select[Normal@gstar,(#/.\[Epsilon]->0)==0&];


If[OptionValue["print"],
Print[Style[" Selected \!\(\*SuperscriptBox[\(g\), \(*\)]\)s= ",{RGBColor[0, 0, 1],Bold}],gstar];];
];

\[Gamma]f=\[Gamma]f*\[Beta]/factor;

If[OptionValue["print"],
Print[Style[Row[{" \[Gamma]f= - \[Beta]/",factor ,"* dLogZ/dg= "}],{RGBColor[0, 0, 1],Bold}],FS[\[Gamma]f]];];

If[OptionValue["gstar"],
\[Gamma]f=Normal[\[Gamma]f]/.g->gstar[[1]];
];

\[Gamma]f=Series[\[Gamma]f,{\[Epsilon],0,nLoop}]//Expand;

\[Gamma]f=Factor@(FullSimplify/@\[Gamma]f);
(*Print[\[Gamma]f];*)
(*\[Gamma]f=Normal[\[Gamma]f];*)
Return[Normal[\[Gamma]f]]
]


\[Gamma]FunctionFromZ[Zobservable_,ZCoupling_,options:OptionsPattern[]]:=
\[Gamma]FunctionFromZ[{Zobservable},ZCoupling,options,0]

\[Gamma]FunctionFromZ[Zobservable_,ZCoupling_,options:OptionsPattern[],LoopOrder_]:=
\[Gamma]FunctionFromZ[{Zobservable},ZCoupling,options,LoopOrder]



(* ::Input::Initialization:: *)
(* REFERENCE, DO NOT TOUCH *)
goodGuys=-b^3 (2 doubleBanana + 4 hat +6 hat)-b^2(doubleBanana +2 b hat)*2-b^3(6 hat + doubleBanana);

realNasties=b(b-1)(4 doubleBanana + 8 hat )+b(b-1)2 hat - b(b-1)(2  doubleBanana +4 hat )- b(b-1)( 4 doubleBanana);

betterNasties=b^2(b-1)6 hat+b^2(b-1)(2 doubleBanana +4 hat)+b^2(b-1)(2 doubleBanana)+b^2(b-1)(2 hat);

gammagGuys=b(2 hat + 2 hat) + b^2 doubleBanana +4 b^2 hat + b^2 doubleBanana;


(* ::Input::Initialization:: *)
(* IN WHAT FOLLOWS, I SUB doubleBanana-> MINUS 1/\[Epsilon]^2. SO HERE I NEED TO SUM THE BANANA SQUARED. Actually, the replacement ALREADY implements the partial subtraction of subdivergencies *)

(* GradImmediateIntNotAllowed=0 then it is not allowed. To implement it also for \[Gamma]1 and \[Gamma]2, one should set h,h2->1*)

twoLoopZ\[Gamma]1=1/b (-b^2 doubleBanana-2 b^3 hat+(1/2 b^2 (b-1)(banana)^2(* From \[CapitalGamma]Grad counterterm*))- b^2 (b-1)(a doubleBanana+h hat) (*If not all the \[CapitalGamma]grad can be used*));/.h->-1;

twoLoopZ\[Gamma]2=1/b (-b^2 doubleBanana-2 b^3 hat +(1/2 b^2 (b-1)(banana)^2(* From \[CapitalGamma]Grad counterterm*)) +b^2 (doubleBanana+1/2 (banana)^2(* From \[CapitalGamma]paoloG counterterm*))+2 b (hat +1/2 (banana)^2(* From \[CapitalGamma]paoloG counterterm*))- b^2 (b-1)(a2 doubleBanana+h2 hat) (*If not all the \[CapitalGamma]grad can be used*));/.h2->-1(*(2 b hat-2 b^3 hat)/b*)(*/.hat->(hat+1/4(banana)^2(* From \[CapitalGamma]Grad counterterm*))*)

twoLoopZg=((goodGuys+b^2(doubleBanana +2 b hat)*2(*Moved to Z\[Gamma]1 and Z\[Gamma]2 *)+b^3( doubleBanana)(*Should arise from the 1loops of Z\[Gamma]1*Z\[Gamma]2 *))
+(*realNasties modified*)
(* ONLY \[Gamma]Grad 1) in my notes*)b(b-1)(4 (doubleBanana+(banana)^2(* From \[CapitalGamma]Grad counterterm*)) + 8 (hat+1/2 (banana)^2(* From \[CapitalGamma]Grad counterterm*)) )
+(* ONLY \[Gamma]Grad 3) in my notes*)
b(b-1)2 (hat+1/2 (banana)^2(* From \[CapitalGamma]Grad counterterm*)) GradImmediateIntNotAllowed
-  (* \[Gamma]Grad + \[Gamma]Plus 1) in my notes *)
b(b-1)(2  (doubleBanana+(banana)^2(* From \[CapitalGamma]Grad counterterm*)) +4 (hat+1/2 (banana)^2(* From \[CapitalGamma]Grad counterterm*)) )
-(* \[Gamma]Grad + \[Gamma]Plus 2) in my notes *)
 b(b-1)( 4 (doubleBanana+(banana)^2(* From \[CapitalGamma]Grad counterterm*)))
+(*betterNasties modified*)
(* ONLY \[Gamma]Grad 2) in my notes*)
b^2(b-1)6 (hat+1/2 (banana)^2(* From \[CapitalGamma]Grad counterterm*))
+(* \[Gamma]Grad + \[Gamma]Minus 1) in my notes *)
b^2(b-1)(2 (doubleBanana+(banana)^2(* From \[CapitalGamma]Grad counterterm*)) +4 (hat+1/2 (banana)^2(* From \[CapitalGamma]Grad counterterm*)))
+(* \[Gamma]Grad + \[Gamma]Minus 2) in my notes *)
b^2(b-1)(2 (doubleBanana+(banana)^2(* From \[CapitalGamma]Grad counterterm*)))
+(* \[Gamma]Grad + \[Gamma]Minus 2) in my notes (continues) *)
b^2(b-1)(2 (hat+1/2 (banana)^2(* From \[CapitalGamma]Grad counterterm*)))
+(*gammagGuys modified*)
(gammagGuys -(b(2 hat )+ b^2 doubleBanana (*Should arise from the 1loops of Z\[Gamma]1*Z\[Gamma]2 *))- b^2 doubleBanana (*Moved to Z\[Gamma]2 *))(*b(2 hat )  +4 b^2 hat *))/b; 
(*Here I'm missing the subdiv from the grad vertex. Try to remove them by hand see if the rest is finite*)

twoLoopZ\[Gamma]=(b(b-1))/2 ( sunset + (hat+1/2 (banana)^2(* From \[CapitalGamma]Grad counterterm*)))/b;


(* ::Input::Initialization:: *)
(*This is Probably necessarely *)
twoLoopZ\[Gamma]1=twoLoopZ\[Gamma]1/.(banana)^2->0(banana)^2/2;
twoLoopZg=twoLoopZg/.(banana)^2->0(banana)^2/2;
twoLoopZ\[Gamma]2=twoLoopZ\[Gamma]2/.(banana)^2->0(banana)^2/2;
twoLoopZ\[Gamma]=twoLoopZ\[Gamma]/.(banana)^2->2(banana)^2/2;


(* ::Input::Initialization:: *)
dfRG1L:=2-b \[Epsilon]/(2+b)
dfRG1Lsimp:=2-(b \[Epsilon])/(1+2 b)

dfRG2Lsimp:=Collect[fractalDim,\[Epsilon],FS]

dfRG2Lwf:=dfWF
dfRG2L:=2-b \[Epsilon]/(2+b)-b (\[Epsilon]/(2+b))^2

(*dfRG2Lsimp:=2-(b \[Epsilon])/(1+2 b)-(b ^2 \[Epsilon]^2)/(1+2 b)^2*)(*BAD*)

dfSLE=1+3/(4(2b+1));



