(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
dfSLE=1+3/(4(2bb+1));
endRange=5;

plotSLE=Plot[dfSLE,{bb,0,endRange},PlotStyle->Red,PlotRange->All];

Show[{plotSLE},PlotRange->{1,2},AxesLabel->{b,Subscript[d, f]},PlotLabel->"Lawer's result (\!\(\*SubscriptBox[\(SLE\), \(\[Kappa]\)]\))",AxesOrigin->{0,1}]



(* ::Input::Initialization:: *)
fitFuncs=Table[x^(-i),{i,-1,3}]
fitFuncs={x,1,Exp[-x]}



