(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
SetOptions[EvaluationNotebook[],NotebookEventActions->{"Open":>(Print["Notebook opened at ",DateString[]];
<<"D:\\Offline_Documents\\University\\PhD_Paris\\PhD_work\\Simulations\\MathematicaFiles-LRW-DLA-bLRW\\bLRW\\bLRW-MicroscopicAction-RG-FractalDim-etc\\bLRW-FractalDimFromData\\2d-FractalDim\\2d-bLRW-FractalDimension.m")}]
<<"D:\\Offline_Documents\\University\\PhD_Paris\\PhD_work\\Simulations\\MathematicaFiles-LRW-DLA-bLRW\\bLRW\\bLRW-MicroscopicAction-RG-FractalDim-etc\\bLRW-FractalDimFromData\\2d-FractalDim\\2d-bLRW-FractalDimension.m"
Directory[]


(* ::Input::Initialization:: *)
b=4;

rawData=Import["data4Sqaure-AfterValidation.mx"];

Length[rawData]


(* ::Input::Initialization:: *)
Global`logData=Log[rawData];

fitFunc=a+c Exp[-\[Omega] x]+df x;


(* ::Input::Initialization:: *)
Quiet@LaunchKernels[];
DistributeDefinitions[rawData];


(* ::Input::Initialization:: *)
ClearAll[StdDevEstimate];

Options[StdDevEstimate]={"print"->False};

StdDevEstimate[data_,binSize_,options:OptionsPattern[]]:=StdDevEstimate[data,binSize,options,0];

StdDevEstimate[data_,binSize_,OptionsPattern[],repeat_:0]:=Module[{size,locBinSize,repeatNumber,binNumber,scramble,means,stdDevs,completedCount=0,startTime=AbsoluteTime[],formatTime},

size=Length[data];
locBinSize=binSize;
repeatNumber=repeat;

If[locBinSize>size/2,Print[Style["### WARNING: binSize too large, defaulting to half the data length ###",RGBColor[1,0,0]]];
locBinSize=Floor[size/2]];

binNumber=Floor[size/locBinSize];

If[OptionValue["print"],Print[Style[" binNumber= ",{RGBColor[0,0,1],Bold}],binNumber]];
If[repeatNumber==0,repeatNumber=Ceiling[size/binNumber]];

If[OptionValue["print"],Print[Style[" repeatNumber= ",{RGBColor[0,0,1],Bold}],repeatNumber]];

formatTime[sec_]:=With[{s=Round[sec]},StringRiffle[IntegerString[#,10,2]&/@{Quotient[s,3600],Mod[Quotient[s,60],60],Mod[s,60]},":"]];

(*Monitor tracks the calculation and shows a live panel*)
Monitor[stdDevs=Table[scramble=RandomSample[data];
scramble=Partition[scramble,UpTo[locBinSize]];
means=Mean/@scramble;
completedCount++;
{N[StandardDeviation[means]/Sqrt[Length[means]]]},repeatNumber],
(*Progress panel layout inside Monitor*)
Panel[Column[{Row[{Style["Task Progress: ",Bold],completedCount," / ",repeatNumber}],ProgressIndicator[completedCount,{0,repeatNumber},ImageSize->Large],With[{elapsed=Round[AbsoluteTime[]-startTime]},Row[{Style["Elapsed: ",Gray],formatTime[elapsed],"   |   ",Style["ETA: ",Gray],If[completedCount>0,With[{remaining=Round[(elapsed/completedCount)*(repeatNumber-completedCount)]},formatTime[remaining]],"00:00:00"]}]]},Spacings->1],Background->GrayLevel[0.95],FrameMargins->15]
];

stdDevs={Mean[stdDevs[[All,1]]]};

If[OptionValue["print"],Print[Style[" Std deviation/\!\(\*SqrtBox[\(N\)]\) estimate= ",{RGBColor[0,0,1],Bold}],stdDevs[[1]]//N]];

stdDevs[[1]]*Sqrt[size]]



